### ISSUE TITLE
[Updates/Revisions] Research (Eng. and Span.) R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1000]
> META: #743 
> Creation Ticket (with source data/files): #764

### Description
Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

This ticket documents updates and revisions following the creation of the recommendations and associated comps.

### Sub-Tasks
- [x] Reply via to questions posed in the Mural board **N/A**
- [x] Aggregate suggestions that require review/approval
    - [x] Make recommendations **Slated 05/17**
    - [x] Make determination w/federal team regarding changes **Slated 05/18 & 05/23**
    - [x] Make updates following federal review
- [x] Update comps based on English Review # 2
- [x] Update comps based on Spanish-language meeting 

### Notes
- Insert notes as needed

**Comment by laurelthrash** [comment]
[Forthcoming: comp updates following federal team meetings on 05/18 and 05/22]

**Comment by monika-jaeger** [comment]
@laurelthrash @adriancofie changes above made to [Research comps](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7002&type=design&node-id=142-9370&viewport=-633%2C1109%2C0.25&scaling=min-zoom). New hero images are on slides 3-8.

**Comment by laurelthrash** [comment]
**[Spanish] Changes to Spanish comp following Spanish-language meeting on 5/30 @monika-jaeger** 
- [ ] Update guide card images [priority is to update the left image, with preference for both] to demonstrate more diversity/collaboration. Image should demonstrate broader than lab setting. Consider bringing in line with English comp.
- [ ] Update Cancer Moonshot promo block crop to match English
- [ ] Change feature card row heading to "Iniciativas y noticias"
- [ ] Update hero to align with English selection

_Awaiting Carolina review_
- [ ] Link update in right guide card
- [ ] Determine updated label for right guide card that is more representative of the content and fewer characters

**Comment by monika-jaeger** [comment]
All changes made to the [Spanish Research](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7002&type=design&node-id=142-10130&viewport=-3631%2C796%2C0.5&scaling=scale-down-width) comps.

- Updated [left image](https://www.istockphoto.com/photo/health-care-female-worker-in-hospital-with-computer-and-mri-gm1315172179-403212255) with image from iStock the team discussed yesterday. This image is currently watermarked, so we will have to purchase. Also updated the right image with an image from Visuals Online. If we don't like this one, I also have recorded the previous image if we want to change back to the women in the lab coat with test tubes.
- For the Cancer Moonshot Spanish graphic, do we have a source file for this? I looked in the [CMS and I only see a 4:3 crop](![image](https://github.com/NCIOCPL/ncids/assets/109552399/c2284ce5-9acb-453d-8e52-711b0f06a67b)). I added a solid color to the background of it for the comp, but we will need to find/create a 1:1 crop for this. 
- Updated hero image with the light blue image that Carolina preferred.

**Comment by laurelthrash** [comment]
**[English] Changes to comp following meeting on 6/6 @monika-jaeger**
- [ ] Replace hero with updated image (lighter version) prepared by Chuck
- [ ] Remove "Cancer" from in front of "Prevention" on left guide card
- [ ] Replace "Awareness Month" feature card with CCDI Content
