### ISSUE TITLE
[Updates/Revisions] About Cancer (Eng. and Span.) R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1001]
> META: #743 
> Creation Ticket (with source data/files): #761

### Description
Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

This ticket documents updates and revisions following the creation of the recommendations and associated comps.

### Sub-Tasks
- [x] Reply via to questions posed in the Mural board
- [x] Aggregate suggestions that require review/approval
    - [x] Make recommendations
    - [x] Make determination w/federal team regarding changes **05/22**
    - [x] Make updates following federal review
- [x] Update comps based on Review # 2
- [x] Update comps based on Spanish-language meeting 

### Notes
- Insert notes as needed

**Comment by monika-jaeger** [comment]
@laurelthrash All changes added to the [About Cancer](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=0%3A1&type=design&node-id=20-2546&viewport=982%2C-736%2C0.5&scaling=min-zoom) comps.
@adrianacastaneda I put in placeholders for the Stomach Cancer promo block and Feature Card Row for CIS resources for English and evergreen resources for Spanish. Let me know if you would like the order changed at all.

**Comment by laurelthrash** [comment]
**@monika-jaeger requested changes to the Spanish comp based on 6/1 Spanish-specific meeting:** 
- [ ] Left guide card: Change "Encuentre a un doctor o centro de tratamiento" to "Búsqueda de servicios médicos" 
- [ ] Replace image for "Cancer avanzado" since this image appears on several other pages

Cc: @adrianacastaneda

**Comment by monika-jaeger** [comment]
Updated guide card & selected a new image from iStock to add variety from the image that has been used on other pages. [Link to iStock photo](https://www.istockphoto.com/photo/shot-of-a-senior-man-supporting-his-wife-during-a-difficult-time-at-home-gm1357522267-431400344?phrase=sad+hug). Also updated the link/image in the [Image Audit](https://www.figma.com/file/x5x9fvmpwvVOdKWoa1tuPJ/R2.1-Landing-Pages-Image-Audit?type=whiteboard&node-id=42%3A10179&t=FhkS9IrV9gCZSG77-1).

cc @laurelthrash @adrianacastaneda

**Comment by laurelthrash** [comment]
**Changes based on 6/6 ODDC federal team sync @monika-jaeger @adrianacastaneda**
- [ ] Replace guide card image for "Newly Diagnosed" that gives equal attention to patient and provider
- [ ] Replace guide card image for "Treatment" to one that is not used for CCDI
- [ ] Replace feature card image for "Coping with Cancer" to one that shows people being supportive but not as light-hearted/celebratory as current image. Try for caring, facing future together.
- [ ] Replace feature card image for "Managing Cancer Costs" to one that is not already used for "Finding Trusted Resources." Suggestion: choose an image of a couple working together for managing cancer costs.
- [ ] Use existing image on live site for "Patient Education Publications" 
- [ ] Replace "Patient PDQ Summaries" with PDQ Cancer Information Summaries for Adult Treatment [https://www.cancer.gov/publications/pdq/information-summaries/adult-treatment]
