### ISSUE TITLE
Baseline Discovery: Modal

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#101]
## Baseline Discovery: Modal

Do baseline discovery for modals. 

Should consider known use in glossify functionality, and proposed use in future images/infographics. 

Component Details: https://www.notion.so/Modal-4e864c4e4042492c89f91755189b173c

- Findings should be captured in the Notion for discussion. 

> **ESTIMATE** TBD

## Tasks
Enabler
- [x] Investigation of further current uses (Claire)

Next Steps
- [x] Identification of any possible analytics or existing data around modals (Joe/Nicole)
- [x] High-level heuristic review of modals (Ashley)
- [x] Technical or accessibility flags (Paul A)

Optional
- Drupal reporting (Min)
- Best practices around modal use

### Resources
* Notion:  https://www.notion.so/Modal-4e864c4e4042492c89f91755189b173c

### Notes
*Some complementary notes if necessary:*

**Comment by claireblaustein** [comment]
Examples of current use beyond Glossify are now in notion document linked above.

**Comment by blilianyu** [comment]
We removed modals on Images and Infographics. I don't think we'll be considering modals again for them.
