### ISSUE TITLE
[R2.1 Content] CIS Language Differs from Comp (Homepage, About Cancer)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1044]
**Description:** Text for CIS in Production differs than what was outlined on our comps. 

**Recommendation:** In keeping with our decision to align with what was already approved, adopt the language used in production.

**Sub-tasks:**
- [x] Update language in all locations to reflect what is in production.
- [x] Receive approved language
- [x] Obtain approval on language from CIS
- [x] Obtain translation for Spanish pages (in progress)
    - https://tracker.nci.nih.gov/browse/CGOV-19895
- [x] Identify new promo image
- [x] Update new images and language on Cgov pages (2 EN, 2 SP)
    - [x] Homepage (English)
    - [x] Homepage (Spanish)
    - [x] About Cancer (English)
    - [x] About Cancer (Spanish)
- [x] Update the promo image for the Contact Us page

**Homepage Mural v3 Screenshot**

![Image](https://user-images.githubusercontent.com/102998716/245643832-388a505f-79c7-4221-ae08-7855ac92d677.png)

![Image](https://user-images.githubusercontent.com/102998716/245643862-989a6aa0-a8bd-46a8-bbec-77f26ccc2bd7.png)

**ACSF (ie production data) Screenshot**

![Image](https://user-images.githubusercontent.com/102998716/245643748-45873560-9fc0-42fd-bcde-92ee4d9d9671.png)

![Image](https://user-images.githubusercontent.com/102998716/245643774-854c5b95-6bd7-456f-9f90-ed08f61ef582.png)

**Comment by laurelthrash** [comment]
For time being, use language pulling from content and replace with the approved language/image once received. Goal to have updated/approved language prior to content launch.

**Comment by monika-jaeger** [comment]
Figma comps for [Homepage](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7001&type=design&node-id=142-7351&viewport=284%2C3050%2C0.5&scaling=min-zoom) and [About Cancer](https://www.figma.com/file/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?type=design&node-id=32%3A6750&t=xuT9156z1RZ6fkIO-1) are updated to reflect ACSF.
[Figjam](https://www.figma.com/file/x5x9fvmpwvVOdKWoa1tuPJ/R2.1-Landing-Pages-Image-Audit?type=whiteboard&node-id=0%3A1&t=OD4leJTLMnfGelfM-1) is updated with up to date screenshots

cc @laurelthrash

**Comment by adrianacastaneda** [comment]
@laurelthrash This was correct in ACSF and the content templates — just confirming! Thanks!

**Comment by laurelthrash** [comment]
Approved by Anna 7/10 in 3:30pm sync to move forward with the language and imagery approved in the H&L page promo blocks. Need to circle back to modify the newly approved inner page language for the H&L pages.

**Comment by driscollmd** [comment]
@laurelthrash The update copy for English is

**Get Answers**
Connect with a cancer information specialist at 1-800-4-CANCER, through live chat, or by email. 

Get Started (button)

**Comment by laurelthrash** [comment]
Received @driscollmd - as of right now, the CIS promo appears on the following pages:

1. Home page (English and Spanish)
2. About Cancer (English and Spanish)

**Comment by driscollmd** [comment]
@laurelthrash The generic copy can work on both home and about pages.

**Comment by laurelthrash** [comment]
Michael shared proposed copy with Anna for approval via Teams on 10/5. Upon approval, will submit for translation so as to update both pages (English and Spanish). Cc: @driscollmd

**Comment by chuckroseNIH** [comment]
Just putting the two images from the CIS Brochure here for now. I will prep them for use in the promot block and also find some alternatives to share. More to come!
![iStock-918294444](https://github.com/NCIOCPL/ncids/assets/51678055/90479b53-c80b-48cc-8d0b-72707f886ddc)
![iStock-926506596](https://github.com/NCIOCPL/ncids/assets/51678055/6072b2ac-4d0b-41d0-a76f-15a1bcf274da)

**Comment by laurelthrash** [comment]
Submitted Jira ticket for translation of the approved English language content: CGOV-19895. Cc: @driscollmd

**Comment by chuckroseNIH** [comment]
@laurelthrash @driscollmd Attached are 8 options for the CIS promo image. I comped these up on a page so they can be seen in context. I held off on doing the 16:9 version until they made a choice. These comps and this [Mural [](board](https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1698348902190/e3505fabb35be473c1aa2b303112e6e2775bbd09?sender=u9b26a7f5c6b98d9ebf919607)) should be plenty for that. Once decided I can crank out the actual images that will go into Dr
![CIS Promo-block-01](https://github.com/NCIOCPL/ncids/assets/51678055/f1801292-f1f6-4517-bf33-4e922789aa14)
![CIS Promo-block-02](https://github.com/NCIOCPL/ncids/assets/51678055/c54ca058-e7b9-49b0-9cb1-b7872a6bfa8b)
![CIS Promo-block-03](https://github.com/NCIOCPL/ncids/assets/51678055/152b4cbb-c9d6-4f44-9325-825c353fa219)
![CIS Promo-block-04](https://github.com/NCIOCPL/ncids/assets/51678055/a702e511-756f-44d7-8e53-eb24004709ea)
![CIS Promo-block-05](https://github.com/NCIOCPL/ncids/assets/51678055/7bcdd330-3e24-44cc-a494-a603b93abb0e)
![CIS Promo-block-06](https://github.com/NCIOCPL/ncids/assets/51678055/61e84836-168a-4d13-a848-a371943096a4)
![CIS Promo-block-07](https://github.com/NCIOCPL/ncids/assets/51678055/027e18cd-ca15-440d-bec9-b3be860dde56)
![CIS Promo-block-08](https://github.com/NCIOCPL/ncids/assets/51678055/7d3bf216-3dda-455c-b088-9d70fc3c37bc)
upal.[](url)

**Comment by laurelthrash** [comment]
Discussed possible options from Mural board (https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1698348902190/e3505fabb35be473c1aa2b303112e6e2775bbd09?sender=uc8881d65820946a13d002641) with CIS and Anna on 11/8/23. 

- Do not want to move forward with # 1 or # 2 - like engagement component but do not want to indicate that there is no confidentiality
- Option 1 has a "down" vibe
- Open to selecting an image of someone that is not looking directly at the camera and smiling/posed

Next step: pull together another few images and re-share.

**Comment by laurelthrash** [comment]
Closing out this ticket.

As of 12/20, the CIS promo blocks are updated with our image selection and revised text in both English and Spanish. The pages below reflect this update:

•	[Homepage (English)](https://www.cancer.gov/)
•	[Homepage (Spanish)](https://www.cancer.gov/espanol)
•	[About Cancer (English)](https://www.cancer.gov/about-cancer)
•	[About Cancer (Spanish)](https://www.cancer.gov/espanol/cancer)
•	 [“NCI’s Cancer Information Service” contact page](https://www.cancer.gov/contact) (English & Spanish) promotional image updated (reflected in CMS backend) 

Our final three images are added to the CMS in both English and Spanish. These CMS links are shared below for future reference:

•	[CIS promo image 1 (English)](https://www-cms.cancer.gov/media/1173561/edit)
•	[CIS promo image 2 (English)](https://www-cms.cancer.gov/media/1173566/edit)
•	[CIS promo image 3 (English)](https://www-cms.cancer.gov/media/1173571/edit)
•	[CIS promo image 1 (Spanish)](https://www-cms.cancer.gov/media/1173781/edit)
•	[CIS promo image 2 (Spanish)](https://www-cms.cancer.gov/media/1173786/edit)
•	[CIS promo image 3 (Spanish)](https://www-cms.cancer.gov/media/1173791/edit)
