### ISSUE TITLE
[R2.1 Content] About NCI - Guide Card Buttons Require Ampersand?

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1047]
**Description:** [About NCI](https://www-test-acsf.cancer.gov/about-nci) > NCI at a Glance guide card > Buttons. For “Advisory Board and Groups,” should use an ampersand? Please update to be “Advisory Board & Groups”

**Note:** This was approved by Anna in the ODDC testing document. 

**Sub-tasks:**
- [ ] Update in Figma comp (Monika)
- [ ] Update in content template (Adriana)
- [ ] Update in ACSF-test

**Comment by laurelthrash** [comment]
Assigning over to @monika-jaeger since @adrianacastaneda completed ACSF-test and content template.

**Comment by monika-jaeger** [comment]
Updated in [About NCI Figma Comps](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=21%3A4037&type=design&node-id=21-4038&viewport=543%2C332%2C0.25&scaling=min-zoom).

cc @laurelthrash

**Comment by laurelthrash** [comment]
Confirmed - closing out this ticket, thank you! Cc: @adrianacastaneda @monika-jaeger
