### ISSUE TITLE
[R2.1 Content] About NCI - Hero Image Pixel Verification

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1048]
**Description:** Reported by Bryan and Jorge that the hero image for About NCI has a lot of visual artifacts and is pixelated. Established during requirements meeting that this is a content issue and not a functional issue. 

**Next step:** Select a new image to resolve 1) pixilation, and 2) composition of people in the photo. Converting this into an ncids issue.   

**Sub-tasks:**
- [x] Identify new hero image (Monika and Chuck) [N/A - didn't actually pick a new image, rather, we identified the source file for the original image to create fresh crops]
- [x] Obtain approval from Anna/federal team [N/A - not new image]
- [x] Purchase image (if needed) [N/A - not new image]
- [x] Add to ACSF-test (Adriana)
    - [x] Verify that the updated crop fixes the pixelation issue (internal) (Monika, Chuck)
    - [x] Verify that the updated crop fixes the pixelation issue (federal)
- [x] Update content template (Adriana) - NOT NEEDED
- [x] Update Figma comps (Monika)
- [x] Update FigJam for images (Monika)
- [x] Add image to list to be updated in Production (Monika)

**Comment by chuckroseNIH** [comment]
@monika-jaeger I am checking with Kim Connell to see what still shots we have from a shoot done in the DCEG labs a few months ago. I'll keep you posted if I find some candidates for this.

**Comment by chuckroseNIH** [comment]
@monika-jaeger I went through Kim's stuff. Nothing there that will work well. But I did find the PSD for the shot that is up there now. And as Brian said, we can use Art Direction to manually crop an image for each breakpoint. So, you'll have fresh image to start with. https://lion.box.com/s/hw0cs451ehbj1vjtf5pqagdphooq3jp3

**Comment by laurelthrash** [comment]
@monika-jaeger to take new crops and re-upload to verify that it is a content issue.

**Comment by monika-jaeger** [comment]
Added updated images that are higher quality and optimized to the[ teams folder here](https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates/Images/About%20Cancer/[Hero](https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates/Images/About%20Cancer/Hero?csf=1&web=1&e=rXIP4h)?csf=1&web=1&e=rXIP4h)

@laurelthrash this is ready for images to be added to ACSF. cc @chuckhrose @adrianacastaneda

**Comment by laurelthrash** [comment]
@monika-jaeger - will you please review the Teams folder link as I am getting an error? Also, as I am sure you already have, but please make sure to note in the FigJam that we will need to update the files in production - thank you!

Once complete, @adrianacastaneda - will you please add to ACSF-test? 

FYI - @monika-jaeger I added a step to the sub-tasks to verify that the modified image fixes the pixelation issue.

**Comment by monika-jaeger** [comment]
Link Updated: https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates/Images/About%20Cancer/[Hero](https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates/Images/About%20Cancer/Hero?csf=1&web=1&e=OrEzgS)?csf=1&web=1&e=OrEzgS

**Comment by laurelthrash** [comment]
@adrianacastaneda tagging to please upload to ACSF-test

**Comment by adrianacastaneda** [comment]
Updated crops added to ACSF! Ready for you both @monika-jaeger @chuckhrose 

cc: @laurelthrash

**Comment by laurelthrash** [comment]
@monika-jaeger @adrianacastaneda Anna approved the widescreen view now that we have a high res image in place. This confirmed that no technical solution is needed for heros. 

Please proceed with next steps outlined in the ticket above. Cc: @meglake

**Comment by monika-jaeger** [comment]
Updated Figma comps for [About NCI](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=0%3A1&type=design&node-id=32-6750&viewport=-450%2C338%2C1&scaling=min-zoom).
Also updated [Figjam](https://www.figma.com/file/x5x9fvmpwvVOdKWoa1tuPJ/R2.1-Landing-Pages-Image-Audit?type=whiteboard&node-id=0%3A1&t=OD4leJTLMnfGelfM-1) to note images to be updated in prod
cc @laurelthrash @adrianacastaneda

**Comment by laurelthrash** [comment]
Received, @monika-jaeger. Marking this ticket as closed, as an update is not needed to the content template.
