### ISSUE TITLE
[R2.1 Content] About Cancer - Guide Card Label Update (x2)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1049]
**Description:** [About Cancer](https://www-test-acsf.cancer.gov/about-cancer) > Guide cards > Button labels. For the bottom buttons of each card, make the prepositions lowercase: “for” and “about.”

Left guide card: Change "Contact Us For Help" to "Contact Us for Help"
Right guide card: Change "Learn More About Treatment" to "Learn More about Treatment" 

**Sub-tasks:**
- [x] Update Figma comp (Monika)
- [x] Update content template (Laurel)
- [x] Update ACSF-test (Laurel)

**Comment by monika-jaeger** [comment]
Updated [About Cancer comps](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=0%3A1&type=design&node-id=20-2546&viewport=1132%2C120%2C0.5&scaling=scale-down-width) with button text changes.

**Comment by laurelthrash** [comment]
@monika-jaeger verified on comps - closing this ticket.
