### ISSUE TITLE
[R2.1 Content] About Cancer Spanish - Update Guide Card Label Button

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1050]
**Reported Issue:** [About Cancer (Spanish)](https://www-test-acsf.cancer.gov/espanol/cancer) > Tratamiento guide card > Button label. In the second-to-last button, change “clínic” to “clínicos.”

ACSF-test CMS: https://www-test-acsf.cancer.gov/espanol/cancer

- Comp already correct
- Content template already correct

**For Discussion:** Button text exceeds number of characters for the button. Need to determine a new button label with appropriate number of characters. 

**Sub-tasks:**
- [x] Determine recommendation (Adriana)
- [x] Discuss with Anna/federal team
- [ ] Assign next steps, as needed
- [ ] Update ACSF-test

**Comment by laurelthrash** [comment]
@adrianacastaneda - do you have a recommendation for how to handle this issue? Thank you!

**Comment by adrianacastaneda** [comment]
@laurelthrash I would suggest using the following override title for the link button: "Guía sobre como participar en estudios clínico"

**Comment by laurelthrash** [comment]
@adrianacastaneda - received, thank you! I'll run this by Anna/Carolina.

**Comment by laurelthrash** [comment]
Posted question to Carolina via Teams:

> ...are you comfortable adjusting the guide label that currently reads "Guía para entender y participar en estudios clínicos" to Guía sobre como participar en estudios clínico?" Or, do you have another suggestion? Unfortunately, we are 2 characters short from being able to use the first label that is currently represented in our comps.

**Comment by laurelthrash** [comment]
Text received from Carolina. Guide card text should be changed to "Información sobre estudios clínicos"

I verified that this is already updated in the Figma comps, content template, and on ACSF-test. Closing this ticket. Cc: @adrianacastaneda @monika-jaeger
