### ISSUE TITLE
[R2.1 Content] Research Spanish - Heading Discrepancy

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1052]
**Description:** Heading in ACSF-test is "Investigación del cáncer" while comp is "Investigación"

ACSF-test: https://www-cms-test.cancer.gov/research

**Sub-tasks:**
- [x] Determine root cause of the discrepancy 
- [x] Make recommendation on how to move forward
- [x] Align with Anna/federal team (as needed)
- [x] Implement in:
    - [x] Figma Comps (Monika)
    - [x] FigJam images board, as needed (Monika)
    - [x] Content template (Adriana)
    - [x] ACSF-test (Adriana)
    - [x] v3 Mural (Laurel)

**Comment by laurelthrash** [comment]
@adrianacastaneda - will you please investigate what the root cause of the discrepancy is and make a recommendation on the best path forward? Thank you!

**Comment by laurelthrash** [comment]
@adrianacastaneda - received. I'll add this in the bucket to talk with Anna about, and share that we'll want confirmation from Carolina.

**Comment by laurelthrash** [comment]
Use Investigación del cáncer

**Comment by laurelthrash** [comment]
Assigned over to @adrianacastaneda for final updates.

**Comment by adrianacastaneda** [comment]
@laurelthrash confirming this as noted in the content template and ACSF

**Comment by laurelthrash** [comment]
Received, thank you! Closing out this ticket. Cc: @monika-jaeger @adrianacastaneda
