### ISSUE TITLE
[R2.1 Content] About Cancer Spanish - Review Feature Card Text

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1055]
**Description:** Third feature card on "Recursos para pacientes" feature card text differs in comps compared to ACSF-test. 

https://www-test-acsf.cancer.gov/espanol/cancer# 

**Sub-tasks:**
- [x] Determine root cause of the discrepancy 
- [x] Make recommendation on how to move forward
- [x] Align with Anna/federal team (as needed) [N/A since we received pre-approval from Anna to align feature card titles/descriptions with CMS language]
- [x] Implement in:
    - [x] Figma Comp (Monika)
    - [x] Content Template (Laurel - already correct, but verified)
    - [x] ACSF-test [N/A since already correct in ACSF-test]
    - v3 Mural Board (Laurel) N/A since it is an alignment with the CMS approved language, which is pre-approved with Anna

**Comment by laurelthrash** [comment]
@adrianacastaneda - will you please investigate what the root cause of the discrepancy is and make a recommendation on the best path forward? Thank you!

**Comment by adrianacastaneda** [comment]
During stakeholder review, we decided to focus on the treatment page PDQ summaries (switching these out for other types of summaries like screening, causes & risks, etc. later on based on analytics) so the correct card title is the one shown in ACSF 

@monika-jaeger please update card title to the below. Thank you! 

**Card title:** Resúmenes de información del PDQ® sobre el cáncer: Tratamiento en adultos 

cc: @laurelthrash

**Comment by laurelthrash** [comment]
@monika-jaeger Looks like Mural board still shows the old title - will you please update then mark this ticket as closed? Thank you! Cc: @adrianacastaneda

**Comment by monika-jaeger** [comment]
@laurelthrash this is now updated in the [About Cancer Spanish comp](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=0%3A1&type=design&node-id=32-6750&viewport=-64%2C293%2C0.5&scaling=scale-down-width). Would you like me to add a new image to the Mural board before closing it out?

**Comment by laurelthrash** [comment]
@monika-jaeger - apologies, will you please clarify which Mural you are referring to?

**Comment by monika-jaeger** [comment]
@laurelthrash sorry you can ignore that, I realized in the description the Mural Board task is marked as n/a, so disregard!

**Comment by laurelthrash** [comment]
Received! I'll go ahead and close this one out - thank you, @monika-jaeger.
