### ISSUE TITLE
[R2.1 Content] G&T and About Cancer Hero Images - Image Pixelated

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1056]
**Status:** Track down the original image. Make new crops. Monika upload to determine if the new crop resolves the issue.  Will impact all heros except new heroes (HP and Research):

- Grants and Training
- About Cancer
- About NCI (addressed in #1048)

**Description:** Grants and Training: https://www-test-acsf.cancer.gov/grants-training and https://www-test-acsf.cancer.gov/espanol/subvenciones-capacitacion 

Content: Pixelated Hero image 

**Sub-tasks:**
- [x] Identify original image and make new crops
    - [x] G&T 
    - [x] About Cancer
- [x] Upload to ACSF-test to ensure pixelation is resolved with updated crops
    - [x] G&T
    - [x] About Cancer
- [ ] Update for G&T:
    - [x] Figma Comps (Monika)
    - [x] FigJam images board, as needed (Monika)
    - [ ] Content template (Adriana)
    - [ ] ACSF-test (Adriana)
    - [x] v3 Mural (Laurel) - NOT NEEDED, SAME IMAGE
- [ ] Update image for About Cancer
    - [x] Figma Comps (Monika)
    - [x] FigJam images board, as needed (Monika)
    - [ ] Content template (Adriana)
    - [ ] ACSF-test (Adriana)
    - [x] v3 Mural (Laurel) - NOT NEEDED, SAME IMAGE

**Comment by monika-jaeger** [comment]
Grants & Training Image source: https://visualsonline.cancer.gov/details.cfm?imageid=10283

Grants and Training crops are ready to be added to ACSF test from Teams folder here: https://nih.sharepoint.com/:f:/s/NCI-OCPLNewCgovUXDesignSystem/EqOZ8f12m4JBvuyIumWOAgcBcGYplEEDwYmLEborP_4TVQ?e=EZaJEX

Grants and Training images are ready to be added to ACSF @laurelthrash

**Comment by monika-jaeger** [comment]
About Cancer Image Source: https://visualsonline.cancer.gov/details.cfm?imageid=10279

About Cancer crops are ready to be added to ACSF test from Teams folder here: https://nih.sharepoint.com/:f:/s/NCI-OCPLNewCgovUXDesignSystem/EivOLY3cy41JhsArrWcClecBKtev8aypw0S2QlDT49wB2g?e=NoyQQl

About Cancer images are ready to be added to ACSF @laurelthrash

**Comment by monika-jaeger** [comment]
About Cancer Image Source: https://lion.box.com/s/hw0cs451ehbj1vjtf5pqagdphooq3jp3

About NCI crops are ready to be added to ACSF test from Teams folder here: https://nih.sharepoint.com/:f:/s/NCI-OCPLNewCgovUXDesignSystem/Ekw1VPlPj9VJjIJ3ig5frs4B8W3IzYHt7PB_gqvgjMVtxw?e=e9nMO2

**Comment by adrianacastaneda** [comment]
heroes for both About Cancer and G&T are updated! @monika-jaeger @laurelthrash

**Comment by laurelthrash** [comment]
Anna approved the widescreen view of the home page image and confirmed that it looks good now that we have a high res image in place. This confirmed that no technical solution is needed for heros. Converting this to a content ticket to handle separately. Cc: @meglake @adrianacastaneda @monika-jaeger

**Comment by laurelthrash** [comment]
Confirming if these images are approved for content launch, knowing that if we want to update them later on it is not dependent on a technical fix.

**Comment by laurelthrash** [comment]
Confirmed via Slack that these images are fine as-is for content launch. 

@monika-jaeger @adrianacastaneda please proceed with making the appropriate updates noted in the description.

**Comment by monika-jaeger** [comment]
Updates made to comps/Figjam. @laurelthrash @adrianacastaneda 

- [Grants & Training comps](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A11354&type=design&node-id=142-11355&viewport=329%2C761%2C0.25&scaling=min-zoom)
- [About Cancer comps](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=0%3A1&type=design&node-id=32-6750&viewport=-450%2C338%2C1&scaling=min-zoom)
- [Figjam image audit](https://www.figma.com/file/x5x9fvmpwvVOdKWoa1tuPJ/R2.1-Landing-Pages-Image-Audit?type=whiteboard&node-id=0%3A1&t=OD4leJTLMnfGelfM-1)

**Comment by laurelthrash** [comment]
Per comment from @adrianacastaneda [here](https://github.com/NCIOCPL/ncids/issues/1056#issuecomment-1593484427), marking the associated checkboxes complete and closing this ticket. No changes are needed on the content templates. Cc: @monika-jaeger
