### ISSUE TITLE
Set lerna version to 6.6.2

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1062]
Workflow throws a new error

```
Run lerna bootstrap -- --frozen-lockfile
ERR! bootstrap The "bootstrap" command was removed by default in v7, and is no longer maintained.
ERR! bootstrap Learn more about this change at https://lerna.js.org/docs/legacy-package-management
Error: Process completed with exit code 1.
```

Ubuntu20 version 20230611.1 bumped lerna versions from 6.6.2 to 7.0.0, see related links. Locally, the repo has a dev dependency for lerna version 4.0.0. For now, the repo should be updated so that the version is set back to 6.6.2 and then later the team will work on how to update to lerna 7, as this appears to require an update in package manager tooling.

### Tasks
- [ ] Set workflow version back to 6.6.2
- [ ] Update dev dependency to 6.6.2 to match ci. 
- [ ] Update #360 with next steps

### Related Tickets
* #360

### Related Links
* https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#project-management
