### ISSUE TITLE
Image Aggregation Part 2 for Image Issues (Spreadsheet)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1064]
> Related Ticket: #999

**Description:** Need to build on the initial image aggregation completed in preparation for creation of our content template. Need to create a spreadsheet that lists all of the images going into our R2.1 home and landing pages, including which images are pixelated/need remediation. 

As discussed, for images that are pixelated or less than ideal, we want to work with content owners to update those image (either get the source file to see if the image crop can be improved, or find a new high res image to replace it).

**Sub-tasks**
- [x] Create spreadsheet (Monika) [Link to spreadsheet](https://nih.sharepoint.com/:x:/s/NCI-OCPLNewCgovUXDesignSystem/EbAiP_dJrO9AqwculDwj3wgBIAtPuQlYKGQoHs1j886BGA?e=7crV6k).
- [x] Review spreadsheet (Adriana/Laurel)
- [x] Share with Anna/federal team to identify content owners (Laurel)
- [ ] Remediate images as needed

**Comment by monika-jaeger** [comment]
Added [link to spreadsheet](https://nih.sharepoint.com/:x:/s/NCI-OCPLNewCgovUXDesignSystem/EbAiP_dJrO9AqwculDwj3wgBIAtPuQlYKGQoHs1j886BGA?e=7crV6k) above in the description.

**Comment by laurelthrash** [comment]
Sending to Anna via email the morning of Tues. 6/27 for review.

**Comment by laurelthrash** [comment]
@monika-jaeger - As discussed, the only outstanding images with potential issues are those for the rotating feature card content on the home pages, for which we will address after building out the draft pages. Closing out this ticket.
