### ISSUE TITLE
[R2.1 Content] Home Page English - Update Guide Card Link Language

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1070]
**Description:** Per testing completed by ODDC, determined we will update the "People Affected by Cancer" guide card link that currently reads "Treatment & Side Effects" to instead read "Side Effects of Treatment"  

**Sub-tasks:**
- [x] Update on ACSF-test (Laurel)
- [x] Update on v3 Mural board (Laurel)
- [x] Update on content template (Laurel)
- [x] Update on comp (Laurel)

**Comment by laurelthrash** [comment]
@monika-jaeger @adriancofie Tagging you as an FYI that this change was made. I updated in all locations. Closing out the ticket. Thank you!
