### ISSUE TITLE
[Updates/Revisions] NCI-CONNECT (Eng. and Span.) R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1072]
> META: #743 
> Creation Ticket (with source data/files): #759

### Description
Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

This ticket documents updates and revisions following the creation of the recommendations and associated comps.

### Sub-Tasks
- [x] Reply via to questions posed in the Mural board (if applicable) - N/A, no other questions outside of those asked during the stakeholder meeting
- [x] Aggregate suggestions that require review/approval
    - [x] Make recommendations
    - [x] Make determination w/federal team regarding changes
    - [x] Make updates following federal review
- [x] Update comps based on Review # 2
- [x] Update comps based on Spanish-language meeting (if applicable)

**Comment by laurelthrash** [comment]
**Updates following 6/22 ODDC discussion below** _Note: Decided we will make two versions (v1 and v2) to show the stakeholders_

Changes to both v1 and v2
- [ ] Change left guide card title to "Patients"
- [ ] Change right guide card title to "Providers and Advocates"
- [ ] Update guide card links to reflect those in the Word document (linked below)
- [ ] Replace "&" with "and" in "NCI-CONNECT Rare Brain & Spine Tumor Network"
- [ ] Remove "Patient Resources" feature card
- [ ] Add a new "News and Information" feature card row (suggested in Word doc) below "Cancer Care and Support Resources" guide card
    - [ ] Use feature cards outlined in Word document
- [ ]  

Updates on v1 only
- [ ] Change CTA button from "Explore Clinical Studies" to "Explore Clinical Care" 
- [ ] Include new promo block for "Contact Us" (as outlined in the Word doc)

Updates on v2 only
- [ ] Make guide card description text more actionable (language provided by @adrianacastaneda)
- [ ] Change CTA button from "Explore Clinical Studies" to "Request a Referral" 
- [ ] Adjust order of feature cards under "Cancer Care and Support Resources" to be Newly Diagnosed > Guiding Questions (new) > Having a Recurrence
- [ ] Suggest more descriptive title for "News and Information" feature card row (language provided by @adrianacastaneda)

Reference Word document found here: [NCI-CONNECT Landing Page Components EDITS.docx](https://github.com/NCIOCPL/ncids/files/11860594/NCI-CONNECT.Landing.Page.Components.EDITS.docx)

**Comment by dcvijanovic1k** [comment]
hi @laurelthrash @adrianacastaneda - all the updates have been made, except for the ones where Adriana has outstanding items she needs to address.

**Comment by adrianacastaneda** [comment]
@dcvijanovic1k News and Information feature card row attributes are below. 

Feature card row heading: News and Advances 

Title: Bringing the Patient, Caregiver, and Advocate Voice to Clinicians and Researchers
Description: Adam Hayden and Kimberly Wallgren visited NIH to share their invaluable perspectives.
Promo image: https://nciconnect-cms.cancer.gov/rare-brain-spine-tumor/rare-brain-spine-tumor/sites/g/files/xnrzdm226/files/cgov_image/media_image/2023-06/Adam-Hayden-Thumbnail.jpg

Title: Advancing the Science of Survivorship in Neuro-Oncology
Description: Dr. Terri Armstrong joined fellow leaders in the field of cancer survivorship.
Promo image: the same as one in comp

Title: Research Nurse Offers Help, Hope, and a Friendly Voice to People with Rare Brain and Spine Tumors
Description: Research Nurse Tricia Kunst joined the Neuro-Oncology Branch in February 2022 after 21 years in the Thoracic Surgery Branch. She shares what she loves most about her job and the people she gets to meet along the way.
Promo image: https://nciconnect-cms.cancer.gov/rare-brain-spine-tumor/sites/g/files/xnrzdm226/files/styles/cgov_article/public/cgov_image/media_image/2023-04/Tricia_Kunst_and_Patient.jpg?h=ed003dfc&itok=7rV3v314

cc: @laurelthrash

**Comment by laurelthrash** [comment]
Received internal sign-off via Slack 6/29.

**Comment by laurelthrash** [comment]
Determined the following changes during our ODDC sync on 7/18: 

- [ ] Merge back to one comp (remove Option A and Option B)
- [ ] Revert CTA button label to "Explore Clinical Care"
- [ ] Update right guide card description text to: Discover resources for providers and advocates to offer patients with brain and spine tumors a comprehensive clinical care plan.
- [ ] Update left guide card description text to: Learn more about consultations, explore clinical studies, and discover strategies to help manage living with a brain or spine tumor.
- [ ] Remove "Explore Research Advances" from right guide card. Add "Explore Research Advances" as a promo block and update title/desc. to more clearly denote that it is a blog. Place this below news and advances.

**Comment by laurelthrash** [comment]
Updated comps approved internally via Slack 7/20. @laurelthrash to add to the v3 Mural board.

**Comment by laurelthrash** [comment]
Sent Mural board on 7/21. Closing this ticket as all sub-tasks are complete. Will open a new ticket with any subsequent changes to the pages/comps. Cc: @adrianacastaneda @dcvijanovic1k
