### ISSUE TITLE
[R2.1 Content] About Cancer (English and Spanish) - Guide Card Image Update "Treatment"

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1073]
**Description:** On the About Cancer landing page (English and Spanish), we added "Support for Families when a Child has Cancer" into the feature card row. This page has a promotional image already in the CMS that looks similar to the image selected for the "Treatment" guide card. Team suggested a new image and is awaiting confirmation from the federal team that they are comfortable moving forward with the new image.

**Sub-tasks:**
- [x] Share recommendation with Anna [Laurel]
- [x] Share with stakeholders and align on solution [Anna]
- **6/28:** Anna approved new image ([Nurse Giving Patient Injection stock photo](https://www.istockphoto.com/photo/nurse-giving-patient-injection-gm96649383-11815613))
    - [x] Figma Comps (Monika)
    - [x] Image spreadsheet (Monika) 
    - [x] Update content template with new image location, as needed (Monika) 
    - [x] ACSF-test (Laurel) 
    - [x] v3 Mural board (Laurel)
- [ ] Obtain new alt text for the image
    - [x] Draft alt text (Adriana)
    - [x] Send to Anna for approval (Laurel) [N/A - already in the CMS]
    - [x] Translate alt text
    - [ ] Update on content templates - Eng. and Span. (Laurel)

**Similar Images:**

![Image](https://github.com/NCIOCPL/ncids/assets/102998716/f309eb98-5bbc-49d3-9645-d03a43f1be6e) 

**Initial Image (NOT ADOPTED):**

![Image](https://github.com/NCIOCPL/ncids/assets/102998716/414c92e1-1605-4d2a-9b97-0b354dc66b7a)

**Comment by laurelthrash** [comment]
Stakeholders asked if there is an image less "forbidding" / something more "personal/reassuring." Exploring different options for this image. Cc: @monika-jaeger

**Comment by monika-jaeger** [comment]
Link to new image to consider: https://www.istockphoto.com/photo/nurse-giving-patient-injection-gm96649383-11815613

cc @laurelthrash @chuckhrose

**Comment by laurelthrash** [comment]
Anna approved use of the new image (https://www.istockphoto.com/photo/nurse-giving-patient-injection-gm96649383-11815613) for the "Treatment" guide card and confirmed this image should be used for both English and Spanish.

@monika-jaeger please see subtasks outlined in the description of the ticket.

**Comment by monika-jaeger** [comment]
Images have been updated in [Figma](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=0%3A1&type=design&node-id=20-2546&viewport=1099%2C280%2C0.5&scaling=min-zoom&mode=design). Also updated the [R2.1 Image Evaluation Sheet](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/R2.1%20Image%20Evaluation.xlsx?d=wf73f22b0ac4940efab072e943c23df08&csf=1&web=1&e=Y9P03I).

I updated the [English About Cancer](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates/About%20Cancer_Landing%20page%20content%20template_English.docx?d=wb04e36b102ec41d193ef96cab27121d5&csf=1&web=1&e=UvED7v) and [Spanish About Cancer](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates/About%20Cancer_Landing%20page%20content%20template_Spanish.docx?d=w77c1f116daa5467c9fc8db5bfc4b4cd9&csf=1&web=1&e=jlbpMf) content templates. I also noted that we will need new alt text for the English and Spanish images with notes. cc @adrianacastaneda @laurelthrash

**Comment by laurelthrash** [comment]
Updated in ACSF-test and on the v3 Mural.

@adrianacastaneda will you please propose alt text for the new image?

**Comment by adrianacastaneda** [comment]
@laurelthrash this image is actually already used in the CMS and has the alt text below:

health professional gives patient drug through IV

cc: @monika-jaeger

**Comment by laurelthrash** [comment]
@adrianacastaneda Oh, that is great! 
@monika-jaeger will you please update the image tracker with this information? I'll submit the alt text for translation.

**Comment by monika-jaeger** [comment]
Good eye, @adrianacastaneda !
Updated information in [R2.1 Image Evaluation](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/R2.1%20Image%20Evaluation.xlsx?d=wf73f22b0ac4940efab072e943c23df08&csf=1&web=1&e=dUB6iv): lines  40 & 52

cc @laurelthrash

**Comment by laurelthrash** [comment]
Alt text received (Una profesional de la salud administra a una paciente un medicamento por infusión intravenosa.) Added to the content template. Alt text is now reflected on both Eng. and Span. content templates. Closing this ticket. Cc: @adrianacastaneda @monika-jaeger

**Comment by laurelthrash** [comment]
@monika-jaeger apologies, prior to closing this - will you also please update the Teams folder? Looks like Teams still has the version with a watermark? Thank you!

**Comment by monika-jaeger** [comment]
@laurelthrash Updated image in [Teams folder](https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates/Images/About%20Cancer/Guide%20Cards/[jpgs](https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Content%20Templates/Images/About%20Cancer/Guide%20Cards/jpgs?csf=1&web=1&e=f6XJqO)?csf=1&web=1&e=f6XJqO). Also update the [Figma comp](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=0%3A1&type=design&node-id=58-6479&viewport=594%2C-202%2C0.5&scaling=min-zoom&mode=design&t=7FMVRaAerF8kFsCy-1) with a non watermarked image.

**Comment by laurelthrash** [comment]
@monika-jaeger - received! Closing this ticket now, thank you.
