### ISSUE TITLE
[R2.1 Content] Confirm Content for Rotating Feature Card Content

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1074]
**Description:** Per R2.1 content launch schedule, need to solidify the feature card row content that is intended to be added to the rotating/timely feature card rows ahead of launch.

**Sub-tasks:**
- [x] Create tracker for featured content [Laurel]
- [x] Review tracker [Lindsay]
- [x] Send tracker to ODDC for dissemination [Anna] 
- [x] Feature card team complete the tracker by **Decision made for next steps (see comment) on 7/5**
    - Includes Feature Cards and Promo Block (Stomach Cancer)
- [x] Update the home page (English and Spanish) with the featured content from the current News and Events page in the following locations:
    - [x] Content template (English) (Laurel)
    - [x] Content template (Spanish) (Adriana)
    - [x] ACSF-test (English) (Laurel) **[N/A - pages have not been copied down to ACSF-test from Prod]**
    - [x] ACSF-test (Spanish) (Adriana) **[N/A - pages have not been copied down to ACSF-test from Prod]**
    - [x] Figma comps (Monika)
    - [x] Image Excel Tracker (Monika)
    - [x] v3 Mural board (Laurel)  **[N/A - already noted on v3 Mural]**
- [x] Verify none of the new feature card images have quality concerns **[7/5 - Monika]**
    - [x] Sent two issue images to Anna for review
    - [x] Update accordingly (per Anna, we will not remediate these images at this time, rather, will build out the pages on 7/10 and review images at that time)
- [x] Verify if changes were made to the featured content and update in all locations, as needed **[7/10]**
    - [x] Content template (Adriana)
    - [x] ACSF-test (Adriana) **[N/A - pages have not been copied down to ACSF-test from Prod]**
    - [x] Figma Comps (Monika)
    - [x] Image Excel tracker (Monika)

**Comment by laurelthrash** [comment]
Decision shared from Anna via email on 7/5. Next Steps outlined in the description o f this card. 

**Home page (Eng. and Span.)**
- For the immediate future, the 3 feature cards on both the English and Spanish homepages should match the 3 feature cards on the News & Events landing pages.
- For the Thu 7/13 launch, we’ll use the 3 feature cards that are on the News & Events landing page as of Monday 7/10 for both English and Spanish homepages.

**All other pages**
- We will launch with the feature cards and promo blocks included in the approved comps.

**Comment by monika-jaeger** [comment]
[English comps updated](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7001&type=design&node-id=142-7351&viewport=138%2C1748%2C0.25&scaling=min-zoom&mode=design&t=sqWfUMD1vutoRsTn-1)
- Image that may be a concern: Feature Card for "How Cells Reverse Their Decision to Divide" appears to be low resolution. 

[Spanish comps updated](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7001&type=design&node-id=142-8600&viewport=138%2C1748%2C0.25&scaling=min-zoom&mode=design&t=sqWfUMD1vutoRsTn-1)
- Image that may be a concern: Feature Card for "Se afirma el beneficio de la inmunoterapia después de la cirugía de cáncer de vejiga" appears to be low resolution. 

Do we go forward with these images? They appear to be scientific images are are not particularly high quality on the pages themselves.

cc @laurelthrash @adrianacastaneda

**Comment by laurelthrash** [comment]
@monika-jaeger - received. I am going to update ACSF-test to verify how they appear there. Cc: @adrianacastaneda

**Comment by laurelthrash** [comment]
Asked Anna via Teams how she wishes to handle the two images flagged (rows 6 & 21 of our spreadsheet). Cc: @monika-jaeger

**Comment by laurelthrash** [comment]
@adrianacastaneda confirmed that the feature card content templates for the homepage have been updated to the three features from the News and Events page for both English and Spanish as of 7/10 at approx. 2:30pm.

**Comment by laurelthrash** [comment]
Verified on 7/11 at 10am ET that the featured items on the Production News and Events page match the featured items on the draft home page (English and Spanish). Closing this ticket. Cc: @adrianacastaneda @monika-jaeger
