### ISSUE TITLE
Update Images from PNG to JPEG

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1075]
**Description:** Determined that we need to update R2.1 home and landing pages images that are PNGs to JPEGs.

**Sub-tasks:** 
- [x] Replace PNG images in our Teams folder with JPEG (Start with English home page), exclude:
    - Image already in the CMS
    - NCP Image
- [x] Notify Bryan/devs once complete, so they can move forward with PR1065 / re-run page speeds
- [ ] Think through set of guidelines or refresher for what file format to save as in the future (e.g., select format with smaller file sized based on size target/limit) [Laurel]

**Comment by monika-jaeger** [comment]
About NCI images re-exported: https://nih.sharepoint.com/:f:/s/NCI-OCPLNewCgovUXDesignSystem/En2KBIY7YR1BkJWSHA9EoBYB9l1uVRynSC6TplNQ1aPMmw?e=etNrIf

cc @laurelthrash

**Comment by monika-jaeger** [comment]
About Cancer images re-exported: https://nih.sharepoint.com/:f:/s/NCI-OCPLNewCgovUXDesignSystem/ErW6bsryMsRFip-QhZ6MwcIBAY0u4NeMvP6H_mXxwu0ntw?e=jHCycI

cc: @laurelthrash

**Comment by monika-jaeger** [comment]
Research images re-exported: https://nih.sharepoint.com/:f:/s/NCI-OCPLNewCgovUXDesignSystem/Er4W5EEg2nVCuVw-5vTNke4BdQYUItIeVjx2--i6xaXZrQ?e=x79eV5

Note: for Spanish Research... The Cancer Moonshot graphic will need to remain a PNG. The background has a gradient.
cc: @laurelthrash

**Comment by monika-jaeger** [comment]
Grants & Training images re-exported: https://nih.sharepoint.com/:f:/s/NCI-OCPLNewCgovUXDesignSystem/EsdfT4_TfzJDu1rz7mj3x3UBJ52acFq4XeiVaIkKB3gJNw?e=b2fzmM

This should now include all images uploaded to Teams folders for the landing pages.
cc: @laurelthrash

**Comment by laurelthrash** [comment]
@monika-jaeger - seeing that all of the images for the 5 pages are exported, I am going to move the brainstorm to a standalone ticket, and close this out.
