### ISSUE TITLE
[Updates/Revisions] Nano (Eng.) R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1077]
> META: #743 
> Creation Ticket (with source data/files): #755

### Description
Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

This ticket documents updates and revisions following the creation of the recommendations and associated comps.

### Sub-Tasks
- [x] Reply via to questions posed in the Mural board (if applicable) - N/A, no other questions outside of those asked during the stakeholder meeting
- [x] Aggregate suggestions that require review/approval
    - [x] Make recommendations
    - [x] Make determination w/federal team regarding changes
    - [x] Make updates following federal review
- [x] Update comps based on Review # 2
- [x] Update comps based on Spanish-language meeting (if applicable) **[N/A - no Spanish for Nano]**

**Comment by laurelthrash** [comment]
**Changes to comps based on 06/20 stakeholder meeting:**
- [ ] Ensure that labels on the guide cards use the page title (as opposed to overrides) as Nano expressed desire for this to be updated automatically when content is added to the guide card.
- [ ] Add Annual Meeting promo block - include placeholder text for the time being.

**Comment by laurelthrash** [comment]
Anna to send additional changes on 6/28 provided by Nano via email.

**Comment by adrianacastaneda** [comment]
@a-heirtzler I've added the page titles below... There are a few that I would still recommend that they use the override that we recommended in the comp. 

@laurelthrash, we'll go ahead and add the page titles to the button links but I'd like to send the below override recommendations to them. 

**Cancer and Nanotech:**

1. Benefits of Nanotechnology for Cancer — _Would still recommend override be: Benefits of Nanotechnology_ 
2. Earlier Detection and Diagnosis  
3. Treatment and Therapy
4. Current Nanotechnology Treatments
5. Safety of Nanotechnology Cancer Treatment — _Would still recommend override be: Safety of Nanotechnology_ 

**Research:**

1. Nanotechnology Characterization Laboratory (NCL) — _Would still recommend override be: Nanotechnology Characterization Laboratory_
2. Data Sharing
3. Companies Formed by PIs of the NCI Alliance for Nanotechnology in Cancer — _Would still recommend override be: NCI Alliance Companies_
4. Related NCI Funding and Initiatives

Promo block: 
We only have access to their [2019 Annual meeting](https://www.cancer.gov/nano/news-events/events/2019-alliance-pi-meeting). There was no current feature card description so I've added the following placeholder text— this is NOT approved by the client. I also recommend that they add a bit more detail about the purpose of the event to the description and page. 

Heading: NCI Nano Alliance PI Meeting
Description: Annual Cancer Principal Investigators’ Meeting for the NCI Alliance for Nanotechnology in Cancer held on September 24 to 26, 2019.
Button: Learn more

**Comment by laurelthrash** [comment]
**Additional changes from Nano team received by email and shared via Anna 6/28:**
- [ ] Change right CTA button to "Apply for NCI Nanotechnology Funding"
- [ ] PI Promo block 
    - [ ] Add possible placeholder image
    - [ ] Change title to: NCI Alliance for Nanotechnology in Cancer Annual Principal Investigator Meeting
    - [ ] Change description to: Alliance investigators and collaborators will convene on October X-Y, 2023 to present their recent research results and discuss emerging opportunities in cancer nanotechnology.
    - [ ] Add above the guide cards

**Comment by laurelthrash** [comment]
Approved internally via Slack on 6/29.

**Comment by laurelthrash** [comment]
Determined the following changes during our ODDC sync on 7/18

- [ ] Make two options (Option A = requested changes, Option B = recommended changes) for the comps

Both Comps
- [ ]

**Comment by laurelthrash** [comment]
Shared for final internal review via Slack 7/20. @a-heirtzler @adrianacastaneda

**Comment by laurelthrash** [comment]
Approved internally via Slack on 7/21. Will add to the v3 Mural board and share with ODDC for dissemination to Nano.

**Comment by laurelthrash** [comment]
Sent Mural board on 7/21. Closing this ticket as all sub-tasks are complete. Will open a new ticket with any subsequent changes to the pages/comps. Cc: @adrianacastaneda @a-heirtzler @dcvijanovic1k
