### ISSUE TITLE
R2.1 Content Launch CMS User Email

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1078]
### Description
Draft email to be shared with CMS users the day of R2.1 content launch. This should be an explanatory email that points them to documentation, as needed. Needs to include mention of the 16x9 crop. 

**META:** https://github.com/NCIOCPL/cgov-digital-platform/issues/3317

### Subtasks
- [x] Draft email
- [x] Review/revise internally
- [x] Share with federal team for review
- [x] Update accordingly [N/A]
- [x] Add to content launch checklist

**Comment by laurelthrash** [comment]
Sent to Anna via email for review 7/6.

**Comment by laurelthrash** [comment]
Draft message approved by Anna with no suggested edits on Mon. 7/10 via email. Closing this ticket.
