### ISSUE TITLE
R2.1 Updates to Branding/Logo Guide on MyNCI

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1079]
### Description
Determine required updates to the Branding/Logo Guide on MyNCI (https://mynci.cancer.gov/topics/nci-branding-and-logo-use-guide) based on updates made during R2.1. Then, make changes to the PDF and implement the updated information on MyNCI following the R2.1 content launch.

**META:** https://github.com/NCIOCPL/cgov-digital-platform/issues/3317

### Sub-tasks
- [x] Review Branding/Logo Guide to determine needed updates
- [x] Outline specific updates
- [x] Obtain internal approval of updates
- [x] Obtain federal approval of updates
- [x] Make specified changes following federal team review
- [x] Obtain final approval
- [x] Schedule update to MyNCI on Thurs. 07/13 [JIRA CGOV-19176]

### Resources
- Insert final updated guide once complete: INSERT HERE

**Comment by laurelthrash** [comment]
**Notes from 7/6 conversation:**
- Note that luminance will be updated 
- Only need to update screenshot with Cgov, not DCEG since we have not implemented R2.1 for microsites

**Comment by laurelthrash** [comment]
Approved by Anna 7/10 in 3:30pm sync. Requested that this document goes through a review for 508 remediation. Anna comfortable posting as-is and reposting with an updated version.

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - here is the PDF for you! Please let me know if you have any questions or comments.
[NCI-Branding-and-Logo-Use-Guide-0723.pdf](https://github.com/NCIOCPL/ncids/files/12017309/NCI-Branding-and-Logo-Use-Guide-0723.pdf)

**Comment by laurelthrash** [comment]
Posted to MyNCI via JIRA CGOV-19176. Closing out this ticket.
