### ISSUE TITLE
Guidelines/refresher for file format exports

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1081]
**Description:** During 6/27 Redesign meeting, noticed that some images were exported as PNG instead of JPEG (as well as note being optimized) which causes size issues for loading the page. Determined we would like to think through set of guidelines or create refresher documentation for what file format to save files in the future.

**Related to:** #1075 

**Audience:** Internal team for quick guidance

**Sub-tasks:** 
- [x] Set time to discuss internally on best solution (e.g., shared document, Mural)
    - Recommendation: start with Word doc to save and share/pin 
- [x] Establish best practices for format (size, file type), optimization, and file naming conventions
    - [x] Clarify best practices based on final location (e.g., Drupal generally, NCIDS home and landing pages, NCIDS Documentation Site)
    - [x] Clarify best practices based on image (e.g., headshot, logo, stock photo)
    - [x] Include guidance on transparent images and images with gradients 
- [x] Save to appropriate designer folder/location
    - Same location as blended logo guide?

**Comment by laurelthrash** [comment]
Created Word document and saved to Box (Creative > File Format Best Practices). Will share with internal UX team week of 11/13. Closing out this ticket.
