### ISSUE TITLE
NCIDS For All Pilot - Finalize Figma Files (Primary)

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#1082]
### Tasks
- [x] The inventory for the components to be shown on the Figma, will be the components listed on the DS Documentation Site listed under "Components". (This excludes the USWDS pass through components
- [x] Finalize Figma with these components
- [x] QA by design [Shared via Slack 7/20 for @a-heirtzler @dcvijanovic1k @blilianyu]
- [x] QA by dev [Shared via Slack 7/20 for @dlescarbeau @karlikpj @olitharp-nci @arcepaul @bryanpnih review]
- [x] Update accordingly
- [x] Review with Client

### Resources:
* DS Documentation Site Link: https://designsystem-dev.cancer.gov/develop/
* Adding Link to Documentation Site Ticket: #933 

### Prerequisites
- None Identified

**Comment by monika-jaeger** [comment]
Adding initial notes here:
- Do we remove/notate components that are USWDS pass-throughs?
- QA by fellow designers/devs prior to sharing?

**Comment by laurelthrash** [comment]
Sub-tasks:
- [ ] Create sub-page for USWDS pass-through components

@sarinapadilla @andyvanavery @bennettcc we determined that Figma files for USWDS pass through components will be added as a sub-page. We want to discuss if there are considerations for these files we are not considering. I will reach out separately on this.

**Comment by laurelthrash** [comment]
Slated for internal discussion during 7/19 requirements meeting Cc: @monika-jaeger

**Comment by laurelthrash** [comment]
@monika-jaeger @blilianyu and others working through Word document. On track to demo on 8/8.

**Comment by monika-jaeger** [comment]
All feedback is implemented in the [Figma file](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?type=design&node-id=3917%3A6868&mode=design&t=GqfzGzzUvttKIq07-1). cc @blilianyu @dcvijanovic1k 
The only feedback [in the document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/NCIDS/Project%20Management/Figma%20File%20Discussion%20Points.docx?d=w18ce6a32a58845269d28118f25dc4c37&csf=1&web=1&e=TXXzcJ) not implemented are items related to the Community file, and is noted on those items. 
cc @laurelthrash

**Comment by laurelthrash** [comment]
Questions that came up during demo from end of sprint 08/08:

- [ ] In NCIDS for all - do we remove the USWDS color so no one can use them?

**Comment by laurelthrash** [comment]
Note: working through final pass through by IAs, then will seek final approval from developers.

**Comment by laurelthrash** [comment]
Created #1140 to capture changes to and questions around community DS Figma Files.

**Comment by laurelthrash** [comment]
Changes to Figma files from 08/09 Requirements Meeting:
- [ ] Decision: leave as-is for the pilot (including USWDS colors that are not being used) and reconsider after pilot if we want to remove USWDS colors that are not being used

Notes
- Colors and fonts considered together as they are the same concept

**Comment by laurelthrash** [comment]
As of 08/11, developers reviewed. Designers implementing final feedback.

**Comment by laurelthrash** [comment]
Confirmed with Anna during mid-sprint on 08/15 that we will consider the primary/master DS Figma File complete. ODDC does not need to take another review (reviewed during previous two end of sprints). We will review the Community file (tracked in #1140) with ODDC to finalize all Figma Files. Cc: @monika-jaeger @blilianyu
