### ISSUE TITLE
[R2.1 Content] About Cancer Spanish - Update Feature Card Title

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1085]
**Description:** After sharing the v3/final Mural with the About Cancer group, we identified a few new stickies/comments on the board One of them is to change the title for the 3rd feature card under the "Recursos para pacientes" feature card row from “Resúmenes de información del PDQ sobre el cáncer: Tratamiento en adultos” to “Tratamiento en adultos” to match English. This was approved verbally by Anna the week of 6/19.

**To-do:** Change title of feature card from “Resúmenes de información del PDQ sobre el cáncer: Tratamiento en adultos” to “Tratamiento en adultos”

**Sub-tasks:**
- [x] Update in all necessary locations
    - [x] ACSF-test (Adriana)
    - [x] Content template (Adriana)
    - [x] Figma comp (Monika)
    - [x] v3 Mural (Laurel)

**Comment by laurelthrash** [comment]
Assigning over to @monika-jaeger for final updates - thanks!

**Comment by monika-jaeger** [comment]
@laurelthrash this is updated in the [About Cancer Spanish](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=0%3A1&type=design&node-id=32-6750&viewport=2%2C192%2C0.25&scaling=min-zoom&mode=design&t=q37nrg6Mffurip1R-1) comps.

**Comment by laurelthrash** [comment]
Received and verified, @monika-jaeger - closing out this ticket. Thank you!
