### ISSUE TITLE
[R2.1 Content] Home Page English - Update Guide Card Label/Link

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1088]
**Description:** Determined via Teams that we will make the following label/link update on the home page:

Update label on left guide card that reads "Side Effects of Treatment" to "Treatment & Side Effects" and the button will link to https://www.cancer.gov/about-cancer/treatment.

**Sub-tasks:**
 - [ ] Update ACSF-test (Adriana)
 - [ ] Update content template (Adriana) [highlight in pink so it is reviewed in our second copy edit]
 - [ ] Update Figma comp
 - [x] Update v3 Mural board (Laurel)

**Comment by laurelthrash** [comment]
Tagging @adrianacastaneda & @monika-jaeger for above updates - thank you!

**Comment by monika-jaeger** [comment]
Updated [English Homepage](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7001&type=design&node-id=142-7351&viewport=-442%2C5283%2C1&scaling=scale-down-width&mode=design&t=iPXlSFlGR8QzVmoa-1) comps with button text.

**Comment by laurelthrash** [comment]
Assigning remaining items over to myself.

**Comment by laurelthrash** [comment]
Complete on content template and on ACSF-test. Closing this ticket.
