### ISSUE TITLE
[R2.1 Content] Alt Text for Two New Images

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1089]
**Description:** Determined we will purchase two new stock images (below). Need to identify alt text for these images, obtain approval from Anna, then submit for translation.

1. [G&T English] Japanese African-American mature businesswoman student sitting learning listening in education training seminar meeting in business office classroom with multiracial colleagues stock photo: https://www.istockphoto.com/photo/japanese-african-american-mature-businesswoman-student-sitting-learning-listening-in-gm1427845964-471598070
2. [About Cancer - Spanish] Together through the good times and the bad stock photo: https://www.istockphoto.com/photo/together-through-the-good-times-and-the-bad-gm1283692146-381031663

**Sub-tasks:**
- [x] Write recommended alt text (x2)
- [x] Obtain approval (obtained via email from Anna - noted we will not move this through a copy edit)
- [x] Submit for translation
- [x] Add to English content templates (G&T - English) (Adriana)
- [x] Add to Spanish content templates (About Cancer - Spanish) (Adriana)

**Comment by adrianacastaneda** [comment]
@laurelthrash please see alt text below for both images:

1. Woman dressed professionally looks up attentively while holding a pen and paper
2. Senior couple listens to pay attention as doctor speaks

**Comment by laurelthrash** [comment]
Shared with Anna for review via email.

**Comment by laurelthrash** [comment]
Alt text approved by Anna. Submitting ticket for translation.

**Comment by laurelthrash** [comment]
Translation obtained via CGOV-19146: 

**Image 1**

Image: [https://www.istockphoto.com/photo/japanese-african-american-mature-businesswoman-student-sitting-learning-listening-in-gm1427845964-471598070](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.istockphoto.com%2Fphoto%2Fjapanese-african-american-mature-businesswoman-student-sitting-learning-listening-in-gm1427845964-471598070&data=05%7C01%7Claurel.thrash%40nih.gov%7C870b120248ee4a21cf2f08db7e576823%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638242686089311695%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sXFhVC%2BqBgJbyauOY8Z3DjxBe8vbhXq8B%2BvCE4D1vVQ%3D&reserved=0)
Approved English Alt Text: Woman dressed professionally looks up attentively while holding a pen and paper.
Spanish translation: Una mujer vestida con una blusa profesional presta atención mientras sostiene un bolígrafo y un papel 

**Image 2**

Image: [https://www.istockphoto.com/photo/together-through-the-good-times-and-the-bad-gm1283692146-381031663](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.istockphoto.com%2Fphoto%2Ftogether-through-the-good-times-and-the-bad-gm1283692146-381031663&data=05%7C01%7Claurel.thrash%40nih.gov%7C870b120248ee4a21cf2f08db7e576823%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638242686089311695%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3D63JxIl%2FgDnK4raj1qn%2Fg%2FcEXnm1GaN%2BxQEZxvMlgI%3D&reserved=0)
Approved English Alt Text: Senior couple listens to pay attention as doctor speaks.
Spanish translation: Una pareja de adultos mayores escucha con atención mientras el médico habla.

**Comment by laurelthrash** [comment]
@adrianacastaneda Updated the content template accordingly.

**Comment by laurelthrash** [comment]
@adrianacastaneda - received and verified. Closing this ticket, thank you!
