### ISSUE TITLE
Develop Drupal "Power User" Training for Home and Landing Page R2.1 Components

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1090]
**Description:** Determined the need to develop specific training for users that update the home and landing pages. 

**Sub-tasks:**
- [x] July 14-19: Create Drupal training materials (Laurel)
- [x] July 19-21: Review Drupal training materials (Lindsay)
- [x] July 24-25: Update/revise training materials (Laurel)
- [x] July 26: Deliver user training (Laurel, with Lindsay as optional, 1 hour)

**Comment by laurelthrash** [comment]
Training delivered on 7/26. Closing this ticket.
