### ISSUE TITLE
Image regressions failing again

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1093]
BackstopJS regressions are failing again, but appears to be only locally.

45 total, looks like they're all dealing with section padding

![image](https://github.com/NCIOCPL/ncids/assets/85901679/16d72d11-f14f-4bbd-8022-9c59330a3662)
![image](https://github.com/NCIOCPL/ncids/assets/85901679/950697c1-7b04-42ca-adb0-d20bab62b73a)
![image](https://github.com/NCIOCPL/ncids/assets/85901679/5a50b960-215f-4952-ab5f-84593584ace8)

Probably related to this PR https://github.com/NCIOCPL/ncids/pull/1028

### Tasks

- [x] Fix the regressions on develop
- [ ] Try to figure out why GA isn't seeing them
- [x] IDK, it's sassy Friday, do a little dance while you're at it.

**Comment by olitharp-nci** [comment]
dev user error. closing.
