### ISSUE TITLE
[R2.1 Content] G&T Spanish - Image Alt Text Update

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1098]
**Description:** Selected new image for right feature card for Grants & Training (Spanish). Need to ensure the new image is added to ACSF-test as well as ensure the alt text is included on the content templates:

![Image](https://user-images.githubusercontent.com/102998716/252355912-aa772dd5-5296-45d8-a720-1386f32ddc4a.png)

**Sub-tasks:**
- [x] Add image to ACSF-test (Adriana)
- [x] Add alt text to content template (Laurel) - already there, but verified.
- [x] Verify image is correct on Figma Comps (Laurel)
- [x] Update v3 Mural (Laurel)

**Comment by laurelthrash** [comment]
@adrianacastaneda - received, closing out this ticket. Thank you!
