### ISSUE TITLE
[R2.1 Content] About Cancer - Stomach Cancer Promo Block

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1099]
**Description:** Received updated language for the Stomach Cancer promo block on the About Cancer Page:

- Description: Explore risk factors for stomach cancer, its symptoms, and how it is diagnosed. Also find treatment options and ways to cope with the physical and emotional effects of stomach cancer.
- Image: https://www-cms.cancer.gov/admin/content/media?name=Gastrointestinal+System%2C+Upper%2C+Anatomy&type=All&status=All&langcode=All

**Sub-tasks:**
- [x] Update Figma comps (Monika)
- [x] Update Image Excel doc, if needed (Monika)
- [x] Update v3 Mural board (Laurel)
- [x] Update content template (Adriana)
- [x] Update ACSF-test (Adriana)

**Comment by monika-jaeger** [comment]
@laurelthrash FYI we will have to add new crops to the CMS for the image. I will work on that.

**Comment by monika-jaeger** [comment]
@laurelthrash updated [Image Evaluation](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/R2.1%20Image%20Evaluation.xlsx?d=wf73f22b0ac4940efab072e943c23df08&csf=1&web=1&e=8ImiaO) sheet & updated [Gastrointestinal System, Upper, Anatomy](https://www-cms.cancer.gov/media/915044) crops in CMS (added 1:1 & 16:9 versions)

**Comment by adrianacastaneda** [comment]
@laurelthrash @monika-jaeger new crops work! this ticket's all set

**Comment by laurelthrash** [comment]
@adrianacastaneda - received, closing out this ticket. Thank you!
