### ISSUE TITLE
R2.1 and R2.2 Documentation Update - Include Patterns and Variant Language

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1117]
> META: https://github.com/NCIOCPL/cgov-digital-platform/issues/3317

**Description:** Components (e.g., guide card and feature card) can be in a pattern (e.g., guide card row, feature card row), but in the DS they can live on their own so they are separate components. Our prepared guidance (link to ticket) outlines the singular components. In our Documentation Site, we are incorporating information regarding the patterns. This ticket is to outline the guidance related to the patterns. We will link to the pattern pages from the individual component page.  

**Sub-tasks:**
- [x] Review previous R2.1 and R2. guidance:
    - [x] add to or modify 
    - [x] compile guidance specific for the patterns section
    - [x] update language to reflect correct variant language
- [x] Compile updated pattern guidance
- [x] Review guidance (internal)
- [x] Make necessary changes
- [ ] Verify against GH component
- [ ] Final review
    - [ ] UX (Lindsay, Lilian, Monika)
    - [ ] Development (Paul A.)
- [ ] Review guidance (ODDC)
- [ ] Verify copy edit (PM)
- [ ] Add guidance to GH Wiki as new "patterns" section

**Comment by laurelthrash** [comment]
Set to review internally on Tues.  8/8.

**Comment by laurelthrash** [comment]
Targeting to complete internal review ( @lburack @blilianyu @monika-jaeger ) by EOD Mon. 08/14. Cc: @adrianacastaneda

**Comment by laurelthrash** [comment]
Closing this ticket in favor of using the individual component/page tickets. Cc: @adrianacastaneda @bennettcc @sarinapadilla
