### ISSUE TITLE
Spike: Recreate the Branding and Logo Guide

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1120]
Related ticket: #1079

**Description:** During the update of the Branding/Logo Guide on MyNCI (https://mynci.cancer.gov/topics/nci-branding-and-logo-use-guide) for our R2.1 content launch, we were unable to find the source file for the guide. Meantime, we edited the PDF, however, there are concerns with editing the PDF over editing the source file. This ticket is to conduct a review of the effort it would take to recreate the branding and logo guide and determine if we want to move forward.

**Sub-tasks:**
- [x] Consult Lilian upon her return regarding the location of the source file
- [x] Estimate the LOE to recreate the guide into a source document
- [x] Capture value to creating the guide
- [ ] Discuss the with the team and align internally/ align with federal team as needed

**Comment by chuckroseNIH** [comment]
Lilian is back so you may want to follow up with her. In the meantime I found what I think is Michelle's last inDesign file from 2020. https://lion.app.box.com/file/732204540548

**Comment by dcvijanovic1k** [comment]
@laurelthrash - unfortunately, no one has been able to find this file. Lilian has guessed that Russell (former employee) potentially updated it and didn't upload to Box. The file that Chuck linked is the same one that many of us (including myself) have found; unfortunately, it is out of date.

At this point, I would estimate around 40-60 hours to recreate this file. Part of that estimate is the fact that it will need to be manually redone page by page, including exporting and/or searching for assets; the other part is the 508 steps that will need to be implemented on the backend and after the PDF is exported.

Lilian mentioned this guide is internal; I would ask if there are not enough other style guides that contain the same information (the Digital Reference guide seems very close in this regard), and I'd like to take the next meeting to find out how often the rest of the team actually references this guide. Using that information and a discussion, I think that would best indicate whether or not we need to recreate this guide or not. 

Please let me know if you have any other questions. Thanks!

**Comment by laurelthrash** [comment]
Slated for internal discussion during backlog grooming on Wed. 8/2 @dcvijanovic1k

**Comment by laurelthrash** [comment]
Discussed as internal team on 8/1. Determined the current PDF on MyNCI (pending remediation) will suffice for now but recommend recreating the source file of this document. Will obtain estimated time/cost to recreate the source file and confer with ODDC regarding desired timing to slot in this work. Will close this spike ticket and create a new ticket, as needed. Cc: @dcvijanovic1k
