### ISSUE TITLE
Update Guides Based on Luminance Decision

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1130]
**Description:** Updated the Branding and Logo Guide as well as the Digital Reference Guide in relation to R2.1 updates. Made a decision regarding Luminance (PR linked below) and need to update the 

**Related tickets:**
- Luminance PR: #1005
- Digital Reference Guide: #1080
- Branding/Logo Guide: #1079

**Sub-tasks:**
- [x] Update guides
- [x] Send guides around internally via Slack
- [x] Make updates based on internal review
- [x] Send guides to Nanci for remediation
- [x] Replace guides on MyNCI

**Comment by laurelthrash** [comment]
Updated documents replaced on MyNCI via CGOV-19388. Closing this ticket - thank you! Cc: @dcvijanovic1k
