### ISSUE TITLE
R2.1 Batch 2 - Create Image Inventory

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1131]
**Description:** Ahead of publishing R2.1 content for batch 2 (NCI-CONNECT and Nano), need to create an inventory of images used. 

**Resources:**
- Tracker: [link here](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/R2.1%20Image%20Evaluation.xlsx?d=wf73f22b0ac4940efab072e943c23df08&csf=1&web=1&e=oCzQfk)
- CGOV ticket: #1064

**Sub-tasks:**
- [x] Create image inventory @dcvijanovic1k 
- [x] Review internally @adrianacastaneda @laurelthrash 
- [x] Ensure that images are reflected in the content templates

**Comment by adrianacastaneda** [comment]
@laurelthrash All images in the CMS have been added accordingly to the content templates. Waiting on image purchases in order to add these to Teams and the content templates. Thanks!
