### ISSUE TITLE
[Updates/Revisions] Nano Home Page R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1132]
**Description:** Spoke with Nano on 7/26 and gained alignment on approach. We will move forward with Option B, with some modifications.

**Sub-tasks:**
- [ ] Update comp
    - [ ] Add guide card description text (provided by Nano by Fri. 7/28]
    - [ ] Pull image gallery link to the top of the list in right guide card 
    - Confirmed will launch with existing images from the comps, but will replace image for the “Apply for Alliance” promo block and guide card images using original imagery from Nano after launch
- [ ] Verify the broken links on home page

**Comment by laurelthrash** [comment]
Also made several small copy edit changes, noted above and catalogued below: 

- Promo block: Change “are” to “is” in the second sentence: “…are listed here.”
- Left guide card: Capitalize “t” after the hyphens: 
    - “Current Cancer Nano-Treatments”
    - “Safety of Cancer Nano-Treatments”
- Right guide card: Capitalize “d” in Database: “Data Sharing and caNanoLab Database”

**Comment by laurelthrash** [comment]
@adrianacastaneda shared recommendations regarding link updates to Alex and Anna via Teams on 7/28. Once any necessary changes are established, will update the ticket accordingly.

**Comment by adrianacastaneda** [comment]
Submitted a JIRA ticket for an impact analysis report for the broken links on current homepage. Waiting to hear back on Alex/Leela's thought on redirect links. cc: @laurelthrash

**Comment by laurelthrash** [comment]
Final comp approved by Leela via Alex via email. Confirmed decision for redirects for which @adrianacastaneda will implement. Closing this ticket ahead of R2.1 content launch.
