### ISSUE TITLE
[Final Prep] NCI-C and Nano Home Page Content Launch

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1133]
**Description:** Opening one ticket to keep final go-live steps top of mind from NCI-CONNECT and MyPART schedule. This includes the following:

**Sub-tasks:**
- [x] Finalize content templates @adrianacastaneda (deadline: 7/28)
- [x] Purchase missing stock imagery [CGOV-19300] (deadline: 8/3)
- [x] Alt text 
    - [x] Draft alt text @adrianacastaneda 
    - [x] Receive ODDC approval on alt text (sent to Alex 7/27)
    - [x] Add to content template @adrianacastaneda 
- [x] Copy edits [CGOV-19253] (deadline: 8/2)
- [x] Spanish alt text [CGOV-19339]
