### ISSUE TITLE
META: Use Twigs for NCIDS Components in Doc Site, Example Site, Storybook

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#1137]
*Description of what is to be accomplished.*
There should be a singular twig template for each component/variant to be used in the doc site, example site, and storybook so there is consistent html

### Sub-Tasks
- [ ] Generate individual tickets for the following tasks
- [ ] Updating Doc Site
- [ ] Updating Example Site
- [ ] Updating Storybook
