### ISSUE TITLE
Create NCIDS Pilot Introductory One Pager

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1139]
**Description:** Create a PDF that will be shared with the NCIDS Pilot users following the initial DS Pilot meeting. The goal of the one pager is to be a quick reference guide that briefly describes the resources and materials that they have been given access to and communicates a few key process/expectations for support throughout the engagement. A Word document, from which the PDF should be adapted, is created and has been reviewed by ODDC. [Document is found here.](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/NCIDS/DRAFT_NCIDS%20Pilot%20-%20One%20pager.docx?d=w6f9c7f38a7de46f4bea9f1fa7ff83755&csf=1&web=1&e=Np1UEk)

- This is not intended to be posted to the Documentation Site
- This will be shared via email/Teams/other mechanism with pilot users

**Sub-tasks:**
- [x] Create PDF one pager based on Word document (08/20 - 08/28)
- [x] Review internally (08/29)
- [x] Make updates (08/29 - 08/30)
- [x] Align on design (08/31)
- [x] Review for clarity and consistent tone throughout document (09/06 - 09/08) @adrianacastaneda 
- [x] ODDC review (08/31 - 09/08)
- [x] Final approval (09/11)
- [ ] Ensure meta information for a11y is incorporated into the PDF (09/12)
- [ ] Save to appropriate location to be pulled into pilot documentation (09/13)
    - Intended to be shared via email for pilot participants

**Comment by bennettcc** [comment]
@laurelthrash Per 8/21 meeting with Anna - here is the approved content for the one pager. Please assign to a designer as available, thx!

**Comment by laurelthrash** [comment]
Thanks, @bennettcc! @blilianyu @monika-jaeger this is ready for pickup. I've added proposed due date at the top of the page but please shout with concerns.

**Comment by blilianyu** [comment]
@laurelthrash, @dcvijanovic1k will help us and take on creating this PDF to be inline with out style guides. Thanks!!

**Comment by laurelthrash** [comment]
Review during UX meeting 08/29:
- [ ] Hyperlink the title text for items 1-6
    - Alternative: review if Figma plugin to shorten link is available to apply for the NCIDS Design Kit 
- [ ] Add external link indicator for items 1-6, to indicate user is being taken to an external link
    - Move the external link to the left of the title and add "icon for external link" to the alt text 
- [ ] For item 6, make same structure so that text is hyperlinked:
    - NCIDS CSS Package
    - NCIDS JS Package

**Comment by laurelthrash** [comment]
Approved internally 08/31. Will share with Anna/Alex via Teams today, noting that we will 1) take a final pass through for voice/tone, and 2) implement 508 remediation following final approval.

**Comment by dcvijanovic1k** [comment]
Posting V1 
[NCIDS-Pilot-Intro-One-Pager_V1.pdf](https://github.com/NCIOCPL/ncids/files/12488664/NCIDS-Pilot-Intro-One-Pager_V1.pdf)

**Comment by dcvijanovic1k** [comment]
V2 attached that reflects all edits from the Mural board. Please shout with any thoughts or concerns! cc @laurelthrash 
[NCIDS-Pilot-Intro-One-Pager_V2.pdf](https://github.com/NCIOCPL/ncids/files/12589293/NCIDS-Pilot-Intro-One-Pager_V2.pdf)

**Comment by dcvijanovic1k** [comment]
Remediated version of the PDF attached, cc @laurelthrash 
[NCIDS-Pilot-Intro-One-Pager_V3-Remediated.pdf](https://github.com/NCIOCPL/ncids/files/12612845/NCIDS-Pilot-Intro-One-Pager_V3-Remediated.pdf)

**Comment by laurelthrash** [comment]
Saved to Teams folder. Closing this ticket. Cc: @dcvijanovic1k @bennettcc
