### ISSUE TITLE
NCIDS For All Pilot - Finalize Figma Files (Community)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1140]
**Description:** Team is creating thr primary DS Figma Files in #1082. Need to also make subsequent changes and answer questions related to the community DS Figma Files, which are adapted from the primary files. 

**Sub-tasks:**
- [ ] Make changes to community files per designer/developer input: [document here ](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/NCIDS/Project%20Management/Figma%20File%20Discussion%20Points.docx?d=w18ce6a32a58845269d28118f25dc4c37&csf=1&web=1&e=TXXzcJ)
- [ ] Answer questions regarding community file governance:
    - [ ] Will comments be permitted on the community file?
    - [ ] If so, who will answer the comments and what are expectation for replies?
    - [ ] Insert other questions, as needed

**Comment by laurelthrash** [comment]
Pickup after we finalize primary files in #1082. @monika-jaeger to build out the list of specific changes to the community file for documentation. Adding to "Approved backlog" until finalize.

**Comment by monika-jaeger** [comment]
[Link to Community File](https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCI-Design-System---Community?type=design&node-id=3917%3A6868&mode=design&t=DkIOKM7Qm4NkLZsA-1)

All changes listed above are completed. We also added the changes to the [Figma Feedback Doc](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B18CE6A32-A588-4526-9D28-118F25DC4C37%7D&file=Figma%20File%20Discussion%20Points.docx&action=default&mobileredirect=true) to track any additional notes.

This should be ready for review from the developers @laurelthrash 

cc: @blilianyu

**Comment by laurelthrash** [comment]
[In Progress] Discussion during UX meeting 08/17:

Will comments be permitted on the community file? (Option to have comment section closed.) If so, who will answer the comments and what are expectation for replies?
- Recommend disabling comments in Figma and encourage DOC users to file a formal issue via Teams

Do we only want DOCs to submit questions?
- Yes

If so, where should those be captured, who will answer them and what are expectations for replies?
- Go through Teams, go through Triage process outlined

Are marketing materials required?
- Cover photo (graphic asset)
- Name
- Description (note how DOC users can get in touch?)
- Tags to search for it
- Contact information (consider leaving blank to encourage people to go to Teams)
- Disable/enable comments

How to track version history?
- Keep release updates in one place (suggestion: GitHub release notes for DS) so we synchronize GH/development updates with Figma

Outstanding questions:
- [ ] Can we see who/how many downloads of the community file there are?

**Comment by laurelthrash** [comment]
@blilianyu @monika-jaeger - As discussed during standup, let's please pause on any updates to the DS Community Figma file based on developer feedback.

Update: developer review of the community file via Slack on 08/18 sparked need to re-establish the best way to organize our components/variants for team visibility. PO team reviewing how to accomplish this. Once complete, this will influence the DS Community Figma file. Cc: @andyvanavery

**Comment by laurelthrash** [comment]
@blilianyu @monika-jaeger Governance discussed with Anna on 08/21:
 - Noted potential concern with showing NCI logo on a third party site 
 - Received approval/confirmation from Anna that we will disable people from allowing people to comment on the community file 

To-dos:
- [ ] Create an OCPL tool that has a distribution list (if Monika, for instance, is not available 
- [ ] Consider NCI logo representation in thumbnail

**Comment by blilianyu** [comment]
@laurelthrash, @monika-jaeger and I are also proposing adding a 'Brand' page to both master & community file where we move the logos and blended logos there from 'NCIDS Components' page. And we will have a section for  'Brand Usage Guidelines" in the Figma Guide.

**Comment by laurelthrash** [comment]
Per standup: Bryan and Olivia to discuss the GitHub component and variant page today. Figma Community file to be updated after this is finalized.

**Comment by laurelthrash** [comment]
@monika-jaeger @blilianyu per standup, GitHub Wiki ([page here](https://github.com/NCIOCPL/ncids/wiki/Storybook-Structure)) ready to be referenced in order to update the Community file. Please proceed with making updates, which will be followed by re-review by developers.

**Comment by blilianyu** [comment]
@laurelthrash, @monika-jaeger reviewed and now it is ready for dev review!

**Comment by laurelthrash** [comment]
Anna approved file name, logo, and description via Teams. Added final language to the description of this card. Cc: @blilianyu @monika-jaeger

**Comment by laurelthrash** [comment]
Aligned on final feedback from federal team during 09/26/23 @ 9:30am meeting. @monika-jaeger @blilianyu to remove the  "USWDS Pass-Through Templates" page from the DS Community Figma file to avoid confusion. From there, team will move forward with publishing the community file using the approved name, logo, and description. Cc: @blilianyu @monika-jaeger

**Comment by laurelthrash** [comment]
Community file published on 09/26/23. Link to community file and community page added to description of the ticket. Closing out this ticket. Cc: @blilianyu @monika-jaeger @bennettcc
