### ISSUE TITLE
[R2.1 Content] Nano and NCI-C Content Launch

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1142]
**Description:** Slated for R2.1 content launch for Nano and NCI-CONNECT homes pages (3 total pages) on Thurs. 08/17. 

**Sub-tasks**
- [x] Draft pages in production (leave in draft) [08/14]
- [x] QC draft pages
- [x] Update pages, as needed
- [x] Spot check (Mel) [08/16]
- [x] Final review and sign off (Anna) [08/16]
- [x] Publish pages [08/17] 
- [x] Notify stakeholders [08/17]

**Comment by laurelthrash** [comment]
Pick up ticket on Monday 08/14 to draft pages.

**Comment by laurelthrash** [comment]
Published updated pages (3) on Thurs. 08/17. Closing this ticket.
