### ISSUE TITLE
Create auto init script for subscribe component (backlog)

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1160]
## Create auto init script for the subscribe component 

Standalone auto init script for the subscribe component -- should not include any footer work, footer will auto init its own subscribe form instance. We can backlog this for now as we do not currently use the subscribe form anywhere else other than the footer.

### Tasks

- [ ] Create auto init module
- [ ] Update example js site
- [ ] Update documentation site

### Related

- #1108 
- #1159

**Comment by sarinapadilla** [comment]
Closing because this isn't a component.
