### ISSUE TITLE
Create auto init script for the Autocomplete component (backlog)

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1162]
## Create auto init script for the Autocomplete component 

Backlog this item for a future release.

Will need to pass attributes to init. More discussion needed.

### Tasks

- [ ] Create auto init module
- [ ] Update example js site
- [ ] Update documentation site

### Related

- #1108

**Comment by andyvanavery31** [comment]
Needs further solutioning/discussion between Developers.

**Comment by sarinapadilla** [comment]
Closing this ticket since 1) the ticket doesn't have enough information and 2) it's complicated and people won't use it as an auto init. We'll create a new ticket if somehow that happens.
