### ISSUE TITLE
Component page: Autocomplete

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1165]
Update the Autocomplete component page with the content needed for NCIDS for All pilot launch.

**Prerequisite:** #1164 
**Parent Issue:** #945 

### Sub-Tasks
- [x] Create content in shared [Word Doc](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BF5834A46-A1F0-4C90-A678-FCA64CEE6320%7D&file=Autocomplete.docx&action=default&mobileredirect=true&wdLOR=c2C77C30C-9692-EF47-A0C5-C9FDD577BFEE)
    - [x] IA Responsibility: Overview, Variants, Usage, Best Practices
    - [x] Developer Responsibility: Accessibility, Component Preview
    - [x] Designer Responsibility: Static Image(s) (if applicable)
- [x] Review content in shared Word Doc
- [x] Create Images in shared Folder (Insert Shared Folder Link)
- [x] Convert content and images to [Markdown Template](https://github.com/NCIOCPL/ncids/issues/1164)
- [ ] Add to Documentation Site

Autocomplete image:
![autocomplete_overview](https://github.com/NCIOCPL/ncids/assets/22639543/e04a6a8a-5f9b-4a66-8afa-accd4864f7a9)

Markdown file:
https://nih.sharepoint.com/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=kyhT4s&cid=a24896f7%2D63e2%2D4447%2Dbdc4%2D98e0920070a8&FolderCTID=0x0120005F2FA21B2C6E704CB4EDDD13D67036B6&id=%2Fsites%2FNCI%2DOCPLNewCgovUXDesignSystem%2FShared%20Documents%2FGeneral%2FDetails%20%2D%20NCIDS%20Pilot%2FDocumentation%20Site%2FPage%20Content%20%2D%20Markdown%2FAutocomplete%20Markdown%2Etxt&viewid=983144df%2D37bd%2D4e06%2D9fe2%2Db72f877fcf98&parent=%2Fsites%2FNCI%2DOCPLNewCgovUXDesignSystem%2FShared%20Documents%2FGeneral%2FDetails%20%2D%20NCIDS%20Pilot%2FDocumentation%20Site%2FPage%20Content%20%2D%20Markdown

### References
- [Doc Site Content Tracker](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=xA4cHF)

**Comment by bennettcc** [comment]
@karlikpj The autocomplete markdown is here: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BF5834A46-A1F0-4C90-A678-FCA64CEE6320%7D&file=Autocomplete.docx&action=default&mobileredirect=true
