### ISSUE TITLE
Component Page: Banner

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1166]
Update the banner component page with the content needed for NCIDS for All pilot launch.

**Prerequisite:** #1164 
**Parent Issue:** #945 

### Sub-Tasks
- [ ] Update text content to fit [component page template](https://github.com/NCIOCPL/ncids/issues/1164)
- [ ] Convert to .mdx
- [ ] Add images
- [ ] Add component code previews

**Comment by sarinapadilla** [comment]
@karlikpj the markdown for this page is [here](https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Banner.txt?csf=1&web=1&e=ALCpzx) and the static image is [here](https://nih.sharepoint.com/:i:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Static%20Images/banner_overview.png?csf=1&web=1&e=QIw9Yg)!
