### ISSUE TITLE
Component page: Character Count

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1169]
Update the Character Count component page with the content needed for NCIDS for All pilot launch.

**Prerequisite:** #1164 
**Parent Issue:** #945 

### Sub-tasks
- [ ] Create content in shared [Word Doc](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BC8A49122-D7D4-487B-A1F1-56C244E15B66%7D&file=Character%20Count.docx&wdLOR=cF289A314-2C7A-E144-9650-DB558B0E6A86&action=default&mobileredirect=true)
    - [ ] IA Responsibility: Overview, Variants, Usage, Best Practices
    - [ ] Developer Responsibility: Accessibility, Component Preview
    - [ ] Designer Responsibility: Static Image(s) (if applicable)
- [ ] Review content in shared Word Doc
- [ ] Create Images in shared Folder (Insert Shared Folder Link)
- [ ] Convert content and images to [Markdown Template](https://github.com/NCIOCPL/ncids/issues/1164)
- [ ] Add to Documentation Site

### References
- [Doc Site Content Tracker](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=xA4cHF)

**Comment by arcepaul** [comment]
Accessibility blurb added to word doc.

**Comment by arcepaul** [comment]
## Accessibility
- Associate the character count message to the input. Use `aria-describedby` on the input to allow the message to be announced to those using screen readers. 
- Use the `aria-live` attribute on character count message. Use `aria-live="polite"` so that updates to character count message are also announced when using a screen reader.

**Comment by bennettcc** [comment]
Closing this ticket - the character count is a passthrough, not a supported NCIDS component. This will not need its own page
