### ISSUE TITLE
Component page: Call to Action Strip

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1170]
Update the Call to Action Strip component page with the content needed for NCIDS for All pilot launch.

**Prerequisite:** #1164 
**Parent Issue:** #945 

### Sub-Tasks
- [x] Create content in shared [Word Doc](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BB4B1F9A1-B689-42F6-9015-3922F59D4811%7D&file=CTA%20Strip.docx&wdLOR=c80C3C27B-403D-5B49-A895-B24B85266CF5&action=default&mobileredirect=true)
    - [x] IA Responsibility: Overview, Variants, Usage, Best Practices
    - [x] Developer Responsibility: Accessibility, Component Preview
    - [x] Designer Responsibility: Static Image(s) (if applicable)
- [x] Review content in shared Word Doc
    - [x] Voice and tone (Lindsay)
    - [x] Developer gut check (Paul A.) 
- [x] Create Images in shared Folder (Insert Shared Folder Link)
- [x] Convert content and images to [Markdown Template](https://github.com/NCIOCPL/ncids/issues/1164)
- [ ] Add to Documentation Site

### References
- [Doc Site Content Tracker](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=xA4cHF)

**Comment by laurelthrash** [comment]
Guidance language ready for review. Assigning over to @lburack. Cc: @adrianacastaneda

**Comment by bennettcc** [comment]
@karlikpj The content markdown is ready and lives here: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/CTA%20Strip.docx?d=w7388d6703432481f891c7fe013bab7c3&csf=1&web=1&e=tGTsZS

**Comment by bennettcc** [comment]
@arcepaul @karlikpj the CTA image lives here: https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Static%20Images?csf=1&web=1&e=NfGNKk
