### ISSUE TITLE
Component page: Card

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1171]
Update the Feature Card component page with the content needed for NCIDS for All pilot launch.

**Prerequisite:** #1164 
**Parent Issue:** #945 

### Sub-Tasks
- [x] Create content in shared [Word Doc](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B5AA8329A-1C8D-4DAE-9967-6A3BA502692F%7D&file=Feature%20Card.docx&wdLOR=cE0C8D2E8-C45D-5E4E-8ECD-F3B55BBAB0F9&action=default&mobileredirect=true)
    - [x] IA Responsibility: Overview, Variants, Usage, Best Practices
    - [x] Developer Responsibility: Accessibility, Component Preview
    - [ ] Designer Responsibility: Static Image(s) (if applicable)
- [x] Review content in shared Word Doc
    - [x] Voice and tone (Lindsay)
    - [x] Developer gut check (Paul A.) 
- [ ] Create Images in shared Folder (Insert Shared Folder Link)
- [x] Convert content and images to [Markdown Template](https://github.com/NCIOCPL/ncids/issues/1164)
- [ ] Add to Documentation Site

### References
- [Doc Site Content Tracker](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=xA4cHF)

**Comment by laurelthrash** [comment]
Guidance language ready for review. Assigning over to @lburack. Cc: @adrianacastaneda

**Comment by bennettcc** [comment]
@karlikpj The markdown for Card is done and lives here: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Card.docx?d=wbc03b7b587314895ab9f0d73fc830dac&csf=1&web=1&e=OI7qZC
