### ISSUE TITLE
Component Page: Memorable Date

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1177]
Update the memorable date component page with the content needed for NCIDS for All pilot launch.

**Prerequisite:** #1164 
**Parent Issue:** #945 

### Sub-Tasks
- [ ] Update text content to fit [component page template](https://github.com/NCIOCPL/ncids/issues/1164)
- [ ] Convert to .mdx
- [ ] Add images
- [ ] Add component code previews

**Comment by arcepaul** [comment]
## Accessibility
* **Follow input guidance.** These text fields should follow the accessibility [guidelines for all text inputs](https://designsystem.digital.gov/components/text-input).
* **Don’t auto-advance focus.** Do not use JavaScript to auto advance the focus from one field to the next. This makes it difficult for keyboard-only users to navigate and correct mistakes.
* **Use “text” instead of “number” inputs.** Research indicates that [numeric inputs still carry many usability problems](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/), according to the gov.uk Technology in Government blog.
