### ISSUE TITLE
Component page: Hero

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1178]
Update the Hero component page with the content needed for NCIDS for All pilot launch.

**Prerequisite:** #1164 
**Parent Issue:** #945 

### Sub-Tasks
- [x] Create content in shared [Word Doc](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BB92A3C23-3CCC-4E2E-8E08-CBBBE28C3EB0%7D&file=NCIDS%20Hero.docx&wdLOR=c2AC5B3F0-9B7B-1140-9E6F-5E6DCDB92E13&action=default&mobileredirect=true)
    - [x] IA Responsibility: Overview, Variants, Usage, Best Practices
    - [x] Developer Responsibility: Accessibility, Component Preview
    - [x] Designer Responsibility: Static Image(s) (if applicable)
- [x] Review content in shared Word Doc
    - [x] Voice and tone (Lindsay)
    - [x] Developer gut check (Paul A.) 
- [x] Create Images in shared Folder (Insert Shared Folder Link)
- [x] Convert content and images to [Markdown Template](https://github.com/NCIOCPL/ncids/issues/1164)
- [ ] Add to Documentation Site

### Markdown
https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Hero%20Markdown.txt?csf=1&web=1&e=C0Hxsi
[Hero Markdown.txt](https://github.com/NCIOCPL/ncids/files/12848901/Hero.Markdown.txt)

### References
- [Doc Site Content Tracker](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=xA4cHF)

**Comment by laurelthrash** [comment]
Guidance language ready for review. Assigning over to @lburack. Cc: @adrianacastaneda
