### ISSUE TITLE
Component page: Promo Block

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1179]
Update the Promo Block component page with the content needed for NCIDS for All pilot launch.

**Prerequisite:** #1164 
**Parent Issue:** #945 

### Sub-Tasks
- [x] Create content in shared [Word Doc](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B9A4A8C20-620D-4E4C-8EE4-A347BCE4B6BF%7D&file=Promo%20Block.docx&wdLOR=c062A6CE3-1CC4-B049-BC41-9F677CD8CED6&action=default&mobileredirect=true)
    - [x] IA Responsibility: Overview, Variants, Usage, Best Practices
    - [x] Developer Responsibility: Accessibility, Component Preview
    - [x] Designer Responsibility: Static Image(s) (if applicable)
- [x] Review content in shared Word Doc
    - [x] Voice and tone (Lindsay)
    - [x] Developer gut check (Paul A.) 
- [x] Create Images in shared Folder (Insert Shared Folder Link)
- [x] Convert content and images to [Markdown Template](https://github.com/NCIOCPL/ncids/issues/1164)
- [ ] Add to Documentation Site

### References
- [Doc Site Content Tracker](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=xA4cHF)

* Page markdown [here](https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/PromoBlock.txt?csf=1&web=1&e=TS8Sk9)

[PromoBlock.txt](https://github.com/NCIOCPL/ncids/files/12848905/PromoBlock.txt)

* Static image [here](https://nih.sharepoint.com/:i:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Static%20Images/promo-block_overview.png?csf=1&web=1&e=SCkG7H)

**Comment by laurelthrash** [comment]
Guidance language ready for review. Assigning over to @lburack. Cc: @adrianacastaneda

**Comment by sarinapadilla** [comment]
@karlikpj locations of markdown and static images have been added to this ticket!+

**Comment by andyvanavery31** [comment]
Latest markdown as of 12OCT2023
[PromoBlock.txt](https://github.com/NCIOCPL/ncids/files/12886045/PromoBlock.txt)
