### ISSUE TITLE
Component Page: Side Navigation

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1180]
Update the side navigation component page with the content needed for NCIDS for All pilot launch.

**Prerequisite:** #1164 
**Parent Issue:** #945 

### Sub-Tasks
- [ ] Update text content to fit [component page template](https://github.com/NCIOCPL/ncids/issues/1164)
- [ ] Convert to .mdx
- [ ] Add images
- [ ] Add component code previews
