### ISSUE TITLE
Component page: Site Alert

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1181]
Update the Site Alert component page with the content needed for NCIDS for All pilot launch.

**Prerequisite:** #1164 
**Parent Issue:** #945 

### Sub-Tasks
- [x] Create content in shared [Word Doc](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B779F62DF-F030-4D65-8D8D-A26E73F896C5%7D&file=Site%20Alert.docx&wdLOR=c65B52043-C43E-6440-ADFD-7CA18A524726&action=default&mobileredirect=true)
    - [x] IA Responsibility: Overview, Variants, Usage, Best Practices
    - [x] Developer Responsibility: Accessibility, Component Preview
    - [x] Designer Responsibility: Static Image(s) (if applicable)
- [x] Review content in shared Word Doc
- [x] Create Images in shared Folder (Insert Shared Folder Link)
- [x] Convert content and images to [Markdown Template](https://github.com/NCIOCPL/ncids/issues/1164)
- [x] Add to Documentation Site

### Markdown
https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Site%20Alert.txt?csf=1&web=1&e=TFuUsK

### References
- [Doc Site Content Tracker](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=xA4cHF)

**Comment by bennettcc** [comment]
Lone remaining issue will be addressed once the JS issues for https://github.com/NCIOCPL/ncids/issues/1173 is fixed
