### ISSUE TITLE
Component page: Skipnav

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1183]
Update the Skipnav component page with the content needed for NCIDS for All pilot launch.

**Prerequisite:** #1164 
**Parent Issue:** #945 

### Sub-Tasks
- [x] Create content in shared [Word Doc](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BCDC9B4AB-037B-45AA-A43E-C97B91621A84%7D&file=Skipnav.docx&wdLOR=cD82C86EC-8861-EB49-9633-1475B17E9AB4&action=default&mobileredirect=true)
    - [x] IA Responsibility: Overview, Variants, Usage, Best Practices
    - [x] Developer Responsibility: Accessibility, Component Preview
    - [x] Designer Responsibility: Static Image(s) (if applicable)
- [x] Review content in shared Word Doc
- [x] Create Images in shared Folder (Insert Shared Folder Link)
- [x] Convert content and images to [Markdown Template](https://github.com/NCIOCPL/ncids/issues/1164)
- [ ] Add to Documentation Site

### References
- [Doc Site Content Tracker](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=xA4cHF)

[SkipNav.txt](https://github.com/NCIOCPL/ncids/files/12848599/SkipNav.txt)

* Page markdown [here](https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/SkipNav.txt?csf=1&web=1&e=iyrago)
* Static image [here](https://nih.sharepoint.com/:i:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Static%20Images/skipnav_overview.png?csf=1&web=1&e=qmcIJe)
