### ISSUE TITLE
Component pages: USWDS Components

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1184]
Update the USWDS component pages with the content needed for NCIDS for All pilot launch.

**Prerequisite:** #1164 
**Parent Issue:** #945 

### Sub-Tasks
- [x] Create content (if needed) and add links to USWDS Components in shared [Word Doc](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B8110DF27-9607-4C27-9637-A8A03FFCF1C9%7D&file=USWDS%20Components.docx&wdLOR=cC659A503-B8E0-1C4E-B105-B302AB3BCE78&action=default&mobileredirect=true)
    - [x] IA Responsibility: Overview, Links to USWDS
- [x] Review content in shared Word Doc
- [x] Convert content and images to [Markdown Template](https://github.com/NCIOCPL/ncids/issues/1164)
- [x] Add to Documentation Site

### Markdown
https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/USWDS%20Components%20Markdown.txt?csf=1&web=1&e=vblchf

### References
- [Doc Site Content Tracker](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=xA4cHF)
