### ISSUE TITLE
R2.3 News and Events - Comp Updates

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1185]
**Description:** Comp was finalized via other tickets (XX). During requirements discussion on 08/23/23, determined following changes that need to be made to the comp.

**Sub-tasks:**
- [x] Add in the "News and Events" page title to be consistent with the other NCIDS landing pages
- [x] Review adding vertical space to items in the right rail
    - [x] Make changes
    - [x] Obtain approval from team
- [x] Review comp changes with Anna [08/28]
- [x] Style new ‘heading’ classes for "Recent News Releases," and the headings of the right rail
    - Would not be any visual changes, just what is represented in Figma
    - Marking as complete - will address as part of #1150

**Comment by laurelthrash** [comment]
Approved minor changes to comp (adding "News and Events" page title / add space for vertical lines for right rail) with Anna on 08/28.

**Comment by laurelthrash** [comment]
Comp complete. Moving to "on hold" while we address other time sensitive items with NCIDS pilot tickets. Will pick back up to review the heading classes.

**Comment by laurelthrash** [comment]
Marked final sub-task as complete as this will be addressed via #1150. Cc: @monika-jaeger @blilianyu
