### ISSUE TITLE
Foundations Landing Page

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1188]
Update the Foundations landing page with the content needed for NCIDS for All pilot launch.

Parent Issue / Prerequisite: #934 

### Tasks
- [x] Create content in shared [Word Doc](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B0D56F119-4CC3-4C0F-8D6D-092D32C21BD2%7D&file=Foundations.docx&wdLOR=c8C8CEF88-5593-A042-BA64-8567107EB258&action=default&mobileredirect=true)
    - [x] IA Responsibility:
    - [x] Developer Responsibility:
    - [x] Designer Responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [x] Add to documentation site 

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)

**Comment by bennettcc** [comment]
@karlikpj The foundations landing page is ready for you - the markdown lives here:

https://nih.sharepoint.com/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=kyhT4s&cid=a24896f7%2D63e2%2D4447%2Dbdc4%2D98e0920070a8&FolderCTID=0x0120005F2FA21B2C6E704CB4EDDD13D67036B6&id=%2Fsites%2FNCI%2DOCPLNewCgovUXDesignSystem%2FShared%20Documents%2FGeneral%2FDetails%20%2D%20NCIDS%20Pilot%2FDocumentation%20Site%2FPage%20Content%20%2D%20Markdown%2FFoundations%5Fmarkdown%2Etxt&viewid=983144df%2D37bd%2D4e06%2D9fe2%2Db72f877fcf98&parent=%2Fsites%2FNCI%2DOCPLNewCgovUXDesignSystem%2FShared%20Documents%2FGeneral%2FDetails%20%2D%20NCIDS%20Pilot%2FDocumentation%20Site%2FPage%20Content%20%2D%20Markdown
