### ISSUE TITLE
Foundations subpage: Overview

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1189]
Update the Overview page within the Foundations section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [ ] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BFB66AD76-8DD8-4ADB-B175-FAA581743335%7D&file=Overview.docx&wdLOR=cAB3108CE-1E58-3E4B-AAC8-A1EAA644B3F3&action=default&mobileredirect=true)
    - [ ] IA responsibility:
    - [ ] Dev responsibility:
    - [ ] Design responsibility:
- [ ] Review content in shared document
- [ ] Create images in shared folder: `<insert link to shared folder>`
- [ ] Convert content and images to markdown
- [ ] Add to documentation site 

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)

**Comment by bennettcc** [comment]
Closing ticket - this page is not needed on the doc site
