### ISSUE TITLE
Story: Create Strawman layout for documentation site

### ISSUE THREAD

**Issue by karlikpj** [NCIOCPL/ncids#119]
This strawman site can have greeking as placeholders since we are really building out our layouts and site structures. Ultimately this initial strawman will be iterated upon until it is built off of our new NCIDS styles.

This should be based on https://github.com/uswds/uswds-site. The reason to use it as the initial basis:
* It is responsive by default
* It is using pure USWDS (mostly)
* The HTML already exists, so there should be less fiddling.

The content pages we should start with are:
* A homepage with greeking (Use landing layout)
* A components landing page (Use secondary layout)
* Our "hello world" button page under components (Use component layout)

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
TBD
```

### Tasks
We should be copying the templates for the following from the uswds site (or at least make sure that what we have matches the USWDS)
- [ ] Header
- [ ] Site Footer 
- [ ] Side Nav (See https://github.com/arcepaul/gatsby-nci/blob/main/src/components/molecules/side-nav.js) (Use a static query for now)
- [ ] Main/Mobile Nav
- [ ] Component Layout
- [ ] Landing Page Layout
- [ ] Secondary Page Layout
- [ ] Government Site Banner?

**Comment by VictoriaSunNIH** [comment]
This has been completed.  As each component is being built, we put the documentation for that component into the documentation site as a subtask and we also put it on the documentation site.
