### ISSUE TITLE
Foundations subpage: Color

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1190]
Update the Color page within the Foundations section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in [shared document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BF1F53375-736E-4AAC-8714-3CFE9B78CFDE%7D&file=Color.docx&wdLOR=c9CB93DB6-A176-5344-B038-C91CE341093B&action=default&mobileredirect=true)
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [x] Add to documentation site 
- [x] Add content from the Foundations/Appearance/Color page (see original [shared doc here](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B8536D727-9354-47B3-8780-6AC37CB96F69%7D&file=Appearance%20-%20Color.docx&action=default&mobileredirect=true)) to this page
- [x] Re-review content in shared document
- [x] Update markdown
- [x] Update documentation site
  - [x] Remove Foundations/Appearance/Color
  - [x] Remove Foundations/Appearance/State Color Tokens
  - [x] Remove Foundations/Appearance/System Color Tokens
  - [x] Remove Foundations/Appearance/Theme Color Tokens

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)

**Comment by monika-jaeger** [comment]
[Color](https://nih.sharepoint.com/:w:/s/NCI-OCPLNewCgovUXDesignSystem/EXUz9fFuc6xKhxQ8_pt4z94Bd2FFeZDaHTKnD-6-hjzcMQ?e=HytY2r) word doc has been started. This page likely will not need static images, the full color tables for State, Theme, and Color tokens should be on the Color page for ticket https://github.com/NCIOCPL/ncids/issues/1198

**Comment by bennettcc** [comment]
@karlikpj the markdown for Color page is complete, it lives here: https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Color_markdown.txt?csf=1&web=1&e=twGEo2

FYI, the tables that should be pulled in are currently displaying at the links below (adding in case they don't appear correctly in the new markdown)

State Tokens table:  https://designsystem-dev.cancer.gov/develop/foundation/appearance/state-tokens 

Theme Tokens table: https://designsystem-dev.cancer.gov/develop/foundation/appearance/theme-tokens  

System Tokens table:  https://designsystem-dev.cancer.gov/develop/foundation/appearance/system-tokens

**Comment by laurelthrash** [comment]
@karlikpj - On the Theme tokens table, it should be 'base-darkest; instead of 'base-darktest' - we found a typo on current table. Can we please make this adjustment? Thank you! @bennettcc

**Comment by bennettcc** [comment]
Thanks @laurelthrash @karlikpj! I just updated the markdown with that correction

**Comment by bryanpizzillo** [comment]
@sarinapadilla and @andyvanavery31 - we will need a ticket that will be done before this one to:
1. Disable USWDS colors from the `$tokens-color-basic`. The NCIDS colors that exist today should stay. This generated the "Basic palette" colors on any foundation page that has colors.

The NCIDS colors defined today are:
-  "cerulean": get-system-color('cerulean', 50, "vivid"),
-  "cranberry": get-system-color('cranberry', 50, "vivid"),
-  "golden": get-system-color('golden', 50, "vivid"),
-  "navy": get-system-color('navy', 50, "vivid"),
-  "teal": get-system-color('teal', 50, "vivid"),
