### ISSUE TITLE
Foundations subpage: Typography

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1192]
Update the Typography page within the Foundations section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B57365813-2449-474C-99A2-877928E8BBF4%7D&file=Typography.docx&wdLOR=cEAB2BF9E-3301-0444-AB1D-AECBA05A746C&action=default&mobileredirect=true)
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [ ] Add to documentation site 

[Typography.txt](https://github.com/NCIOCPL/ncids/files/12860979/Typography.txt)
[Font Size and Family.txt](https://github.com/NCIOCPL/ncids/files/12861213/font_size_family_markdown.txt)

Needed images are here:

Poppins: ![poppins-sample](https://github.com/NCIOCPL/ncids/assets/22639543/f31a309a-5708-43d9-952a-e09293047fcf)
Roboto: ![roboto-mono_sample](https://github.com/NCIOCPL/ncids/assets/22639543/005fc19c-7a22-44ba-bbc7-d5440a4c5139)
Open Sans: ![open-sans_sample](https://github.com/NCIOCPL/ncids/assets/22639543/82d722c9-d444-4655-8451-8542f0e9f80c)

### Resources
- [Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)
- [Markdown for Typography](https://nih.sharepoint.com/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FNCI%2DOCPLNewCgovUXDesignSystem%2FShared%20Documents%2FGeneral%2FDetails%20%2D%20NCIDS%20Pilot%2FDocumentation%20Site%2FPage%20Content%20%2D%20Markdown%2FTypography%2Etxt&parent=%2Fsites%2FNCI%2DOCPLNewCgovUXDesignSystem%2FShared%20Documents%2FGeneral%2FDetails%20%2D%20NCIDS%20Pilot%2FDocumentation%20Site%2FPage%20Content%20%2D%20Markdown)
- [Markdown for Font Size and Family](https://nih.sharepoint.com/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FNCI%2DOCPLNewCgovUXDesignSystem%2FShared%20Documents%2FGeneral%2FDetails%20%2D%20NCIDS%20Pilot%2FDocumentation%20Site%2FPage%20Content%20%2D%20Markdown%2Ffont%5Fsize%5Ffamily%5Fmarkdown%2Etxt&parent=%2Fsites%2FNCI%2DOCPLNewCgovUXDesignSystem%2FShared%20Documents%2FGeneral%2FDetails%20%2D%20NCIDS%20Pilot%2FDocumentation%20Site%2FPage%20Content%20%2D%20Markdown)

**Comment by monika-jaeger** [comment]
[Typography](https://nih.sharepoint.com/:w:/s/NCI-OCPLNewCgovUXDesignSystem/ERNYNldJJExHmaKHeSjou_QBfrgtgTiDKWnJ0UY1rhywog?e=9peEnN) word doc has been started. We likely don't need any images for this page. We could place sample text for each font as HTML.

cc: @blilianyu @laurelthrash

**Comment by laurelthrash** [comment]
Typography markdown added to description of ticket.
