### ISSUE TITLE
Foundations subpage: Spacing Units

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1193]
Update the Spacing Units page within the Foundations section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B03DD9DCA-2572-42EA-AFD4-8A5A1D5F264D%7D&file=Spacing%20Units.docx&wdLOR=c78551894-44CF-5C4C-8343-020A5BDE695F&action=default&mobileredirect=true)
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [ ] Add to documentation site 
[Spacing Units (1).txt](https://github.com/NCIOCPL/ncids/files/12717963/Spacing.Units.1.txt)

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)

**Comment by laurelthrash** [comment]
@karlikpj Outline is ready for you. The markdown lives here:

https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Spacing%20Units.txt?csf=1&web=1&e=0nLkoD

Note: "Figma Guide under Spacing Units" should link to the Figma Guide page on the Documentation Site.

**Comment by bennettcc** [comment]
@dlescarbeau Spacing units markdown has been attached to the ticket
