### ISSUE TITLE
Get Started Landing Page

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1195]
Update the Get Started landing page with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B81B7560B-5295-4D1F-B0F1-5312F13C05BB%7D&file=Get%20Started.docx&action=default&mobileredirect=true&wdLOR=cD71F7C53-9273-AA4A-A24C-B87EBCAFDBDA)
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [x] Add to documentation site 

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)

**Comment by andyvanavery31** [comment]
Content Markdown for Get Started is here: https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Get%20Started%20with%20NCIDS%20Markdown.txt?csf=1&web=1&e=S1jn7B

**Comment by bennettcc** [comment]
@karlikpj The markdown for this page is done and lives here: https://nih.sharepoint.com/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=kyhT4s&cid=a24896f7%2D63e2%2D4447%2Dbdc4%2D98e0920070a8&FolderCTID=0x0120005F2FA21B2C6E704CB4EDDD13D67036B6&id=%2Fsites%2FNCI%2DOCPLNewCgovUXDesignSystem%2FShared%20Documents%2FGeneral%2FDetails%20%2D%20NCIDS%20Pilot%2FDocumentation%20Site%2FPage%20Content%20%2D%20Markdown%2FGet%20Started%20with%20NCIDS%20Markdown%2Etxt&viewid=983144df%2D37bd%2D4e06%2D9fe2%2Db72f877fcf98&parent=%2Fsites%2FNCI%2DOCPLNewCgovUXDesignSystem%2FShared%20Documents%2FGeneral%2FDetails%20%2D%20NCIDS%20Pilot%2FDocumentation%20Site%2FPage%20Content%20%2D%20Markdown
