### ISSUE TITLE
Get Started subpage: For Developers

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1197]
Update the For Developers subpage within the Get Started section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B00D8D971-6487-44F5-A931-0E41EF7EB4E5%7D&file=For%20Developers.docx&wdLOR=c224FAE3A-CE37-094D-B711-8326690DDF44&action=default&mobileredirect=true)
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [x] Add to documentation site 

Markdown text:

https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/ForDevelopers.txt?csf=1&web=1&e=0zHd7T

**Comment by bennettcc** [comment]
This page is ready for building in the doc site - markdown text has been added to the description
