### ISSUE TITLE
Appearance subpage: Color

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1198]
Update the Color page within the Appearance section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/doc2.aspx?sourcedoc=%7B8536D727-9354-47B3-8780-6AC37CB96F69%7D&file=Appearance%20-%20Color.docx&action=default&mobileredirect=true)
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [ ] Add to documentation site 

Markdown lives here:

https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/[Border_markdown.txt](https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Border_markdown.txt?csf=1&web=1&e=psNz7b)?csf=1&web=1&e=psNz7b

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)

**Comment by bennettcc** [comment]
The border page is ready - markdown lives here:

https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/[Border_markdown.txt](https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Border_markdown.txt?csf=1&web=1&e=psNz7b)?csf=1&web=1&e=psNz7b

**Comment by bennettcc** [comment]
Closing this ticket, all color content is being built via https://github.com/NCIOCPL/ncids/issues/1190
