### ISSUE TITLE
Appearance subpage: Border

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1199]
Update the Border page within the Appearance section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B6C6226AA-40DE-4679-96DB-387EAAE7445D%7D&file=Border.docx&wdLOR=cE294A9D1-A49F-4941-B9E3-517FF62C08D1&action=default&mobileredirect=true)
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [ ] Add to documentation site 

[Border_markdown.txt](https://github.com/NCIOCPL/ncids/files/12702413/Border_markdown.txt)

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)
