### ISSUE TITLE
Appearance subpage: Opacity

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1202]
Update the Opacity page within the Appearance section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BCDEBDA48-10BF-4BE4-9B0D-2420ECD19046%7D&file=Opacity.docx&wdLOR=c5FFBA675-6154-564F-A4C4-BC56B768B816&action=default&mobileredirect=true)
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [x] Add to documentation site 

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)

**Comment by bennettcc** [comment]
@karlikpj the opacity ticket is ready for you. The markdown has been added and lives here:

https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Opacity_markdown.txt?csf=1&web=1&e=UAH16B
