### ISSUE TITLE
Typography subpage: Font Size and Family

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1203]
Update the Font Size and Family page within the Typography section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B031CD7C8-410C-4514-971E-111D3F82803A%7D&file=Font%20Size%20and%20Family.docx&wdLOR=c96351260-D48C-244D-8FA0-CD445A5A5FBD&action=default&mobileredirect=true)
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [x] Add to documentation site 

Markdown for Font Size and Family lives here: 

https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/font_size_family_markdown.txt?csf=1&web=1&e=3iaTov

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)

**Comment by bennettcc** [comment]
@karlikpj the font size and family ticket is ready for you. Markdown has been added to the desc and commented here:

https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/font_size_family_markdown.txt?csf=1&web=1&e=3iaTov
