### ISSUE TITLE
Typography subpage: Text Styles

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1204]
Update the Text Styles page within the Typography section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in shared document: `<insert link to word doc>`
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder:
- [x] Convert content and images to markdown: [text file](https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/TextStyles.txt?csf=1&web=1&e=I5RWu8)
- [x] Add to documentation site 

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)

Text file with markdown

**Comment by sarinapadilla** [comment]
@karlikpj the text file with the markdown lives [here](https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/TextStyles.txt?csf=1&web=1&e=I5RWu8)! I took the font weight table from [this existing page](https://designsystem-dev.cancer.gov/develop/foundation/typography/fonts#font-weight-tokens) so hopefully it works.
