### ISSUE TITLE
Typography subpage: List Reset

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1206]
Update the List Reset page within the Typography section of the documentation site with the content needed for NCIDS for All pilot launch.

### Sub-Tasks
- [ ] Draft content for page
- [ ] Add images (if needed)
- [ ] Convert to .mdx
- [ ] Update documentation site page
