### ISSUE TITLE
Spacing Units subpage: Margin and Padding

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1208]
Update the Margin and Padding page within the Spacing Units section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BF3D1AC41-71D6-4E91-B996-AECA8E59647B%7D&file=Margin%20and%20Padding.docx&wdLOR=cDC1EFA17-F20D-854B-95CA-F645F3256FB2&action=default&mobileredirect=true)
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [ ] Add to documentation site 

Markdown lives here:

https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Margin_padding_markdown.txt?csf=1&web=1&e=h1EZfv

[Margin_padding_markdown.txt](https://github.com/NCIOCPL/ncids/files/12686573/Margin_padding_markdown.txt)

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)

**Comment by bennettcc** [comment]
@karlikpj Margin and padding is ready for you. The markdown lives here:

https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Margin_padding_markdown.txt?csf=1&web=1&e=h1EZfv
