### ISSUE TITLE
Layout and Positioning subpage: Float

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1209]
Update the Float page within the Layout and Positioning section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [ ] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BBBC868EB-02B8-47EE-9C26-62390FA14F8C%7D&file=Float.docx&wdLOR=c99E78395-5A6C-9841-BD1C-BA6D4384B9BB&action=default&mobileredirect=true)
    - [ ] IA responsibility:
    - [ ] Dev responsibility:
    - [ ] Design responsibility:
- [ ] Review content in shared document
- [ ] Create images in shared folder: `<insert link to shared folder>`
- [ ] Convert content and images to markdown
- [ ] Add to documentation site 

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)

**Comment by bennettcc** [comment]
Per slack discussion on 7/1: the clearfix content will be added to the float page because “Clearfix” is how you clear a float to make sure other content does not float. 

@adrianacastaneda to update the doc site sitemap to remove the clearfix page
