### ISSUE TITLE
Layout and Positioning subpage: Clearfix

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1212]
Update the Clearfix page within the Layout and Positioning section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [ ] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B0BEB0D68-D171-4631-B693-9A171B1429A2%7D&file=Clearfix.docx&wdLOR=c985C5E3B-61C1-3F4F-9EDA-5C2230274A20&action=default&mobileredirect=true)
    - [ ] IA responsibility:
    - [ ] Dev responsibility:
    - [ ] Design responsibility:
- [ ] Review content in shared document
- [ ] Create images in shared folder: `<insert link to shared folder>`
- [ ] Convert content and images to markdown
- [ ] Add to documentation site 

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)

**Comment by laurelthrash** [comment]
Discussed during 10/11 UX backlog meeting and determined we will move these out of the Design backlog. Need further discussion from developer perspective if pages associated with "Layout and Positioning" are still needed and, if so, what modifications to the requirements of this ticket are required. @sarinapadilla @andyvanavery31

**Comment by bennettcc** [comment]
Closing this ticket - the content for clearfix will be added to the float content page. 

(Float ticket: https://github.com/NCIOCPL/ncids/issues/1209)
