### ISSUE TITLE
Layout and Positioning subpage: Display

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1213]
Update the Display page within the Layout and Positioning section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B5102C32D-9BAB-4111-B5BB-EF710E800BB0%7D&file=Display.docx&wdLOR=cD6324434-C16A-9149-ACE2-11574CEB287B&action=default&mobileredirect=true)
    - [ ] IA responsibility:
    - [x] Dev responsibility:
    - [ ] Design responsibility:
- [ ] Review content in shared document
- [ ] Create images in shared folder: `<insert link to shared folder>`
- [ ] Convert content and images to markdown
- [x] Add to documentation site 

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)
