### ISSUE TITLE
Layout and Positioning subpage: Order

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1214]
Update the Order page within the Layout and Positioning section of the documentation site with the content needed for NCIDS for All pilot launch.

### Sub-Tasks
- [ ] Draft content for page
- [ ] Add images (if needed)
- [ ] Convert to .mdx
- [ ] Update documentation site page

**Comment by laurelthrash** [comment]
Discussed during 10/11 UX backlog meeting and determined we will move these out of the Design backlog. Need further discussion from developer perspective if pages associated with "Layout and Positioning" are still needed and, if so, what modifications to the requirements of this ticket are required. @sarinapadilla @andyvanavery31

**Comment by sarinapadilla** [comment]
Closing this ticket, as it will be done as part of the Flex page (#1216).
