### ISSUE TITLE
Layout and Positioning subpage: Layout Grid

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1215]
Update the Layout Grid page within the Layout and Positioning section of the documentation site with the content needed for NCIDS for All pilot launch.

NOTE: We did change this from USWDS, so while we will link to their documentation we need to have a disclaimer:
  ```“A) NCIDS does not recommend changing settings ever, and B) we changed setting X to be foo.”```

### Tasks
- [ ] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B4E8FF002-559E-41AB-9306-69FEBC3DFE49%7D&file=Layout%20Grid.docx&wdLOR=c29D145C5-A665-8B48-95BA-127D7FC1245E&action=default&mobileredirect=true)
    - [ ] IA responsibility:
    - [ ] Dev responsibility:
    - [ ] Design responsibility:
- [ ] Review content in shared document
- [ ] Create images in shared folder: `<insert link to shared folder>`
- [ ] Convert content and images to markdown
- [ ] Add to documentation site 

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)

**Comment by sarinapadilla** [comment]
Duplicate of #1194 - closing
