### ISSUE TITLE
Layout and Positioning subpage: Flex

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1216]
Update the Flex page within the Layout and Positioning section of the documentation site with the content needed for NCIDS for All pilot launch.

### Sub-Tasks
- [ ] Draft content for page
- [ ] Add images (if needed)
- [ ] Convert to .mdx
- [ ] Update documentation site page

**Comment by karlikpj** [comment]
Approach: to use code blocks for the examples. Currently each flex example has various differences in dom and example classes - would be very time consuming to make a single do all module for this and show code snippets.

**Comment by karlikpj** [comment]
Approach to use code preview's for the examples in the utility template.
