### ISSUE TITLE
Home and Landing Pages subpage: Guide Card Row

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1219]
Update the Guide Card Row page within the Home and Landing Pages section of the documentation site with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BFD0E91F2-8D88-4362-830A-AD439FFBBAE6%7D&file=Guide%20Card%20Row.docx&wdLOR=c84D9BC62-974F-EA4F-9C03-60D380280EF1&action=default&mobileredirect=true)
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [x] Add code previews
- [x] Add to documentation site

### Markdown
https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/Guide%20Card%20Row%20Markdown.txt?csf=1&web=1&e=bvUszQ

[Guide Card Row Markdown.txt](https://github.com/NCIOCPL/ncids/files/12848929/Guide.Card.Row.Markdown.txt)

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)
