### ISSUE TITLE
About NCIDS Landing Page

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1220]
Update the About NCIDS landing page with the content needed for NCIDS for All pilot launch.

### Tasks
- [x] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B3B73AD25-8F30-43ED-A91B-384C3A098A31%7D&file=About%20NCIDS.docx&wdLOR=cD9F1F179-E68F-3947-B06F-C055A4EB917E&action=default&mobileredirect=true)
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [ ] Add to documentation site 

### Markdown
https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/About%20NCIDS%20Markdown.txt?csf=1&web=1&e=Lgv68w
[About NCIDS Markdown.txt](https://github.com/NCIOCPL/ncids/files/12794093/About.NCIDS.Markdown.txt)

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)
