### ISSUE TITLE
Components Landing Page

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1221]
Update the Components landing page with the content needed for NCIDS for All pilot launch.

**Parent Issue:** #945

### Tasks
- [x] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BDF14C61F-C1B4-4107-A27B-C2EBE396E707%7D&file=Components.docx&wdLOR=cA1B9C9F6-9291-7743-8D31-A7BD2980687F&action=default&mobileredirect=true)
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: `<insert link to shared folder>`
- [x] Convert content and images to markdown
- [ ] Add to documentation site 

Markdown:

https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/[components_markdown.txt](https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Markdown/components_markdown.txt?csf=1&web=1&e=w5swOP)?csf=1&web=1&e=w5swOP

[components_markdown.txt](https://github.com/NCIOCPL/ncids/files/12754170/components_markdown.txt)

### Resources
[Doc Site Content Inventory](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Doc%20Site%20Content%20Inventory.xlsx?d=wff83f29cd1554e99892fd963404c69a1&csf=1&web=1&e=QZgQLq)
