### ISSUE TITLE
Add USWDS Link for Layout and Positioning pages

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1223]
Several pages on the documentation site do not need any extra documentation other than a link to USWDS documentation.

- Layout Grid
  - NOTE: We did change this from USWDS, so while we will link to their documentation we need to have a disclaimer:
  ```“A) NCIDS does not recommend changing settings ever, and B) we changed setting X to be foo.”```
- Float
- Z-index
- Clearfix
- Display
- Order
- Flex
- List Reset

### Tasks
- [ ] Create content in the shared [Word Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BF1F53375-736E-4AAC-8714-3CFE9B78CFDE%7D&file=Color.docx&wdLOR=c9CB93DB6-A176-5344-B038-C91CE341093B&action=default&mobileredirect=true)
  - NOTE: This won't be very much content for most pages in this ticket. (Mostly USWDS link)
- [ ] Review content in shared document
  - NOTE: This won't be very much content for most pages in this ticket. (Mostly USWDS link)
- [ ] Create images in shared folder: `<insert link to shared folder>`
- [ ] Convert content and images to markdown
- [ ] Add to documentation site 

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by andyvanavery31** [comment]
This task of linking to USWDS on this ticket will be completed for each of the listed pages for the Documentation Site as a part of the completion of those standalone tickets. Therefore, this is redundant, and will be closed.
