### ISSUE TITLE
[R2. Content] Final To-Dos: DCEG R2 Home and Landing Page Go-Live

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1246]
**Description:** This ticket is to outline the final to-dos ahead of our upcoming DCEG home and landing page go-live.

**Sub-tasks:**
- [x] Copy edit (Mel - in progress) **[09/18 - 09/20]**
- [x] Update content templates based on copy edit (Laurel/Michael) **[09/21 - 09/22]**
- [x] Purchase stock imagery (In Progress) **[09/18 - 09/20]**
- [x] Verify rotating featured content **[09/21 - 09/22]**
- [x] Draft pages (Laurel/Michael) **[09/25 - 09/26]**
- [x] Review pages (Alex) **[09/27]** 
- [x] Spot check pages (Mel/ODDC) **[09/27]** 
- [x] Publish pages (Laurel/Michael) **[09/28]**

**Comment by laurelthrash** [comment]
Pages published on 09/28. Closing this ticket.
