### ISSUE TITLE
Update Design Assets - PowerPoint Templates

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1249]
META: #969

**Description:** 
- Details: Need to update existing design assets to align with the updated color palette/style. Assets should also be verified to meet 508 compliance standards. 
- Assets that need to be updated are found here on MyNCI: https://mynci.cancer.gov/topics/nci-branding-logo-use-templates#Templates. 

**Sub-tasks:**
- [x] Update PPT Templates (Dragutin)
    - [x] Align with updated color palette/style
    - [x] Include a slide with basic guidance for how to make slides sets 508 compliant from MyNCI 
        - Include single placeholder ticket slide 
        - ODDC to plug in text later on (no more than 5-6 bullets per slide, two slides max, with a link out)
    - [x] Run "Check Accessibility" tool in PowerPoint to identify and additional errors reported in the inspection results
        - [x] Ensure all slides have a heading
        - [x] Reconsider "Thank You" solution on the last slide
    - [x] Recommendation: consolidate "PowerPoint Templates" and "Webinar, Meeting, and Presentation Videos" to set of 4  templates (instead of 8) (confirm with Anna this was accepted by DOC PMO) **Asked Anna via Teams 09/22**
- [x] Internal review
- [x] ODDC review
- [x] Finalize templates
- [x] Create Jira ticket to update existing templates on MyNCI
- Moving to separate ticket:
    - Update NCI Branding Guide on MyNCI to reflect updated templates ([page 14 here](https://mynci.cancer.gov/topics/nci-branding-and-logo-use-guide ))
        - Review guide for any other necessary tweaks
        - Review Alex email (to Laurel and Dragutin) with specific recommendations and changes (subject: "Branding guide updates for new PowerPoint templates")

**Comment by laurelthrash** [comment]
Received confirmation that we can consolidate to a single set of 4 PowerPoint Templates (from the existing 8). Cc: @dcvijanovic1k

**Comment by laurelthrash** [comment]
Update: making updates based on conversation between Alex/Dragutin on 11/29. Then, will share a copy with DCEG to test. Once finalized, we will proceed with updating the other colors post to MyNCI for DOCs to use.

**Comment by dcvijanovic1k** [comment]
Update: Alex is currently talking with Anna about next steps/how to resolve recent feedback

**Comment by laurelthrash** [comment]
@dcvijanovic1k Discussed the PPTs with the federal team today. We have the green light to make updates to all color templates and upload them to MyNCI. 

Note: need to update "www.cancer.gov" to "cancer.gov" on the final slide to be consistent with the GovDelivery banners.

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - here are the PPTs for MyNCI. Alex has signed off, and we are at long last good to go. Please let me know if you need anything else! 
[NCI PPT Template 16x9 BLUE.pptx](https://github.com/NCIOCPL/ncids/files/14128469/NCI.PPT.Template.16x9.BLUE.pptx)
[NCI PPT Template 16x9 GRAY.pptx](https://github.com/NCIOCPL/ncids/files/14128470/NCI.PPT.Template.16x9.GRAY.pptx)
[NCI PPT Template 16x9 RED.pptx](https://github.com/NCIOCPL/ncids/files/14128471/NCI.PPT.Template.16x9.RED.pptx)
[NCI PPT Template 16x9 WHITE.pptx](https://github.com/NCIOCPL/ncids/files/14128472/NCI.PPT.Template.16x9.WHITE.pptx)

**Comment by laurelthrash** [comment]
Created Jira ticket CGOV-20499 to replace the existing PPTs on MyNCI with the above templates. Cc: @dcvijanovic1k

**Comment by laurelthrash** [comment]
PPTs complete and added to MyNCI. There are remaining steps to update the corresponding Branding Guide but will pull that into a separate ticket. Closing this ticket. Cc: @dcvijanovic1k
