### ISSUE TITLE
Research: Personas - Heartbeat Synthesis 

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#127]
> Feature/Main User Story: [Enter user story ticket association here] 
Part of the larger Heartbeat Synthesis research initiative https://github.com/NCIOCPL/ncids/issues/85

### What do you want to learn from this research?
List the questions you would like to answer

1. Question
2. Question
3. Question

##

### User / Audience
Who will be using this design? What personas / audiences are you considering?

##

### Project Stage
- [ ] Discovery
- [ ] Design
- [ ] Development
- [ ] Live

##

### Timeline
When would you need findings / insights?

##

### Resources
* Link to product brief:
* Github link:
* Screens or site: 

##

### Additional Notes
*Any other comments or notes if needed:*

---
>Section to be completed by user research after ticket creation
### Research Activity
- [ ] Intake and Approach
- [ ] Research plan 
- [ ] Draft tasks, guides, materials
- [ ] Recruitment
- [ ] Study launch
- [ ] Analysis and report
