### ISSUE TITLE
R2.3 News and Events Page Content Launch

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1287]
> [Schedule Here](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.3/Project%20Management/DRAFT_R2.3%20Sprint%20Timeline.xlsx?d=wff23f95780c14ff287a506891ffcdc30&csf=1&web=1&e=wanhjj)

### Description
- https://www.cancer.gov/news-events
- https://www.cancer.gov/espanol/noticias

Team is preparing for content conversations ahead of R2.3 launch. Designers & IAs will determine R2.3 recommendations and create mock up that use R2.3 components. 

PAGES in ENGLISH and SPANISH: Home and landing page with both English and Spanish must launch at the same time. 

### Sub-Tasks
- [x] Refresh English comp with latest content 
- [x] Create Spanish comp
- [x] Review internally
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]
- [x] Content stakeholder review
- [x] Align with federal team and update comp
- [x] Obtain needed translations (tracked via Jira)
    - [x] Update content template (Adriana)
    - [x] Update Figma file (Lilian)
    - [x] Make a notation on R2.3 Mural board (Laurel)
- Obtain tagline information from Anna/Kelli M. > then translate to Spanish (as of 12/11, decided to move forward with current tagline for now)
    - Update content template (Adriana)
    - Update Figma file (Lilian)
    - Make a notation on R2.3 Mural board (Laurel)
- [x] Determine if will include hero image (as of 12/19, decided not to include hero but need to share with appropriate folks first before confirming)
- [x] Send stakeholder messaging
- [x] Build draft pages
- [x] Review draft pages
- [x] Launch content 

### Final Documentation
- Mural board for content owner feedback:
- Content supplemental document/talking points:
- Comp: [Figma Link](https://www.figma.com/file/XH87Z6GvJ0MWoX16l0FzKo/News-%26-Events-Landing-Page?type=design&node-id=0-1&mode=design&t=hQ2Ek27SNbH2BvrY-0)
- Analytics PDF: 
- Analytics Dashboard:

**Comment by blilianyu** [comment]
News and Events English & Spanish comps are ready for review: https://www.figma.com/file/XH87Z6GvJ0MWoX16l0FzKo/News-%26-Events-Landing-Page?type=design&node-id=770%3A2948&mode=design&t=Bd4zZSQLMMDEZNfK-1

**Comment by blilianyu** [comment]
@laurelthrash Comps have been updated. https://www.figma.com/file/XH87Z6GvJ0MWoX16l0FzKo/News-%26-Events-Landing-Page?type=design&node-id=770%3A2948&mode=design&t=Bd4zZSQLMMDEZNfK-1

**Comment by laurelthrash** [comment]
Thanks, @blilianyu! Mind please sending around to the team via Slack as an FYI? Marking as "On hold" until our review with the federal team on Tues. 10/24.

**Comment by laurelthrash** [comment]
Final internal review approved during 10/19 UX team review.

**Comment by laurelthrash** [comment]
Reviewed comps with ODDC on 10/24. No changes to comps discussed, with exception of update to mobile version where thumbnail on Collections component is removed (consistent with determined requirements change). @adrianacastaneda preparing the Mural board for stakeholder meeting. Cc: @lburack @blilianyu

**Comment by laurelthrash** [comment]
Changes to English comp following stakeholder review (also outlined in the Mural board) @blilianyu 
- [ ] Update feature card row heading from "Latest Stories" to "Latest Blog Posts"
- [ ] Change "Recent News Releases" to "Latest News Releases"
- [ ] Add "Inside Cancer Careers Podcast" to Media Resources list after "Images and B-roll"
- [ ] Remove Twitter icon/button
- [ ] Add "Blog" before "Cancer Currents" section so it reads "Cancer Currents Blog"
- [ ] Change text description under Cancer Current from "Find the latest in...." to "Find news and updates on the latest cancer research."
- [ ] Add "Advisory Board Meetings" between "Conferences" and "Social Media Events" under "Events" section
- Update tagline (information from Anna forthcoming but will not be ready for updated comp)

Changes to Spanish comp:
- [ ] Change collection heading from "Ultimos comuncados de prensa" to "Comunicados de prensa"

Still need to align on final changes to the Spanish comp.

**Comment by blilianyu** [comment]
Comps have been updated: https://www.figma.com/file/XH87Z6GvJ0MWoX16l0FzKo/News-%26-Events-Landing-Page?type=design&node-id=770%3A2948&mode=design&t=s3jKx2hZDtUf2VSF-1

**Comment by laurelthrash** [comment]
Additional comp changes for comps following continued Teams conversation: @blilianyu @adrianacastaneda @lburack 

Spanish Comps
- [ ] Remove Twitter/X from media resources, as done in English
- [x] Add description below media resources "Encuentre nuestras redes sociales y recursos en Inglés como información de contacto de los medios, materiales de archivo para periodistas, y fotografías e ilustraciones para comunicadores médicos y de salud pública."
- [x] Changing collection button label text to: Spanish: "Todos los comunicados de prensa

English Comps
- [ ] Remove "Inside Cancer Careers Podcast" under Media Resources
- [x] Changing collection button label text to: “All NCI News Releases"

Both Comps
- [x] Remove social media events link

Notes
- Changes for tagline (EN and SP) forthcoming

**Comment by adrianacastaneda** [comment]
@blilianyu @laurelthrash Please see updates for the Spanish N&E comp below:

Feature card row:
- [ ] Change heading to: Novedades recientes

Collection component (News releases / Comunicados de presenda section):
- [ ] Change button label to: Más comunicados de prensa

- Media Resource section:
- [ ] Change heading to: Recursos para los medios de comunicación
- [ ] Remove description
- [ ] Change link labels to:
> - [ ] Contactos
> - [ ] Material digital
> - [ ] Redes sociales
- [ ] Remove Facebook button

Blog section
- [ ] Capitalize the "T" in "Temas"
- [ ] Change description to: Infórmese sobre las últimas noticias y actualizaciones sobre el cáncer

**Comment by blilianyu** [comment]
@adrianacastaneda Comp has been updated. 

cc: @laurelthrash

**Comment by laurelthrash** [comment]
Content launched the afternoon of 01/09/24. Closing this ticket.
