### ISSUE TITLE
[R2] Post Launch Analytics Analysis/Recommendations (NCI-CONNECT)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1293]
**Description:** Initiated post-launch dashboards for Nano, and NCI-C. Need to check-in to determine if enough data has accumulated to initiate analysis of the home and landing pages.

Determined on 02/26/24 with Anna that we will not proceed with recommendations for Nano since Nano will be folded into the DCTD site migration. 

**Sub-tasks:**
- [x] Verify data accumulation via significance calculator spreadsheet
- [x] Prepare analysis and recommendations
- [x] Share analysis/recommendation with Alex/Anna (Email)
- [x] Share analysis/recommendation with DOC (Email)
- [x] Invite DOC to implement recommendations on their site
-  Initiate additional analytics tickets for tracking, as needed [N/A since NCI-CONNECT is responsible for making changes, if desired, and future analytics will roll into O&M]

**Comment by laurelthrash** [comment]
Confirmed 01/25/24 that DCEG has accumulated enough data to move forward. Adjusting this ticket to include only Nano and NCI-Connect, and creating a separate ticket to proceed with analytics for DCEG. Moving this ticket back to the backlog.

**Comment by laurelthrash** [comment]
Shared analysis, recommendation, and next steps with Alex (cc: Anna) via email 03/13/24. Awaiting confirmation before sharing with NCI-CONNECT.

**Comment by laurelthrash** [comment]
Sent analysis summary and recommendations to NCI-CONNECT on 03/19.
