### ISSUE TITLE
[Pilot] Batch 1 Doc Site Link Review (ODDC)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1295]
**Description:** ODDC to review pages for the DOC site in batches. Batch 1 for review through EOD Tues. 10/10.

**Sub-tasks:**
- [x] Share batch 1 review sheet with ODDC
- [x] ODDC add review of mission critical edits
- [x] Edits either 1) added to appropriate CR or to, 2) backlog for future remediation

**Comment by laurelthrash** [comment]
All feedback either added to the appropriate change request (CR) or backlogged for future prioritization. Closing this ticket. Final changes will be tracked via the appropriate CR.
