### ISSUE TITLE
[Pilot] Refresh One Pager with Updated Links

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1296]
> Related ticket: #1139 

**Description:** We created the one pager for the pilot but need to refresh several links to point to the updated location. These are outlined below.

**Sub-tasks:**
- [x] Update one pager with following links:
    - [x] Update the NCIDS Documentation Site link to point to: https://designsystem-dev.cancer.gov/develop/ 
    - [x] Update Example Site link to point to: https://designsystem-dev.cancer.gov/develop/example-site/
- [x] Remediate for 508 compliance, as needed
- [ ] Replace exiting one pages on Pilot Teams space (PM)

**Comment by laurelthrash** [comment]
@dcvijanovic1k - updated one pager looks great! I'll replace the current one pager in our Teams space. Thank you! Closing this ticket.
