### ISSUE TITLE
[Pilot] Batch 2 Doc Site Link Review (ODDC)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1307]
**Description:** ODDC to review pages for the DOC site in batches. Batch 2 for review through EOD Fri. 10/13.

**Sub-tasks:**
- [x] Share batch review sheet with ODDC
- [ ] ODDC add review of mission critical edits
- [ ] Edits either 1) added to appropriate CR or to, 2) backlog for future remediation
