### ISSUE TITLE
[Pilot] Batch 3 Doc Site Link Review (ODDC)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1342]
**Description:** ODDC to review pages for the DOC site in batches. Batch 2 for review through EOD Fri. 10/20.

**Sub-tasks:**
- [x] Share batch review sheet with ODDC
- [x] ODDC add review of mission critical edits
- [x] Edits either 1) added to appropriate CR or to, 2) backlog for future remediation

**Comment by laurelthrash** [comment]
Batch 3 review is complete. Closing this ticket.
