### ISSUE TITLE
[R2.1 Analytics] Group 1 - Homepage, About Cancer, About NCI

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1343]
**Description:** Following our R2.1 home and landing page launch, we are capturing analytics to analyze and produce recommendations for changes/content improvements.

**Sub-tasks:**
- [x] Review R2.1 analytics data and document insights/findings in [R2.1 Landing Page Analytics Notes Questions document] **[Nicole - Deadline 11/20]**
- [x] Finalize high level findings to present to Anna **[Deadline 12/5]**
- [x] Finalize detailed findings and recommendations for Homepage **[Deadline 12/15]**
- [x] Finalize detailed findings and recommendations for About Cancer **[Deadline 12/15]**
- [x] Share with Anna **[Deadline week of 12/15]**
- [x] Pare down list of content stakeholders for all pages (Anna) **[Deadline 12/15]**
- [x] Finalize detailed PPT for About NCI and review with Anna 
    - About NCI on a different timeline as we retroactively pulled it into Group 1 
- [x] Draft Combined PPT for Group 1 (Adriana and Joe) **[Deadline 1/22]**
    - [x] Send to Anna for reference 
- [x] Draft pre-meeting summary email (Adriana) **[Deadline 1/19]**
- [x] Review and update pre-meeting summary email (Joe) **[Deadline 1/22]**
- [x] Send pre-meeting summary email (Laurel) **[Deadline 1/23]**
- [x] Meet with content stakeholders to share recommendations **[Scheduled 1/29]**
- [x] Follow-up from Meeting (see Canvas)
- [x] Implement content changes [02/15]
- [x] Create milestone to check-in on homepage promo blocks
- [x] Ensure potential development enhancements are captured 
- [x] Create tickets with summarization of each change (3 tickets) (Adriana)

**Resources**
- [Timeline](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Measurement%20%26%20Evaluation/R2.1%20Analytics%20Recommendations.xlsx?d=we6579666a99647d3b0df88cd7e386601&csf=1&web=1&e=75jbRt)
- [Dashboards linked in this Word doc](https://gcc02.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fnih.sharepoint.com%2F%3Aw%3A%2Fs%2FNCI-OCPLNewCgovUXDesignSystem%2FEU9yf71c6mpGu03Rtj7YZDsBcvf7jsb5IifO-bnvIZI__Q%3Fe%3D5ASm0D&data=05%7C01%7Clindsay.burack%40nih.gov%7C648870726b2841e823db08dbc90b93e8%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638324823781937114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XsvqA6ckLgcRFPyxnCffoT9ud4DN%2F3kTKm%2BEilJHIwI%3D&reserved=0)

**Comment by adrianacastaneda** [comment]
updates have been made and will be QCed by @laurelthrash by EOD

**Comment by laurelthrash** [comment]
Adopted recommendations by Anne M. in addition to the discussed changes for the Homepage and the About Cancer and About NCI landing pages. The one exception is on the Homepage for which we will hold on adjusting the current promo blocks until a later time. Content published on 02/15/24. Closing this ticket.
