### ISSUE TITLE
[R2.4] CT Landing Page Final Comp Updates

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1362]
**Description:** Initiated final updates to the comp following 10/25 requirements meeting. 

**Sub-tasks:**
- [x] Update comp (Dragutin)
- [x] Align internally **(Tues 10/31)**
- [x] Align during req. meeting **(Wed 11/1)**
- [x] Share with Anna/ODDC for final review **(Mon 11/6)**
- [x] Generate next steps accordingly

**Comment by laurelthrash** [comment]
Changes from 11/1 requirements meeting:
- [ ] Revert color of drop down to be out of the box color
- [ ] Second comp with "A" result open should be changed to "Close All Cancer Types" with a minus

Cc: @dcvijanovic1k

**Comment by laurelthrash** [comment]
[In Progress] Notes from 11/6 with Anna:

- Q: do you type in the box? A: it is a combo box - either use drop down or can start typing.
- Q: have we talked about functionality for this? A: We have started. Need to determine how the list and combo box are populated. Confirming the look here. 
- Q: are the accordions manually edited? 
- Q: how often do the list of cancer types change? A: not that often, although, the names may change.
