### ISSUE TITLE
TTC Homepage: R2 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1380]
> META: #743

### Description
https://techtransfer.cancer.gov/

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2 recommendations and create mock up that use R2 components only. 

### Sub-Tasks
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]

### Final Documentation
- Mural board for content owner feedback: [Link](https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1698845231951/2b066bd4ea0ffc4cdb2e5da89f7343a3c323d627?sender=u4f98fba0cad73dd945780265)
- Content supplemental document/talking points: [INSERT]
- English Comp: [https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26[…]%2C99%2C0.25&t=sd6l9jMFauIwY4wA-1&scaling=min-zoom&mode=design](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=4412%3A9404&type=design&node-id=4412-10247&viewport=-588%2C99%2C0.25&t=sd6l9jMFauIwY4wA-1&scaling=min-zoom&mode=design)
- Analytics Dashboard: https://www5.an.adobe.com/x/5_12y4kl

**Comment by monika-jaeger** [comment]
Figma comps will live here: [WIP]
- [TTC Homepage Widescreen](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=4412%3A9404&type=design&node-id=4412-10247&viewport=250%2C389%2C0.25&t=mESSJqtLddn8UDSJ-1&scaling=min-zoom&mode=design)
- [TTC Homepage Mobile](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=4412%3A9404&type=design&node-id=4412-10213&viewport=250%2C389%2C0.25&t=mESSJqtLddn8UDSJ-1&scaling=min-zoom&mode=design)

cc: @laurelthrash @driscollmd @dcvijanovic1k

**Comment by laurelthrash** [comment]
No changes on comp discussed during 11/7 internal UX meeting.

**Comment by dcvijanovic1k** [comment]
Link to comp here: [https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26[…]%2C99%2C0.25&t=sd6l9jMFauIwY4wA-1&scaling=min-zoom&mode=design](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=4412%3A9404&type=design&node-id=4412-10247&viewport=-588%2C99%2C0.25&t=sd6l9jMFauIwY4wA-1&scaling=min-zoom&mode=design)

**Comment by laurelthrash** [comment]
@driscollmd @dcvijanovic1k @monika-jaeger Updates from sync with federal team:
- [ ] Replace video at the bottom of the page with the "Partnering with NIH" video. Alex provided the thumbnail in the meeting chat

Notes
- During the demo, we'll need to acknowledge that the video isn't public yet, but we assume it will be by launch

**Comment by laurelthrash** [comment]
Mural board shared with ODDC ahead of 12/4 kick-off meeting.

**Comment by laurelthrash** [comment]
Mural board shared with client for review. Will close this ticket since the work outlined in the ticket is complete. Will create additional tickets for next steps. Cc: @driscollmd @dcvijanovic1k
