### ISSUE TITLE
Headings - Create Doc Site Language

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1382]
**Description:** Work is in progress to develop R2.3 components that will be added to our Documentation Site. Need to draft language for Headings (Foundations > Typography > Headings). 

Page initiated here: https://designsystem-dev.cancer.gov/pr-1356/foundations/typography/headings

**Sub-tasks:**
- [x] Draft language for Documentation Site
- [x] Internal review (one person from IA, Dev, Design)
- [x] Make changes accordingly
- [x] Create markdown
- [x] Initiate change request to add to documentation site

**Comment by adrianacastaneda** [comment]
@laurelthrash @lburack Here is the [Heading page for the doc site](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Word%20Docs/[Headings.docx](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Headings.docx?d=w3fbeb515a449473eadcad879e0eceaca&csf=1&web=1&e=D94uqM)?d=w3fbeb515a449473eadcad879e0eceaca&csf=1&web=1&e=D94uqM). Let me know if you have any questions! Thanks!

**Comment by adrianacastaneda** [comment]
Most content on the page is good to go, and has passed IA / dev approval. We're missing notes under the accessibility section for this page

**Comment by adrianacastaneda** [comment]
@laurelthrash 
accessibility information has been added and [Heading page for the doc site](https://nih.sharepoint.com/:w:/s/NCI-OCPLNewCgovUXDesignSystem/ERW1vj9JpD5HrcrYeeDs6soBY8YtIs_qK-TnAT8Vo_Q7hw?e=pmLBei) is now all set!

**Comment by laurelthrash** [comment]
Changes initiated via https://github.com/NCIOCPL/ncids/pull/1476. Closing this ticket to fulfill the updates via the mentioned PR.
