### ISSUE TITLE
[R2.1 Analytics ] Group 2 - Research

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1403]
**Description:** Following our R2.1 home and landing page launch, we are capturing analytics to analyze and produce recommendations for changes/content improvements.

**Sub-tasks:**
- [x] Review R2.1 analytics data and document insights/findings in R2.1 Landing Page Analytics Notes Questions document **[Nicole - Deadline 12/1/23]**
- [x] Finalize detailed findings and recommendations for Research **[Deadline 1/2/24]**
- [x] Finalize detailed findings and recommendations for Grants & Training **[Deadline 1/2/24]**
- [x] Finalize detailed findings and recommendations for About NCI **[Deadline 1/2/24]**
- [x] Internal alignment/refinement for all three pages **[Deadline 1/17/24]**
- [x] Share detailed findings with Anna **[During 02/06 PM/PO meeting]**
- [x] Draft pre-meeting summary email (Adriana) **Week of 02/05/24**
- [x] Send pre-meeting summary email (Laurel) **Week of 02/12/24**
- [x] Meet with content stakeholders to share recommendations **02/21/24**
- [x] Obtain feedback from stakeholders
- [x] Implement content changes **[Deadline TBD]**
- [x] Ensure potential development enhancements are captured **[N/A]**

**Resources**
- [Timeline](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Measurement%20%26%20Evaluation/R2.1%20Analytics%20Recommendations.xlsx?d=we6579666a99647d3b0df88cd7e386601&csf=1&web=1&e=75jbRt)
- [Dashboards linked in this Word doc](https://gcc02.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fnih.sharepoint.com%2F%3Aw%3A%2Fs%2FNCI-OCPLNewCgovUXDesignSystem%2FEU9yf71c6mpGu03Rtj7YZDsBcvf7jsb5IifO-bnvIZI__Q%3Fe%3D5ASm0D&data=05%7C01%7Clindsay.burack%40nih.gov%7C648870726b2841e823db08dbc90b93e8%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638324823781937114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XsvqA6ckLgcRFPyxnCffoT9ud4DN%2F3kTKm%2BEilJHIwI%3D&reserved=0)

**Comment by laurelthrash** [comment]
SU: analytics for these three pages are in. Awaiting blurbs by @adrianacastaneda @lburack that describe recommendations and and analysis

**Comment by laurelthrash** [comment]
Research landing page published 02/26/24 with analytics updates. Closing this ticket.
