### ISSUE TITLE
Create NCIDS Summary Box and Summary Box Row Content for Documentation Site

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1410]
This task is to track the development of the content to be added to the NCIDS Documentation Site regarding the NCIDS Summary Box, which is in development.

**Parent Issue:** #1398 

### Sub-Tasks
- [x] Draft content for the NCIDS Summary Box page on the NCIDS Documentation Site
- [x] Review the drafted content (Need 1 individual from IA, Development, and Design)
- [x] Revise drafted content from the reviews
- [ ] Develop markdown of the drafted content
- [ ] Update the NCIDS Documentation Site using the Editing the NCIDS Documentation Site Content Procedure

**Comment by adrianacastaneda** [comment]
@laurelthrash please see [summary box doc here](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Summary%20Box.docx?d=w71c03bd31d50414b9bbc7ca76e88b5de&csf=1&web=1&e=rfDOsC) for review! thanks!

**Comment by laurelthrash** [comment]
In review via Slack along with scenarios and ACs for the NCIDS build ticket (#1398).

**Comment by laurelthrash** [comment]
Review of content for Doc Site is complete. This is ready for markdown to be created. The Doc Site page will be created as part of the development process so the information cannot yet be added to the Doc Site.

**Comment by laurelthrash** [comment]
Markdown and creation of these pages shifting to development board. Closing this ticket on design board.
