### ISSUE TITLE
CCG R2 Homepage Content Go-Live

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1433]
> Related to: #744

**Description:** This ticket represents content go-live steps for the CCG home page content launch. [Full calendar and checklist found here](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B6976516D-4D80-48CB-9F83-258530F202B8%7D&file=R2.1%20Landing%20Page%20Update%20Schedule.xlsx&action=default&mobileredirect=true).

**Sub-tasks:**
- [x] Purchase stock photos / approve alt text (In progress via Jira)
- [x] Add stock photos to Drupal
- [x] Obtain desired content for "News and Events" row
    - [x] Add to content template
- [x] Send go-live communications
- [x] Finalize content template (In progress) 
- [x] Build page (12/18)
- [x] Review page (12/19)
- [x] Launch content (12/20)
- [ ] Send post-launch communications (12/20)

**Comment by laurelthrash** [comment]
Page implemented on 12/20. Closing this ticket!
