### ISSUE TITLE
Update Design Assets - Icons for Use in Presentations (thumbnail only)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1452]
META: #969

**Description:** 
- Details: Need to update existing design assets to align with the updated color palette/style. Assets should also be verified to meet 508 compliance standards. 
- Assets that need to be updated are found here on MyNCI: https://mynci.cancer.gov/topics/nci-branding-logo-use-templates#Templates. 

**Sub-tasks:**
- [x] Update design asset(s)
    - [x] Align with updated color palette/style
    - [x] Verify 508 compliance 
- [x] Internal review/alignment/updates
- [x] ODDC review/alignment/updates
- [x] Finalize asset(s)
- [x] Save to appropriate local folder
- [x] Determine if asset(s) need to be saved or updated in secondary location
- [x] Create Jira ticket to update existing templates on MyNCI

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - here is the updated icon image for when you return. Please let me know if you have any questions (but only when you get back! :D) thanks much. 
![icons](https://github.com/NCIOCPL/ncids/assets/102183929/ca2b0d4b-2918-4411-a84b-5a4c0042f0fc)

**Comment by laurelthrash** [comment]
Hi, @dcvijanovic1k! To confirm, is the existing PPT on MyNCI ([downloadable here](https://mynci.cancer.gov/topics/nci-icons-use-presentations)) already aligned with the updated color palette/style and just the preview image needs to be updated? Want to confirm I am tracking.

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - yes, you are absolutely correct. The currently hosted PPT is updated and good to go, we simply need to update the preview image to match.

**Comment by laurelthrash** [comment]
Awesome! @a-heirtzler - mind please giving a thumbs up to the preview image copied above? Once confirmed, I can move this to Jira to request an update for the preview image currently found on MyNCI. Cc: @dcvijanovic1k

**Comment by laurelthrash** [comment]
Received approval from Anna/Alex via Teams on 01/30/24. Will proceed with updating the screenshot on MyNCI.

**Comment by laurelthrash** [comment]
Request to update MyNCI in progress via CGOV-20493. Cc: @dcvijanovic1k

**Comment by laurelthrash** [comment]
Thumbnail image updated on MyNCI. Closing this ticket. Cc: @dcvijanovic1k
