### ISSUE TITLE
Update Design Assets - Scientific Posters

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1453]
META: #969

**Description:** 
- Details: Need to update existing design assets to align with the updated color palette/style. Assets should also be verified to meet 508 compliance standards. 
- Assets that need to be updated are found here on MyNCI: https://mynci.cancer.gov/topics/nci-branding-logo-use-templates#Templates. 
- NOTE: First confirm with Anna on sizing needed

**Sub-tasks:**
- [ ] Confirm with Anna on sizing needed
- [ ] Update design asset(s)
    - [ ] Align with updated color palette/style
    - [ ] Verify 508 compliance 
- [ ] Internal review/alignment/updates
- [ ] ODDC review/alignment/updates
- [ ] Finalize asset(s)
- [ ] Save to appropriate local folder
- [ ] Determine if asset(s) need to be saved or updated in secondary location
- [ ] Create Jira ticket to update existing templates on MyNCI

**Comment by laurelthrash** [comment]
**Note:** Please connect with Anna on the scope of additional layout changes (not yet defined) before proceeding with this ticket. 

**Context:** There is a request to change the layout of the scientific templaes. Since this ticket exists to update the branding for the templates, Anna would like to incorporate layout changes at the same time. The layout updates are not fully defined so a conversation needs to take place with Anna to establish this. 

To: @andyvanavery31 @sarinapadilla Cc: @meglake

**Comment by laurelthrash** [comment]
Determined that this ticket and all remaining tickets within the META will transition to Jira to be addressed as part of O&M. Please reference https://tracker.nci.nih.gov/browse/CGOV-21791 for next steps on this ticket. Closing this ticket and the associated META to clear from the Redesign backlog.
