### ISSUE TITLE
Update Design Assets - Background for Virtual Meetings

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1454]
META: #969

**Description:** 
- Details: Need to update existing design assets to align with the updated color palette/style. Assets should also be verified to meet 508 compliance standards. 
- Assets that need to be updated are found here on MyNCI: https://mynci.cancer.gov/topics/nci-branding-logo-use-templates#Templates. 

**Sub-tasks:**
- [x] Update design asset(s)
    - [x] Align with updated color palette/style
    - [x] Verify 508 compliance 
- [x] Internal review/alignment/updates
- [x] ODDC review/alignment/updates
- [x] Finalize asset(s)
- [x] Save to appropriate local folder
- [x] Determine if asset(s) need to be saved or updated in secondary location [N/A]
- [x] Create Jira ticket to update existing templates on MyNCI

**Comment by dcvijanovic1k** [comment]
[Here is a Mural with the old and new versions of the virtual background](https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1703615752169/510e4c36cda1977440c2ecee01ac397ab3fc389e?sender=ubcb8ca32cd83c9d3c7029304), to be reviewed internally as a next step.

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - these have been reviewed internally with Aaron and ready for client review/discussion; link above in previous comment.

**Comment by laurelthrash** [comment]
Add mirrored options for single logo and teal. From there, no other changes and received approval from Anna/Alex via Teams on 01/30/24. We will proceed with adding the two additional backgrounds and replacing the existing options on MyNCI. 

Alex to review the directions for customizing your background via the three options. Alex to add this via the same Jira ticket.

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - all the updated versions mentioned in your comment are attached. Please let me know if you need anything else. Thanks! 
![01 - Dark Blue_V2](https://github.com/NCIOCPL/ncids/assets/102183929/94ac9ab0-8d21-4b40-81ab-045df03f13b1)
![02 - Dark Blue Mirrored_V2](https://github.com/NCIOCPL/ncids/assets/102183929/96e04dc1-5963-4509-9716-b2e334dc3399)
![03 - Dark Blue Single_V2](https://github.com/NCIOCPL/ncids/assets/102183929/43586835-ea26-413f-9024-9c87af0cc6bd)
![04 - Dark Blue Single Mirrored_V2](https://github.com/NCIOCPL/ncids/assets/102183929/7145f22a-b49a-4470-aef3-473153d09027)
![05 - Teal_V2](https://github.com/NCIOCPL/ncids/assets/102183929/7b6b4f5e-65c7-428f-a9db-9e603fcdf625)
![06 - Teal Mirrored_V2](https://github.com/NCIOCPL/ncids/assets/102183929/f3e0de56-b511-47b8-9d4e-fb94f91a8890)
![07 - Gray_V2](https://github.com/NCIOCPL/ncids/assets/102183929/95fcd644-3e7e-40e9-ad4b-8a2f534bfe28)
![08 - Gray Mirrored_V2](https://github.com/NCIOCPL/ncids/assets/102183929/566300f5-49c9-4b30-8806-117e8401a3f5)

**Comment by laurelthrash** [comment]
Virtual backgrounds complete. Fulfilling the request to upload this to MyNCI via CGOV-20487.

**Comment by laurelthrash** [comment]
Virtual backgrounds added to MyNCI via CGOV-20487. Closing this ticket.
