### ISSUE TITLE
Update Design Assets - Mass Email Banners

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1455]
META: #969

**Description:** 
- Details: Need to update existing design assets to align with the updated color palette/style. Assets should also be verified to meet 508 compliance standards. 
- Assets that need to be updated are found here on MyNCI: https://mynci.cancer.gov/topics/nci-branding-logo-use-templates#Templates. 

**Sub-tasks:**
- [x] Update design asset(s)
    - [x] Align with updated color palette/style
    - [x] Verify 508 compliance 
- [x] Internal review/alignment/updates
- [x] ODDC review/alignment/updates
- [x] Finalize asset(s)
- [x] Save to appropriate local folder
- [x] Determine if asset(s) need to be saved or updated in secondary location
- [ ] Create Jira ticket to update existing templates on MyNCI

**Comment by dcvijanovic1k** [comment]
I believe this should be closed out, per this ticket: https://github.com/NCIOCPL/ncids/issues/876#issuecomment-1549746429

@laurelthrash, when you return, please let me know. Thanks!

**Comment by laurelthrash** [comment]
@dcvijanovic1k I agree that #876 covers this ticket and no additional work on the email banners is required. However, will you please clarify what you mean by the URL uses the old font? I am not tracking on this - thank you!

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - sure, sorry I didn't clarify. The text on the right-hand side of the banner (www.cancer.gov) uses an old font (Montserrat) that is no longer used in our current group of redesign fonts. So I was hoping to take this as an opportunity to update that text to Open Sans. Please let me know if we need to talk through it some more!

**Comment by laurelthrash** [comment]
@dcvijanovic1k - got it! Thanks for clarifying. This makes sense. Please proceed with updating the www.cancer.gov found on the banners to replace the existing Montserrat font with Open Sans. We can then coordinate update on MyNCI as well as within GovDelivery.

**Comment by dcvijanovic1k** [comment]
Great, thank you @laurelthrash - updated versions are attached. I'll review these with Aaron tomorrow along with the other files we had previously discussed. 
![Cerulean_V2](https://github.com/NCIOCPL/ncids/assets/102183929/aeff1a8f-1025-4543-9c5d-fee10f615c9a)
![Cool Gray_V2](https://github.com/NCIOCPL/ncids/assets/102183929/bff71f46-cb59-4f54-bad2-9c3f9f845229)
![Cranberry_V2](https://github.com/NCIOCPL/ncids/assets/102183929/0e2e1d19-5294-4f81-9127-64ff52ca5403)
![Dark Teal_V2](https://github.com/NCIOCPL/ncids/assets/102183929/69be46c6-765d-4e07-b36e-b590c93df9fe)
![Navy_V2](https://github.com/NCIOCPL/ncids/assets/102183929/67b86dc3-2714-4d04-87a9-cfe5efa5d773)
![Slate_V2](https://github.com/NCIOCPL/ncids/assets/102183929/6a3c600e-2833-4a36-a32a-5b11f2c7b90a)
![White_V2](https://github.com/NCIOCPL/ncids/assets/102183929/8ff87fd8-8f96-4a26-a9e2-104814904b3b)

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - above banners have been reviewed/approved by Aaron and are ready for external review.

**Comment by laurelthrash** [comment]
Notes from call with Anna/Alex on 01/30/24.

- Only change to the banner from the previously approved versions are the fonts. 
- Curious about why it is "www.cancer.gov" vs. "Cancer.gov"
- Three different groups require updates: 350 banners in GovDelivery, about 1/3 would be a 1:1 swap, about 1/3 are the DOC sites, and 1/3 we would need to ask Granicus - about 8-10 hours each
    - Move forward with the swap but treat as something that could happen in spare time - Anna clear this with Sabrina

Actions from the call:

- Determine if we want to change "www.cancer.gov" to "cancer.gov" (and make slightly bigger)
- Anna clear with Sabrina that comfortable with manual effort to update

**Comment by dcvijanovic1k** [comment]
Updated banners attached with approval from Alex/Anna in Teams. cc @laurelthrash 
![Cerulean_V3](https://github.com/NCIOCPL/ncids/assets/102183929/ac9cf7bd-f6e4-4b1c-af85-59fc18c2fe2a)
![Cool Gray_V3](https://github.com/NCIOCPL/ncids/assets/102183929/c459571a-8736-474b-a4b5-f752701b9d07)
![Cranberry_V3](https://github.com/NCIOCPL/ncids/assets/102183929/6c1c46c6-1a7f-479d-b72d-a610c3fc5b71)
![Dark Teal_V3](https://github.com/NCIOCPL/ncids/assets/102183929/cf2fed86-f0b2-498d-bfe8-9c2ea9882046)
![Navy_V3](https://github.com/NCIOCPL/ncids/assets/102183929/97c2625c-8c71-45c2-80e0-ba6013f62f93)
![Slate_V3](https://github.com/NCIOCPL/ncids/assets/102183929/6adec27c-821a-48f4-856e-4e81069b450c)
![White_V3](https://github.com/NCIOCPL/ncids/assets/102183929/6480925b-70d8-450d-b5fd-6d0283fae442)

**Comment by laurelthrash** [comment]
Awesome, received, @dcvijanovic1k ! Awaiting confirmation from Anna to proceed with updating effort.

**Comment by laurelthrash** [comment]
Determined with Anna that we will proceed with updating the banners listed on myNCI https://mynci.cancer.gov/topics/powerpoint-templates-scientific-posters-and-other-downloadable-templates#email%20banners and check in again in 6 months to reconsider prioritizing the work for the template updates.
