### ISSUE TITLE
Update Design Assets - Letterhead and General Use Documents

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1456]
META: #969

**Description:** 
- Details: Need to update existing design assets to align with the updated color palette/style. Assets should also be verified to meet 508 compliance standards. 
- Assets that need to be updated are found here on MyNCI: https://mynci.cancer.gov/topics/nci-branding-logo-use-templates#Templates. 

**Sub-tasks:**
- [x] Update design asset(s)
    - [x] Align with updated color palette/style
    - [x] Verify 508 compliance 
- [x] Internal review/alignment/updates
- [x] ODDC review/alignment/updates
- [x] Finalize asset(s)
- [x] Save to appropriate local folder
- [x] Determine if asset(s) need to be saved or updated in secondary location
- [x] Create Jira ticket to update existing templates on MyNCI

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - here are updated versions of these documents for internal review. 
[_1456-Letterhead-General-Use-Docs_Black_V1.docx](https://github.com/NCIOCPL/ncids/files/13773387/_1456-Letterhead-General-Use-Docs_Black_V1.docx)
[_1456-Letterhead-General-Use-Docs_Black-PDF_V1.pdf](https://github.com/NCIOCPL/ncids/files/13773388/_1456-Letterhead-General-Use-Docs_Black-PDF_V1.pdf)
[_1456-Letterhead-General-Use-Docs_Color_V1.docx](https://github.com/NCIOCPL/ncids/files/13773389/_1456-Letterhead-General-Use-Docs_Color_V1.docx)
[_1456-Letterhead-General-Use-Docs_Color-PDF_V1.pdf](https://github.com/NCIOCPL/ncids/files/13773390/_1456-Letterhead-General-Use-Docs_Color-PDF_V1.pdf)

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - above documents have been reviewed internally and are ready for external review.

**Comment by laurelthrash** [comment]
Approved via email by Anna and Alex. Request to replace the current documents on MyNCI fulfilled via CGOV-20445.

**Comment by laurelthrash** [comment]
Update complete via CGOV-20445 and replaced on MyNCI. Closing this ticket.
