### ISSUE TITLE
Update Design Assets - Digital Signs

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1457]
META: #969

**Description:** 
- Details: Need to update existing design assets to align with the updated color palette/style. Assets should also be verified to meet 508 compliance standards. 
- Assets that need to be updated are found here on MyNCI: https://mynci.cancer.gov/topics/nci-branding-logo-use-templates#Templates. 

**Sub-tasks:**
- [x] Update design asset(s)
    - [x] Align with updated color palette/style
    - [ ] Verify 508 compliance 
- [ ] Internal review/alignment/updates
- [ ] ODDC review/alignment/updates
- [ ] Finalize asset(s)
- [ ] Save to appropriate local folder
- [ ] Determine if asset(s) need to be saved or updated in secondary location
- [ ] Create Jira ticket to update existing templates on MyNCI

**Comment by dcvijanovic1k** [comment]
HI @laurelthrash - here is the updated digital sign file. I'd like to do a review with Anna/Alex first, before doing the final 508 remediation, so we aren't duplicating work. Please let me know if you have any concerns. Thanks! 
[_1457-Digital-Signs_V1a.pptx](https://github.com/NCIOCPL/ncids/files/13862020/_1457-Digital-Signs_V1a.pptx)

**Comment by laurelthrash** [comment]
Determined that this ticket and all remaining tickets within the META will transition to Jira to be addressed as part of O&M. Please reference https://tracker.nci.nih.gov/browse/CGOV-21790 for next steps on this ticket. Closing this ticket and the associated META to clear from the Redesign backlog.
