### ISSUE TITLE
[R2.2] MyPART Spanish Homepage Updates

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1469]
**Description:** On 1/4/24, MyPART requested several changes to the MyPART homepage ahead of our R2 content launch. These are:
- Use the same photo from English for the "Participate in our trial" feature card.
- Use the attached photo for the right "Colabore con nosostros" feature card. 
- Change final feature card row to a single promo block for the nirogacestat article. 

**Sub-tasks:**
- [x] Update comp (Dragutin)
- [x] Update image inventory (Dragutin)
- [x] Update content template (Adriana)
- [x] Revise stock image request to reflect new alt text for images (Laurel)

![Image](https://github.com/NCIOCPL/ncids/assets/102998716/97f1ad0c-8f3a-44af-b0e5-8ec34fb83329)

**Comment by laurelthrash** [comment]
Will follow the alt text Jira ticket. All other adjustments made. Closing out this ticket.
