### ISSUE TITLE
Correcting Color Tokens on Figma and DS

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1473]
### Issue description
There are inconsistencies with the color tokens on the Figma and on the DS. This ticket is to resolve those conflicts and ensure that the colors used pass accessibility requirements.

### What's the expected change?
- All colors used on Figma and on the NCIDS will be consistent and will pass accessibility requirements (contrast checking)

### What's the current functionality?
- Colors on Figma and the NCIDS are inconsistent

### Additional Notes
- [Color Token Inventory](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B35CA3A39-9929-438B-98C4-80F04B66EB2E%7D&file=Color%20Tokens%20Inventory.docx&action=default&mobileredirect=true)

**Comment by blilianyu** [comment]
**Figma Updates** 
- [ ] Update `State Tokens` in Figma to match DS (see [inventory](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B35CA3A39-9929-438B-98C4-80F04B66EB2E%7D&file=Color%20Tokens%20Inventory.docx&action=default&mobileredirect=true))
- [ ] Update `golden-5` to `#FDF2BF`
- [ ] Update `teal-40` to `#3C989E`
- [ ] Update `secondary` to `teal-50`
- [ ] Update `secondary-dark` to `teal-70`
- [ ] Update `secondary-darker` to `teal-80`

 
 **DS Site Updates**
- [ ] Update State Tokens `emergency` from `cranberry-60v` to `cranberry-60`
- [ ] Update Theme Tokens
  - [ ] `base-darkest` from `gray-cool-90` to `gray-90`
  - [ ] `primary-dark` hex from `#004e7a` to `#004971`
  - [ ] `primary-darker` hex from `#003a57` to `#00314b` 
- [ ] Update `cerulean-70` hex from `#004e7a` to `#004971`
- [ ] Update `cerulean-80` hex from `#003a57` to `#00314b`
- [ ] Update `cranberry-10v` hex from `#fde2ea` to `#ffdbe7`
- [ ] Update `teal-40` hex from `#298085` to `#3c989e`


**Outstanding item** 
- Do we make a DS change to update `primary-vivid` to `cerulean-60v`?

**Comment by blilianyu** [comment]
All updates have been made in Figma

**Comment by bryanpizzillo** [comment]
@blilianyu The DS Site Updates list seems to be mixing up change requests for colors in the code and places on the documentation site where it does not match the code. Can you please separate them? 

For example the the emergency token IS `cranberry-60v` in the [code](https://github.com/NCIOCPL/ncids/blob/develop/packages/ncids-css/patches/%40uswds%2Buswds%2B3.3.0.patch#L741). So this is not just updating documentation, you are asking for a change.

**Comment by laurelthrash** [comment]
Seeking confirmation from @blilianyu regarding what is needed to address the comment above and move this ticket forward.

**Comment by blilianyu** [comment]
This is done on design side. Changes were pushed on 01/22/24 to community file (Version 1.1.1 patch)

**Comment by laurelthrash** [comment]
Remaining changes are updates to the markdown on the Documentation Site. @blilianyu to pick this up and follow the guidance for updates to the Doc Site.

**Comment by blilianyu** [comment]
Remaining changes will be handled in #1531 & #1532
