### ISSUE TITLE
[R2 Analytics] Verify Post Launch Analytics Accumulation (MyPART)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1485]
**Description:** Initiated post-launch dashboards for MyPART. Need to check-in to determine if enough data has accumulated to initiate analysis of the home and landing pages.

**NOTE:** MyPART includes the English and Spanish homepage.

**Sub-tasks:**
- [x] Verify data accumulation via significance calculator spreadsheet
- [x] Prep analytics [Nicole] 
- [x] Review analytics and prep recommendations based on review [Adriana] [Week of 05/13]
- [x] Align internally on recommendations [Tues. 05/21]
- [x] Align with ODDC on recommendations (email) 
- [x] Send information to DOC (email)

**Comment by laurelthrash** [comment]
Send analysis (no recommended changes to the homepage, EN or SP, at this time) to MyPART via email on 05/28. Closing this ticket.
