### ISSUE TITLE
[R2.1 Analytics] Spanish CGov Pages

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1487]
**Description:** Following our R2.1 home and landing page launch, we are capturing analytics to analyze and produce recommendations for changes/content improvements. This ticket includes all CGov R2.1 Spanish pages:
- Homepage
- About Cancer
- Research 
- Grants & Training
- About NCI
- News & Events (added to this batch 07/08)

**Sub-tasks:**
- [x] See how the updated Research page performs (English) as it is the final CGov English page we are tracking performance (#1753)
- [x] Review data prepared for Spanish CGov pages and validate that our plan to update Spanish to mirror English still makes sense
- [x] Prep a summary of proposed changes to all Spanish Cgov pages that mirror English
- [x] Consult Anna on how best to route these changes to the landing pages team/Carolina

**Resources**
- [Timeline](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Measurement%20%26%20Evaluation/R2.1%20Analytics%20Recommendations.xlsx?d=we6579666a99647d3b0df88cd7e386601&csf=1&web=1&e=75jbRt)
- [Dashboards linked in this Word doc](https://gcc02.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fnih.sharepoint.com%2F%3Aw%3A%2Fs%2FNCI-OCPLNewCgovUXDesignSystem%2FEU9yf71c6mpGu03Rtj7YZDsBcvf7jsb5IifO-bnvIZI__Q%3Fe%3D5ASm0D&data=05%7C01%7Clindsay.burack%40nih.gov%7C648870726b2841e823db08dbc90b93e8%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638324823781937114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XsvqA6ckLgcRFPyxnCffoT9ud4DN%2F3kTKm%2BEilJHIwI%3D&reserved=0)

**Comment by laurelthrash** [comment]
Determined that Cgov Spanish pages largely mirror the findings for English (#1403 & #1487). Our plan is to implement changes for the English pages, test performance, and then make these same updates made to English to the Spanish pages. Adding this ticket back into the backlog for the time being so we revisit the Spanish pages at a future date. Cc: @adrianacastaneda @lburack @nicolecrom @welshja

**Comment by laurelthrash** [comment]
Update: Team is seeing how changes to English pages are performing, and making subsequent recommendations for page updates, if applicable. Next steps for the corresponding Spanish pages are: 

1. See how the updated Research page performs (English) as it is the final CGov English page we are tracking performance
    > Create recommendations, if applicable
2. Prep a summary of proposed changes to all Spanish Cgov pages that mirror English
3. Consult Anna on how best to route these changes to the landing pages team/Carolina

**Comment by laurelthrash** [comment]
Second round of recommendations for Research (English) page is complete. This unblocked the CGov Spanish pages. Determined 07/08 that we will add News & Events (Spanish) to the initial list of recommendations as part of this ticket.

**Comment by bennettcc** [comment]
Content sent to Carolina and OCC team - closing ticket
