### ISSUE TITLE
[R2.1 Analytics ] DCEG Analysis and Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1496]
**Description:** Following our R2.1 home and landing page launch, we are capturing analytics to analyze and produce recommendations for changes/content improvements.

**Sub-tasks:**
- [x] Prep analytics [Nicole] [Confirm on 04/08]
- [x] Review analytics and prep recommendations based on review [Michael] [04/09 - 04/17]
- [x] Align internally on recommendations [Thurs. 04/18 - UX meeting]
- [x] Align with ODDC on recommendations [Week of 04/22]
- [x] Present information to DCEG [Week of 04/29]

**Comment by laurelthrash** [comment]
Discussed during SU: Wish to provide a bulleted summary of current findings/blockers and an ETA of when full analytics will be complete.

**Comment by laurelthrash** [comment]
Moving to the backlog until we are prepared to revisit the analytics data.

**Comment by laurelthrash** [comment]
Determined during UX meeting 04/18 that we will proceed with an email approach for sharing findings/recommendations with ODDC and DCEG.

**Comment by laurelthrash** [comment]
Sent summary and recommendations to DCEG on 05/09. Closing this ticket.
