### ISSUE TITLE
[R3 Discovery] Current State Analysis and Competitor Landscape Review

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1500]
**Description:** We need to better understand how mini landing pages are currently being used by content stakeholders (across Cgov and platform microsites) as well as site visitors using these pages, and pain points for both stakeholders and audiences. This discovery work will analyze and classify mini landing pages across the platform, look to performance metrics from the analytics team, and work with audience researchers to interview stakeholders and users of these pages.

**Subtasks:**

- [x] Mini landing page report ([CGOV-20319](https://tracker.nci.nih.gov/browse/CGOV-20319))
- [x] Analyze and classify mini landing pages
   - [x] Cgov
   - [x] Microsites (list out each one or create groups?)
- [x] Final analysis [end of week 02/16]
- [x] Discuss internally 02/27
- [x] Landscape review to see how other sites handle hubs of content/MLPs
    - [x] 03/12 - compile ideas based on analysis (Adriana/Lindsay/Liz) 
    - [x] 03/14 - gather pain points from Anna (Laurel/Lindsay) 
    - [x] 03/18 - complete competitor analysis (All) 
    - [ ] 03/19 - share out during Tues. UX meeting (All) 
    - [x] 03/25 - share out with federal team

Resources:
- Analytics data (https://tracker.nci.nih.gov/browse/CGOV-20444)
- ["Next Steps" outline document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Measurement%20%26%20Evaluation/R2.1%20Analytics%20-%20Next%20Steps.docx?d=wa490b36a1b31425abc31d155a738eb26&csf=1&web=1&e=Ohkett)

**Comment by laurelthrash** [comment]
Shared out with federal team on 04/01. On deck to share high level findings during end of sprint on 04/02. Closing this ticket.
