### ISSUE TITLE
[R2.1 Analytics ] Group 3 - Grants & Training

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1511]
**Description:** Following our R2.1 home and landing page launch, we are capturing analytics to analyze and produce recommendations for changes/content improvements.

**Sub-tasks:**
- [x] Review R2.1 analytics data and document insights/findings in R2.1 Landing Page Analytics Notes Questions document **[Nicole - Deadline 12/1/23]**
- [x] Finalize detailed findings and recommendations for Research **[Deadline 1/2/24]**
- [x] Finalize detailed findings and recommendations for Grants & Training **[Deadline 1/2/24]**
- [x] Finalize detailed findings and recommendations for About NCI **[Deadline 1/2/24]**
- [x] Internal alignment/refinement for all three pages **[Deadline 1/17/24]**
- [x] Share detailed findings with Anna **[During 02/06 PM/PO meeting]**
- [x] Draft pre-meeting summary email (Adriana) **Week of 02/05/24**
- [x] Send pre-meeting summary email (Laurel) **Week of 02/12/24**
- [x] Meet with content stakeholders to share recommendations **02/20/24**
- [x] Obtain feedback from stakeholders
- [x] Implement content changes **[Deadline TBD]**
- [x] Ensure potential development enhancements are captured **[Deadline TBD]**

**Comment by laurelthrash** [comment]
Updated Grants & Training page published in production on 02/23/24. Small updates made on 02/26/24. Closing this ticket as complete.
