### ISSUE TITLE
NCIDS Documentation Site Update Footer Guidance Regarding Design Elements

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1534]
### Sub-tasks
- [x] Update language
- [x] Review and approve language 
- [ ] Update CGOV-19739 so that it’s added to the Digital Reference Guide Content too
- [ ] Create markdown
- [ ] Create PR to update Doc Site

### Change Request
Update the Footer guidance on the Documentation Site (https://designsystem-dev.cancer.gov/develop/components/footer) recommending against or prohibiting use of design elements in the site footer. An example of this from CCDI is below. 

This request was made by Anna to Laurel/Cameron via email in February 2024.

### What's the expected change?
- Footer guidance includes mention regarding the use of design elements in the site footer. Anna suggests we should recommend against or prohibit the use of design elements in the site footer due to the potential for inconsistency. 

### What's the current functionality?
- The Footer guidance currently does not mention design elements in the site footer.

![Image](https://github.com/NCIOCPL/ncids/assets/102998716/608d99fd-335c-4c46-ae08-dc30b453e8e9)

**Comment by laurelthrash** [comment]
This ticket is awaiting completion of CGOV-20034. Then, CGOV-19739 and this ticket should be completed simultaneously.

**Comment by adrianacastaneda** [comment]
Updated addressed in Footer doc: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Footer.docx?d=w75370034a6db4bb9b33d8121f7057e96&csf=1&web=1&e=sldwpg

cc: @andyvanavery31

**Comment by andyvanavery31** [comment]
Complete.
