### ISSUE TITLE
Add Maturity Model Content to the Documentation Site

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1538]
Following discussion with Anna on 2/20:

Update the documentation site to include information about the NCIDS Maturity Model. We'll need to determine where the language is displayed on the doc site and finalize that language (before it can be added to the site).

Maturity model content attached here: [NCIDS Adoption and Evaluation.docx](https://github.com/NCIOCPL/ncids/files/15471775/NCIDS.Adoption.and.Evaluation.docx)

Maturity Model Content: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Pilot_Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/NCIDS%20Adoption%20and%20Evaluation.docx?d=w9ebb493eb870463782cf0e92612e72a0&csf=1&web=1&e=7qrcb2

Should be created as a new page under the 'Get Started' section: https://designsystem-dev.cancer.gov/develop/get-started/

Additionally, it should be listed as the fourth header under 'Figma Guides' on the Get Started Page. 
**Header:** NCIDS Maturity Model: Adoption and Evaluation  
**Description:** Use the NCIDS maturity model to adopt the design system in a way that grows with your team.

**Tasks**
 

- [x] Determine page location for maturity model content (will it be added to an existing page or created on a new page)
- [x] Create content in the shared word doc:
- [x]  Review content in shared document (Share with Anna too)
- [ ]  Add to documentation site

**Comment by laurelthrash** [comment]
Closing from the design board as work for this is complete. Implementation with the development team/board.

**Comment by bennettcc** [comment]
Moving to on hold - content is in flux with Anna
