### ISSUE TITLE
Epic: Strategy for Home and Landing Pages

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#156]
# Discuss and refine the strategy for home and landing pages

- including what our overall goal is for these pages
- what testing we may need to do ahead of the next PI starting in 6 weeks

*Description of what is to be accomplished.*
*Examples:*
* *Initial Setup of Dev Tier*
* *Create Application Framework*
* *Define Unit Test Approach*
* *Research UX Patterns for Search*

> **ESTIMATE** TBD

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* References: *URL to web site with examples*
* Web Page: *Here goes a URL to an existing web page*

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Landscape review [SP: 5] #175 
- [ ] Determine baseline user research for home and landing pages [SP: 3] #176
- [ ] Execute baseline user research for home and landing pages [SP: 5] #177

* Include mobile & desktop

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by anthonycuellar** [comment]
This should be an Epic

**Comment by VictoriaSunNIH** [comment]
Closing this out - I have broken out tasks into their 3 separate tickets.
