### ISSUE TITLE
R2.4 Comps - Refresh English and Create Spanish

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1613]
**Description:** We are preparing for our upcoming content launch using R2.4 components. This ticket is to refresh the English comp and create the Spanish comp. 

**Sub-tasks:**
- [x] Refresh English comp
    - [x] Obtain input from IA regarding confirmation for call out box content
    - [x] Approve internally
    - [x] Approve with federal team [slated for 04/02]
- [x] Create Spanish comp
    - [x] Obtain translations from CGOV-20845
        - No results found = No hay resultados
    - [x] Approve internally
    - [x] Approve with federal team [slated for 04/03]

Full timeline [found here](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.4/Project%20Management/DRAFT_R2.4%20Sprint%20Timeline.xlsx?d=w5529645607454cb6ae6ac3018e1d7b95&csf=1&web=1&e=Zh4lie&nav=MTVfe0RGNjE5MTkxLTcyNzktNEVBMy05OTgyLUM1QzE2ODUzNkRDOX0).

**Comment by blilianyu** [comment]
Here are the updated comps for review.

- English - minor updates to combo box widths to use utility width classes and on Mobile 320 stacking because of Spanish
  - https://www.figma.com/file/ZIgPLcQOlHYrbUxeWYaanZ/Cancer-Types?type=design&node-id=0%3A1&mode=design&t=rhf2JlDC3ytWyOLC-1
- Spanish - Carolina seemed to have a question about 'Ongoing Diagnosis' on JIRA ticket
 - https://www.figma.com/file/ZIgPLcQOlHYrbUxeWYaanZ/Cancer-Types?type=design&node-id=1729%3A7250&mode=design&t=rhf2JlDC3ytWyOLC-1

cc: @laurelthrash @adrianacastaneda @lburack

**Comment by laurelthrash** [comment]
Week of 03/25:
- [ ] Verify items within call out boxes to confirm selection (English and Spanish) @adrianacastaneda 
- [ ] Verify Spanish translation @adrianacastaneda 
- [ ] Update comps accordingly @blilianyu

**Comment by laurelthrash** [comment]
Reviewed with federal team on 04/03. Made small tweaks following the update. Closing this ticket and will create a new ticket for next steps for the R2.4 content launch. Cc: @adrianacastaneda @blilianyu
