### ISSUE TITLE
Epic: Navigation Prototype Buildout 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#162]
## As a content owner, I want to build out navigation for the website using USWDS, so that I can see how our levels content would work in the USWDS provided layout for primary navigation

Notion Link: https://www.notion.so/Secondary-Navigation-Behavior-64aef479e77c4375b18e96483a1a2e7b

Things we would want to include in the prototype:

Desktop - Main Nav (bar and megamenus)

- [ ] Able to click to navigate to an L1 pages (e.g. About Cancer and Research sections or primary navigation sections)
- [ ] Click to open a primary navigation section, and then navigate to an L2 page within that section 
- [ ] Able to click to navigate to an L3
- [ ] Pull content lists for About Cancer and Research mega menus - @claireblaustein , @lburack 

Desktop - Left Nav

- [ ] Display section nav based on Drupal priority (set as section nav root) and visibility (show/hide)
- [ ] Limit ancestor and descendant display
  - [ ] All ancestors (parents and parent's siblings, grandparents and grandparent's siblings) until reaching site section root
  - [ ] Siblings of current location
  - [ ] Only immediate descendants (children) of the page you are on

Mobile Nav Hamburger (eliminating the tongue section nav)

- [ ] Click on mobile hamburger exposes content 
  - [ ]  L1 of the page (IF not already included in section nav)
  - [ ]  Section navigation following same rules as desktop
  - [ ]  Main menu button (Click displays same elements that are visible in the desktop primary menu)
- [ ] Removal of "tongue"

Content Types that should be clickable:

- [ ] Home/Landing
- [ ] Articles
- [ ] Titles for Mini Landing Pages
- [ ] Titles for Blog Series

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario: Primary Navigation on the development site
  Given User is looking at the prototype
    When  user clicks on primary navigation
  Then navigation shows 3 levels deep
    And left navigation shows 3 levels deep
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update section nav tree #165 
- [ ] Build desktop sidenav component (usa-sidenav) #168 
- [ ] Build mobile nav component (copied mostly from sidenav component) (hamburger with sidenav structure inside)
  ** note: is there a back button after clicking main menu? (go to main menu but how do we go back to section we were in?) #169 
- [ ] Build out content type templates #166
- [ ] Build megamenu #167 

### Technical Notes
- Megamenu content PLEASE!!!
-

**Comment by VictoriaSunNIH** [comment]
This was broken out into several tickets. Closing this epic.
