### ISSUE TITLE
[R2 Analytics] SBIR Landing Page Post Launch Analysis and Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1624]
**Description:** Initiated post-launch dashboards for SBIR. Need to check-in to determine if enough data has accumulated to initiate analysis of the home and landing pages.

**Sub-tasks:**
- [x] Verify data accumulation via significance calculator spreadsheet (05/22/24)
- [x] Prep analytics [Nicole] 
- [x] Review analytics and prep recommendations based on review [Adriana] [Week of XX/XX]
- [x] Align internally on recommendations [Tues. or Thurs. XX/XX OR via Slack]
- [x] Align with ODDC on recommendations (email) 
- [x] Send information to DOC (email)

**Comment by adrianacastaneda** [comment]
Tagged you in slack but adding here for reference @lburack @welshja @nicolecrom 

[SBIR – Analysis and Recommendations Email.docx](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/Measurement%20%26%20Evaluation/Communications/DOC%20Pages/SBIR%20%E2%80%93%20Analysis%20and%20Recommendations%20Email.docx?d=w3b94c41c3d4a4d2ab879647ef4bc294e&csf=1&web=1&e=BYluE4)

cc: @bennettcc
