### ISSUE TITLE
R2.4 Cancer Types Landing Page Content Launch

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1639]
> [Schedule Here](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.4/Project%20Management/DRAFT_R2.4%20Sprint%20Timeline.xlsx?d=w5529645607454cb6ae6ac3018e1d7b95&csf=1&web=1&e=2QUXRK&nav=MTVfe0RGNjE5MTkxLTcyNzktNEVBMy05OTgyLUM1QzE2ODUzNkRDOX0)

### Description
- https://www.cancer.gov/types
- https://www.cancer.gov/espanol/tipos

Team is preparing for content conversations ahead of R2.4 launch.

PAGES in ENGLISH and SPANISH: Home and landing page with both English and Spanish must launch at the same time. 

### Sub-Tasks
- [x] Determine 04/11 stakeholder meeting flow
- [x] Stakeholder review meeting 04/11
- [x] Obtain stakeholder feedback
- [x] Align on stakeholder feedback
- [x] Update comps and go-live documentation accordingly
- [x] Send stakeholder messaging
- [x] Obtain Spanish translation for "Other Cancer Topics" via [CGOV-20845](https://tracker.nci.nih.gov/browse/CGOV-20845?focusedCommentId=1342894)
- [x] Add to HTML for go-live
- [x] Build draft pages
- [x] Review draft pages
- [x] Launch content 

### Final Documentation
- Mural board for content owner feedback: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1711659482246/97a4b3c36bcb01bebce6db468c0da8495134e343?sender=uc8881d65820946a13d002641
- Comp: [Figma Link](https://www.figma.com/file/ZIgPLcQOlHYrbUxeWYaanZ/Cancer-Types?type=design&node-id=0%3A1&mode=design&t=06byRBd6cwZfllwn-1)

**Comment by laurelthrash** [comment]
Page content for English and Spanish launched on 04/25. Closing this ticket.
