### ISSUE TITLE
Story: "Basic" Megamenu Buildout (Desktop)

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#167]
## As a user, I want a megamenu, so that I may browse the top level navigation of a site to understand the content available to me.
> **ESTIMATE** TBD

Desktop - Main Nav (bar and megamenus)

- [x]  Able to click to navigate to an L1 pages (e.g. About Cancer and Research sections or primary navigation sections)
- [x]  Click to open a primary navigation section, and then navigate to an L2 page within that section
- [x]  Able to click to navigate to an L3
- [x]  Pull content lists for About Cancer and Research mega menus - @claireblaustein , @lburack
- [x] Create basic mock for visual presentation @mworrest 

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Lists of Content (Excel, PDF, Markdown) - in Box: **https://lion.box.com/s/n07oudfupakz6tcxhq6dp4senn5ks2nr**
* Mockups: https://publicis.invisionapp.com/share/NF117KVHDPGH 

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by claireblaustein** [comment]
Pulled content lists for About Cancer and Research - all file types in box. Design will mock up in the wireframes.

**Comment by mworrest** [comment]
Link to About Cancer and Research megamenu mocks are in the description: https://publicis.invisionapp.com/share/NF117KVHDPGH

**Comment by VictoriaSunNIH** [comment]
Closing this - we have multiple tickets for implementing megamenu
