### ISSUE TITLE
Hide back to top on load

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1673]
While working on #1584, we've discovered bugs with the back to top component that blocks the ability to complete the ticket.

On load, the back to top link will appear and transition away. This element should not be visible until scroll.

https://github.com/NCIOCPL/ncids/assets/85901679/e0a000b4-be99-44e0-ba56-5baf83201b44

## Tasks

- [ ] Remove back to top from html, add back to top to the DOM once the footer is initialized.
- [ ] Back to top fades in on scroll.
- [ ] The HTML is updated in the:
   - [ ] Documentation site
   - [ ] Storybook
   - [ ] Example site
- [x] A new ticket is created to update the guidance for the footer: #1674

**Comment by bryanpizzillo** [comment]
@dlescarbeau (cc @olitharp-nci ) So additional points to note:
1. We should make this somewhat backwards compatible:
    1. The return to top should be injected into the page on scroll/first show.
    2. If the `<div class="grid-container usa-footer__return-to-top">` element DOES exist, it should be removed from the DOM. 
    3. The CSS for `<div class="grid-container usa-footer__return-to-top">` should still be included. So if someone does not have JS, then, whatever, they can use return to top.
        * There should be a storybook test case for no JS, with the Back to top -- THIS IS DIFFERENT from the no-js test case. (because no-js test case should NOT have this element.
