### ISSUE TITLE
[R3 Design] Prep for Design Burst

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1676]
**Description:** Team is preparing materials ahead of the upcoming R3 Design Burst exercise. 

**Sub-tasks**
- [x] Determine MLP priorities 
    - [x] Brainstorm [04/29 - 05/01]
    - [x] Align internally [05/02]
    - [x] Gut check with formal readout [05/03]
- [x] Prep for design burst
    - [x] Send Mural board to design burst participants
    - [x] Prepare Mural board [Wed. 05/01] @adrianacastaneda @lburack @blilianyu @monika-jaeger 
    - [x] Review materials [05/01 - 05/07] **All attendees**

**Materials**
- Detailed Schedule: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Phase%202)%20Design/Design%20Phase%20Planning%20-%20Detailed.docx?d=w417b1fa14841438a809b248713dd11b0&csf=1&web=1&e=eWfwGI
- Mural board: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1714064954539/4be033cee9e335841d42efc295724de6c0571265?sender=uc8881d65820946a13d002641

**Comment by laurelthrash** [comment]
Prep for design burst on 05/08 is complete. Marking this ticket as closed.
