### ISSUE TITLE
[R3 Design] Generate List of MLPs

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1677]
**Prioritized list of MLPs found here:** https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Mini%20Landing%20Page%20Analysis/R3%20Prioritized%20MLPs.xlsx?d=w057aa59069ee46848caa1c996d6f8cfe&csf=1&web=1&e=SbwQ6v

**Description:** As part of the R3 Design Phase, we are investigating which DOC, program, and OCPL co-owned MLPs should be considered for 2024 iterations. To inform this, we want to pull together a list of:

1. DOCs within Cgov that use MLPs as their primary entry point/landing page (e.g., DCB)
2. A list of special programs (e.g., Moonshot) that use MLPs as their main landing page

Pages that should definitely be included are: 
1. [CCHE (formerly CRCHD)](https://www.cancer.gov/about-nci/organization/crchd) 
2. [DCB](https://www.cancer.gov/about-nci/organization/dcb) 
3. [RAS](https://www.cancer.gov/research/key-initiatives/ras) 
4. [Cancer Moonshoot](https://www.cancer.gov/research/key-initiatives/moonshot-cancer-initiative) 
5. [CGH](https://www.cancer.gov/about-nci/organization/cgh) 
6. [CCDI](https://www.cancer.gov/research/areas/childhood/childhood-cancer-data-initiative)

**Goal of list:** Use as an order in which we can roll out the R3 components. Thus, we create the two example pages (RAS and AI). Then, we share the example pages (RAS and AI) + documentation/training with priority group 1. Then, we iterate on the documentation/training as needed and share with priority group 2.

**Sub-tasks:**
- [x] Pull list (Adriana)
- [x] Review list internally (send around via Slack)
- [x] Verify list with Anna (05/28)

**Comment by adrianacastaneda** [comment]
@lburack @laurelthrash here's my first pass at the list of primary entry points. Let me know your thoughts! Thanks!

**DOCs:**
[CCHE (formerly CRCHD)](https://www.cancer.gov/about-nci/organization/crchd)
[DCB](https://www.cancer.gov/about-nci/organization/dcb)
[CGH](https://www.cancer.gov/about-nci/organization/cgh)
[CCDI](https://www.cancer.gov/research/areas/childhood/childhood-cancer-data-initiative)
[FNLCR](https://www.cancer.gov/research/infrastructure/fnlcr)
[CCT](https://www.cancer.gov/grants-training/training)
[CCCT](https://www.cancer.gov/about-nci/organization/ccct)
[OHAM](https://www.cancer.gov/about-nci/organization/oham)
[NCI Frederick](https://www.cancer.gov/about-nci/organization/nci-frederick)
[CRS](https://www.cancer.gov/about-nci/organization/crs)

Included these just incase but they don't get too many visits/don't have too much on them:
[OAR](https://www.cancer.gov/about-nci/organization/oar)
[OGA](https://www.cancer.gov/about-nci/organization/oga)
[OBF](https://www.cancer.gov/about-nci/organization/obf)
[OA](https://www.cancer.gov/about-nci/contracts)
[OCPL](https://www.cancer.gov/about-nci/organization/ocpl)

**Initiatives/Resources:**
[EOP](https://www.cancer.gov/grants-training/training/at-nci/eop)
[NCI Equity and Inclusion Program](https://www.cancer.gov/research/key-initiatives/nci-equity-inclusion-program)
[RAS](https://www.cancer.gov/research/key-initiatives/ras)
[Cancer Moonshoot](https://www.cancer.gov/research/key-initiatives/moonshot-cancer-initiative)
[CCDI](https://www.cancer.gov/research/areas/childhood/childhood-cancer-data-initiative)
[Cancer Grand Challenges](https://www.cancer.gov/grants-training/grants-funding/cancer-grand-challenges)
[Artificial Intelligence (AI) in Cancer Research](https://www.cancer.gov/research/resources/ai-cancer-research)
[Cryo-Electron Microscopy at the Frederick National Laboratory](https://www.cancer.gov/research/resources/cryoem)
[Biomedical Citizen Science](https://www.cancer.gov/research/resources/citizen-science)
[PDQ® Cancer Information for Health Professionals](https://www.cancer.gov/publications/pdq)

**Comment by laurelthrash** [comment]
List drafted above converted to Excel document here to proceed with review, discussion, and sign off: [Excel Document](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Mini%20Landing%20Page%20Analysis/R3%20Entry%20Point%20MLPs.xlsx?d=w057aa59069ee46848caa1c996d6f8cfe&csf=1&web=1&e=2ilPHm)

Will discuss with Anna at conclusion of end of sprint on 05/07.

**Comment by laurelthrash** [comment]
Connect with Anna/Alex on 05/07. Determined we will plan to build out two pages (tentatively: https://www.cancer.gov/research/key-initiatives/ras & https://www.cancer.gov/research/resources/ai-cancer-research) to then share with other DOCs as examples, equipping them to build out the pages themselves using guidance. 

Anna/Alex to confirm the list of priority DOC pages, for which we would first share information regarding how to update their pages.

**Comment by laurelthrash** [comment]
Will discuss list with Anna during 1:1 on 05/28. Moving to "Hold or Dependency" for time being.
