### ISSUE TITLE
[R2 Analytics] TTC Landing Page Post Launch Analysis and Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1678]
**Description:** Initiated post-launch dashboards for TTC. Need to check-in to determine if enough data has accumulated to initiate analysis of the home and landing pages.

**Sub-tasks:**
- [x] Verify data accumulation via significance calculator spreadsheet
- [x] Prep analytics [Nicole] 
- [x] Review analytics and prep recommendations based on review [Michael] [Week of 06/17]
- [x] Align internally on recommendations (email)
- [x] Align with ODDC on recommendations (email) 
- [x] Send information to DOC (email)

**Comment by laurelthrash** [comment]
Shared information with TTC via email on 07/01/24. Closing this ticket.
