### ISSUE TITLE
Story: "Basic" Desktop Left Nav (usa-sidenav) Component

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#168]
## As a user, I want a left navigation (or side navigation), so that I may further see other available content within the site structure.

> **ESTIMATE** TBD

Desktop - Left Nav

- [ ] Display section nav based on Drupal priority (set as section nav root) and visibility (show/hide)
- [ ] Limit ancestor and descendant display
  - [ ] All ancestors (parents and parent's siblings, grandparents and grandparent's siblings) until reaching site section root
  - [ ] Siblings of current location
  - [ ] Only immediate descendants (children) of the page you are on

### Acceptance Criteria

```gherkin
Scenario: User is on an L2 and lower and not a section nav root
  Given they are on a screen 1024px and larger
    And not on a section nav root
  Then the left nav appears
    And the current page is highlighted with an indicator
    And any children of the page are exposed
    And any siblings of the page are exposed
    And all ancestors (parents and parent's sibilings, grandparents and grandparent's siblings) appear until reaching site section root
    And the ancestors are highlighted
```

```gherkin
Scenario: User is on an L2 and lower that has child pages
  Given they are on a screen 1024px and larger
    And not on a section nav root
    And the page has child pages
  Then the left nav appears
    And the current page is highlighted with an indicator
    And a plus sign appears to the right of the label of the current page 
    And the whole line is clickable (label and plus sign)
    And any children of the page are exposed
```

```gherkin
Scenario: User is on a section nav root
  Given they are on a screen 1024px and larger
  Then the left nav appears
    And the current page is highlighted as the first item with an indicator
    And any children of the page are exposed
  When a child page is clicked on OR its corresponding + is clicked (the whole line is clickable - no split buttons)
  Then the page loads to that child page
    And the left nav appears
    And the current page is highlighted with an indicator
    And any children of the page are exposed
    And any siblings of the page are exposed
    And all ancestors (parents and parent's sibilings, grandparents and grandparent's siblings) appear until reaching site section root
    And the ancestors are highlighted
```

### Resources:
* Notion Screenshots: https://www.notion.so/Secondary-Navigation-Behavior-64aef479e77c4375b18e96483a1a2e7b
* Mockups: https://publicis.invisionapp.com/share/SY11BOIJQK4T#/454941204_Sidenav

### Notes

*Some complementary notes if necessary:*

* No split buttons, icon is there to show that there are children.

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by anthonycuellar** [comment]
@karlikpj Demo-ing to design today 7/6

**Comment by claireblaustein** [comment]
Made small update to clarify that only immediate ancestors (parent, grandparent) are highlighted.

**Comment by VictoriaSunNIH** [comment]
This prototype was completed in sprint 10, closing this ticket.
