### ISSUE TITLE
Prototype: Mobile Nav Buildout 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#169]
## As a mobile user, I want a mobile menu, so that I can easily browse the content on the site.

Build mobile nav component (copied mostly from sidenav component) (hamburger with sidenav structure inside)
  ** note: is there a back button after clicking main menu? (go to main menu but how do we go back to section we were in?) YES: By clicking on "back to menu" it takes you back to the page you are on. 

Mobile Nav Hamburger (eliminating the tongue section nav)

- [ ] Click on mobile hamburger exposes content 
  - [ ] L1 of the page (IF not already included in section nav)
  - [ ] Section navigation following same rules as desktop
  - [ ] Main Menu button
    - [ ] From any sub-menu, displays "Main Menu" button - Click displays same elements that are visible in the desktop primary menu (L1's and back to menu button)
    - [ ] If user clicks from sub-menu to main, "Back to Menu" button appears, otherwise, it does not show.
    - [ ] If starting from a L0 or L1, no button appears
- [ ] Removal of "tongue"

Notion Screenshots: https://www.notion.so/Secondary-Navigation-Behavior-64aef479e77c4375b18e96483a1a2e7b

### UX Writing

Consider the labels for the buttons

- Main Menu?
- Back to Menu/Back to Section/Back to ???? (consider testing different labels)

### Acceptance Criteria

- L1 always appearing (IF not already included in section nav)
- Behavior of the main menu button (when it appears, and what happens when clicked), and animations. Slides in from right.
- back to menu button (when it appears, and what happens when clicked), and animations. Slides in from left. 
- indicator line is on the page you are on all the time
- Direct ancestors (parents, grandparents of current page) get a highltight treatment
- location of search bar (different from uswds)
- Overlay takes 80% of the screen, menu is located to the top left, and when clicked flies out to the right
  - [ ] If there is no side nav, what does it look like? For example sitewide search (just show the main menu with no back to menu or main menu options)

```gherkin
Scenario: User is on a page and opens and closes the mobile menu
  Given they are on a screen 1023px and smaller
  When the menu button is clicked
  Then the mobile menu appears, sliding in from the left 
    And covers 80% of the screen
    And has an overlay of the content behind it at rgba(0, 0, 0, 0.2);
  When the "x" button is clicked
  Then the mobile menu slides left and disappears
```

```gherkin
Scenario: User is on a L1 page and opens the mobile menu, navigates to another page
  Given they are on a screen 1023px and smaller
    And on the homepage or one of the landing pages
  When the menu button is clicked
  Then the mobile menu appears
  	And the current page has an indicator
    And siblings of the page are exposed	
   And when a visible menu item OR its corresponding + is clicked (the whole line is clickable - no split buttons)
  Then the page loads to that particular page 
    And the menu closes, sliding left
```

```gherkin
Scenario: User is on an L2 or lower page, opens the mobile menu, navigates to a visible page in the menu, then re-opens the menu 
  Given they are on a screen 1023px and smaller
     And on a page that is at an L2 or lower
     And that page is NOT set the section nav root
  When the menu button is clicked
  Then the mobile menu opens
     And the current page has an indicator
     And appears under its section nav root 
     And appears under the L1 for the section they are in
     And any siblings of current page are exposed
     And any children of current page are exposed
     And all ancestors (parents and parent's siblings, grandparents and grandparent's siblings) appear until reaching site section root
     And the direct ancestors are highlighted
     And main menu button appears
When a visible menu item OR its corresponding + is clicked (the whole line is clickable - no split buttons)
Then the page loads to that particular page 
    And the menu closes, sliding left
When the menu button is clicked
Then the mobile menu opens
     And the current page has an indicator
     And appears under its section nav root (if applicable)
     And the L1 for the section they are in appears at the top
     And any children of the current page are exposed
     And any siblings of the page are exposed
     And all ancestors (parents and parent's siblings, grandparents and grandparent's siblings) appear until reaching site section root
     And the direct ancestors (parents and grandparents) are highlighted
     And main menu button appears
```

```gherkin
Scenario: User is on an L2 or lower page, opens the mobile menu, goes to the main menu, and returns to their menu
  Given they are on a screen 1023px and smaller
     And on a page that is at an L2 or lower
     And that page is NOT set the section nav root
  When the menu button is clicked
  Then the mobile menu opens
     And the current page has an indicator
     And appears under its section nav root 
     And appears under the L1 for the section they are in
     And any siblings of current page are exposed
     And any children of current page are exposed
     And all ancestors (parents and parent's sibilings, grandparents and grandparent's siblings) appear until reaching site section root
     And the direct ancestors are highlighted
     And main menu button appears
When the main menu button is clicked
  Then the L1s appear in the menu 
     And slide in from the right
     And the back to menu button appears
When the back to menu button is clicked
  Then the menu of the page they are on reappears
     And slides in from the left
     And current page gets the indicator
```

```gherkin
Scenario: User is on a page set as the section nav root and opens the mobile menu
  Given they are on a screen 1023px and smaller
     And on a page set as the section nav root 
  When the menu button is clicked
  Then the mobile menu opens
     And the current page is highlighted with an indicator
     And appears under the L1 for the section they are in
     And any children of the page are exposed
     And main menu button appears
When a visible menu item OR its corresponding + is clicked (the whole line is clickable - no split buttons)
Then the page loads to that particular page 
    And the menu closes, sliding left
When the menu button is clicked
Then the mobile menu opens
     And the current page is highlighted with an indicator
     And the L1 for the section they are in appears at the top
     And any children of the current page are exposed
     And any siblings of the current page are exposed
     And all ancestors (parents and parent's siblings, grandparents and grandparent's siblings) appear until reaching site section root
     And the direct ancestors (parents and grandparents) are highlighted
     And main menu button appears
```

### Resources:

* Mockups: Notion Screenshots: https://www.notion.so/Secondary-Navigation-Behavior-64aef479e77c4375b18e96483a1a2e7b
* Functionality mocked up (from Immunotherapy to main menu and back to menu) https://publicis.invisionapp.com/share/GE11CJS2HY4R#/455099555_Immunotherapy_To_Treat_Cancer_-_Mobile_Menu_Open

### Notes

* Secondary links above the search bar can be ignored, as they will not be used on our site.
  ![image](https://user-images.githubusercontent.com/31222859/124794792-623ad300-df1d-11eb-9596-84618964a025.png)
* Our side nav will exist, but for other DOCs, there may not be a need for back to menu, or main menu options if their site is not as deep.
* Needs more consideration for tablet and whether or not we need more rules for tablet

---

### Prerequisites

- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks

- [ ] Build hamburger menu on desktop or main page
- [ ] 

### Technical Notes

- More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
To Do:
@mworrest:
- please create invision comps and add to this ticket
- use the mobile nav from uswds, but with side nav data as part of the comp

**Comment by claireblaustein** [comment]
Updated acceptance criteria
- separating general menu appearance
- creating seperate scenarios for L1, section nav root, and L2+ non-section nav root
- new scenario for main menu/back to menu navigation

@mworrest @karlikpj can you take a look, make sure this all flows?

**Comment by mworrest** [comment]
@claireblaustein in the second scenario when you are on about cancer or another landing page, how do you get to child pages if they aren't exposed?

**Comment by claireblaustein** [comment]
@mworrest Good catch.....and I'm not sure about the answer. Because About Cancer and other landing pages aren't set as section nav roots, they would be considered to be child pages of the home, and you'd be seeing sibling pages (the other L1s). If we changed them to be section nav roots, then when on About Cancer, you'd see it's underlying structure.  I'm gonna jump this one over to Slack. 

Scenario 3 - you're right, that line should be included in the second half, assuming the item clicked on is not also marked as a section nav root. I've updated.
