### ISSUE TITLE
Create documentation for usa-section

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1691]
## As a documentation site user, I want to see documentation on `usa-section`, so that I can incorporate it correctly on my website.

Create page for usa-section within the Components section of the documentation site with the content needed for NCIDS launch.

### Tasks
- [x] Create content in shared Word Document `<insert link to shared folder>`
    - [x] IA responsibility:
    - [x] Dev responsibility:
    - [x] Design responsibility:
- [x] Review content in shared document
- [x] Create images in shared folder: See comment below.
- [ ] Convert content and images to markdown
- [ ] Add to documentation site

**Comment by andyvanavery31** [comment]
@bryanpizzillo @adrianacastaneda @lburack where should usa-section live on the documentation site? It doesn't feel like a standalone component, and seems more like a Foundation item, but unsure where it should live.****

**Comment by lburack** [comment]
> @bryanpizzillo @adrianacastaneda @lburack where should usa-section live on the documentation site? It doesn't feel like a standalone component, and seems more like a Foundation item, but unsure where it should live.****

Is it related to [Layout and Positioning](https://designsystem-dev.cancer.gov/develop/foundations/layout-positioning/)?

**Comment by dlescarbeau** [comment]
Developers Notebook for usa-section:
https://github.com/NCIOCPL/ncids/wiki/Developer's-Notebook#for-laying-out-new-pages--adding-components-to-a-page

**Comment by andyvanavery31** [comment]
usa-section is a component, and it will be placed under the Components section. It will be named "Section".

**Comment by adrianacastaneda** [comment]
@dlescarbeau here's the [Section component page](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Section_9.9.docx?d=w216014588506445193a54b0a9f81be24&csf=1&web=1&e=PCg68J)https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/[Section_9.9.docx](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Section_9.9.docx?d=w216014588506445193a54b0a9f81be24&csf=1&web=1&e=PCg68J)?d=w216014588506445193a54b0a9f81be24&csf=1&web=1&e=PCg68J for review! Let me know if you have questions. Thanks!

cc: @andyvanavery31

**Comment by bennettcc** [comment]
Hey @olitharp-nci - could you review this section documentation please? Thanks much

[Section component page](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/%5BSection_9.9.docx%5D(https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Section_9.9.docx?d=w216014588506445193a54b0a9f81be24&csf=1&web=1&e=eE60ma)?d=w216014588506445193a54b0a9f81be24&csf=1&web=1&e=eE60ma)

**Comment by bennettcc** [comment]
Thanks @adrianacastaneda - we'll keep this on the design board for Monika/Lilian to help with the image next week

**Comment by bennettcc** [comment]
Tagging and assigning to @blilianyu - we'll need design support to finalize the content for the USA Section page

**Comment by monika-jaeger** [comment]
Section component sample image attached. 
<img width="733" alt="section-component sample" src="https://github.com/user-attachments/assets/97da0c7d-a244-4297-a5a4-046b6f21498e">

Also added this as a comp to our NCIDS for all file in Figma: https://www.figma.com/design/8qu1psEjnehVDoZyWrH7ny/NCIDS-For-All?node-id=2306-22930&t=4jTlWcjp7z2IYuXz-1

cc: @andyvanavery31 @adrianacastaneda @bennettcc

**Comment by adrianacastaneda** [comment]
Attaching the section file here for reference: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20NCIDS%20Launch/Documentation%20Site/Page%20Content%20-%20Word%20Docs/Section.docx?d=w216014588506445193a54b0a9f81be24&csf=1&web=1&e=N8YLn0

**Comment by blilianyu** [comment]
@adrianacastaneda I added 2 questions but otherwise looks good on my end!

**Comment by adrianacastaneda** [comment]
@blilianyu— One of these definitely had a typo but removed them both anyway cause we were able to address those point in the code snippets were devs would find that information anyway! Thanks for reviewing!
