### ISSUE TITLE
[R2 Analytics Continued] Grants & Training analysis and recommendations (iteration 2)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1700]
**Description:** Completed one round of analytics review and associated recommendations (#1511 ). Implemented changes to the Grants & Training landing page based on those recommendations. Now, we are reviewing analytics data for these changes and intend to make subsequent recommendations. 

**Sub-tasks:**
- [x] Draft email to for Anna to send to stakeholders (Adriana)
- [x] Review internally 
- [x] Review raw HTML for G&T
- [x] Test on ACSF env
- [x] Send draft email to Anna/Alex
- [x] Implement in production (after stakeholders are alerted)
- [x] Ensure analytics ticket is logged accordingly

**Comment by laurelthrash** [comment]
On hold while we confirm the HTML for the two guide card row without image.

**Comment by laurelthrash** [comment]
Anna approved the 2 guide card row HTML for Grants & Training that includes our recommended approach: headings included in the box and centered aligned, in keeping with the three guide card row. Sent draft language for the content owners sent to Anna/Alex for review.

**Comment by laurelthrash** [comment]
Raw HTML component of two guide card row without images launched on Grants and Training landing page. Initiated CGOV-21443 to track performance. Closing this ticket.
