### ISSUE TITLE
[R2.4 Analytics] Verify Post Launch Analytics Accumulation (Cancer Types Landing Page)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1714]
**Description:** Initiated post-launch dashboards for R2.4 Cancer Types Landing Page. Need to check-in to determine if enough data has accumulated to initiate analysis of the home and landing pages.

**Sub-tasks:**
- [x] Verify data accumulation via significance calculator spreadsheet
- [x] Establish if EN and SP will be addressed together
- [x] Review analytics and prep recommendations based on review [Nicole/Joe]
- [x] Align internally on recommendations [On 10/9 in weekly reqs]
- [x] Align with ODDC on recommendations (email) 
- [x] Meeting on 11/8 to share data with DOCs (once recommendations for A/B testing are set: https://github.com/NCIOCPL/cgov-digital-platform/issues/4469)

**Comment by bennettcc** [comment]
Presented data analysis outcomes and A/B testing approaches with the cancer type landing page owners on Friday 11/8 - they approved of all A/B next steps. This ticket is complete
