### ISSUE TITLE
Atomic Component: Footer

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#172]
### Handoff of footer component from design to development

This ticket is for building the footer.  This will be dependent on the components being built.

Pre-requisite tickets:

- [ ] List: #184
- [ ] Collapsible div: #187
- [ ] Social Media: #186
- [ ] GovDelivery: #185 

> **ESTIMATE** TBD

### Acceptance Criteria
*Include specs:  List of colors (hex, token name), variants, and states.* 

### Acceptance Criteria

Need to add ACs for footer regions and how they behave (based on components built that are being pulled)

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Desktop: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/454062769_Header_-_Footer_-_Desktop
* Mobile: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/454062770_Header_-_Footer_-_Mobile

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ]  Draft needed internal documentation (insert Notion link)
- [ ]  Publish completed component in DSM

### Notion documentation:
- [ ]  Include information from Notion here

### Technical Notes
- More notes, or technical nuances/direction

**Comment by karlikpj** [comment]
* Nothing on Guidance/Usage for this component? or the specific atomic components.
* Can we get just the footer in an invision comp | / without all the other stuff we're not building.
* What grid are we using here (ok with anything) but not matching up to USWDS defaults.. if we're using another - than what is the size/breakpoints etc..
* Questions about font's in this area.. currently we only implemented light/normal/bold in Poppins as per ticket - but header shows it as semibold?
https://github.com/NCIOCPL/ncids/issues/91

**Comment by blilianyu** [comment]
@karlikpj 
- Guidance/usage we can hold off on for now. I don't think we've have anything yet.. 
- I've updated the wireframes so that it's only showing the header and footer. 
- For grid, we're using whatever is the USWDS sketch template. We haven't changed any of the breakpoints.
- We'd like to also have semi bold for Poppins. Can we add that or should that be a different ticket?

**Comment by karlikpj** [comment]
@blilianyu 
* Fonts - We can add it (semi bold) in this PR - it's all from google so just need to update the SCSS file for it! Wanted to make sure it was correct!
* Grid - Cool, we'll use that as the default - gutters/padding and any changes we can do once we see the whole page to tweak! 
* Guidance - will be FPO for now! (reminder to make separate ticket for that)

**Comment by VictoriaSunNIH** [comment]
#202 is the ticket for building footer, closing this one out.
