### ISSUE TITLE
Create Reference Documentation for Component Reasoning

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1742]
**Description:** During conversations for R3/MLPs, it was determined that it would be helpful to have documentation for the reasoning behind each proposed component. This will be used during conversations around scope to help determine which component to keep/cut/modify. 

**Sub-tasks:**
- [x] Create documentation for each proposed component (Adriana)
- [x] Review internally (week of 06/17)
- [x] Make edits (R3.2 - 06/26)
- [x] Share internally w/POs (Adriana)
- [x] Make edits - R3.3 (07/03)
- [x] Make edits - R3.4
- [x] Make edits - R3.5
- Review with federal team and use as part of scope conversations

**Comment by laurelthrash** [comment]
Mural board for the component glossary as way to present above information: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1718208797008/b6f1316c8de402b7d40ebd222170526d7652f31b?sender=uc8881d65820946a13d002641

**Comment by laurelthrash** [comment]
Notes from 06/18 conversation:
- Goal of Mural: have reasoning behind each component, complement analytics findings, consider for education/documentation
- Could consider using the Mural/information in the Mural for for education/documentation 

Actions
- [ ] Call out on Mural board how components meet stakeholder or content needs/specific use cases (e.g., add call out or use bold)

Timeline
- R3.2 portion revised by 06/25

**Comment by adrianacastaneda** [comment]
@laurelthrash @lburack confirming 3.5 reasoning has also been added to the Mural

https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1718208797008/b6f1316c8de402b7d40ebd222170526d7652f31b?sender=u44cc8ba0586f3bbc923b4447
