### ISSUE TITLE
Establish R3 Components and Approach

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1743]
**Description:** Formal comps completed as part of #1690. Proceeding with alignment on the selected components for R3 and overall approach.

**Sub-tasks:**
- [x] Prepare PPT for Thurs 06/13 meeting [Tues. 06/11]
- [x] Share PPT with Anna for Thurs. meeting [Tues. 06/11 or Wed. 06/12]
- [x] Share R3 approach with Lakshmi and receive approval to proceed with R3.1 development work [Thurs. 06/13]
- [ ] Create next step tickets, as needed
