### ISSUE TITLE
Establish R3 Content Launch/Update Plan

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1749]
**Description:** The team is preparing the content launch/update plan to accompany the Release 3 component launch. This ticket is to broadly track work on the content plan but please reference linked documentation for detailed steps/timing. 

**Timeline**
Detailed timeline and next steps here: https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Phase%203)%20Content%20Launch/Content%20Launch%20Tasks%20and%20LOE%20Estimates.xlsx?d=w9c3e77fef84347f7a9a5cc95d315c25a&csf=1&web=1&e=xgliVk

**Sub-tasks:**
- [x] Identify possible pages for phase 1 that we can successfully iterate on over time (Adriana)
- [x] Combine Priority MLP Excel (70 pages) and broad analysis Excel (373 pages) (Adriana)
- [x] Establish tasks for the plan and assign estimate LOE (Laurel + Joe)

**Comment by laurelthrash** [comment]
Discussed 07/03 for @adrianacastaneda to update the "All Sites" tab in the mega list of MLPs to include missing sites. Noting this action here!

- [ ] Update "All Sites" tab to include missing MLPs (@adrianacastaneda )

**Comment by laurelthrash** [comment]
Actions from 07/08 working session @adrianacastaneda @lburack :

- [ ] Reminder: action from above 07/03 session
- [ ] Share plan internally with PM/POs (Laurel - Wednesday)
- [ ] Add LOE for training options (Laurel - Tuesday)
- [ ] Create high level summary of content rollout plan and add calendar goals (Laurel - Tues); then sync with Adriana/Lindsay (Laurel - Thurs)
- [ ] Pare down list of measurement pages (Adriana, Lindsay - EOW)
