### ISSUE TITLE
Discovery: Landscape Review for Home/Landing Pages

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#175]
# Landscape review for Home/Landing Pages

*Description of what is to be accomplished.*
1. What are the best practices other similar sites are using for home/landing pages?
2. What are common features shared on other home/landing pages?

### Sub-Tasks
- [x] Identify criteria for potential sites
- [x] Narrow to 3-4 to dig into
- [x] pull together reporting on potential features and directions

### Resources:
* Mural: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1624482670336/2c2bd1aa2b8d139d6ae96853d42037ac02299156?sender=claireblaustein5539

### Notes
- Decided on five sites - American Cancer Society, Mayo Clinic, VA.gov, ASCO's beta site, CDC

**Comment by claireblaustein** [comment]
Landscape review activities are available here: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1624482670336/2c2bd1aa2b8d139d6ae96853d42037ac02299156?sender=claireblaustein5539

We'll be reviewing with client tomorrow (Wed July 7)
