### ISSUE TITLE
[R2 Analytics Continued] Research Landing Page analysis and recommendations (iteration 2)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1753]
**Description:** Completed one round of analytics review and associated recommendations (#1403). Implemented changes to the About Cancer landing page based on those recommendations. Now, we are reviewing analytics data for these changes and intend to make subsequent recommendations. 

**Sub-tasks:**
- [x] Review analytics and determine new recommendations, if applicable (Adriana)
- [x] Draft email to stakeholders
- [x] Review internally 
- [x] Send to ODDC for review
- [x] Make changes or updates, as needed
- [x] Send to stakeholders and invite them to make edits accordingly 

**Blocking:** #1487

**Comment by adrianacastaneda** [comment]
Sent over for internal review over Slack. Adding here for reference: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Measurement%20%26%20Evaluation/Communications/Monitoring%20R2.1%20Analytics%20-%20Research%20Cancer.gov%20%E2%80%93%20Analysis%20and%20Recommendations%20Email.docx?d=w3ff36482673043fdbfaa59c9a5d596d1&csf=1&web=1&e=L55FPB

cc: @laurelthrash

**Comment by laurelthrash** [comment]
Sent to ODDC for review on 07/01/24.

**Comment by laurelthrash** [comment]
Alex sent summary to stakeholders on Friday 07/12. Closing this ticket.
