### ISSUE TITLE
R3/MLP Stakeholder Share-out Messaging

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1759]
**Description:** Part of the R3/MLP effort includes sharing out of information with the individuals that were part of the stakeholder interviews conducted in April 2024. Agreed with Anna on 06/17 that we will reach out to this group via email (similar to our process for contacting the broader Redesign stakeholder group).

**Sub-tasks:**
- [x] Modify R3 summary PPT for stakeholder audience **[Due: 06/25]**
- [x] Draft email for stakeholders to accompany PPT **[Due: 06/25]**
- [x] Send to Anna for review **[Due: 06/26]**
- [x] Make edits/modify accordingly
- [ ] Anna send

**Comment by laurelthrash** [comment]
PPT/email draft/stakeholder list found here: https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%203/Phase%202)%20Design/Stakeholder%20Readout?csf=1&web=1&e=KnzIFx

**Comment by laurelthrash** [comment]
Anna sent to stakeholders on 07/08. Closing this ticket.
