### ISSUE TITLE
External links

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1773]
Add support for external links to the NCIDS.

`usa-link--external`

## Tasks

- [ ] Remove external link css from the button package. This is a link package, not button.
- [ ] Storybook
   - Missing tests for current and new tab, can we would test for spanish in storybook/backstop
   - How is this applied to external links in `usa-prose`?
- [ ] Patch translation to [lang=es/en]
   - Need Spanish translations for:
      -  "External, opens in a new tab."
      - "External."
- [ ] Guidance? No link documentation. Is guidance we do have for NCIDS or Cgov?
- [ ] Close old PRs in favor of using USWDS's method

## Related

- [ ] https://github.com/NCIOCPL/ncids/issues/579
- [ ] https://github.com/NCIOCPL/ncids/issues/1279

**Comment by andyvanavery31** [comment]
Closing due to the work on #1883
