### ISSUE TITLE
Remove NCIDS deprecations

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1774]
Preparing to launch 3.0.0, clean up NCIDS with deprecated breaking changes.

## Tasks

- [x] **Breaking changes: NCIDS 3.0.0**      
   - [x] **All module imports paths should be updated to point directly to the component and not the ncids module.** 
      Use `import { NCIBigFooter } from '@nciocpl/ncids-js/usa-footer'` instead of 
          `import { NCIBigFooter } from 
 '@nciocpl/ncids-js'`
   - [x] **Removed module exports**
      - [x] `NCISubscribe`
      - [x] `NCISubscribeOptions`
   - [x] **Banner**
      - [x] `.usa-banner .usa-button` has been replaced by `.usa-banner__language-toggle`
   - [x] **Header mega menu**
      - [x] `AutocompleteAdaptor` module has been replaced by `AutocompleteAdapter`
      - [x] `MegaMenuAdaptor` module has been replaced by `MegaMenuAdapter`
      - [x] `useUrlForNaviationId` has been removed
      - [x] `data-megamnu-disabled` has been removed. Add `data-menu-id` attribute to a primary navigation item if it truly has a mega menu.
      - [x] `.nci-header--extended` has been replaced by `.nci-header--megamenu`
   - [x] **Site Alert**
      - [x] `NCISiteAlert` module has been replaced by `USASiteAlert`
      - [x] `NCISiteAlertOptions` has been replaced by `USASiteAlertOptions`
      - [x] `.usa-site-alert--nci-standard` has been replaced by `.usa-site-alert` (Default variant)
      - [x] `.usa-site-alert--nci-slim` has been replaced by `.usa-site-alert--slim`
      - [x] `.usa-site-alert--nci-info` has been replaced by `.usa-site-alert--info`
      - [x] `.usa-site-alert--nci-emergency` has been replaced by `.usa-site-alert--emergency`
      - [x] `.usa-site-alert .usa-alert__nci-list` has been replaced by `.usa-list.usa-list--nci-two-column`
   - [x] Removed unused theme variables `$theme-section-padding-height-first` and `$theme-section-padding-height-first-mobile`
## Related

- https://github.com/NCIOCPL/cgov-digital-platform/issues/4355
