### ISSUE TITLE
Explore Design for Wide Guide Card

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#1778]
**Description:** Team is reviewing the design for the proposed Page Title Wide Guide Card and Wide Guide Card to address preliminary concerns/questions.

**Sub-tasks:**
- [x] Discuss concerns and brainstorm ideas (07/09)
- [ ] Create modified designs that address concerns while meeting stakeholder/user needs (Lilian/Monika)
- [ ] Review modified designs (07/10)
- [ ] Align internally on designs
- [ ] Fold into release conversations

**Primary Concerns to Address:**
- Unclear that heading is for the page vs. the component only
- Ensure there is enough room for into text

**Comment by laurelthrash** [comment]
From @lburack during 07/08 brainstorm:

Use this (https://www.cancer.gov/about-nci/organization/cgh) as the title card example that does not include heading. CTA buttons could be:
- Research & Training Programs
- Partnerships & Dissemination
- Funding Opportunities

**Comment by monika-jaeger** [comment]
### For UX discussion today (Thursday 7/11) 
**Wide Guide Card**
- [CRCHD](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=5158-29834&t=mVmGVoOKrRNRG6ZC-1)
- [Clinical Trials Spanish](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=5158-30262&t=mVmGVoOKrRNRG6ZC-1)
_notes: content area is a fixed height, discuss governance with number of buttons._ 

Revisiting CTA Strip
- [CTA Strip on CGH](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=3858-4985&t=vaRP2cbvzqxvkICh-1)
notes: light version vs dark, discuss governance on tagline length

cc: @blilianyu @laurelthrash

**Comment by laurelthrash** [comment]
@blilianyu @monika-jaeger Actions from 07/11 UX Discussion: 

Comp out options:
- Option 1: Existing component (where heading is pulled out of component)
- Option 2: Promo block-ish design
- Option 3: CTA strip on Slim hero
- Option 4: Use existing components (Title + Slim Hero + Two Column) to meet need

Next Steps:
- [ ] Send comps around internally via Slack
- [ ] Align internally on options and recommendation
- [ ] Bring to federal team for discussion and brainstorm/validate meeting concerns and needs

**Comment by blilianyu** [comment]
@monika-jaeger  and I reworked some options below.

- Option 1: [Existing w/ optional h2](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=5297-34698&t=NG9V0LTNJWOLPq0x-1) (One component; title will have to be added to the page if used as first component on the page)
- Option 2: [Slim Promo w/ CTA strip](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=5297-37262&t=NG9V0LTNJWOLPq0x-1) (New Component; title will have to be added to the page if used as first component on the page)
- Option 3: [Slim Hero w/ CTA Strip](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=5297-34701&t=NG9V0LTNJWOLPq0x-1) (New Variant)
- Option 4: [2-Column Layout w/ Lead Image](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=5297-36749&t=NG9V0LTNJWOLPq0x-1) (No component, requirements will need to be updated)

cc: @adrianacastaneda @lburack @lizsiciliano @laurelthrash

**Comment by laurelthrash** [comment]
Note from SU: Need to align on options as well as 1) goal of conversation with the federal team, and 2) alignment on if the recommendation includes user testing.

**Comment by laurelthrash** [comment]
Internally aligned that options 1, 2, and 4 as preferred, followed by 3.

**Comment by laurelthrash** [comment]
Closing this ticket as the team has aligned on the new design options. Moving this into conversations with the federal team and will open a new ticket(s), as needed. Cc: @monika-jaeger @blilianyu @andyvanavery31
