### ISSUE TITLE
Documentation: Header Guidance and Usage 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#180]
Provide guidance and usage text for the extended NCI DS Header: https://designsystem-dev.cancer.gov/develop/

**Parent Issue:** #171 

### Sub-Tasks
- [ ] Create guidance text
- [ ] Create usage text
- [ ] Add text to the design system for the header component

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

### NCIDS Guidance
- [x] *When to use component and its variant(s)*
  * Example: Use a card when featuring content
- [x] *When to consider something else*
  * Example Use a list when you have multiple pieces of content, and will display too many cards*
- [x] *Usability Guidance*
  * Example: Don't have 1 button in CTA strip

Link to header documentation: [CLICK HERE!
](https://lion.box.com/s/7gzhizzkees9k9k52trknoiua0otezmc)

# Header
The header is the top portion of a web page that should be consistent for every page on a website. . The header should include the logo, search, and primary site navigation. A header helps users identify where they are and provides a quick, organized way to reach the main sections of a website.

Additionally, per the U.S. and NCI Web Design Systems, all federal websites must include the “official government website” banner at the top of the header. 

## When to use a header component
The NCI design system requires all web pages to have a header and specifies the elements to include and their placement. A consistent header across all NCI websites will give our users a consistent experience.  

**Most websites require header navigation.** Websites require a form of navigation to help users find the information they need. While a horizontal navigation bar is one option for navigation design, it is one of the most visible and familiar ways of helping users navigate a site.

## Header usability
**List main website sections as links in the horizontal navigation.**

**Dropdown menus help preview lower-level content.** For large websites, use dropdown menus to help users preview lower-level content. Do NOT include more than 3 levels of  navigation in dropdown menus. If content has more than levels are present, it is recommended that another navigation pattern should be explored or the primary navigation links should be reconsidered. If lower-level sections are closely related and users will need to quickly jump between them, consider using a side navigation instead of — or in addition to — a dropdown.

**Use short, clear link labels.** While navigation labels need to align with the title of the page they link to, they should be short—no more than xx characters to make the text easy to scan. Don’t use jargon or unfamiliar terms. 

**Left-justify labels.** Left-justified link labels are more scannable.

**Avoid org-structure navigation.** Don’t model your navigation after your org structure. Instead, structure it to the tasks and information your users need the most.

**Highlight the current section.** Show users where they are within the site by highlighting the current section.

**Always research your navigation.** Conduct research with your users, review analytics, and base decisions about your site’s information architecture and navigation structure on your findings. Continue researching to confirm that updates meet your users’ needs.

**Use the appropriate logo.** Standalone DOC websites may use their DOC blended logo. Web applications may use a program blended logo. Contact your DOC Communications Manager, your OCPL Communications Lead, or email the NCI Branding team at ncilogoqs@mail.nih.gov with logo questions.

## Header accessibility
Include skip navigation links to allow users with screen readers to bypass long navigation lists. Make sure you include an id at the beginning of your main content and that it matches the skipnav link. Find more information on these links at WebAIM.

Include tab focus for all top-level navigation items — this feature will allow keyboard-reliant users to navigate interactive items.

Ensure your horizontal navigation is keyboard compatible; test to make sure users can use Tab to navigate and Space (or Enter) to open pages.
Avoid using hover to expand dropdown lists. Hover is difficult for users and won't work on touch screens. Dropdowns should expand on click or with keyboard navigation.

**Comment by olitharp-nci** [comment]
Notes/questions from when I spoke with the Pauls/Bryan:

* Image required, do not use just text logo
* USWDS has 4 header variants, which variants do we allow? (basic, basic w/ mega menu, extended, extended w/ mega menu)
* If a variant differs from USWDS, call out difference with alert/warning message
* Document header parts (and if they are required or optional): Logo, search, primary menu, secondary menu, mega menu

**Comment by VictoriaSunNIH** [comment]
Next steps is to get this into DS for header

**Comment by russellwyatt** [comment]
Pull request has been approved. This is complete.
