### ISSUE TITLE
Documentation: Footer Guidance and Usage

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#181]
Provide guidance and usage text for the NCI DS Footer.  

Example: https://designsystem.digital.gov/components/footer/

**Parent Issue:** #171 

### Sub-Tasks
- [ ] Create guidance text
- [ ] Create usage text
- [ ] Add text to the design system for the footer component

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by russellwyatt** [comment]
Closed
