### ISSUE TITLE
Wide Guide Card Validation Testing

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1814]
Three options have been created to meet the user needs for Mini Landing Pages of having a component that has a visual introduction to content, contextual text, and an interface to allow users to engage with calls-to-action.  

### User Needs

1. The user needs a visual introduction to content 
2. The user needs contextual text to introduce calls-to-action
3. The user needs an interface that allows them to navigate to important content on the site 

### Tasks

- [x] Proposal of testing to client
- [x] Approval of testing by client
- [x] Decision on page to use for testing
- [x] Proposal of page to use for testing to client
- [x] Approval of page to use for testing by client
- [x] Draft of Testing Screener
- [x] Internal Review of Testing Screener
  - [x] Designer Review
  - [x] IA Review
  - [x] Product Review
- [x] Internal Approval of Testing Screener
  - [x] Designer Approval
  - [x] IA Approval
  - [x] Product Approval
- [x] Draft Unmoderated Script
- [x] Internal Review of Unmoderated Script
  - [x] Designer Review
  - [x] IA Review
  - [x] Product Review
- [x] Internal Approval of Unmoderated Script
  - [x] Designer Approval
  - [x] IA Approval
  - [x] Product Approval
- [x] Present Testing Screener and Unmoderated Script to Client
- [ ] Conduct Unmoderated Testing
- [ ] Draft Findings Report
- [ ] Presentation of Findings to Internal Team
- [ ] Presentation of Findings to Client

### Resources
- [Validation Testing Document](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B9FE8259D-0338-4B0B-82B8-BE7817A29CF7%7D&file=Mini%20Landing%20Pages%20Wide%20Guide%20Card%20Investigation%20and%20Validation%20Testing.docx&action=default&mobileredirect=true)
- [MLP WGC User Testing Screener](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B5E3DE18D-BB1A-4166-8C53-180016787337%7D&file=MLP%20WGC%20User%20Testing%20Screener%20-%20General%20Audience.docx&action=default&mobileredirect=true)
- [MLP WGC Unmoderated Script](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B2B22B1F8-C416-4CCF-A09A-AE0681C29F14%7D&file=MLP%20WGC%20Unmoderrated%20Script%20-%20DRAFT%20for%20Discussion.docx&action=default&mobileredirect=true)
- [Comps](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=5955-38949&t=ALnM7sLYNHXBWBjq-0)
