### ISSUE TITLE
Build: List Component

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#184]
### Build List component based on design specs/requirements documented in this ticket

> **ESTIMATE** 3

### Variants Information:
* Related USWDS Links: https://designsystem.digital.gov/components/list/
* Variants: ordered, unordered, unstyled

### Invision Mockups: 
  * Desktop: N/A
  * Tablet: N/A
  * Mobile: N/A

### Notion Documentation:
 * N/A

---

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create List component that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used - copied from USWDS
- [ ] Update NCIDS-CSS
  - list

**Comment by olitharp-nci** [comment]
USWDS footer defaults blue text over white, we are flipping them here. 

Design note/changes for footer lists:

- White on blue background
- Underline on hover only
