### ISSUE TITLE
MLP Content Launch Support: Tier 1

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1844]
Capturing the actions needed to support Tier 1 of MLP Content Launch efforts.

### Tasks
- [ ] Prepare emails to send to DOC POC's
- [ ] Review draft emails with ODDC Feds (Alex, Anna)
- [ ] Build draft/recommended content in CMS (unpublished)
- [ ] Address feedback from DOCs
- [ ] Publish content on MLPs

### Notes

*The Tier 1 schedule is linked here: https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B9c3e77fe-f843-47f7-a9a5-cc95d315c25a%7D&action=edit&activeCell=%27Tier%201%20Timing%27!N16&wdinitialsession=617a362e-ca89-e019-fe8e-d1f76afc5243&wdrldsc=5&wdrldc=1&wdrldr=AccessTokenExpiredWarningUnauthenticated%2CRefreshin

**Comment by bennettcc** [comment]
Closing tickets - Tier 1 publishing complete
