### ISSUE TITLE
META: MLP Content Launch Support: Tier 2 and 3

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1845]
Capturing the actions needed to support Tier 2 of MLP Content Launch efforts.

### Tasks
- [x] Define tier 2 training plan and timing - create training plan/offerings document
- [x] Review training plan document and timing with ODDC Feds (Alex, Anna)
- [x] Create training materials, as defined in training plan
- [x] #1912

Prioritized list of MLPs and tiers: https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B057AA590-69EE-4684-8CAA-1C996D6F8CFE%7D&file=R3%20Prioritized%20MLPs.xlsx&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0&action=default&mobileredirect=true

**Comment by andyvanavery31** [comment]
Tiers 2 and 3 are complete.
