### ISSUE TITLE
Build: GovDelivery Subscribe Component for Footer

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#185]
Implement the placeholder text box and signup for govdelivery subscribe component.

![image](https://user-images.githubusercontent.com/31222859/123146923-72868480-d42c-11eb-8e36-c350e301ae78.png)

> **ESTIMATE** 2

### Acceptance Criteria

```gherkin
Scenario: User clicks sign up and has provided a valid email address
  Given I click sign up after entering an email address
    Then the system sends the email address through to govdelivery, onto the email confirmation page
```

```gherkin
Scenario: User clicks sign up without providing an address 
  Given I click sign up without providing an email address
    Then the system displays an error message, prompting me to enter an email address
```

```gherkin
Scenario: User provides content but its not an email address
  Given I enter content that does not have an "@" symbol
    Then the system displays an error message, prompting me to enter a valid email address
```

### Resources:
* Mockups: 
* * Fail State: https://invis.io/6Q11WK4CPGHZ#/460017992_Header_-_Footer_-_Desktop_GovD_Error
* * Desktop: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/454062769_Header_-_Footer_-_Desktop
* * Tablet: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/455696386_Header_-_Footer_-_Tablet_Portrait
* * Mobile: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/454145716_Header_-_Footer_-_Mobile

* Web Page: *Here goes a URL to an existing web page*

#### When to use this component:
This component should be used when including a way for users to subscribe to your content in the footer of your website.  NCI uses GovDelivery (Granicus) as its main subscription service, and should pass the email address entered in this component through to GovDelivery's subscription page.

This consists of a text input, and a button component from the design system. 

#### Usability Guidance
Validation messages or stylings should only appear after a user has interacted with a particular field or button within this component.

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Subtasks
- [ ]  Build subscribe component with text input box and button for signup
- [ ]  Unit tests
- [ ] Styling for footer

### Notion documentation:
- [ ]  Include information from Notion here

### Technical Notes
- More notes, or technical nuances/direction

**Comment by anthonycuellar** [comment]
This hasn't kicked off yet.

**Comment by olitharp-nci** [comment]
@mworrest when you get a chance, can you add the mocks for the failed message and the AC for expected behavior on success (even if it's opening in a new tab/same window to a separate url)?

**Comment by VictoriaSunNIH** [comment]
@VictoriaSunNIH - write basic guidance.

**Comment by olitharp-nci** [comment]
Update: states approved during mid sprint review

**Comment by mworrest** [comment]
Updated fail state that was approved on 10/20/2021: https://invis.io/6Q11WK4CPGHZ#/460017992_Header_-_Footer_-_Desktop_GovD_Error
