### ISSUE TITLE
R3 MLP Flag Card Group Measurement Page Approach and Content Publishing

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1851]
The R3.3 release is tentatively scheduled to launch in the first week of October. Following the code launch, we'll coordinate with select content owners to convert their MLPs to use the NCIDS template and incorporate the new flag card group component. This ticket is to track the coordination, communications, and CMS effort to convert the target measurement pages for the R3.3 release.

This ticket will go into Iteration 55.

### Tasks
- [x] Identify MLPs that are a part of the flag card group measurement pages
- [ ] Draft communications to send to site/content owners about the purpose/process/timing of measurement page publishing (by end of week 9/20) (https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BFDEAC79E-FEB8-4C11-A0E2-2ECCD32C6B73%7D&file=Communications%20-%20Flag%20Card%20Group%20-%20Measurement%20Pages.docx&action=default&mobileredirect=true)
- [ ] Review list of target measurement pages and communications approach with Alex/Anna (9/23)

Approach/Timing: https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BCCAE6EE5-B1DD-4E8E-A29E-043C113B5951%7D&file=Cgov_and_DOCs%20MLP_analysis_v2.xlsx&nav=MTVfe0MzRjI1NzQzLTkzNDgtNDdGRi1CQTc3LUY2ODY1ODk0NDdEOX0&action=default&mobileredirect=true

- [x] Launch flag card group component (estimated 10/3 via c.gov platform release)
- [x] Converted target MLPs to use the NCDIS template, and flag card group component - save changes in post publication review to allow for content owner review (by 10/8)
- [x] ODDC Fed review and approve MLP (by 10/8 - 10/11)
- [x] Content owners review and approve MLP (10/14-10/17)
- [x] Publish MLPs (10/18)
- [x] Notify analytics team of published content - to initiate analytics tracking efforts

Inventory of measurement pages lives here: https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BCCAE6EE5-B1DD-4E8E-A29E-043C113B5951%7D&file=Cgov_and_DOCs%20MLP_analysis_v2.xlsx&action=default&mobileredirect=true

**Comment by bennettcc** [comment]
All five flagcard measurement pages have been published on Prod - analytics team has been notified to begin gathering data
