### ISSUE TITLE
Build: Social Media Icons Component

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#186]
> **ESTIMATE** 3

Social Media Icons Component (incorporate social media icons from fontawesome, provide links for social media) 

![image](https://user-images.githubusercontent.com/31222859/123146994-87631800-d42c-11eb-8dc4-6a561ed56b77.png) 

### Subtasks
- [ ]  Incorporate social media icons from fontawesome
- [ ] Unit tests

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Notion documentation:
- [ ]  Include information from Notion here

### Technical Notes
- More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
This will be part of the larger footer story
