### ISSUE TITLE
META: R4 User Research and Discovery

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/ncids#1861]
This ticket is to track the support needed to complete user research and discovery for the R4 Inner page release. 

### Sub-Tasks

- [x] Have Fed discussions about the audiences and mobile vs desktop breakpoints. Will we recruit health professionals or general public? - week of 10/7 (Decided on 10/11 to target general public)
- [x] Develop Test Plan Proposal - Week of 10/14
The testing plan should include the steps for stakeholder testing, user testing, concept validation testing (bringing wireframes to users following the first two tests), component validation, and page-level (system) validation )
- [x] Review and approve Test Plan and specific audiences/test sample internally and with the client (Week of 10/21)
- [x] #1916 (end by 11/27) 
- [x] #1917 
       1) Build test script: by 12/6
       2) Review script with Feds on 12/9
       3) Scheduled testing to begin on the 11th
       4) Complete testing by 1/10
       5) Analysis the week of 1/13-17
       6) Fed shareout the following week – week of 20th
- [x] #1918
- [x] #1919
- [x] #1920 (share stakeholder interviews + user testing outcomes by the end of Jan)

Materials related to User Research should be stored in this location: https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%204/User%20Research?csf=1&web=1&e=wq3oTY

**Comment by bennettcc** [comment]
This was completed the week of 1/13 - closing ticket
