### ISSUE TITLE
META: Add External Link Icons to Components

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1883]
### Meta Description
This ticket will track all the steps for the different components that will need an external link. The individual tickets linked on this Meta will be the ones that will track the deliverables for each component.

Overarching Specification:
- A link/button can be overridden to have an external link icon
- A link/button with an external link icon can be overridden to remove it (add ACs where this is explained that there is an override class that knows that the rule would add the icon but it doesn't show)
- External link icons shall always appear on the right side of the link
- Any time a social media icon is used to target an NCI approved Facebook, X, Instagram, Youtube, or LinkedIn then the external link icon will not appear

## Related Tickets

- #1898 
- #1899 
- #1900 
- #1901 
- #1902 
- #1932 
- #1935 
- #1945 
- #1946 
- #1949 
- #1950 
- #[4497](https://github.com/NCIOCPL/cgov-digital-platform/issues/4497)
- #[4498](https://github.com/NCIOCPL/cgov-digital-platform/issues/4498)

### Comps Needed
- [x] Comp 1
  - Create one comp that has 1 example that covers Anchor (styled with usa-button)
  - Functional Specifications:
    - The person putting the raw html of the button on the page should put the external link on it.
    - When the button goes to the fixed width (full size), then the text will be centered and the icon will be fixed on the right
    - When the button is added then the icon will be fixed on the right
    - When the text wraps, the external link icon will be fixed to the right with the padding/spacing maintained/set per the spacing tokens in the comp
  - Edge Cases/Test Scenarios:
    - Wrap text in button
    - Different breakpoints
    - All the buttons listed on the individual ticket, with scenarios for overriding when there is/is not an external link icon
  - Technical Notes/Ideas:
    - Place an svg into the markup. If there is already an icon in the button, hide the existing one, display the external link icon, use the after tag.
    - There will only be one icon on an anchor button (i.e., if there is an icon on a button, either on the left or the right, the original icon would be removed and the external link icon will go on the right).
    - The rules for hiding an icon will be aligned with the overarching rule for displaying the social media icon for NCI approved socials (FB, X, IG, YouTube, and LinkedIn).
    - At full width, the external link icon will the fixed on the right
- [x] Comp 2
  - Create one comp that has 1 example that covers Anchor Full Width
  - Functional Specifications:
    - The external link icon is always fixed on the right
    - The icon will always be middle aligned in the vertical dimension even when the text wraps
  - Edge Cases/Test Scenarios:
    - Wrapping the text
    - Different breakpoints
  - Technical Notes:
    - Make a rule for the component
- [x] Comp 3
  - One example of Anchor Big
  - Functional Specifications:
    - For all things usa-button, we will not do anything. It will be on the individual to make the external link icon get inserted on the right per guidance
- [x] Comp 4
  - One example of Anchor Small
  - Functional Specifications:
    - For all things usa-button, we will not do anything. It will be on the individual to make the external link icon get inserted on the right per guidance
- [x] Comp 5:
  - One example of Anchor Icon Left
  - Functional Specifications:
    - For all things usa-button, we will not do anything. It will be on the individual to make the external link icon get inserted on the right per guidance
- [x] Comp 6:
  - One example of Anchor Icon Right
  - Functional Specifications:
    - For all things usa-button, we will not do anything. It will be on the individual to make the external link icon get inserted on the right per guidance
- [x] Comp 7:
  - One example that covers CTA Strip and Hero w/ CTA Strip
  - Functional Specifications:
    - Change the `>` to the external link icon
    - The icon will always be fixed on the right
    - The icon will always be middle aligned in the vertical dimension
    - If the title would wrap, the last word of the title will wrap with the icon so the icon does not sit alone (occurring for the dynamic width, not full width) attempt this as long as there is not a huge cost to do so
  - Edge Cases/Test Scenarios:
    - Wrapping the text
    - Different breakpoints
  - Technical Notes:
    - The `::after` is after the button on the `<li>` and is setting its position
- [x] Comp 8:
  - One example of EACH variant of Collection
  - Technical Specifications:
    - External Link icon is center aligned on the title text
    - Follows usa-link styling
    - If the title would wrap, the last word of the title will wrap with the icon so the icon does not sit alone
  - Edge Cases/Test Scenarios:
    - Wrapping when it would just be the icon and not any of the words
    - The different variants of the collection
- [x] Comp 9:
  - One example of Feature Card
  - Technical Specifications:
    - External Link icon is center aligned on the title text
    - If the title would wrap, the last word of the title will wrap with the icon so the icon does not sit alone
  - Edge Cases/Test Scenarios:
    - Wrapping when it would just be the icon and not any of the words
  - Technical Notes:
    - This is not a usa-link so a special rule will be applied
- [x] Comp 10:
  - Flag Card AFTER MERGE NCIDS UPGRADE
  - Technical Specifications:
    - External Link icon is center aligned on the title text
    - If the title would wrap, the last word of the title will wrap with the icon so the icon does not sit alone
  - Edge Cases/Test Scenarios:
    - Wrapping when it would just be the icon and not any of the words
  - Technical Notes:
    - This is not a usa-link so a special rule will be applied
- [x] Comp 11:
  - Imageless Card AFTER MERGE NCIDS UPGRADE
  - Technical Specifications:
    - External Link icon is center aligned on the title text
    - If the title would wrap, the last word of the title will wrap with the icon so the icon does not sit alone
  - Edge Cases/Test Scenarios:
    - Wrapping when it would just be the icon and not any of the words
  - Technical Notes:
    - This is not a usa-link so a special rule will be applied
- [x] Comp 12:
  - One example of Link in Text that will cover usa-link, Site Alert (all variations), Summary Box, and Usa-prose anchors that don’t have a class applied
  - Technical Specifications:
    - It will look the same
    - The icon will scale to the size of the associated text
  - Edge Cases/Test Scenarios:
    - Test different text sizes/headings 
- [x] Comp 13:
  - One example of links in the Footer
  - Technical Specifications:
    - External Link icon is center aligned vertically on the link text
    - If the link text would wrap, the last word of the title will wrap with the icon so the icon does not sit alone (if possible)
  - Edge Cases/Test Scenarios:
    - Wrapping when it would just be the icon and not any of the words
  - Technical Notes:
    - This is not a usa-link so a special rule will be applied
    - Try to use the mixins that apply all these things to the footer links to make this function
    - Keep standard external link rules in footer, but if someone wants to adjust the behavior they can use the override ability
- [x] Promo Block
- [x] Hero with Primary CTA
- [x] Guide Cards

### Components for tracking purposes only

- [ ] Card
  - [ ] Feature Card (NCIDS)
  - [ ] Feature Card (Prod)
  - [ ] Flag Card (Prod)
  - [ ] Imageless Card (Prod)
- [ ] Anchors (with usa-button class styling) (NCIDS & Prod)
  - [ ] CTA Strip (NCIDS)
  - [ ] CTA Strip (Prod)
  - [ ] Guide Card Default (NCIDS)
  - [ ] Guide Card Default (Prod)
  - [ ] Guide Card Default Card Group (NCIDS)
  - [ ] Guide Card with Image and Description (NCIDS)
  - [ ] Guide Card with Image and Description (Prod)
  - [ ] Hero Default with Button (NCIDS)
  - [ ] Hero Default with Button (Prod)
  - [ ] Hero with CTA (NCIDS)
  - [ ] Hero with CTA (Prod)
  - [ ] Promo Block (NCIDS)
  - [ ] Promo Block (Prod)
  - [ ] Promo Block with Image (NCIDS)
  - [ ] Promo Block with Image (Prod)
  - [ ] Promo Block With Image Alternating Image Right (NCIDS)
  - [ ] Promo Block With Image Alternating Image Right (Prod)
  - [ ] Promo Block Dark Theme (NCIDS)
  - [ ] Promo Block Dark Theme (Prod)
  - [ ] Promo Block Dark Theme With Image (NCIDS)
  - [ ] Promo Block Dark Theme With Image (Prod)
  - [ ] Promo Block Dark Theme With Image Alternating Image Right (NCIDS)
  - [ ] Promo Block Dark Theme With Image Alternating Image Right (Prod)
  - [ ] Button Default Anchor (NCIDS)
  - [ ] Button Default Anchor (Prod)
  - [ ] Button Full Width Anchor (NCIDS)
  - [ ] Button Full Width Anchor (Prod)
  - [ ] Button Icon Left Anchor (NCIDS)
  - [ ] Button Icon Left Anchor (Prod)
  - [ ] Button Icon Right Anchor (NCIDS)
  - [ ] Button Icon Right Anchor (Prod)
  - [ ] Button Big Anchor (NCIDS)
  - [ ] Button Big Anchor (Prod)
  - [ ] Button Small Anchor (NCIDS)
  - [ ] Button Small Anchor (Prod)
  - [ ] Button Outline Anchor (NCIDS)
  - [ ] Button Outline Anchor (Prod)
  - [ ] Button Unstyled Anchor (NCIDS)
  - [ ] Button Unstyled Anchor (Prod)

- [ ] Collection
  - [ ] Collection Default (NCIDS)
  - [ ] Collection Default (Prod)
  - [ ] Collection Media (NCIDS)
  - [ ] Collection Media (Prod)
  - [ ] Collection Calendar (NCIDS)
  - [ ] Collection Calendar (Prod)
  - [ ] Collection Condensed (NCIDS)
  - [ ] Collection Condensed (Prod)
- [ ] Footer
  - [ ] Footer NCI Big (NCIDS)
  - [ ] Footer NCI Big (Prod)
- [ ] Link In Text
  - [ ] Link (NCIDS)
  - [ ] Link (Prod)
  - [ ] Legacy External Link Block (Prod - check to see if this is still a thing)
  - [ ] Content Block (Prod)
  - [ ] Site Alert Default (NCIDS)
  - [ ] Site Alert Default (Prod)
  - [ ] Site Alert Default Dismissible (NCIDS)
  - [ ] Site Alert Default Dismissible (Prod)
  - [ ] Site Alert Emergency Default (NCIDS)
  - [ ] Site Alert Emergency Default (Prod)
  - [ ] Site Alert Emergency Dismissible (NCIDS)
  - [ ] Site Alert Emergency Dismissible (Prod)
  - [ ] Site Alert Emergency Slim (NCIDS)
  - [ ] Site Alert Emergency Slim (Prod)
  - [ ] Site Alert Emergency Slim Dismissible (NCIDS)
  - [ ] Site Alert Emergency Slim Dismissible (Prod)
  - [ ] Site Alert Info Default (NCIDS)
  - [ ] Site Alert Info Default (Prod)
  - [ ] Site Alert Info Dismissible (NCIDS)
  - [ ] Site Alert Info Dismissible (Prod)
  - [ ] Site Alert Info Slim (NCIDS)
  - [ ] Site Alert Info Slim (Prod)
  - [ ] Site Alert Info Slim Dismissible (NCIDS)
  - [ ] Site Alert Info Slim Dismissible (Prod)
  - [ ] Site Alert Slim (NCIDS)
  - [ ] Site Alert Slim (Prod)
  - [ ] Site Alert Slim Dismissible (NCIDS)
  - [ ] Site Alert Slim Dismissible (Prod)
  - [ ] Summary Box (NCIDS)
  - [ ] Summary Box (Prod)
  - [ ] WYSIWYG (Prod)

- [ ] usa Prose
  - [ ] target any anchors that don't have a class attribute applied to them

### Notes

Related Tickets:
- [#2538](https://github.com/NCIOCPL/cgov-digital-platform/issues/2538)
  - External Link on Legacy Feature Cards. This should not need to be addressed - to be confirmed.
- [#2228](https://github.com/NCIOCPL/cgov-digital-platform/issues/2228)
  - External Link on Legacy Feature Cards. This should not need to be addressed - to be confirmed.
- #1773 
  - Notes for supporting external links in the NCIDS
- #1279 
  - Adding external links to appear on the NCIDS Documentation Site as needed
- #579 
  - Original update Buttons with External link ticket
- #357 
  - Original ticket to create external links

**Comment by monika-jaeger** [comment]
We may be able to combine some of these comps. WIP comps here: https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=8661-39439&t=pomAW1wxe94OruVf-1

Will continue working on these on Tuesday.

cc: @blilianyu @andyvanavery31

**Comment by monika-jaeger** [comment]
Update: All use cases accounted for and ready for team review: https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=8661-39439&t=pomAW1wxe94OruVf-1

cc: @andyvanavery31 @blilianyu
