### ISSUE TITLE
Story: Add External Link Icon to NCIDS Buttons

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/ncids#1899]
### Specifications
**Visual**
- External Link icon is center aligned vertically on the button and fixed on the right within the button itself
- If the link text would wrap, the last word of the title will wrap so that the icon stays fixed on the right where it is center aligned vertically 
- If there is an icon in the button and the icon is on the left side, then both the icon and the external link will appear on the button, on the left and right respectively.
- If there is an icon in the button and the icon is on the right side, then the external link will replace the icon on the right side of the button

**Functional**
- If the link text does not have `.gov` it will get an external link icon
- An internal button link can be overridden to have an external link icon
- An external button link can be overridden to not have an external link icon

### Tasks

- [x] Developers to determine which components are unique from being a standard button

**Impacted Components**

**Ensure the following components have the same behavior as buttons**
- [ ] CTA Strip
  - [ ] [Documentation Site CTA Strip Page](https://designsystem-dev.cancer.gov/develop/components/cta-strip)
  - [ ] [Storybook CTA Strip](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-cta-strip-default--default-long) (is it default/test case/modifier/variant?)
- [ ] Guide Card Default
  - [ ] [Doc Site Guide Card Default](https://designsystem-dev.cancer.gov/develop/components/guide-card)
  - [ ] [Storybook Guide Card Default](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-guide-card-default--default)
- [ ] Guide Card with Image and Description
  - [ ] [Doc Site Guide Card with Image and Description](https://designsystem-dev.cancer.gov/develop/components/guide-card)
  - [ ] [Storybook Guide Card with Image and Description](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-guide-card-variants-guide-card-with-image-and-description--single-guide-card-with-image-and-description-without-heading)
- [ ] Hero Default with Button
  - [ ] [Doc Site](https://designsystem-dev.cancer.gov/develop/components/hero)
  - [ ] [Storybook](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-hero-default--with-button)
- [ ] Hero with CTA
  - [ ] [Doc Site](https://designsystem-dev.cancer.gov/develop/components/hero)
  - [ ] [Storybook](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-hero-variants--with-cta)
- [ ] Promo Block
  - [ ] [Doc Site](https://designsystem-dev.cancer.gov/develop/components/promo-block)
  - [ ]  [Storybook Promo Block Default](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-promo-block-default--default)
  - [ ] [Storybook Promo Block with Image](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-promo-block-variants--with-image)
  - [ ]  [Storybook Promo Block With Image Alternating Image Right](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-promo-block-modifiers-alternating-image-right--with-image)
  - [ ]  [Storybook Promo Block Dark Theme](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-promo-block-modifiers-dark-theme--default)
  - [ ]  [Storybook Promo Block Dark Theme With Image](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-promo-block-modifiers-dark-theme--with-image)
  - [ ]  [Storybook Promo Block Dark Theme With Image Alternating Image Right](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-promo-block-modifiers-alternating-image-right--dark-theme-with-image)

**Items for Button**
- [ ] Button
  - [ ] [Doc Site](https://designsystem-dev.cancer.gov/develop/components/button)
  - [ ] [Storybook Button Default Anchor](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-default--anchor)
  - [ ]  [Storybook Button Default Button](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-default--button)
  - [ ] [Storybook  Button Full Width Anchor](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-modifiers-full-width--anchor)
  - [ ]  [Storybook Button Full Width Button](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-modifiers-full-width--button)
  - [ ]  [Storybook Button Icon Left Anchor](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-modifiers-icon-icon-left--anchor)
  - [ ]  [Storybook Button Icon Left Button](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-modifiers-icon-icon-left--button)
  - [ ] [ Storybook Button Icon Right Anchor](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-modifiers-icon-icon-right--anchor)
  - [ ]  [Storybook Button Icon Right Button](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-modifiers-icon-icon-right--button)
  - [ ] [ Storybook Button Big Anchor](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-modifiers-size-big--anchor)
  - [ ]  [Storybook Button Big Button](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-modifiers-size-big--button)
  - [ ]  [Storybook Button Small Anchor](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-modifiers-size-small--anchor)
  - [ ]  [Storybook Button Small Button](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-modifiers-size-small--button)
  - [ ]  [Storybook Button Outline Anchor](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-variants-outline--anchor)
  - [ ]  [Storybook Button Outline Button](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-variants-outline--button)
  - [ ]  [Storybook Button Unstyled Anchor](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-variants-unstyled--anchor)
  - [ ]  [Storybook Button Unstyled Button](https://designsystem-dev.cancer.gov/develop/storybook/?path=/story/components-button-variants-unstyled--button)

### DoR Tasks

- [x] Comps Created
- [ ] Comps Reviewed
  - [x] Developer Review
  - [ ] IA Review
  - [x] Product Review
- [ ] Comps Approved
  - [x] Developer Approval
  - [ ] IA Approval
  - [x] Product Approval
- [x] Acceptance Criteria Drafted
- [x] Scenarios created for YAML
- [ ] Acceptance Criteria Reviewed
  - [x] Developer Review
  - [ ] IA Review
- [ ] Acceptance Criteria Approved
  - [x] Developer Approval
  - [ ] IA Approval

### DoD Tasks

- [ ] Governance Drafted
- [ ] PR Review (see PR for review and comments)
- [ ] Client review with demo

### Technical Notes

- Use the comps here: [Anchor Big](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=8658-9414&m=dev), [Anchor Small](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=8659-35794&m=dev). NOTE: Other buttons appear across the Figma which can be used. The behavior of the buttons and components that use buttons (see list above) will need to be standardized.
- On the [NCIDS Documentation Site Button Page](https://designsystem.cancer.gov/components/button) add:
  - In the Best Practices section, add a subsection which will be the last subsection with the heading "External Links", and in the subsequent paragraph explain how and when to use and add the External Link Icon. In this section, explain how the external links are mostly "auto-magical", and provide an explanation of the override.
  - One more Code Snippet example where the code snippet has 3 buttons. The buttons will all use the `<button class="usa-button">Default</button>` styling as an anchor and:
    - "Link to Google", linking to www.google.com, and the external link icon will appear
    - "External Link Overridden", linking to www.google.com, and the external link icon will not appear
    - "Internal Link Overridden", linking to www.cancer.gov, and the external link icon will appear
- On Storybook:
  - Within the Button folder, add one story to the Test Cases folder:
    - The story will have the following buttons:
      - A `usa-button` anchor, with text "Link to Google", linking to www.google.com, and the external link icon will appear
      - A `usa-button` anchor, with text "External Link Overridden", linking to www.google.com, and the external link icon will not appear
      - A `usa-button` anchor, with text "Internal Link Overridden", linking to www.cancer.gov, and the external link icon will appear
      - A `usa-button` full width anchor, with text "External Link Full Width", linking to www.google.com, and the external link icon will appear
      - A `usa-button` icon left anchor, with text "External Link Icon Left", linking to www.google.com, and the external link icon will appear on the right and the icon on the left will stay there.
      - A `usa-button` icon right anchor, with text "External Link Icon Right", linking to www.google.com, and the external link icon will replace the icon on the right
      - A `usa-button` big anchor, with text "External Link Icon Big", linking to www.google.com, and the external link icon will appear
      - A `usa-button` small anchor, with text "External Link Icon Small", linking to www.google.com, and the external link icon will appear
      - A `usa-button` outline anchor, with text "External Link Icon Outline", linking to www.google.com, and the external link icon will appear
      - A `usa-button`unstyled anchor, with text "External Link Icon Unstyled", linking to www.google.com, and the external link icon will appear

### Acceptance Criteria

```gherkin
Scenario: A button anchor with an external link is viewed on the NCIDS
  Given the external link icon has been added to the NCIDS Documentation Site and NCIDS Storybook for buttons
    And the button anchor link is linked to a url that does not contain `.gov`
  When the button anchor link is a linked url that does not contain '.gov'
  Then the button anchor will appear with the external link icon
    And the icon on the button anchor will match the comp (see links above)
    And the external link icon will remain center aligned vertically on the button that it is on
  When the text of the button wraps
  Then the external link icon will stay on the right side of the button anchor
  When a user wants to override the behavior with an override class
  Then they will override the behavior with an override class
    And the external link icon will not be displayed
  When a user has a button anchor with a link that contains '.gov'
    And they want to override the behavior to include the external link icon
  Then they will override the behavior with an override class
    And the external link icon will be displayed
```
```
