### ISSUE TITLE
Epic: DS Header, Search, Primary Nav, Mobile Menu

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#205]
### Build Header, Primary Nav, Mobile menu component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

## Design Definition of Done
*When all criteria below are met.*

Tickets included in this epic:
- [x] NCIOCPL/ncids#296 
- [x] NCIOCPL/ncids#311
- [x] NCIOCPL/ncids#297 
- [x] NCIOCPL/ncids#298 
- [x] https://github.com/NCIOCPL/ncids/issues/445
- [x] NCIOCPL/ncids#280
- [x] https://github.com/NCIOCPL/ncids/issues/436
- [x] https://github.com/NCIOCPL/ncids/issues/426
- [x] NCIOCPL/ncids#437 
- [x] NCIOCPL/ncids#494 

### Baseline Discovery (add any additional info or links)
- [ ] Heuristics/Best Practices
- [ ] Analytics
*Related links:
- [ ] Accessibility
*Related links:

### Design
- [ ] Design component. Link to design ticket:
- [ ] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [ ] Get component approved by client

### USWDS Component Equivalent
*Is there a USWDS variant?  If we are using it - include the names of the variants, and links to USWDS. If we are creating something new, provide links to what it is based off of in resources section*

- Variant on extended header with megamenu: https://designsystem.digital.gov/components/header/
- Variant on the mobile menu button and search box/button on mobile and desktop. 
- Variant on menu and megamenu

### Styling: 
*Anatomy of a component*
- [x] Use correct spacing (8px grid) size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTA strip

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*

### Invision Mockups: 
*Here goes a URL to or the name of the mockup(s) in inVision to include hex codes, etc.*
  * Desktop: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/454062769_Header_-_Footer_-_Desktop
  * Desktop (no language toggle)::https://publicis.invisionapp.com/share/FA10EYZRDWP2#/458693996_Header_-_Footer_-_Desktop_-_No_Language_Toggle
  * Tablet: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/455696386_Header_-_Footer_-_Tablet_Portrait
  * Tablet (no language toggle): https://publicis.invisionapp.com/share/FA10EYZRDWP2#/458693997_Header_-_Footer_-_Tablet_Portrait_-_No_Language_Toggle
  * Mobile: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/454145716_Header_-_Footer_-_Mobile
  * Mobile (no language toggle): https://publicis.invisionapp.com/share/FA10EYZRDWP2#/458692943_Header_-_Footer_-_Mobile_-_No_Language_Toggle

### Notion Documentation *Additional background information for requirements*:
 *Here goes a URL to notion documentation*

### Notes
*Some complementary notes if necessary:*
* Animations: https://animate.style/ 
* * Megamenu opening: animate__fadeInDown
* * Megamenu closing: animate__fadeOutUp
* Another animation example but slow down from .4s to .8s: https://codepen.io/ahsanrathore/pen/wMRwpZ

### Acceptance Criteria for Header and Primary Nav 
*If a component changes its between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: User is on c.gov page with USA banner
  Given the user is on c.gov page
  Then the USA banner will appear at the very top
```

```gherkin
Scenario: User wants to read content in another language (AC's specified here: https://github.com/NCIOCPL/ncids/issues/164)
  Given User is on a c.gov page with a translation equivalent
  When they click on the language toggle link
  Then the translation for that page will load
     And the label will change to the opposite language
```

```gherkin
Scenario: User wants to read content in another language on mobile
  Given User is on screen 1023px and smaller
     And User is on a c.gov page with a translation equivalent
  Then a pipe will appear between USA text and language toggle text
     And when clicked label will change to the opposite language
```

```gherkin
Scenario: User is on a c.gov page with Covid banner
  Given User is on a c.gov page
  Then the Covid banner will appear beneath the USA banner
  And it will have link(s) NEED TO FINALIZE
```

```gherkin
Scenario: User is on c.gov clicking on logo
  Given User is on c.gov 
  When they click on the logo
  Then the homepage loads
```

```gherkin
Scenario: User is using Search on desktop
  Given the user is on a screen size 1024px and larger
  When the user clicks on the search box
  Then they will be able to enter text
     And autosuggest up to 10 items show
  When the user presses enter or clicks on the search icon
  Then the user will be taken to a search results page
  When the user clicks on suggested item and clicks on the search icon
  Then the user will be taken to a search results page
```

```gherkin
Scenario: User is using Search on Mobile
  Given the user is on a screen size 1023px or less
  Then the search box appears on the right of the Menu button
  When the user clicks on the search box
  Then they will be able to enter text
     And autosuggest up to 10 items show
  When the user presses enter or clicks on the search icon
  Then the user will be taken to a search results page
  When the user clicks on suggested item and clicks on the search icon
  Then the user will be taken to a search results page
```

```gherkin
Scenario: User is activating the megamenu
  Given user is on c.gov on desktop
  When the user clicks on an L1 item in the main nav
  Then the megamenu for that L1 will appear below 
     And the L1 will be highlighted in the main nav
     And the caret for the L1 will flip to point upwards
  When the user hovers on any link in the megamenu
  Then the link will receive an underline
  When the user clicks on the L1 item that appears in the megamenu ("Explore L1")
  Then the landing page will load
     And the megamenu will close
     And an indicator will appear in the main nav under that L1
  When an L2 is clicked on 
  Then the page will load
     And the megamenu will close
     And an indicator will appear in the main nav under the L1 parent
  When an L3 is clicked on 
  Then the page will load
     And the megamenu will close
     And an indicator will appear in the main nav under the L1 parent
  When the user clicks on an L1 item in the main nav
  Then the megamenu for that L1 will appear below 
  When the user clicks outside of the megamenu overlay or on the L1 again
  Then the megamenu will close
  When the user clicks on an L1 item in the main nav
  Then the megamenu for that L1 will appear below 
  When another L1 is clicked on
  Then the megamenu for that L1 will appear below 
```

```gherkin
Scenario: User is on mobile looking for menu
  Given User is a screen size 1023px or less
  Then the Menu button will appear on the left below the logo and to the left of search
```

### Acceptance Criteria for Mobile Menu
```gherkin
DS Scenario: User is on a page and opens and closes the mobile menu 
  Given they are on a screen 1023px and smaller
  When the menu button is clicked
  Then the mobile menu appears, sliding in from the left 
    And covers 80% of the screen
    And has an overlay of the content behind it at rgba(0, 0, 0, 0.2);
    And the current page has an indicator (blue line and bolded blue text)
  When the "x" button is clicked
  Then the mobile menu slides left and disappears
```

```gherkin
CGDP Scenario: User navigating down the nav tree from the home page
  Given they are on a screen 1023px and smaller
    And on the home page
  When the menu button is clicked
  Then the L1 mobile menu appears
  When a nav item is clicked on
  Then that nav label changes to "Explore [nav label]"
    And any children of that nav item are exposed	
  When a child page is clicked on
  Then that nav label changes to "Explore [nav label]"
    And any children of that nav item are exposed	
(repeats)
```

```gherkin
Scenario: Page without child page
  Given the screen is 1023px and smaller
  When the menu button is clicked
  Then the mobile menu appears
    And the menu displays page(s) without child pages
  When a page without children is clicked on
  Then the page loads 
    And the mobile menu disappears
```

```gherkin
Scenario: Page with child page
  Given the screen is 1023px and smaller
  When the menu button is clicked
  Then the mobile menu appears
    And the menu displays page(s) with child pages
    And any page with children has a > icon to the right of the nav label
  When a page with children is clicked on
  Then the menu for that page loads
    And the page label changes to "Explore [nav label]"
    And child pages are shown
```

```gherkin
Scenario: User is on a L1 page and opens the mobile menu to navigate up the nav tree
  Given they are on a screen 1023px and smaller
    And on an L1 page 
  When the menu button is clicked
  Then the mobile menu appears
    And the current page label changes to "Explore [nav label]"
    And the current page has an indicator (blue line and bolded blue text)
    And children of the current page are exposed	
    And the "Main Menu" label with < icon appears top left
  When the "Main Menu" label is clicked
  Then the menu with all L1's is loaded
```

```gherkin
Scenario: User is on a page with children besides an L1 page and opens the mobile menu to navigate up the nav tree
  Given they are on a screen 1023px and smaller
    And on any page at a lower level than L1
    And are on a page with children
  When the menu button is clicked
  Then the mobile menu appears
    And the current page has an indicator (blue line and bolded blue text)
    And the current page label changes to "Explore [nav label]"
    And children of the current page are exposed	
    And the "back" label with < icon appears top left
  When the "back" label is clicked
  Then the menu reloads with the parent of the current page at the top with "Explore [nav label]" label
    And the children of this parent page appear (including the current page)
```

```gherkin
Scenario: User is on a page without children and opens the mobile menu to navigate up the nav tree
  Given they are on a screen 1023px and smaller
    And are on a page without children
  When the menu button is clicked
  Then the mobile menu appears
    And the current page has an indicator (blue line and bolded blue text)
    And the "back" label with < icon appears top left
  When the "back" label is clicked
  Then the menu reloads with the parent of the current page at the top with "Explore [nav label]" label
    And the children of this parent page appear (including the current page)
```

```gherkin
Scenario: User is on a page and opens the mobile menu, then navigates to a child page that has children
  Given they are on a screen 1023px and smaller
    And on a page with children
  When the menu button is clicked
  Then the mobile menu appears
    And the current page has an indicator (blue line and bolded blue text)
    And the current page label changes to "Explore [nav label]"
    And children of the current page are exposed	
    And any page with children has a > icon to the right of the nav label
    And when a visible menu item OR its corresponding > icon is clicked (the whole line is clickable - no split buttons)
  When a child page with children is clicked on
  Then the menu opens to that section
    And the label for the now parent page changes to "Explore [nav label]"
    And any children of the current section are exposed	
  When the parent page is clicked on 
  Then the page loads 
    And the menu closes
```

```gherkin
Scenario: User is on a page and opens the mobile menu, then navigates to a child page that does not have children
  Given they are on a screen 1023px and smaller
    And on a page with children
  When the menu button is clicked
  Then the mobile menu appears
    And the current page has an indicator (blue line and bolded blue text)
    And the current page label changes to "Explore [nav label]"
    And children of the current page are exposed	
    And the "back" label with < icon appears top left
  When a child page is clicked on
  Then the page loads 
    And the menu closes
```

```gherkin
Scenario: User is on a page that has no children and opens the mobile menu to navigate to the parent page
  Given they are on a screen 1023px and smaller
    And on a page without children
  When the menu button is clicked
  Then the mobile menu appears
    And the current page has an indicator (blue line and bolded blue text)
    And siblings of the current page are exposed	
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS (NOTE: THIS IS THE CSS ANYONE, React, Vanilla JS, Angular, Drupal, etc) 
  - [ ] Create `usa-header--nci-extended-mega`partial
  - [ ] Create `usa-megamenu` variant or new block (e.g. `nci-megamenu`
  - [ ] Create new `nci-mobilemenu` block to support everything having to do with the mobile menu 
- [ ] Update NCIDS-JS
  - `DynamicMobileMenu`: This is a component driven by a json file.
     - Click mobile button and open nav area
     - A provided handler will return Promise<NavTree>
     - It may be smart to create a `BaseMobileMenu` class that DynamicMobileMenu derives from for open and closing.
     - We probably need the modal component or some sort of modal manager component.
  - `DynamicMegaMenuComponent` : This handles the showing and closing of mega menus that have a dynamic source
     - A provided handler will return Promise<NavTree>
     - It may be smart to create a `BaseMegaMenu` class that DynamicMobileMenu derives from for open and closing.
  - Also, it should not be an autosuggest in our ncids. Search box goes to search page. Autosuggest will be done as part of CGDP. 
  - Create a `HeaderComponent` wrapper that supports all the functionality.
     - this should wire things up nice and cleanly
  - When the header is initialized we need to wire up button clicks and whatnot with custom event handlers. These event handlers can be used for many different purposes, the chief one being Analytics.
  - DEFINE THE EVENTS!!!
- NCIDS-React will be a separate ticket.

**Comment by anthonycuellar** [comment]
In PR, to be reviewed by @arcepaul @bryanpizzillo

**Comment by anthonycuellar** [comment]
Awaiting on prototype work to be completed.

**Comment by anthonycuellar** [comment]
This is on hold until the navigation prototype testing is completed.

**Comment by anthonycuellar** [comment]
This is on hold until the navigation prototype testing is completed.

**Comment by mworrest** [comment]
Update: Variant on the mobile menu button and search box/button on mobile and desktop. Comps linked in description are updated.

**Comment by VictoriaSunNIH** [comment]
Break this up into an epic - we need to create break this out into tickets for:

-  CSS for extended header, primary nav and mobile menu, and limit the JS on it. 
- megamenu JS is another ticket on CGDP
- mobile nav JS is also CGDP ticket.

**Comment by bennettcc** [comment]
This epic was completed with the launch of MVP1
