### ISSUE TITLE
Build: Page Options

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#215]
### Build Page Options component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

## Design Definition of Done
*When all criteria below are met.*

### Baseline Discovery (add any additional info or links)
- [ ] Heuristics/Best Practices
- [ ] Analytics
*Related links:
- [ ] Accessibility
*Related links:

### Design
- [ ] Design component. Link to design ticket:
- [ ] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [ ] Get component approved by client

### USWDS Component Equivalent
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section* 

- New component

* Related USWDS Links: *Here goes a URL to an existing web page*

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTA strip

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*

### Invision Mockups: 
*Here goes a URL to or the name of the mockup(s) in inVision to include hex codes, etc.*
  * Desktop: https://publicis.invisionapp.com/share/MW1112N6286R#/screens/451934895_What_Is_Cancer-
  * Tablet: same as desktop
  * Mobile: N/A, hide on mobile
    * we default to the native mobile app share functionality 

### Notion Documentation *Additional background information for requirements*:
 *https://www.notion.so/Page-Options-a487250b2be542c4b034b67adddb3fe7

### Notes
*Some complementary notes if necessary:*
* Page options will be on top and bottom (same line as "Return to Top")
* Design ticket: https://github.com/NCIOCPL/ncids/issues/27
* 
#### When to use this component:
Use the print and/or email icons to include a way for users to print or share an email URL of the content page they are currently on. There are two icons available: print and email.  

#### Usability Guidance
These icons should only be used on desktop and tablet displays.  These icons should not be displayed when user is viewing a page on mobile.  The print option should default to open the browser's native print preview. The email option should default to "mailto"

---

### Acceptance Criteria for Behaviors 
*If a component changes its between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: User wants to share a c.gov page on desktop or tablet
  Given User is on a c.gov page on desktop
  Then the print and email icons show in the top right under the main nav and above the footer on the right
    And onclick of the email icon, the native email client appears
    And in the email client the subject is pre-populated with "Information from the National Cancer Institute Web Site"
    And in the email client the body is pre-populated with "I found this information on www.cancer.gov and I'd like to share it with you: [enter URL]

NCI's Web site, www.cancer.gov, provides accurate, up-to-date, comprehensive cancer information from the U.S. government's principal agency for cancer research. If you have questions or need additional information, we invite you to contact NCI’s LiveHelp instant messaging service at https://livehelp.cancer.gov, or call the NCI's Contact Center 1-800-4-CANCER (1-800-422-6237) (toll-free from the United States)."
```

```gherkin
Scenario: User wants to print a c.gov page on desktop or tablet
  Given User is on a c.gov page on desktop or tablet
  Then the print and email icons show in the top right under the main nav and above the footer on the right
    And onclick of the print icon, the print dialogue appears
    And the user has the choice to print the page (print style sheet applied)
```

```gherkin
Scenario: User wants to share or print a c.gov page on mobile
  Given User is on a c.gov page on mobile
  Then no icons appear for sharing or printing options
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - **_At this point there are no requirements/need for a page options React Component_**

**Comment by anthonycuellar** [comment]
For all content types

**Comment by karlikpj** [comment]
Can we use the token names for this type of thing - (primary/secondary/accent) etc - we dont use hex just the token names. thks!

**Comment by russellwyatt** [comment]
Yeah, it pre-populates for a plugin I use in Sketch. But I'll update.

**Comment by VictoriaSunNIH** [comment]
This is on hold for the DS - it is not a component but rather 2 icons on cancer.gov: https://github.com/NCIOCPL/cgov-digital-platform/issues/3256

**Comment by meglake** [comment]
The outstanding question for whether we move forward with this ticket is: Do we create a DS component for page options (i.e. print and email icons) and create a page in the DS with documentation/guidance and code?

Leaning toward this not as DS component but documented as part of #385. Confirming with team then will closing out.

**Comment by sarinapadilla** [comment]
@laurelthrash , closing this ticket as we have [implemented](https://github.com/NCIOCPL/cgov-digital-platform/issues/3256) the page options in `cgov-digital-platform`!
