### ISSUE TITLE
Build: Small Button Variant 

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#231]
### Build Language Toggle component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

## Design Definition of Done
_When all criteria below are met._

### Baseline Discovery (add any additional info or links)
- [x] Heuristics/Best Practices
- [x] Analytics
*Related links:
- [x] Accessibility
*Related links:

### Design
- [x] Design component
- [x] Conduct Design QA
** Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [x] Get component approved by client

### USWDS Component Equivalant
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section*

1. This is essentially the secondary button we've established. Its location on the usa banner is a variation on the banner.

* Related USWDS Links: *https://designsystem.digital.gov/components/button* and https://designsystem.digital.gov/components/banner

### Styling: 
*Anatomy of a component*
- [x] Use correct spacing (8px grid)
Size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Only use this small button variant when space is at a premium.

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTS strip

1. Dont: Use more than 1 button in usa banner (What if there are multiple languages?)
2. Do: Use the secondary color of the palette.
3. Dont: Show button if there is no translation for the page.

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*

1. The existing functionality will remain. The button will link to the translation of the page. If there is no translated equivalent of the page, then the button would not appear. The button would get the states (hover/active) that are already defined.

### Invision Mockups: 
*Here goes a URL to or the name of the mockup(s) in inVision to include hex codes, etc.*
  * Desktop: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/454062769_Header_-_Footer_-_Desktop
  * Tablet: https://publicis.invisionapp.com/d/main#/console/21179883/455696386/preview
  * Mobile: https://publicis.invisionapp.com/d/main#/console/21179883/454145716/preview

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by anthonycuellar** [comment]
test

**Comment by mworrest** [comment]
FYI the style will likely change based on an email Fedora sent today:

The font for the Spanish toggle is pretty small. Especially on the desktop version, it looks like the font size is limited by the height of the “official website” header at the top of the page. I know that when the DOJ Civil Rights Division complaint portal was redesigned recently, they also put the non-English language indicators in the official website header, but there they changed the background color to black and made the text yellow so it would stand out more. I know those are not our colors but how can we make the toggle more noticeable? Ideally, it should be a button.
 
BTW, this is still in draft, but these are the guidelines from the multilingual group so far:
Websites with 2 languages:


Format Style:
Button 
Placement: 
Top right corner in all screen resolutions for consistency. Users accessing the site with assistive technology will have the option to switch to their preferred language before they read the rest of the content on the page.
Implementation/Functionality:
For easier implementation, make the language access button a single/independent element.
The button should take users to an equivalent page (toggle between pages with the same/similar content, or other pertinent resources)
Accessibility/Usability:
There should be enough color contrast between the button, the text inside the button, and the background.
Recommendation: provide a visual element that shows when text is a link. Example: permanent underline text or when hovering.
If the text visually will be presented as a button but coded as a link, it is recommended to add ARIA role="button" so that screen readers announce it as a button. Additionally, JavaScript will also need to be added so that keyboard users can activate the button using both the Enter and Spacebar keys. See for reference: https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html?cm_mc_uid=79615163929714381992345&cm_mc_sid_50200000=1449171451
The language of the page should be identified using the HTML lang attribute (<html lang='en'>, for example) Please see the link for reference https://www.w3.org/WAI/WCAG21/Techniques/html/H57
If the page is presented in the English language and some content/words are presented in different languages, then the second language should be defined using the lang attribute on a <span> tag wrapping the relevant text (e.g. “<span lang="es">Hola</span> means Hello”). Please see the link for reference  https://www.w3.org/WAI/WCAG21/Techniques/html/H58
 
Iconography:
Do not use any icons/graphics as they may mean/represent different things to people that share a language, but not a culture.
Languages:
Capitalization: The name of the language on the button should be capitalized. Example: English, Spanish, Italian.

**Comment by bryanpizzillo** [comment]
@VictoriaSunNIH How does this related to #261 and can this be closed?

**Comment by mworrest** [comment]
This is completed from a design standpoint.
