### ISSUE TITLE
Discovery: Content Features - Article

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#24]
# Discovery for Content Feature - Article

Understanding and analysis of the components that make up an article.

Description of what is to be accomplished.
- Syndication text
- Public Use text
- Date attribution
- References
- On This Page
- Intro Text

**Outcomes**

- Understanding of features
- Define problems to solve

### Elements of Feature
_Should be filled out after the first working session to determine labels_

> **ESTIMATE** TBD

### Resources

* Design ticket on Github: https://github.com/NCIOCPL/ncids/issues/63
* Article Discovery Mural: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1613764635058/fe62055ca614f0dbd6fc405f622ef410a9b9119e
* Platform Wiki - Article: https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Article

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] Inventory and analysis of content type features (Creation of article with all possible features, screen captured)
- [x] Creation of Mural board to capture discovery (logical groupings of sub-features, grids for analysis)

### Sub-Tasks
- [ ] Heuristic review of feature and sub-features
- [ ] Secondary research compilation and synthesis
- [ ] Technical impacts analysis
- [ ] Analytics data analysis and synthesis
- [ ] Identification of potential USWDS equivalents
- [x] Drupal reporting on use of feature

### Working Sessions
- inventory Mural review  (30 minutes)
- Analysis review and problem identification (1-2 hours)

### Notes

*Some complementary notes if necessary:*
* > 
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by claireblaustein** [comment]
Moved content into https://github.com/NCIOCPL/ncids/issues/62 - establishing as kickoff ticket with sub-tickets for specific design and discovery work.
