### ISSUE TITLE
Discovery: Cards

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#25]
# Cards Discovery

Understanding and analysis of cards throughout the site.

**Outcomes**

- Understanding of features
- Define problems to solve

  

> **ESTIMATE** TBD

### Resources

* Cards Discovery Mural: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1611677677716/6fc9296c74966cb4950edd800e44c40358e8ec6d
* USWDS: https://designsystem.digital.gov/components/card/

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] Inventory and analysis of content type features (Creation of article with all possible features, screen captured)
- [x] Creation of Mural board to capture discovery (logical groupings of sub-features, grids for analysis)

 
### Sub-Tasks
- [x] Heuristic review of feature and sub-features
- [x] Secondary research compilation and synthesis
- [x] Technical impacts analysis
- [x] Analytics data analysis and synthesis
- [x] Identification of potential USWDS equivalents
- [ ] Drupal reporting on use of features

### Working Sessions

- inventory Mural review  (30 minutes)
- Analysis review and problem identification (1-2 hours)

### Notes
*Some complementary notes if necessary:*
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

### Design Tickets
*Add links to the design tickets:*
