### ISSUE TITLE
Prototype: Cancer.gov Redesign Mobile Nav

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#255]
### Build mobile nav component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

### Variants Information
*Is there a USWDS variant?  Not really, the usa-nav is the mega menu content displaying differently on mobile. Our mobile nav will work in a much different way with different elements. https://designsystem.digital.gov/components/header/#extended-header-with-megamenu

### Invision Mockups: 
*Here goes a URL to or the name of the mockup(s) in inVision to include hex codes, etc.*
  * Desktop: N/A
  * Tablet: N/A
  * Mobile: https://publicis.invisionapp.com/share/4G11TDSW58SE#/screens/459263421

### Notion Documentation *Additional background information for requirements*:
N/A

### Notes
*Some complementary notes if necessary:*
* parent ticket (build for design system) https://github.com/NCIOCPL/ncids/issues/205

### Acceptance Criteria for Behaviors 
*If a component changes its between breakpoints, or things show/hide, that gets captured here* 

### Acceptance Criteria for Mobile Menu
```gherkin
Scenario: User is on a page and opens and closes the mobile menu
  Given they are on a screen 1023px and smaller
  When the menu button is clicked
  Then the mobile menu appears, sliding in from the left 
    And covers 80% of the screen
    And has an overlay of the content behind it at rgba(0, 0, 0, 0.2);
    And the current page has an indicator (blue line and bolded blue text)
  When the "x" button is clicked
  Then the mobile menu slides left and disappears
```

```gherkin
Scenario: User navigating down the nav tree from the home page
  Given they are on the "tablet" breakpoint and below (a screen 1023px and smaller)
    And on the home page
  When the menu button is clicked
  Then the L1 mobile menu appears
  When a nav item is clicked on
  Then that nav label changes to "Explore [nav label]"
    And any children of that nav item are exposed	
  When a child page is clicked on
  Then that nav label changes to "Explore [nav label]"
    And any children of that nav item are exposed	
(repeats)
```

```gherkin
Scenario: Page without child page
  Given they are on the "tablet" breakpoint and below (a screen 1023px and smaller)
  When the menu button is clicked
  Then the mobile menu appears
    And the menu displays page(s) without child pages
  When a page without children is clicked on
  Then the page loads 
    And the mobile menu disappears
```

```gherkin
Scenario: Page with child page
  Given they are on the "tablet" breakpoint and below (a screen 1023px and smaller)
  When the menu button is clicked
  Then the mobile menu appears
    And the menu displays page(s) with child pages
    And any page with children has a > icon to the right of the nav label
  When a page with children is clicked on
  Then the menu for that page loads
    And the page label changes to "Explore [nav label]"
    And child pages are shown
```

```gherkin
Scenario: User is on a L1 page and opens the mobile menu to navigate up the nav tree
  Given they are on the "tablet" breakpoint and below (a screen 1023px and smaller)
    And on an L1 page 
  When the menu button is clicked
  Then the mobile menu appears
    And the current page label changes to "Explore [nav label]"
    And the current page has an indicator (blue line and bolded blue text)
    And children of the current page are exposed	
    And the "Main Menu" label with < icon appears top left
  When the "Main Menu" label is clicked
  Then the menu with all L1's is loaded
```

```gherkin
Scenario: User is on a page with children besides an L1 page and opens the mobile menu to navigate up the nav tree
  Given they are on the "tablet" breakpoint and below (a screen 1023px and smaller)
    And on any page at a lower level than L1
    And are on a page with children
  When the menu button is clicked
  Then the mobile menu appears
    And the current page has an indicator (blue line and bolded blue text)
    And the current page label changes to "Explore [nav label]"
    And children of the current page are exposed	
    And the "back" label with < icon appears top left
  When the "back" label is clicked
  Then the menu reloads with the parent of the current page at the top with "Explore [nav label]" label
    And the children of this parent page appear (including the current page)
```

```gherkin
Scenario: User is on a page without children and opens the mobile menu to navigate up the nav tree
  Given they are on the "tablet" breakpoint and below (a screen 1023px and smaller)
    And are on a page without children
  When the menu button is clicked
  Then the mobile menu appears
    And the current page has an indicator (blue line and bolded blue text)
    And the "back" label with < icon appears top left
  When the "back" label is clicked
  Then the menu reloads with the parent of the current page at the top with "Explore [nav label]" label
    And the children of this parent page appear (including the current page)
```

```gherkin
Scenario: User is on a page and opens the mobile menu, then navigates to a child page that has children
  Given they are on the "tablet" breakpoint and below (a screen 1023px and smaller)
    And on a page with children
  When the menu button is clicked
  Then the mobile menu appears
    And the current page has an indicator (blue line and bolded blue text)
    And the current page label changes to "Explore [nav label]"
    And children of the current page are exposed	
    And any page with children has a > icon to the right of the nav label
    And when a visible menu item OR its corresponding > icon is clicked (the whole line is clickable - no split buttons)
  When a child page with children is clicked on
  Then the menu opens to that section
    And the label for the now parent page changes to "Explore [nav label]"
    And any children of the current section are exposed	
  When the parent page is clicked on 
  Then the page loads 
    And the menu closes
```

```gherkin
Scenario: User is on a page and opens the mobile menu, then navigates to a child page that does not have children
  Given they are on the "tablet" breakpoint and below (a screen 1023px and smaller)
    And on a page with children
  When the menu button is clicked
  Then the mobile menu appears
    And the current page has an indicator (blue line and bolded blue text)
    And the current page label changes to "Explore [nav label]"
    And children of the current page are exposed	
    And the "back" label with < icon appears top left
  When a child page is clicked on
  Then the page loads 
    And the menu closes
```

```gherkin
Scenario: User is on a page that has no children and opens the mobile menu to navigate to the parent page
  Given they are on the "tablet" breakpoint and below (a screen 1023px and smaller)
    And on a page without children
  When the menu button is clicked
  Then the mobile menu appears
    And the current page has an indicator (blue line and bolded blue text)
    And siblings of the current page are exposed	
```
TODO: Add scenario about desktop and up being hidden.

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] Prototype Navigation HTML/JS Setup https://github.com/NCIOCPL/ncids/issues/263

### Tasks
- [ ] Update Prototype site with new Mobile Navigation
  - [x] Create temp Json/Data for consumption.
  - [x] Create new HTML/Dom that will be generated 
     - [x] Mock CSS and styles to match USWDS/NCIDS
     - [x] Mock HTML that needs to be generated.
  - [x] Create new vanilla JS that will activate navigation for display.
  - [ ] Integrate with Gatsby Prototype
    - [ ] Update and integrate GraphQL for new mobile nav tree.
    - [ ] Update Page Layouts
    - [ ] Update styles

**Comment by VictoriaSunNIH** [comment]
Closing this as completed, it is now in testing.
