### ISSUE TITLE
Build: Text Input Component

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#256]
### Build text input component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

## Design Definition of Done
*When all criteria below are met.*

### Baseline Discovery (add any additional info or links)
- [x] Heuristics/Best Practices
- [x] Analytics
*Related links:
- [x] Accessibility
*Related links:

### Design
- [x] Design component
- [x] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [x] Get component approved by client

### USWDS Component Equivalent
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section*
* Related USWDS Links: https://designsystem.digital.gov/components/text-input/

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid)
Size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTA strip

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*
*For any instance that is not in the footer the error state color should be BB0E3D.

### InVision Mockups: 
*Here goes a URL to the mockup(s) in InVision that include specs*
  * https://publicis.invisionapp.com/share/NF11XLA2BMJT

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by VictoriaSunNIH** [comment]
Closing - this has been completed and merged
