### ISSUE TITLE
Build: Button Component

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#257]
### Build button component based on design specs/requirements documented in this ticket

> **ESTIMATE** 3

## Design Definition of Done
*When all criteria below are met.*

### Baseline Discovery (add any additional info or links)
- [ ] Heuristics/Best Practices
- [ ] Analytics
*Related links:
- [ ] Accessibility
*Related links:

### Design
- [ ] Design component. Link to design ticket:
- [ ] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [ ] Get component approved by client

### USWDS Component Equivalent
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section*
* Related USWDS Links: *Here goes a URL to an existing web page*

### Variants Information
The USWDS is currently working on implementing a number of additional buttons. In the sketch file, they have some buttons not documented on the site, as well as not fully built out either. The variants to be built are:
* `usa-button`
* `usa-button--secondary`
* `usa-button--accent-cool`
* `usa-button--accent-warm`
* `usa-button--base`
* `usa-button--outline`
* `usa-button--outline usa-button--inverse`
* `usa-button--big`
* `usa-button--unstyled`

These can be found on https://designsystem.digital.gov/components/button/

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTA strip

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*

### InVision: 
  * DSM link: *insert link here, or enter N/A if not needed*
  * Desktop mockup: https://publicis.invisionapp.com/share/A8UB2W74PRN
  * Tablet mockup: N/A
  * Mobile mockup: N/A

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create Button Component that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - src/components/usa-button/_all.scss
  - src/components/usa-button/_default.scss
  - src/components/usa-button/_accent-cool.scss
  - src/components/usa-button/_accent-warm.scss
  - src/components/usa-button/_outline.scss
  - src/components/usa-button/_outline-inverse.scss
  - src/components/usa-button/_base.scss
  - src/components/usa-button/_secondary.scss
  - src/components/usa-button/_big.scss
  - src/components/usa-button/_unstyled.scss
  - src/components/usa-button/internal/_shared.scss
  - src/components/usa-button/internal/_accent-cool.scss
  - src/components/usa-button/internal/_accent-warm.scss
  - src/components/usa-button/internal/_outline.scss
  - src/components/usa-button/internal/_outline-inverse.scss
  - src/components/usa-button/internal/_base.scss
  - src/components/usa-button/internal/_secondary.scss
  - src/components/usa-button/internal/_big.scss
  - src/components/usa-button/internal/_unstyled.scss

**Comment by mworrest** [comment]
These are the updated colors. I am having issues with my sapient invision account so sorry I had to create a new prototype: https://invis.io/8G11WK06XBA3

**Comment by mworrest** [comment]
@olitharp-nci we have recently added another outline button using the secondary color.
