### ISSUE TITLE
Build: Site Alert Component

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#262]
### Build alert component based on design specs/requirements documented in this ticket

COVID AND SHUTDOWN ALERTS SHOULD BE IN THIS TICKET

> **ESTIMATE** 3 (this may have been underestimated 5)
Need to complete all tests (PR changes were required) - estimated SP left: 2

## Design Definition of Done
*When all criteria below are met.*

### Baseline Discovery (add any additional info or links)
- [x] Heuristics/Best Practices
- [x] Analytics
*Related links:
- [x] Accessibility
*Related links:

### Design
- [x] Design component
- [x] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [x] Get component approved by client

### USWDS Component Equivalent
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section*

Yes this is a variant on the standard-informational-site-alert: https://designsystem.digital.gov/components/site-alert/

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid)
Size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

- Use the blue site alert for the COVID content.
- Use the red site alert for government shutdowns.
- When there is more than one link, the site alert becomes a drop down that can be opened and closed to reveal links in a bulleted list (separated by columns for desktop). 
- Users need the opportunity to close a site alert so that it no longer appears during their time on the site. This should be an optional setting in drupal. Ex: gov shutdown site alert would not get the "x".
- Site alerts include the icons from USDWS.

### From USWDS:
**When to use the site alert component**
Critical system notifications. Use a site alert to deliver a static system status update, such as notices about unavailable services or content. Site alerts should appear by default and not in response to an action.
Messages that should be displayed on every page. A site alert makes critical information obvious and findable on every page.

**When to consider something else**
Responding to user actions. Use the alert component for page-level validation messages (like error messages on a form) or to inform a user that a task was completed successfully.
Validating form input. On most forms, especially longer forms, validation messages should appear inline with error messages at the top of the form.

**Usability guidance**
Place prominently. Use a full-width site alert positioned near the top of the page so it’s one of the first things users see.
Avoid stacking multiple site alerts. If you need to convey more than one message, provide a list of links within a single site alert instead of multiple, stacked alerts.
Avoid overwhelming use of color. It may be tempting to make heavy use of bright red or orange to draw attention to an emergency-related site alert. However, these colors can produce strong negative emotional reactions such as fear or panic. Positioning the banner at the top of the screen provides enough weight that such strong colors may not be necessary.

**Accessibility**
Don’t visually hide alert messages and then make them visible when they are needed. Users of older assistive technologies may still be able to perceive hidden alert messages. Fully remove alert messages when they’re not needed.

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTA strip
1. Use the COVID alert according to NCI's policy. Do not change icons, text, colors, links, or functionality.
2. Use the Shutdown alert according to NCI's policy. Do not change icons, text, colors, links, or functionality.

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*
When the arrow is clicked on, the alert will expand and collapse. When the x is clicked on, the alert will disappear for the remainder of the users' session. The alerts appear beneath the USA banner. When the shutdown banner is added, it appears beneath the USA banner and above other alerts that may be present.

### InVision Mockups: 
*Here goes a URL to the mockup(s) in InVision that include specs*
  * Navigate through different breakpoints: https://publicis.invisionapp.com/project/21811368
  ** The site alert components have been added to the DSM: https://publicis.invisionapp.com/dsm/publicis/nci-ds-new

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: User expands and collapses a site alert
  Given user is on a Cancer.gov page (or another NCI site)
    And the site alert has multiple links under it
    And they haven't closed out the site alert previously
  Then the site alert appears and is collapsed
  When user clicks on down arrow in the site alert
  Then the site alert expands and links are exposed
    And the arrow icon changes direction to an upward facing arrow
  When user clicks on up arrow 
  Then site alert collapses 
    And the arrow icon changes direction to a downward facing arrow
```

```gherkin
Scenario: User explores site alert links
  Given user is on a Cancer.gov page (or another NCI site)
    And the site alert has multiple links under it
    And they haven't closed out the site alert previously
  When user clicks on down arrow in the site alert
  Then the site alert expands and links are exposed
    And the arrow icon changes direction to an upward facing arrow
  When user hovers on link in site alert
  Then hover state is applied to link
  When user clicks on an external link in the site alert
  Then the page is loaded
When user clicks on a cgov link 
Then the page loads
    And site alert is collapsed
```

```gherkin
Scenario: User removes site alert
  Given user is on a Cancer.gov page (or another NCI site)
    And they haven't closed out the site alert previously
 When user clicks on the x icon
 Then the site alert disappears
 When user navigates to another Cancer.gov page
 Then the site alert does not appear
```

```gherkin
Scenario: Shutdown site alert does not have multiple links
  Given user is on a Cancer.gov page (or another NCI site)
    And the shutdown site alert is added
    And the site alert does not have multiple links under it
  Then the shutdown site alert appears beneath the USA banner and above any other site alerts
```

---

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - site banner with no header 
  - default: banner without collapsible, not shouty
  - variant: `.usa-site-alert--info`
  - variant: `.usa-site-alert--emergency`
  - not real variant: collapsible
    - include new element: `.usa-alert__nci-list`: creates column lists
- [ ] Update NCIDS-JS
  - create nci collapsing site alert
- [ ] Create new ticket for React
- [ ] Create Storybook regression tests

**Comment by mworrest** [comment]
We believe this is done from a design standpoint.

**Comment by VictoriaSunNIH** [comment]
Clarifying:

- Slim can never be expandable/collapsible.  
- Full can be expanded/collapsed.
- A site alert can be made dismissible, as an add-on available for both slim and full.
