### ISSUE TITLE
Build: Modal Component

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#267]
### Build a modal component for use by things such as dictionary popups.

> **ESTIMATE** 3

## Design Definition of Done
*When all criteria below are met.*

### Baseline Discovery (add any additional info or links)
- [ ] Heuristics/Best Practices
- [ ] Analytics
*Related links:
- [ ] Accessibility
*Related links:

### Design
- [ ] Design component. Link to design ticket:
- [ ] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [ ] Get component approved by client

### USWDS Component Equivalent
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section*
* Yes, variant on `usa-modal--lg`
* Related USWDS Links: https://designsystem.digital.gov/components/modal/

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTA strip

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*

### Notes
* This is for a generic "content" modal that is a pop-up with contents, no buttons.
* We should document multiple uses:
   * What does this look like for just a "popup" (only usa-prose)?
   * What does this look like for the modal large with the header, prose and footer?

### InVision: 
  * DSM link: *insert link here, or enter N/A if not needed*
  * Desktop mockup: https://publicis.invisionapp.com/share/QV11KIJ53XEA#/457141692_Immunotherapy_To_Treat_Cancer_-_Desktop_Open_Modal
  * Tablet mockup: @mworrest please provide if needed
  * Mobile mockup: @mworrest please provide if needed

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: On click of close it closes the window
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]

Scenario: user can hit escape to get it out
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]

Scenario: user can click outside to close
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
    
Scenario: Content is larger than the window, should show scrollbar for `usa-prose` content
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks

- [ ] Update Documentation Site (docs)
  - [ ] Create Modal Component that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (JS Tab) (for vanilla js) What is the js library to import?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - src/components/usa-modal/_default.scss
  - src/components/usa-modal/_large.scss
  - src/components/usa-modal/_nci_large.scss
  - src/components/usa-modal/internal/_shared.scss
  - src/components/usa-modal/internal/_large.scss
  - src/components/usa-modal/internal/_nci-large.scss
- [ ] Update NCIDS-JS
  - path/to/component/modal.js
  - see uswds/src/js/components/modal.js
- [ ] Create NCIDS-React ticket

**Comment by meglake** [comment]
Closing, will create new ticket with actual requirements when this becomes part of a release.
