### ISSUE TITLE
Build: Tooltip (not tooltip) Component

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#268]
### Build a Tooltip (not tooltip) component for use by things such as dictionary popups.
> **ESTIMATE** 5

## Design Definition of Done
*When all criteria below are met.*

### Baseline Discovery (add any additional info or links)
- [ ] Heuristics/Best Practices
- [ ] Analytics
*Related links:
- [ ] Accessibility
*Related links:

### Design
- [ ] Design component. Link to design ticket:
- [ ] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [ ] Get component approved by client

### USWDS Component Equivalent
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section*

So the USWDS tooltip is NOT to be used in this way. It ONLY displays the "title" attribute how you asked for it. We need to make a new name, hoverbox? This is pretty much a re-implementation of the jqueryUI Tooltip with stylings from ncids.
* Related USWDS Links: *Here goes a URL to an existing web page*

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTA strip

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*

### InVision: 
  * DSM link: *insert link here, or enter N/A if not needed*
  * Desktop mockup: https://publicis.invisionapp.com/share/QV11KIJ53XEA#/458803390_Immunotherapy_To_Treat_Cancer_-_Desktop_Dictionary_Tooltip
  * Tablet mockup: @mworrest please provide if needed
  * Mobile mockup: Hide tooltip on mobile breakpoint screen.

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: On hover it displays
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]

Scenario: Edge boundaries (making sure it does not appear offscreen) are handled.
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]

Scenario: on mobile breakpoint "tooltip" should not show
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create Tooltip-Not-Tooltip Component (name TBD) that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (JS Tab) (for vanilla js) What is the js library to import?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
- [ ] Update NCIDS-CSS
  - src/components/nci-tooltip-not-tooltip/_tooltip-not-tooltip.scss
  - src/components/nci-tooltip-not-tooltip/internal/_shared.scss
- [ ] Update NCIDS-JS
  -  /path/to/component/nci-tooltip-not-tooltip.js
  - see uswds/src/js/components/tooltip.js
    - on mouseover/hover
    - top/bottom/right/left positioning
    - corrective positioning for close-to-edge scenario
    - margin offsets
- [ ]  Create new ticket for NCIDS-React
- [ ]  Give Tooltip-Not-Tooltip a proper name

**Comment by andyvanavery31** [comment]
Reevaluate this ticket for if it will be made in the future. Not currently in scope for NCIDS Launch nor any of the Redesign launches.

**Comment by sarinapadilla** [comment]
Closing this ticket, and we'll open a new ticket for whenever we need to implement something for the glossary pop-up.
