### ISSUE TITLE
Discovery: Search Bars

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#28]
# Search Bars Discovery

Looking at search bars across the site 

Partial List
- primary navigation
- Clinical Trials search page
- Dictionary (search page and results page)
- Resources for researchers

**Intended Outcomes**

- Understanding of features
- Define problems to solve

> **ESTIMATE** TBD

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Inventory and analysis of content type features (Creation of article with all possible features, screen captured)
- [ ] Creation of Mural board to capture discovery (logical groupings of sub-features, grids for analysis)

 
### Sub-Tasks
- [ ] Heuristic review of feature and sub-features
- [ ] Secondary research compilation and synthesis
- [ ] Technical impacts analysis
- [ ] Analytics data analysis and synthesis
- [ ] Identification of potential USWDS equivalents
- [ ] Drupal reporting on use of features

### Design Tickets
*Add links to the design tickets:*

### Research Tickets
*Add links to the design tickets:*

### Analytics Tickets
*Add links to the design tickets:*

### Dev Tickets
*Add links to the design tickets:*

### Artifacts & Resources

* Modular Features Discovery Mural: 
* USWDS: 

### Working Sessions

- inventory Mural review  (30 minutes)
- Analysis review and problem identification (1-2 hours)

### Notes
*Some complementary notes if necessary:*
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by claireblaustein** [comment]
duplicative ticket - closing
