### ISSUE TITLE
Build: Auto Complete 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#280]
### Build autosuggest component based on design specs/requirements documented in this ticket

> **ESTIMATE** 8

What does the API look like for the autosuggest? How does this thing work and how do people interact with it.

### Design
- [ ] #277  

### InVision: 
  Approved comps: https://publicis.invisionapp.com/console/Header-&-Footer-Wireframes-cl17806xjx3ho01x42xix33gc?sortBy=1&sortOrder=1&viewLayout=2

### Acceptance Criteria for Behaviors 

```gherkin

Scenario: Developer can set the number of characters
  When initializing the autocomplete component, developers to select how many characters are needed at a minimum for the autocomplete to show.  
```

```gherkin
Given the number of characters has been set to zero,
Then auto-suggest appears as soon as a user starts typing
And displays at least ten matches with the characters entered highlighted within the suggestions
When the user selects one of the suggestions
Then the field is populated with selection
And suggestions are removed
```

```gherkin
Scenario: Minimum is set to 3
Given the number of characters has been set to 3,
Then when the user types 1-2 characters, a message stating "Please enter 3 or more characters" will display
When the user has typed 3 or more characters
  Then autosuggest starts appearing
  And displays at least ten matches with the characters entered highlighted within the suggestions
When the user selects one of the suggestions
Then the field is populated with selection
And suggestions are removed
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by VictoriaSunNIH** [comment]
@russellwyatt - when we have the autosuggest, and we want to clear out the element, is the "x" always present? Will autosuggests always need the "clear" element associated with it, or should it be associated with the input field?

**Comment by russellwyatt** [comment]
@VictoriaSunNIH the clear icon should be associated with the input field. It is not clearing auto-suggestion rather the query that was entered.

**Comment by meglake** [comment]
Notes from 3/1/22 meeting:

- "X" to clear search box when any amount of text in textbox should show on mobile and desktop
- Input type = search gets the "X" 
- Auto complete list don't sort in any particular way
- up to 10 results in auto complete list (no scroll bar)
- Invision link: https://publicis.invisionapp.com/project/21910496

**Comment by meglake** [comment]
@olitharp-nci to design the API for the component

**Comment by meglake** [comment]
@arcepaul to add accessibility and documentation info in this ticket

**Comment by bennettcc** [comment]
7/12: 2 SP accomplished in S33, carry over 3SP for S34

**Comment by meglake** [comment]
@arcepaul the translation for "suggestions found, use up and down arrows to review" for screen readers is: Sugerencias automáticas. Use flecha arriba o flecha abajo para escuchar las opciones.

**Comment by bennettcc** [comment]
@arcepaul I updated the ticket desc with the official comp: https://publicis.invisionapp.com/console/Header-&-Footer-Wireframes-cl17806xjx3ho01x42xix33gc?sortBy=1&sortOrder=1&viewLayout=2

**Comment by meglake** [comment]
Per team meeting on 9/13 - around 479 and below when a user clicks into the search box to search, the search box entry expands and covers the menu button, no modal. Ticket #558 needs to be addressed before autocomplete can be completed.

**Comment by arcepaul** [comment]
Add the ability to specify a fixed width for the listbox
