### ISSUE TITLE
DS: Accordion Pattern

### ISSUE THREAD

**Issue by russellwyatt** [NCIOCPL/ncids#286]
### Build xxx component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

## Design Definition of Done
When all criteria below are met.

### Baseline Discovery (add any additional info or links)
- [ ] Heuristics/Best Practices
- [ ] Analytics
*Related links:
- [ ] Accessibility
*Related links:

### Design
- [ ] Design component
- [ ] Conduct Design QA
** Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [ ] Get component approved by client

### USWDS Component Equivalant
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section*
* Related USWDS Links: *Here goes a URL to an existing web page*

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid)
Size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTS strip

### Behaviors
*Summary of state changes and behavoirs. AC's are more detailed.*

### Invision Mockups: 
*Here goes a URL to or the name of the mockup(s) in inVision to include hex codes, etc.*
  * Desktop: *insert link here, or enter N/A if not needed*
  * Tablet: *insert link here, or N/A if not needed*
  * Mobile: *insert link here, or N/A if not needed*

### Acceptance Criteria for Behaviors 
*If a component changes its between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)
