### ISSUE TITLE
Build: CSS for extended header, primary nav and mobile menu

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#296]
### Build extended header, primary nav and mobile menu in CSS

> **ESTIMATE** 5
Remaining SP: 3

### USWDS Component Equivalent
While the Header/Primary Navigation is an existing component, the mobile menu is a NCI unique component that has no USWDS equivalent.
https://designsystem.digital.gov/components/header/

### InVision: 
  * DSM link: N/A
  * Desktop default: (https://publicis.invisionapp.com/share/FA10EYZRDWP2#/screens/454062769_Header_-_Footer_-_Desktop)
  * Tablet default: (https://publicis.invisionapp.com/share/4G11TDSW58SE#/screens/459263421)
  * Mobile default: (https://publicis.invisionapp.com/share/4G11TDSW58SE#/screens/459263421)
  * Menu hover: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/463066988_About_Cancer_Hover
  * Megamenu expanded: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/463070401_About_Cancer_Nav_With_Megamenu
  * Menu active: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/463070090_About_Cancer_OnState
  * Megamenu Explore link/subsection header/item hover: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/463070783_About_Cancer_Nav_With_Megamenu_-hover 
  * SWS button hover: https://publicis.invisionapp.com/share/FA10EYZRDWP2#/463072382_Autosuggest_Sitewide_Search_-_Desktop_Hover

### Tasks
- [x] Create NCIDS-CSS
  - [x] _nci-header.scss
  - [x] _nci-navigation.scss
  - [x] _nci-navigation-mobile.scss
- [x] Update NCIDS-JS
   * Create the NciExtendedMegaMenu class with:
      * `public static create()`
      * `constructor`
      * `public unregister()`
         * some logging and TESTS to know the constructor is being called.
         * some sort of console log in the consructor saying it was created
         * some sort of console.log in unregister saying it was unregistered.

How to create a component class https://github.com/NCIOCPL/ncids/wiki/Technical-JS-Component-Design-Overview

### Acceptance Criteria
```gherkin
Scenario: User is on c.gov page with USA banner
  Given the user is on c.gov page
  Then the USA banner will appear at the very top
```

```gherkin
Scenario: User wants to read content in another language (AC's specified here: https://github.com/NCIOCPL/ncids/issues/164)
  Given User is on a c.gov page with a translation equivalent
  When they click on the language toggle link
  Then the translation for that page will load
     And the label will change to the opposite language
```

```gherkin
Scenario: User wants to read content in another language on mobile
  Given User is on screen 1023px and smaller
     And User is on a c.gov page with a translation equivalent
  Then a pipe will appear between USA text and language toggle text
     And when clicked label will change to the opposite language
```

```gherkin
Scenario: User is on a c.gov page with Covid banner
  Given User is on a c.gov page
  Then the Covid banner will appear beneath the USA banner
  And it will have link(s) NEED TO FINALIZE
```

```gherkin
Scenario: User is on c.gov clicking on logo
  Given User is on c.gov 
  When they click on the logo
  Then the homepage loads
```

### Tasks
Storybook Stories to be created

- **Desktop**
  - [x] Default No JS
  - [x] No JS + Hover
  - [x] Default with JS
  - [x] Primary state Hover
  - [x] Primary state Active
  - [x] Logo state Active
  - [x] Megamenu state Expanded
  - [x] Megamenu Explore Link state Hover (Explore About Cancer)
  - [x] Megamenu Subsection Header state Hover (Understanding Cancer)
  - [x] Megamenu Item state Hover (What is Cancer)
  - [x] SWS input state Focus
  - [x] SWS Search Button state Hover
  
- **Mobile**
  - [x] Menu Button state Hover
  - [x] Mobile Menu state Expanded
  - [x] SWS Input state Focus / Expanded
  - [x] Menu Current Item state Default
  - [x] Menu Current Item state Hover
  - [x] Menu Current Item state Active
  - [x] Menu Current Item state Focus
  - [x] Menu Item state Inactive :w/children
  - [x] Menu Item state Inactive :no/children
  - [x] Menu state Two+ levels
  - [x] Menu state One level
  - [x] Menu state Root
  

 ### Notes
 - Autosuggest is NOT part of this
 
 ### Mocks
 - https://publicis.invisionapp.com/share/FA10EYZRDWP2#/screens/454062769_Header_-_Footer_-_Desktop
 - https://designsystem-dev.cancer.gov/nav-proto/homepage
 4
