### ISSUE TITLE
Build: Megamenu TS for UX functionality

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#297]
### Build megamenu JS component based on design specs/requirements documented in this ticket

> **ESTIMATE** 8

Remaining as of 5/2/22: 5
Remaining as of 5/31: 3

https://github.com/NCIOCPL/cgov-digital-platform/issues/3277 requires this to be done.

### USWDS Component Equivalent
While the Header/Primary Navigation is an existing component, the Mega Menu flyout is a NCI unique component that has no USWDS equivalent.
https://designsystem.digital.gov/components/header/

### Behaviors
*Click to open navigation section
*Click off to close navigation section

### InVision: 
  * DSM link: *insert link here, or enter N/A if not needed*
  * Desktop mockup: (https://publicis.invisionapp.com/share/FA10EYZRDWP2#/screens/454062769_Header_-_Footer_-_Desktop)
  * Tablet mockup: N/A
  * Mobile mockup: N/A

### Acceptance Criteria:

```gherkin
Scenario: User is activating the megamenu
  When the user clicks on an item in the main nav
  Then the megamenu for that will appear below 
     And the L1 will be highlighted in the main nav
     And the caret for the L1 will flip to point upwards
  When the user hovers on any link in the megamenu
  Then the link will receive an underline
  When the user clicks on the L1 item that appears in the megamenu
  Then the landing page will load
     And the megamenu will close
     And an indicator will appear in the main nav under that L1
  When an L2 is clicked on 
  Then the page will load
     And the megamenu will close
     And an indicator will appear in the main nav under the L1 parent
  When an L3 is clicked on 
  Then the page will load
     And the megamenu will close
     And an indicator will appear in the main nav under the L1 parent
  When the user clicks on an L1 item in the main nav
  Then the megamenu for that L1 will appear below 
  When the user clicks outside of the megamenu overlay or on the L1 again
  Then the megamenu will close
  When the user clicks on an L1 item in the main nav
  Then the megamenu for that L1 will appear below 
  When another L1 is clicked on
  Then the megamenu for that L1 will appear below 
```

Link to NCI DS Wiki: See https://github.com/NCIOCPL/ncids/wiki/Technical-NCI-Header-Design

### Tasks
- [x] new nci-megamenu.component.ts
- [x] update nci-header.component.ts for megamenu
- [x] update nci-header-options.ts for megamenu options
- [x] unit tests as per Acceptance Criteria
- [ ] update technical requirements on docsite
- [x] create the mock that returns a hardcoded megamenu for gatsby

**Comment by olitharp-nci** [comment]
Reopened - I believe this ticket was closed accidentally. #411 is still open

**Comment by meglake** [comment]
@blilianyu  and @mworrest  to review and approve today.
