### ISSUE TITLE
Build mobile menu JS functionality

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#298]
### Build JavaScript to display and interface with Navigation API. for the Mobile Menu on Cancer.gov

The mobile menu is a new component specific to NCI.  This ticket includes the JavaScript required to produce the mobile navigation from the set API listed bellow. This includes the fetching, consuming and display of the data as HTML DOM elements using the Navigation API in the ticket listed below. 

> **ESTIMATE** 5
Re-estimated on 5/16: 3

###related tickets: https://github.com/NCIOCPL/cgov-digital-platform/issues/3278 & https://github.com/NCIOCPL/cgov-digital-platform/issues/3243

### USWDS Component Equivalent
The mobile menu is a NCI unique component that has no USWDS equivalent. The design pattern breaks from their uswds header once the mobile MENU button is clicked.  

### Behaviors
*Click [Menu] Button to open Mobile Menu
*Click off or [X] Button to close Mobile Menu
*Click [Section] Parent Link to retrieve json data based on API/ID
*Display current json data
*Click to go [Page Link] to go to url
*Optional tracking callBack on clicks

### API information
input: ```taxonomy_term```
return:
```
{
  id: number, // The term id of the taxonomy node - this should be a unique id
  langcode: 'string', // The 2 char language code
  label: 'string', // This is the field_navigation_label field, or if empty, the name field
  weight: number, // The order of the term
  path: 'string', // The alias of the field_landing_page target
  navigation_display_options: [ ... parameters ... ], // the array of parameters
  is_section_nav_root: boolean, // true if this Site Section is a section nav root
  is_main_nav_root: boolean, // true if this Site Section is a main nav root
  children: [ ... NavItem ... ] // 0 or more NavItem objects
}
```

### InVision: 
  * DSM link: N/A
  * Desktop mockup: N/A
  * Tablet mockup: (https://publicis.invisionapp.com/share/4G11TDSW58SE#/screens/459263421)
  * Mobile mockup:(https://publicis.invisionapp.com/share/4G11TDSW58SE#/screens/459263421)

### Acceptance Criteria

```gherkin
Scenario: User is on a page and opens and closes the mobile menu 
  Given they are on a screen 1023px and smaller
  When the menu button is clicked
  Then the mobile menu appears, sliding in from the left 
    And covers 80% of the screen
    And has an overlay of the content behind it at rgba(0, 0, 0, 0.2);
    And the current page has an indicator (blue line and bolded blue text)
  When the "x" button is clicked
  Then the mobile menu slides left and disappears
```

### Prerequisites
- *dependency* Mock data will be used till API is ready and able to talk with JS
https://github.com/NCIOCPL/cgov-digital-platform/issues/3243

Link to Technical Design: https://github.com/NCIOCPL/ncids/wiki/Technical-NCI-Header-Design#mobile-menu-adapters

### Tasks
- [ ] New NCIDS-JS file for MobileNavigation
  - [ ] Async call to API
  - [ ] Processing / Sorting for Display based on current page
  - [ ] Menu Open/Close
     - [ ] Reset Navigation State on Close 
  - [ ] Section Nav Toggle to show/hide children
     - [ ] Reset Navigation State on Close        
  - [ ] Class for Display of Navigation Node
     - [ ] States for Default/Active
     - [ ] Section Navigation 
     - [ ] Navigation Link

**Comment by bennettcc** [comment]
Mobile menu has been approved as of 7/20: Will plan to demo to clients on 7/26
