### ISSUE TITLE
Story: Megamenu

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#3]
## As a user, I want an overview of the content within each section of the site, so that I easily find content of interest.

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario: 
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Spike - Determine/value and main purpose of megamenu

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by claireblaustein** [comment]
no longer relevant - closing
