### ISSUE TITLE
Discovery: Buttons

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#30]
# Button Discovery

Understanding and analysis of buttons throughout the site.

**Outcomes**

- Understanding of features
- Define problems to solve

  

> **ESTIMATE** TBD

### Resources

* Buttons Discovery Mural: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1611586427071/8906190b53768bef8fc4698d3c82a008cbc39439
* USWDS: https://designsystem.digital.gov/components/button/

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] Inventory and analysis of content type features (Creation of article with all possible features, screen captured)
- [x] Creation of Mural board to capture discovery (logical groupings of sub-features, grids for analysis)

 
### Sub-Tasks
- [x] Heuristic review of feature and sub-features
- [x] Secondary research compilation and synthesis
- [x] Technical impacts analysis
- ~Analytics data analysis and synthesis~
- [ ] Identification of potential USWDS equivalents
- [ ] Drupal reporting on use of features - ISSUE - MAY NEED SPIKE

### Working Sessions

- inventory Mural review  (30 minutes)
- Analysis review and problem identification (1-2 hours)

### Notes
*Some complementary notes if necessary:*
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

### Design Tickets
*Add links to the design tickets:*
