### ISSUE TITLE
Discovery: Cancer Types Landing Page

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#309]
## Cancer Types (A-Z list) Landing Page Goals
- [ ] Identify pain points within landing page
- [ ] Understand what users expect when they come to the page 
- [ ] User goals and business goals, and how they are aligned
- [ ] Understand challenges with mobile experience vs desktop experience
- [ ] Confirm audiences (patient, family, friends, health professionals)

### Tasks Completed by 1/31
Initial discovery
- [ ] Synthesis of any existing analytics data around use and function, including keyword search data (@welshja , @nicolecrom)
    - What are people searching for in external search that lands them on this page?
    - What are the most common paths for those that are navigating to this page (what types of pages are bringing them to this path)?
    - What is the divide between those coming straight from search, versus navigating here?
    - Are people finding what they're looking for (clickthrough)?  Or are they leaving the site (bounce rate)?
    - What percent of people are moving on from this page, to something in the A-Z list?
    - What percent of people are using the links in the common cancer types box?
    - What is the next step people are taking after coming to the page (search box? main menu?)
    - If someone then goes to the search box, what types of things are they searching for? (what is the expectation they had when they came to this page)
    - How many people are coming back to this page over and over again within a single session?
- [ ] Synthesis of heatmaps and recordings for mobile and desktop in CrazyEgg (UX team)
    - User experience with jump links (we do not currently have analytics to capture clicks in the A-Z region)
- [ ] Understand business goals via interviews with content owners of the page (Anne M., Robin J., Lynn) @mworrest 
    - Is it to help users get to specific content, and not another landing page for the cancer type?
- [ ] Landscape review of similar sites (or organizations) / Determine best practices around use of feature (@russellwyatt)

Deeper discovery 
- [ ] Setting up userlytics test for current usability/experience based on heatmaps/recordings (work with Silvia/Ilene)
    - Is the page that I landed on what I expected?
- [ ]  Persona / user empathy exploration and synthesis 

### Resources and Links
*Links to related content on Notion, mockups*

### Notes
Post-discovery, should we consider previous design solutions during the design burst?

**Comment by nicolecrom** [comment]
[AtoZ List Search Terms.xlsx](https://github.com/NCIOCPL/ncids/files/7972564/AtoZ.List.Search.Terms.xlsx)
SEO: Top terms are variations on “types of cancers”. A few in the top 10 also are asking for how many types of cancer there are.
https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1641826995692/d5b163118fc2c015edc206827cd2effd884e2f40?wid=0-1643294671004
Analytics:
- Most traffic is from desktop - fairly even split between navigating and entering directly. Bounce rate is better than the site benchmark
- Mobile visits tend not to navigate to the page. Mobile tends to enter directly and have a higher bounce rate than the norm
- Entries to the page mostly viewed the page (52%) and left, those that stayed did go on to a CTHP (41%) though mostly did not use the quick links (8%). They were unlikely to use other site features like mega menu (2%) or search (2%)
- Navigators mostly made it to a CTHP next (71%) and were more likely use quick links than entries (12%), but may have been using other site features to navigate from the page like mega menu (16%) or search (13%). Few exited after the a-z page (14%).
