### ISSUE TITLE
Discovery: Navigation

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#31]
# Navigation Discovery

Understanding and analysis of navigation throughout the site.

**Outcomes**

- Understanding of features
- Define problems to solve

  
### Elements of Navigation
**Site Banner (everything from main nav up)**
- Alert Bar
- Main Logo
- Language Toggle
- Utility Bar
- Primary Navigation
**Footer**

> **ESTIMATE** TBD

### Resources

* Navigation Discovery Mural: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1602095625783/fa27d5eda78546183c03d428ffee7dc1acfd7fa8
* USWDS: many

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] Inventory and analysis of content type features (Creation of article with all possible features, screen captured)
- [x] Creation of Mural board to capture discovery (logical groupings of sub-features, grids for analysis)

 
### Sub-Tasks
- [x] Heuristic review of feature and sub-features
- [x] Secondary research compilation and synthesis
- [x] Technical impacts analysis
- [x] Analytics data analysis and synthesis
- [x] Identification of potential USWDS equivalents
- ~Drupal reporting on use of features~

### Working Sessions

- inventory Mural review  (30 minutes)
- Analysis review and problem identification (1-2 hours)

### Notes
*Some complementary notes if necessary:*
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

### Design Tickets
*Add links to the design tickets:*
#9 - Banner and Footer, Desktop and Mobile
#22 - Breadcrumbs
#23 - Secondary Navigation
