### ISSUE TITLE
"Basic" Desktop Left Nav (usa-sidenav) Component

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#312]
### Build sidenav component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

## Design Definition of Done
*When all criteria below are met.*

### Baseline Discovery (add any additional info or links)
- [x] Heuristics/Best Practices
- [x] Analytics
*Related links:
- [x] Accessibility
*Related links:

### Design
- [x] Design component. Link to design ticket:
- [x] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [x] Get component approved by client

### USWDS Component Equivalent
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section*
* Related USWDS Links: https://designsystem.digital.gov/components/side-navigation/

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTA strip

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*

### InVision: 
  * DSM link: *insert link here, or enter N/A if not needed*
  * Mockup: https://publicis.invisionapp.com/share/SY11BOIJQK4T#/454941204_Sidenav

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: User is on an L2 and lower and not a section nav root
  Given they are on a screen 1024px and larger
    And not on a section nav root
  Then the left nav appears
    And the current page is highlighted with an indicator
    And any children of the page are exposed
    And any siblings of the page are exposed
    And all ancestors (parents and parent's sibilings, grandparents and grandparent's siblings) appear until reaching site section root
    And the ancestors are highlighted
```

```gherkin
Scenario: User is on an L2 and lower that has child pages
  Given they are on a screen 1024px and larger
    And not on a section nav root
    And the page has child pages
  Then the left nav appears
    And the current page is highlighted with an indicator
    And a plus sign appears to the right of the label of the current page 
    And the whole line is clickable (label and plus sign)
    And any children of the page are exposed
```

```gherkin
Scenario: User is on a section nav root
  Given they are on a screen 1024px and larger
  Then the left nav appears
    And the current page is highlighted as the first item with an indicator
    And any children of the page are exposed
  When a child page is clicked on OR its corresponding + is clicked (the whole line is clickable - no split buttons)
  Then the page loads to that child page
    And the left nav appears
    And the current page is highlighted with an indicator
    And any children of the page are exposed
    And any siblings of the page are exposed
    And all ancestors (parents and parent's sibilings, grandparents and grandparent's siblings) appear until reaching site section root
    And the ancestors are highlighted
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)
