### ISSUE TITLE
Mobile Search

### ISSUE THREAD

**Issue by russellwyatt** [NCIOCPL/ncids#313]
### Build mobile search component based on design specs/requirements documented in this ticket

**This ticket purposefully does not include autocomplete/autosuggest, which is covered in #280 **

> **ESTIMATE** TBD

## Design Definition of Done
*When all criteria below are met.*

### Baseline Discovery (add any additional info or links)
- [x] Heuristics/Best Practices
- Search should be visible and simple: search should be prominent and intuitive to use.
- Auto-suggestions: Try to provide them as quickly as possible, such as after the third character is entered, to provide immediate value.
- Recent searches: When a user searches for a product, it’s great to offer them a quick glance at previous searches for comparison or as a reminder.
- Trending searches: In this screen, the user is shown what other users are most looking for in the app. This helps an uninspired or casual shopper to discover content easily by clicking a suggestion.
- Categories: This search screen guides the user with a number of filter options to define and refine the search, greatly speeding up and simplifying the search process.

*We will need to address the search results screen in a separate ticket but calling it out here as a reminder. Some best practices to consider are:
- Displaying search results the right way
- Provide filtering to reduce screen clutter
- Show only the most relevant results

- [ ] Analytics
*Related links:
- [x] Accessibility
*Related links:
- [Search Bar](http://web-accessibility.carnegiemuseums.org/code/search/)
- [a11ymatters](https://www.a11ymatters.com/pattern/accessible-search/)

- [x] Related Github Tickets
- #277 
- #280 
- #296 

### Design
- [x] Design component. Link to design ticket:
- [x] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [ ] Get component approved by client

### USWDS Component Equivalent
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section*
* Related USWDS Links: [Search Component](https://designsystem.digital.gov/components/search/)

### Styling: 
*Anatomy of a component*
- [x] Use correct spacing (8px grid) size, emphasis, alignment

### Usage
*When to use component and when to use variant(s)*
Ex: Use primary button over secondary

*Style Guide*
Dos and Donts
Ex: Don't have 1 button in CTA strip

### Behaviors
![Mobile Search](https://user-images.githubusercontent.com/87999420/154604655-5d83d24c-3a54-48b8-8da8-4bc286142932.jpg)

### InVision: 
  * DSM link: *insert link here, or enter N/A if not needed*
  * Desktop mockup: N/A
  * Tablet mockup: N/A
  * Mobile mockup: [Mobile Search](https://publicis.invisionapp.com/share/YE12DY3724C7#/464263091_Autosuggest_Sitewide_Search_-_Mobile_Copy_5)

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: Mobile Search
Given the user is using search on a mobile device
And is looking for specific content that is not located on the page or within the navigation
When the user selects the site wide search
Then there is a fullscreen takeover
When user hits enter on provide native keyboard
Then the user is directed to the search results page

Scenario: Cancel Mobile Search
Given the user no longer wishes to search but has typed a query
When the user hits cancel
Then the fullscreen takeover closes
When back at original screen
Then the search input field retains the last query entered
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by VictoriaSunNIH** [comment]
@russellwyatt - can you please clarify, what happens when a user has entered text into the search box modal , and then clicks cancel (screen two of the invision comp). Does the text still appear in the input (screen one of the invision comp) outside of the modal?

**Comment by russellwyatt** [comment]
@VictoriaSunNIH ACs updated
