### ISSUE TITLE
Discovery: Page Options

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#32]
# Page Options Discovery

Understanding and analysis of non-navigation global features throughout the site.

**Outcomes**

- Understanding of features
- Define problems to solve

> **ESTIMATE** TBD

### Resources

* Global Features Discovery Mural: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1613685599666/3cf1510cd52ba568510ab438e1f27e6e82b56ecf
* USWDS: 

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] Inventory and analysis of content type features (Creation of article with all possible features, screen captured)
- [x] Creation of Mural board to capture discovery (logical groupings of sub-features, grids for analysis)

 
### Sub-Tasks
- [x] Heuristic review of feature and sub-features
- [x] Secondary research compilation and synthesis
- [x] Technical impacts analysis
- [x] Analytics data analysis and synthesis
- [ ] Identification of potential USWDS equivalents
- [ ] Drupal reporting on use of features

### Working Sessions

- inventory Mural review  (30 minutes)
- Analysis review and problem identification (1-2 hours)

### Notes
**Discovery synthesis available on Notion**
https://www.notion.so/Page-Options-acbf5b361da143f6ae4f26c520c14231
### Design Tickets
Design: Page Options #27
