### ISSUE TITLE
Discovery: Mini Landing Pages

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#336]
## Mini Landing Page Goals
- [ ] Identify pain points 
- [ ] Understand what users expect when they come to the page 
- [ ] User goals and business goals, and how they are aligned
- [ ] Understand challenges with mobile experience vs desktop experience

### Tasks 
**Initial discovery**
- [x] Pull report of all mini landing pages in Drupal (@lburack to put in ticket for Min: https://tracker.nci.nih.gov/browse/CGOV-15741) **[Sprint 24]**
- [x] Lindsay - Identify initial set of pages for analytics and crazy egg **[Sprint 24]**
- [x] Determine the flavors/goals of the different mini landing pages that we have? **[Sprint 25]**
    - [x] Lindsay - review cancer.gov
    - [x] Microsites review by others (can be split amongst team)
- [x] Gather existing analytics for initial pages, as well as setting up crazy egg **[Sprint 26]**
- [x] Synthesis of any existing analytics data for initial pages **[Sprint 27]**
    - What are people searching for in external search that lands them on a mini landing page?
    - What are the most common paths for those that are navigating to this page (what types of pages are bringing them to this path)?
    - What is the divide between those coming straight from search, versus navigating here?
    - **Are people finding what they're looking for (clickthrough)?  Or are they leaving the site (bounce rate)?**
    - **What percent of people are moving on from this page to child page content?**
    - What is the next step people are taking after coming to the page (search box? main menu?)
    - If someone then goes to the search box, what types of things are they searching for? (what is the expectation they had when they came to this page)
    - How many people are coming back to this page over and over again within a single session?
- [ ] Synthesis of heatmaps and recordings for mobile and desktop in CrazyEgg (UX team)  **[Sprint 28 - SP:5]**
- [ ] Understand and document business goals via interviews with content owners of the page 
    - Identify which DOCs and content owners to talk to -- we will do this when we get to design
- [ ] Landscape review of similar sites (or organizations) / Determine best practices around use of feature - if we decide we still need these pages -- we will do this when we get to design

Deeper discovery 
- [ ] Consider survey as needed?
- [ ] Setting up userlytics test for current usability/experience based on heatmaps/recordings (as needed - work with Silvia/Ilene)
    - Is the page that I landed on what I expected?
- [ ]  Persona / user empathy exploration and synthesis 

### Resources and Links
* High level analysis: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1649772955267/5dfc5653cef24c76162ea8af222ad19fd96c5162?sender=meganlake7790
* Crazy Egg Review Notes: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1649790870719/dbd0f91ce9fe44895bf90a7da9c1adfb3d275717?sender=chuckrose8501

### Notes
Post-discovery, should we consider previous design solutions during the design burst?

**Comment by VictoriaSunNIH** [comment]
Sprint 24: getting the report from Min on all mini landing pages, identify pages for data collection (e.g. crazy egg)
Sprint 25: splitting up analysis (creating new tickets)

**Comment by lburack** [comment]
Spoke with @nicolecrom and here’s the list of pages  for Crazy Egg Recordings:

**List of links with image & description**
- https://www.cancer.gov/about-cancer/treatment/types + Spanish translation

**List of links with descriptions, no image**
- https://www.cancer.gov/publications

**List of links - no image, no description**
- https://www.cancer.gov/about-cancer/treatment/side-effects + Spanish translation

**Two-Item Feature Card Row & Lists**
- http://www.cancer.gov/grants-training/training
(really low traffic, but best of the options)

**Sections of links under headings, no descriptions**
- http://www.cancer.gov/types/by-body-location 

**Sections of links under headings, with descriptions**
- https://www.cancer.gov/about-nci/careers

And then Snapshots will be set up on all of the above pages plus the following list of link with image & description pages: 
- https://www.cancer.gov/about-cancer/treatment (this also includes a feature card)
- https://www.cancer.gov/about-cancer/coronavirus (includes a callout with an image & CTA button)

**Comment by VictoriaSunNIH** [comment]
@lburack to create presentation of analysis of pages that should be moved to articles or landing pages, versus pages that align with the original mini landing page layout intent (sub-navigation type pages) for further discussion.

**Comment by lburack** [comment]
Met with stakeholders on Monday 4/4. Agreement that we will keep the mini landing page. Some pages should be changed to Articles. Will create JIRA tickets for that work.

**Comment by VictoriaSunNIH** [comment]
Closing as complete - we will circle back to design in a later sprint once we're ready to move forward.

**Comment by meglake** [comment]
Added links to Mural Boards for high level analysis and crazy egg review notes to the description of ticket and closing ticket.
