### ISSUE TITLE
Determine and outline standard design process

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#341]
**Stretch goal ticket**

Remaining SP: 1?

*Description of what is to be accomplished.* Russell to work with team to determine and outline a standard process for design work.

### Sub-Tasks
- [x] Facilitate working sessions with team 
- [x] Outline process for team review
- [x] Socialize with the entire team
- [x] Integrate feedback
- [x] Final Review

### Current State

- Github Template Ideas: https://lion.box.com/s/zujbxx3ixys29utyqs359khe2lg0seb9 

![Design Process](https://user-images.githubusercontent.com/87999420/160638572-56072a95-eab2-4b66-895b-2566f9d40ca6.jpg)

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by russellwyatt** [comment]
@VictoriaSunNIH and @meglake this ticket can be closed. The visual is finished. We may want to spin up another ticket for socializing the proposed process and the addition of new Github templates, but we can talk about that in the end of sprint meeting.
