### ISSUE TITLE
Set up USWDS to implement colors, typography, and spacing

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#352]
### Issue description
> **ESTIMATE** TBD

As we have been pulling in components we have begun to trigger AA contrast issues, as well as have unintended colors or style show up. This appears to be caused by some of the USWDS tokens bleeding through that the initial color and font tickets did not account for. We need to setup these tokens and variables not from what do we need for our components, but how should we style all the USWDS components/thinggies. 

This ticket has 2 primary parts:
1. Align the folder structure of `ncids-css` to match USWDS. This is to allow us to better compare differences between files we have replaced and updates to USWDS when upgrading. 
2. Go through the core system tokens and "theme" tokens (those in the `settings` directory) and make sure that we have correctly configured, AND removed anything we will not use, the colors, typography and spacing.

### Tasks
- [x] #363 
- [x] Identify which tokens in USWDS to remove, which tokens to change in our version, and which tokens needs to be added
- [x] Create documentation for colors, typography, and spacing (backlog this task for ticket - low priority for MVP)(created as #451)
- [x] Implement #294 (discussed as part of this - will be done in Sprint 27)

Pages of documentation that need to be updated:
- https://designsystem.digital.gov/components/typography/
- https://designsystem.digital.gov/design-tokens/typesetting/overview/
- https://designsystem.digital.gov/utilities/font-size-and-family/
- https://designsystem.digital.gov/utilities/text-styles/
- https://designsystem.digital.gov/utilities/paragraph-styles/

![Screen Shot 2022-03-01 at 2 50 41 PM](https://user-images.githubusercontent.com/85901679/156246834-82024c40-b85e-4145-817e-d11522bbf0e3.png)
![Screen Shot 2022-03-01 at 2 50 51 PM](https://user-images.githubusercontent.com/85901679/156246835-6a950c4b-081a-4f20-a2d2-39645039ba43.png)

TODO: Decide proper rules for `theme/` and `settings/` directories and document them.
