### ISSUE TITLE
Home and Landing Page Design Guidance Documentation

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#365]
*Description of what is to be accomplished.* Create guidance documentation for how to use the home and landing page modules, what rules they should abide by, and any dos and don'ts. This documentation will be used to update the Drupal Guide on myNCI: https://mynci.cancer.gov/topics/drupal-guide and the digital style guide: https://mynci.cancer.gov/sites/mynci.cancer.gov/files/field/file/NCI-Digital-Style-Guide_9.pdf 

**Parent Issue:** #9999

### Sub-Tasks
- [ ] Create design guidance documentation
- [ ] Review with team
- [ ] Review with client
- [ ] Update myNCI (Drupal Guide & Digital Style Guide)

### Notes

*TBD
