### ISSUE TITLE
Discovery: Sub-branding for DOC sites

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#370]
# Discovery: Sub-branding for DOC sites
As a user, I want to know which site I am on. 
As a site owner, I want to communicate the program while showing its relationship to NCI and the DOC.

### Description of Design request:
Need a solution for branding on sites like these that have the same (CCR) logo:

https://www.cancer.gov/rare-brain-spine-tumor/
https://www.cancer.gov/pediatric-adult-rare-tumor/

Want to move away from the layer cake ribbon treatment. It becomes more of an issue on mobile.

### Tasks
- [x] Inventory all sites that follow into this category
- [x] Identify how all the branding bars are used for all microsites
- [x] Different page-level content types we use on Nano, myPART, and NCI-CONNECT (Biography, Article, Events, Mini landing, Blogs)
- [x] Competitive analysis (CDC, Universities - how do large organizations solve for this)

### Resources and Links
*Links to related content, mockups*
Mural: https://app.mural.co/invitation/mural/publicissapient7269/1649863936838?sender=michellegallo6566&key=0ffb1b88-4379-4274-8063-b4f57a9ee9b0

Sketch File: https://lion.box.com/s/lnwm9k1qoy3vdhr06prb359919d7b5lz 

### Notes
*Some complementary notes if necessary.*
Solution work will be completed in #287

**Comment by meglake** [comment]
Review set for 4/19 at 9:30am with Lynn.

**Comment by meglake** [comment]
Feedback from 4/19 review:
* Blended logos should only include DOC name OR Program/Initiative name (not both)
* Request to update microsite comps to include blended logo with program name only
* Footer on microsite should say 'DOC at the National Cancer Institute'
* Lynn would like the DOC of the program/initiative's microsite to be linked to in the footer of the microsite (new ticket: #424)

Next steps will be outlined in ticket #287 for work during sprint 28.
