### ISSUE TITLE
Component: Back to Top

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/ncids#374]
### Build Back to Top component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

## Design Definition of Done
*When all criteria below are met.*

### Baseline Discovery (add any additional info or links)
- [x] Heuristics/Best Practices
- [x] Analytics
*Related links:
- [x] Accessibility
*Related links:

### Design
- [x] Design component. Link to design ticket: https://github.com/NCIOCPL/ncids/issues/337
- [x] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [x] Get component approved by client

### USWDS Component Equivalent
*Is this a USWDS component?  If so - are there variants? If we are creating something new, provide links to what it is based off of in resources section* The back to top is currently part of the USDS footer. We plan to customize this component.
* Related USWDS Links: https://designsystem.digital.gov/components/footer

### Styling: 
*Anatomy of a component*
- [x] Use correct spacing (8px grid) size, emphasis, alignment

### NCIDS Guidance [in comments]
- [ ] *When to use component and its variant(s)*
  * Use this component on every page and make it sticky with the text "BACK TO TOP"
  * Use the arrow icon version at 1023 and smaller screens

- [ ] *When to consider something else*
  * Do not use back to top links throughout content

- [ ] *Usability Guidance*
  * Use this component on every page and make it sticky with the text "BACK TO TOP"
  * Allow for users to click to get to the top of the page or to scroll back up to the top of the page
  * Use the translation for pages in Spanish = "VOLVER ARRIBA"

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*

### InVision: 
  * DSM link: *insert link here, or enter N/A if not needed*
  * Desktop English mockup: https://publicis.invisionapp.com/share/J612GAGC8NRA#/464821665_Nano_Homepage_-_Desktop_In_Browser_1024
  * Desktop Spanish mockup: https://publicis.invisionapp.com/console/Back-to-top-cl178a6l13rzm01w5kmj9hrxn/cl6410gab1d7q012n0gpi5sns/play
  * Tablet mockup: same as mobile
  * Mobile mockup: https://publicis.invisionapp.com/share/J612GAGC8NRA#/464822888_Mobile_Minimalist_Homepage_Copy_10

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: User interacts with back to top in English
  Given user is on an English page 1024 or larger
  Then user will see "BACK TO TOP" button in the bottom right corner of their screen
    And it will stick to the corner when the user resizes their browser
    And it will scroll with them, sticking in the bottom corner
  When user clicks the button
  Then the page will scroll to the top with a scrolling animation effect
```

```gherkin
Scenario: User interacts with back to top in Spanish
  Given user is on a Spanish page 1024 or larger
  Then user will see "VOLVER ARRIBA" button in the bottom right corner of their screen
    And it will stick to the corner when the user resizes their browser
    And it will scroll with them, sticking in the bottom corner
  When user clicks the button
  Then the page will scroll to the top with a scrolling animation effect
```

```gherkin
Scenario: User interacts with back to top on mobile
  Given user is on a page 1023 or smaller
  Then user will see the back to top button in the bottom right corner of their screen
    And it will only have the arrow icon, no text
    And it will scroll with them, sticking in the bottom corner
  When user clicks the button
  Then the page will scroll to the top with a scrolling animation effect
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by mworrest** [comment]
### NCIDS Guidance
- [ ] *When to use component and its variant(s)*
  * Example: Use a card when featuring content
  * Use this component on every page and make it sticky with the text "Back to top"
  * Use the arrow icon version at 1023 and smaller

- [ ] *When to consider something else*
  * Example: Use a list when you have multiple pieces of content, and will display too many cards*
  * Do not use back to top links throughout content

- [ ] *Usability Guidance*
  * Example: Don't have 1 button in CTA strip
  * Use this component on every page and make it sticky with the text "Back to top"
  * Allow for users to click to scroll back up the page
  * Use the translation for pages in Spanish

**Comment by bennettcc** [comment]
1 SP completed is S35, 1SP remaining in S36

**Comment by olitharp-nci** [comment]
Completed with https://github.com/NCIOCPL/ncids/pull/527
