### ISSUE TITLE
Draft Build Ticket Details for a Home & Landing Page Module

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#393]
*Description of what is to be accomplished.*
Create a list of all Home and Landing page modules and then draft the DS and Drupal Build ticket details for the Guide Card module and the Feature Card module in a Word Doc for review with the team.

Definition of Done: Complete list of Home and Landing page modules and Build ticket details defined and documented in a Word document for Guide Card and Feature Card modules. 

Remaining SP: 2

### Sub-Tasks
- [x] Define list of Home and Landing page modules (see [Mural Board for example](https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1648220476768/8ead9815bfc1d61b77cfba5a6442185e30187fe3)) (see [Annotations](https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1638306879101/4adb7154efb0319ee806fbcd3052a180a57fb137?sender=uf7d7cce75e812c2b5a084619))
- [x] Create a Word Document that details the Build tickets for **guide card module** within the DS
- [x] Create a Word Document that details the Build tickets for supporting **guide card module** within Drupal (e.g. new fields, rules, etc that will need to be built in Drupal)
- [ ] Create a Word Document that details the Build tickets for **feature card module** within the DS
- [ ] Create a Word Document that details the Build tickets for supporting **feature card module** within Drupal (e.g. new fields, rules, etc that will need to be built in Drupal)

### Notes
List of Home and Landing modules:
* Hero
  * Image
  * Video
* Text Card
* Call to Action Strip
* Factoids
  * Vertical
  * Horizontal
  * With Image
* Guide Card
  * Alternating Left
  * Alternating Right
  * Row with Title
  * Row
* Card
  * Audience Guide Card & Image 
  * 2-Up Feature Card
  * 3-Up Feature Card
  * Multiple-Link 3-Up Feature Card
  * Thumbnail Card
* Content Grid
  * Single Tile
  * Double Tile Horizontal
  * Double Tile Vertical
* Promotional Block
* Inline Video
* Quote

**Comment by VictoriaSunNIH** [comment]
@sarinapadilla - can you please take the action item to break the components into their own tickets? We can then add them to future sprints to have requirements discussions and capture the ACs every 2 weeks for a few components (tagging @meglake).
