### ISSUE TITLE
Determine Workload for WYSIWYG/Inner Pages

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#394]
*Description of what is to be accomplished.*
Determine workload for WYSIWYG/inner Page development by defining which elements will follow USWDS, which will not, and which will have a look/feel change when we launch.

### Sub-Tasks
- [ ] Outline WYSIWYG/inner page elements
- [ ] Determine which WYSIWYG/inner page elements will follow the USWDS and which will not
- [ ] Determine which WYSIWYG/inner page elements will change look/feel as part of DS/Drupal dev

**Comment by VictoriaSunNIH** [comment]
Started in sprint 27, will continue into sprint 28. Repointing this to a 3

**Comment by meglake** [comment]
Need to re-storypoint and revise remaining tasks and assign to a future sprint after MVP 1 tickets are built out and estimated.

**Comment by andyvanavery31** [comment]
Closing as this will be addressed in R4 for article pages.
