### ISSUE TITLE
Determine comprehensive content strategy for all home/landing page components

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/ncids#399]
We have started documenting rules and content strategy for using each of the home and landing page components, but we need to continue this work until we have completed captured the business rules for using the various components.

Mural board where this is started: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1637768209940/64811a50e2cebd87fb704b0229c470a32fdb9be2

This should be completed before we engage in further content discussions for laying out home and landing pages for the second release.

### Sub-Tasks
- [ ] Meet with business owners to clearly define the content strategy and usage for each component
- [ ] Document the usage for each component (as part of the DS documentation, or as a separate user guide)
- [ ] Get client sign off on documentation

**Comment by laurelthrash** [comment]
Can revisit SP week of 07/25/22 if needed.

**Comment by laurelthrash** [comment]
Closing this ticket as all sub-tasks are complete.
