### ISSUE TITLE
Create DS inner/content page template with guidance

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#413]
### Build inner/content page template based on design specs/requirements documented in this ticket, similar to USWDS documentation page

> **ESTIMATE** 2
## Design Definition of Done
*When all criteria below are met.*

### Baseline Discovery (add any additional info or links)
- [ ] Heuristics/Best Practices
- [ ] Analytics
*Related links:
- [ ] Accessibility
*Related links:

### Design
- [ ] Design template. Link to design ticket:
- [ ] Conduct Design QA
*Meet with design team to do visual QA for colors, fonts, spacing (padding/margin), etc.
- [ ] Get template approved by client

### USWDS  Equivalent
- https://designsystem.digital.gov/templates/documentation-page/

### Styling: 
*Anatomy of a template*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*

### InVision: 
  * DSM link: *insert link here, or enter N/A if not needed*
  * Desktop mockup: *insert link here, or enter N/A if not needed*
  * Tablet mockup: *insert link here, or N/A if not needed*
  * Mobile mockup: *insert link here, or N/A if not needed*

### Acceptance Criteria for Behaviors 
*If a template changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create template documentation that includes:
    - Developer Documentation
      - (HTML Tab) What is the HTML?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the template should be used

### NCIDS Guidance
- [ ] *When to use page template*
  * Example: Use a card when featuring content
- [ ] *When to consider something else*
  * Example Use a list when you have multiple pieces of content, and will display too many cards*
- [ ] *Usability Guidance*
  * Example: Don't have 1 button in CTA strip
- [ ] Include page option guidance from https://github.com/NCIOCPL/ncids/issues/215

**Comment by bennettcc** [comment]
Closing as complete - this was done as a part of MVP1
