### ISSUE TITLE
Discovery: Breadcrumb Change/Enhancements

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#417]
Design: [1 Discovery Phase](https://lion.box.com/s/r4vh9g37fps4iafbw41cinahthug8ugf)

# Discovery: Breadcrumb Change/Enhancements (long breadcrumbs)
Per discussion on 4/13 we've decided to put the breadcrumb discovery into the backlog for a later date. Current implementation of the breadcrumb is documented here: https://github.com/NCIOCPL/cgov-digital-platform/issues/3242

Discussion was around changing the breadcrumb to truncate some of the ancestor pages to avoid really long breadcrumbs that wrap multiple lines. Potential idea: show only the current page title + parent page link and then the eldest ancestor, with ellipses in between to represent pages in between.
- Example: Home > … > … > … > … > OHAM Research Activities > International Conference on HIV/AIDS Malignancies

Some questions to consider:
- What are the parameters on when to only show page title, parent page, ellipses, and eldest ancestor?
   - character length? 
   - based on depth in the navigation?
     - what if something is deep in the IA but uses short nav labels and the breadcrumb is just one line?
     - what if something is only 3 levels but the nav labels are incredibly long? Here's a Spanish example (this is 4 levels deep, starting at Investigacion, not the Spanish homepage): https://www.cancer.gov/espanol/investigacion/infraestructura/estudios-clinicos/nctn

### Links to related tickets
- Direction Ticket: ...
- Solution Ticket: ...
- Build Ticket(s): ...

### Timeline
*Identify start and end times for discovery work*

### Definition of Done/Complete
*All findings and synthesis will be documented in a shared Mural board for consistency, communication, and reference*

Mural Board Link: *Add you link here*

### What do you want to learn?
- What are the goals and/or mission?
- Who is our audience?
	- As a [role], I want [feature], so that [benefit]
- What are the known user expectations?
- What goals and tasks should be supported?
- What known user problems do we need to solve?
- What are the required features?

### Organization Goals
1. Goal
2. Goal
3. Goal

### Tasks
*Update the list and remove Potential once the scope of the discovery has been set*
- [ ]  Drupal reporting
	- *Link to report*
- [ ]  Synthesis of any existing analytics data around use and function
	- *Link to report* 
- [ ]  High-level heuristic review of feature
	- *Link to review*  
- [ ]  Technical or accessibility flag
	- *Link to flag report* 
- [ ]  Best practices around use of feature
	- *Link to report*
- [ ]  Persona
	- *Link to personas*  
- [ ]  User empathy exploration and synthesis (Empathy Map as a deliverable)
	- *Link to empathy map* 
- [ ]  Journey Mapping
	- *Link to journey map*  

### Key Opportunities
*Document they discovered key opportunities and add a p1, p2, p3, or p4 to establish its priority*
1. Opportunity one
2. Opportunity two
3. Opportunity three

### Resources and Links
*Related links go here*

### Notes
*Complementary notes if necessary.*

**Comment by andyvanavery31** [comment]
Closing due to the decision to follow the USWDS model, and not needing to conduct further testing.
