### ISSUE TITLE
Design: Grants & Training Spanish Solution

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#418]
Design: [1 Discovery Phase](https://lion.box.com/s/r4vh9g37fps4iafbw41cinahthug8ugf)

# Grants & Training - Spanish Solution
Determine if Grants & Training landing page in Spanish (https://www.cancer.gov/espanol/subvenciones-capacitacion) is needed or if the content can be revised to better reflect the landing page structure

### Tasks

- [x] Set up meeting with Lynn, Fedora, Carolina to discuss possible removal of this page or revising content to be more appropriate for a landing page and appropriate for the user (Scheduled for 5/16)
- [x] Pull analytics for this page: https://www.cancer.gov/espanol/subvenciones-capacitacion
- [x] After tasks 1 & 2 determine next steps for comps or to remove page.

### Links to related tickets
- Direction Ticket: ...
- Solution Ticket: ...
- Build Ticket(s): ...

### Timeline
To be completed within 1 sprint

### Definition of Done/Complete
Defined next steps for the Grants & Training Spanish landing page (either remove cause it's not necessary or revised content to comp in another sprint).

Mural Board Link: *Add you link here*

### Notes
*Complementary notes if necessary.*

**Comment by nicolecrom** [comment]
Here are some basic analytics for the page. Let me know if you have questions or there are additional analytics  you want to dig in on
[Spanish Grants and Training.pptx](https://github.com/NCIOCPL/ncids/files/8631084/Spanish.Grants.and.Training.pptx)

**Comment by lburack** [comment]
@nicolecrom - what is the timeframe of this data?

**Comment by meglake** [comment]
Notes from 5/16 Meeting:
* G&T page in Spanish needs to be kept
* Carolina will work on revising content to be more up-to-date, accurate, and shorter [CGOV-16215]
* Once we receive new content we'll comp up using new home and landing page modules (as possible) and determine if any new modules are needed
* Client requested that a content block module be available with the new home and landing page modules (work to be done in #461) 

Moving ticket to Sprint 30 while we wait for new content to comp.

**Comment by laurelthrash** [comment]
7/21: @blilianyu discussed comps with the team. Next steps:
- Create comp with factoid module/component
- Create comps for tablet breakpoint
- @blilianyu to share completed comps once above steps are complete
- Setup time with Fedora to review completed Spanish comps @meglake

**Comment by blilianyu** [comment]
@meglake Updated options have been added to the Stakeholder Mural board 

https://app.mural.co/invitation/mural/publicissapient7269/1652804277768?sender=uf7d7cce75e812c2b5a084619&key=1bc9c527-9e14-4d2c-b775-4e8c71f8c9be

**Comment by laurelthrash** [comment]
Closing out this ticket as the initial comp is complete. Additional updates to this design are being tracked in #536.
