### ISSUE TITLE
Discovery: Link to DOC of program/initiative in microsite footer

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#424]
Design: [1 Discovery Phase](https://lion.box.com/s/r4vh9g37fps4iafbw41cinahthug8ugf)

Feedback from review on sub-branding discovery work (#370) resulted in a request to have the DOC name added to microsites of programs/initiatives (to be done as part of #287) and look into how the DOC can be linked to in the footer (this ticket's work). Please conduct a competitive analysis to inform possible solutions to link to the DOC in the footer of program/initiative microsites. 

Note - Once a solution is approved a change request will need to be put in for MVP Release 1. 

### Links to related tickets
- #370 
- #287 
- Solution Ticket: ...
- Build Ticket(s): ...

### Timeline
This work should be completed as part of sprint 28.

### Definition of Done/Complete
*All findings and synthesis will be documented in a shared Mural board for consistency, communication, and reference*

Mural Board Link: *Add you link here*

### What do you want to learn?
- What are the goals and/or mission?
- Who is our audience?
	- As a [role], I want [feature], so that [benefit]
- What are the known user expectations?
- What goals and tasks should be supported?
- What known user problems do we need to solve?
- What are the required features?

### Organization Goals
1. Goal
2. Goal
3. Goal

### Tasks
*Update the list and remove Potential once the scope of the discovery has been set*
- [ ] Competitive Analysis
- [ ] Determine possible solutions (review with team)
- [ ] Get approval on a solution
- [ ] Document solution as part of footer documentation (see ticket https://github.com/NCIOCPL/ncids/issues/181) 

### Key Opportunities
*Document they discovered key opportunities and add a p1, p2, p3, or p4 to establish its priority*
1. Opportunity one
2. Opportunity two
3. Opportunity three

### Resources and Links
*Related links go here*

### Notes
*Complementary notes if necessary.*

**Comment by meglake** [comment]
@mworrest  since we discussed this with Lynn today I'm going to close this ticket and comp work can be completed in ticket #287 

Note for future reference that Lynn requested microsite footers to be updated as follows:

- Change footer to mimic new Cgov footer columns and labels
- and add linked DOC (spell out DOC name) under 'About'
