### ISSUE TITLE
better support for logos and move search in `nci-header`

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#426]
### Issue description

We need to be able to better support logo sizing in NCIDS. Currently, we have to set a height on the image. This will change per image and therefore needs to not be hardcoded.

> **ESTIMATE** 2

### Additional details / screenshot

Current:

![Screen Shot 2022-04-20 at 3 27 50 PM](https://user-images.githubusercontent.com/85901679/164317087-257c5c53-11c7-4d75-9779-73fbf5e792cf.png)

**Note** must set height  100% on the svg element
```scss
svg {
    height: 100%;
}
```

CCR logo with the same styles:

![Screen Shot 2022-04-20 at 3 41 52 PM](https://user-images.githubusercontent.com/85901679/164319205-d5ea3eba-c962-43dd-9107-82667979a28e.png)

The following will make the logo larger:

![Screen Shot 2022-04-20 at 3 33 37 PM](https://user-images.githubusercontent.com/85901679/164318024-afdd4b5e-2a7e-4880-a521-549d1cb19d85.png)

set `.nci-logo` styles to
 ```scss
.nci-logo {
    max-width: 60%; // Current site uses 60%
    height: 66px; // We should not hardcode this value
}
```

and add 100% width to the svg

```scss
svg {
    height: 100%;
    width: 100%;
}
```

If the number of characters in the menu items forces more lines, the search bar will no longer be centered with the logo.

![Screen Shot 2022-04-20 at 3 47 33 PM](https://user-images.githubusercontent.com/85901679/164320045-5533c561-65ba-4025-b00a-75b77847294c.png)

This is because the search form is located in the nav and absolutely positioned by the logo. This does not need to be in the nav menu because it is not in our mobile menu.

### Related Tickets
* https://github.com/NCIOCPL/cgov-digital-platform/issues/3340
* https://github.com/NCIOCPL/ncids/issues/296

### Prerequisite Tickets
* #433 

### See also
* https://codesandbox.io/s/confident-sid-9t2mdm?file=/ccr-logo.svg
* https://codesandbox.io/s/boring-chaplygin-gqccu8?file=/ccr-logo.svg
* https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/components/preview/header--extended-mega.html
* https://designsystem-dev.cancer.gov/develop/components/header
* https://codesandbox.io/s/empty-cache-4pm4wd?file=/logo.svg

### Tasks
- [x] Update guidance and usage documentation
- [x] Update ncids-css
- [x] Remove search from `nav`
- [x] Allow logo to be either an `img` or `svg`
- [x] Add regression tests for (one illustrator file with all the logos): 
     * Cancer.gov (default)
     * DCCPS (longest text)
     * CBIIT (tallest text)
- [x] Add regression tests for the `primary-item` using more than one line
- [x] Make sure button colors match designs https://publicis.invisionapp.com/console/share/TGU54CQ3ME7/897650016

**Comment by olitharp-nci** [comment]
```scss
.nci-header-nav__inner {
      margin-left: auto;
      margin-right: auto;
      min-width: 25rem;
      max-width: 64rem;
      padding-left: units(2);
      padding-right: units(2);
      width: 100%;

			@include at-media($theme-header-min-width) {
				padding-left: units(3);
				padding-right: units(3);
			}
```
