### ISSUE TITLE
TASK: Inventory all icons in USWDS CSS

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#430]
Search through USWDS CSS to determine what icons they include in their CSS. @mworrest to work on this and pull in @meglake  for help. 

### Sub-Tasks
- [ ] Search through USWDS CSS to determine what icons they include in their CSS
- [ ] Document all icons they use in their CSS in a spreadsheet (include name of icon, where it's located, and any other relevant info)
- [ ] Post link to spreadsheet in this ticket when complete

**Comment by meglake** [comment]
@mworrest  closing this ticket as this task is no longer needed now that we are going to take USWDS icons as is and not create custom ones.
