### ISSUE TITLE
Add resize method to nci big extended footer

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#447]
### Issue description

If the footer is loaded on larger screens and then the screen size shrinks to a smaller size, the the menu should collapse. 

> **ESTIMATE** 3

### What's the expected change?
- `ncids-js` should have a resize method built-in so that the footer does not need to be re-initialized.

### What's the current functionality?
- `ncids-js` expects the app to use a resize method to reinit the footer component so that the menu collapses on mobile. 

### What's the updated acceptance criteria?
```gherkin
# Mobile has collapsible menu items and are collapsed on default

Scenario: Footer has collapsed menu items
  Given Window is mobile breakpoint
  When  Footer component is created or resized 
  Then  Primary link is a button
    And Secondary links are collapsed
```

```gherkin
# Tablet up should never have collapsible menu items

Scenario: Footer has no collapsible menu items
  Given Window is tablet breakpoint and above
  When  Footer component is created or resized 
  Then  Primary link is a header
    And Secondary links are visible
```

### Tasks
- [x] Resize works on default
- [x] `aria-expanded` matches the visual state
- [x] Unit tests added for resize

**Comment by meglake** [comment]
Sprint 31: original estimate 3 SP
Sprint 32: estimated 2 out of 3 SP remaining
