### ISSUE TITLE
Define and document Grid module

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#449]
*Description of what is to be accomplished.*
Connect with the internal team to decide the following:
* how the grid is meant to be used
* our content strategy recommendations
* how we came to these recommendations
* timely content or evergreen content?
* options that the content editor has (ie size of the block, color, text fields, images, etc)

**Parent Issue:** #388

### Sub-Tasks
- [x] Create a mural board to document the items note above along with visuals of the grid options **[Sprint 29]** https://app.mural.co/invitation/mural/publicissapient7269/1652289110778?sender=michellegallo6566&key=671edd02-9455-4422-8d43-29eed75149a1
- [x] Review with internal team first to get alignment **[Sprint 30]**
- [x] Complete actions items from 5/17 meeting (notes below, next steps in comments) **[Sprint 31]**
- [x] Review comps from 6/10 meeting next steps internally and align on next steps for ODDC review **[Sprint 31]**
- [x] Confirm team alignment on design/functionality of exit disclaimer for grid (Lilian to connect with Sarina to plan discussion) **[Sprint 32]**

#### Meeting Notes from 5/18 Internal Meeting

**Grid title/label:**
- Required field 
- Content Editor Guidance: Should be a label that will identify the 'theme' of the content that will be places in the grid.

**Grid content:**
- Can be evergreen or timely content but should connect to the theme establish by the grid title/label
- Any block with content (ie not an image) must have a link (internal, external, media type)
- Any block with a content (ie not an image) can have a title only or a title and description with arrow
-- Title will default pull internal linked page card title with option of override
-- Description will pull internal linked page feature card description with option of override

**Grid configurations for initial release in MVP 2:**
- 4 links - 2 small images - title & description
- 4 links - 1 large image - title & description
- 4 links - 2 small images - title only
- 4 links - 1 large image - title only
_NOTE: Consistent placement of color blocks and images will be defined as part of this ticket (ie determine color order for blocks and placement of images)_
_NOTE: Additional iterations will be decided after MVP 2 launch based on content editor use case/needs and user research_

**Grid images:**
- Small image refers to an image in a single block (1x1)
- Large image refers to an image that spans 2 blocks (2:1)
-- NOTE: This size will require a change to the image media type to add this new crop size (will not be a required crop size)

**Comment by meglake** [comment]
Next steps per internal meeting on 5/18:
* Comp 4 grid options based on the following configurations (use these configurations as the "title' above the grid):
** 4 links - 2 small images - title & description
** 4 links - 1 large image - title & description
** 4 links - 2 small images - title only
** 4 links - 1 large image - title only
* Use descriptive text for content (ie use 'This is the title' and 'This is the feature card description of the page or an override description')
* Show one of the comps with the hover/focus state
* Show one of the comps with exit disclaimer icon for an external link
** Consider current behavior for exit disclaimer and make consistent for any of the 4 grid configurations
See meeting notes in ticket description for reference and reach out to @meglake with any questions.

**Comment by meglake** [comment]
Per internal review on 5/26 @blilianyu to make the following changes:
* Update all 4 grid options to have consistent placement of color blocks and image(s) locations
* Create an alternate external link icon display option (somewhere on the block)
* Change titles to say 'This is a card title'
* Show header style for top of grid (can't remember if this was part of review, just noting in case)
* Show all 4 grid options in mobile/tablet layouts

These updates should be made by Thursday AM so we can review with the internal group again on 6/2 at our 1pm meeting. We'll then use this time to coordinate on Mural Board for presentation and review with stakeholders. Thank you!

**Comment by meglake** [comment]
Confirmed edited from 5/26 meeting were completed today's review (6/2). Plan to loop in Chuck at 6/9 meeting and then discuss with Bryan and devs on 6/10 to confirm no red flags with the design/expected function and LOE/dev implications for the external link icon location/function.

**Comment by meglake** [comment]
Confirmed that we can move forward exit disclaimer as USWDS does it (just icon, no link). Need to talk with dev team to determine which exit disclaimer design/functionality makes sense to move forward with in relation to the grid component.

**Comment by meglake** [comment]
Sprint 31: completed 1 of 1 SP
Sprint 32: estimating 2 SP

**Comment by blilianyu** [comment]
Recommendations for the exit disclaimer for Grid Content Module
- Swap out the arrow icon with the external link icon when the link does not end in .gov
-  Placement of icon will be consistent (if placed after the title, the icon will move around depending on the length of the title)
