### ISSUE TITLE
Document Standards & Guidance for NCI Graphics

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#450]
*Description of what is to be accomplished.*
Create documentation outlining standards and guidance for NCI graphics to align with the ongoing work to redesign [cancer.gov](http://cancer.gov/) using the USWDS. Finished product will be made available to current and future design team members as a PDF for easy sharing. File will be made available at https://lion.box.com/s/subrxbisnc4uhn3m9m7krlq2juzam14z (…/NCI/Design/Style Guides).
**Parent Issue:** #372

### Sub-Tasks
- [ ] Establish color palette
- [ ] Establish font families
- [ ] Establish standard sizing for various graphics to include factoids and infographics and taking into account [cancer.gov](http://cancer.gov/) and social media sizing and usage
- [ ] Establish standards for graphic stylings (background colors/heading treatments/etc.)
- [ ] Establish standards for graphic elements (line width/corner radius/drop shadows/icons/font sizes/etc.)
- [ ] Provide links to related resources (e.g. color libraries, fonts, etc.)

**Comment by meglake** [comment]
Closing and opening new ticket for final refinements in sprint 31.
