### ISSUE TITLE
Create Stakeholder Presentation Mural Board

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#467]
*Description of what is to be accomplished.*
Per request during our 5/17 meeting, please create a mural board to be shared with stakeholders to reference the latest comps. Please include all of the latest comps we have for Cancer.gov and lock the comps to the board so that no one can accidentally remove a comp. Once all comps are in, work with @meglake on any messaging/notes that should be included to note "point in time" of the comps and process for keeping board updated with any changes that come up in future sprints.

### Sub-Tasks
- [ ] Create new mural board with comps for stakeholders
- [ ] Collaborate with Megan for necessary notes needed to be included
- [ ] Share with stakeholders [Megan to do]

### Notes

**Comment by mworrest** [comment]
@meglake this is ready for tomorrow.
