### ISSUE TITLE
Draft Build Tickets for Guide Card Component on Home/Landing Pages

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#468]
Definition of Done: build ticket details for each variation of the Guide Card component defined and documented in `ncids` and `cgov-digital-platform` tickets.

**Parent Issue:** #393 

### Sub-Tasks
- [X] Audience Guide Card/Row
  - [x] DS component ticket: #549
  - [x] Drupal component ticket: https://github.com/NCIOCPL/cgov-digital-platform/issues/3489
- [ ] Guide Card/Row
  - [x] DS component ticket: 
  - [ ] Drupal component ticket: 
- [ ] Alternating Guide Card/Row
  - [ ] DS component ticket: 
  - [ ] Drupal component ticket: 

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by andyvanavery** [comment]
Closing due to not being needed.
