### ISSUE TITLE
Draft Build Tickets for Promotional Block Component on Home/Landing Pages

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#470]
*Description of what is to be accomplished.*

**Parent Issue:** #393 

### Sub-Tasks
- [x] Alternating Promo Block
  - [x] DS component ticket: #550 
  - [x] Drupal component ticket: https://github.com/NCIOCPL/cgov-digital-platform/issues/3490
- [ ] Full-Width Image Promo Block
- [ ] No Image Promo Block

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by andyvanavery** [comment]
Closing due to not being needed.
