### ISSUE TITLE
Investigate break points and determine best design approach

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#478]
Related to change request #429 as a next step per our discussion on 5/19, please investigate the changes to the breakpoints and layouts (especially header/footer) to determine what is absolutely necessary and makes sense for users (see user testing here: https://lion.box.com/s/gu7ujehwy2qnpfh9jokmxk1zqcnvg9pj).

Background:
MVP 1 is being build with the default USWDS breakpoints:
- Mobile lrg 480
- Tablet 640
- Desktop 1024

Change request was to change to these other USWDS breakpoint options:
- mobile 320
- Tablet-lg 880
- Desktop 1024
- Widescreen 1400 

This would change page layouts and header/footer which wasn't intended to be worked on in MVP 2 originally.

[Note: from 6/21/22 meeting, client indicated that they'd want to continue with USWDS default breakpoints (that are being used for MVP 1) and did not approve a spike to be added to MVP1 to look into what it would take to make widescreen display properly. Keep this in mind as you investigate and be sure to clearly document the importance and reason for any breakpoint change recommendation]

### What do you want to learn from this research?
List the questions you would like to answer

1. What breakpoints make the most sense for Cancer.gov and its users and why? (explain if and why we should change the breakpoints)
2. What changes to layout & header/footer (from MVP 1) would need to be made to accommodate these breakpoints and why?
3. What is the dev implications of any of these recommended changes?

##

### Tasks

- [x] Work with the design team to answer questions 1 & 2 above **[Sprint 33]**
- [x] Compile comps or create new comps (as needed) for breakpoint recommendations based on answers to first task and clearly annotate any changes from MVP 1 (header/footer/layout) **[Sprint 33]**
- [x] Update Mural board with desired analytics information (indicated by pink stickies on the board) **[Sprint 36]**
- [x] Review comps and recommendations with dev team to determine implications/trade offs (completed 08/15/22) **[Sprint 36]**
- [ ] Final discussion w/Bryan and determine next steps @meglake 
- [ ] Present comps, recommendations and dev implications to client for decision [Megan/Laurel to schedule]
- [ ] Depending on client decision, update or delete ticket #429  [Megan/Laurel to handle]

**Comment by mworrest** [comment]
@nicolecrom could you please investigate what devices/screen sizes our users are coming from? We haven't had an updated report in some time. Thanks!

**Comment by nicolecrom** [comment]
For cancer.gov - 59% of visits are on mobile, 39% are on desktop, and 2% are on tablet
There is a difference by language for English it is 55% mobile, 42% desktop, and 2.3% tablet
For Spanish it is 63% mobile, 36% desktop, 1.4% tablet

**Comment by nicolecrom** [comment]
[Device type and browser size.xlsx](https://github.com/NCIOCPL/ncids/files/8951083/Device.type.and.browser.size.xlsx)
@mworrest Attached is a breakdown of the top 10 widths for mobile, desktop, and tablet.
Broadly almost 2/3 of mobile visits are between 300-399 pixels, remaining 1/3 are 400-499
Desktop and Tablet are more varied in widths, 1/3 of desktop visits were 1300-1399 px, 1/4 of tablet visits were 1000-1099 px

**Comment by laurelthrash** [comment]
Update from standup: in progress, still need to determine if new comps are needed and likely need to connect with devs to confirm. Expected to roll over to sprint 33.

**Comment by laurelthrash** [comment]
Sprint points in Sprint 32: placeholder 
Sprint points estimated for Sprint 33: placeholder

**Comment by laurelthrash** [comment]
Next steps: create recommendation and document in this ticket (@blilianyu & @mworrest). From there, @meglake and @laurelthrash will set up subsequent conversations/tickets with this information.

**Comment by laurelthrash** [comment]
Standup update: on track for @blilianyu to perform work on this ticket ahead of OOO to hand off to @mworrest for completion.

**Comment by mworrest** [comment]
Mural board for presentation https://app.mural.co/invitation/mural/publicissapient7269/1657297284824?sender=michellegallo6566&key=a5e6b677-2040-49be-9637-65a482b86a92

**Comment by laurelthrash** [comment]
Comps complete, @laurelthrash @meglake to take next steps.

**Comment by blilianyu** [comment]
@laurelthrash @meglake The mural board has been updated with analytics info

**Comment by laurelthrash** [comment]
Update 08/17: Planning to review DS Dev tickets on 08/26, which will inform next steps in regard to breakpoints.

**Comment by meglake** [comment]
Closing this ticket as we've addressed breakpoints via other tickets and will be releasing widescreen next week.
