### ISSUE TITLE
Investigate Header/Footer for MVP 1 and compare to current comps

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#479]
Per our discussion on 5/19, please compare the header/footer that is currently built for MVP 1 to the header/footer on the latest design comps and identify any differences for further discussion. Include English, Spanish, and mobile.

### Sub-Tasks
- [x] compare the header/footer that is currently built for MVP 1 to the header/footer on the latest design comps and outline all differences in this ticket
- [x] using your list of differences, identify if any of them have a current ticket/change request to address this difference (note the ticket number)
- [ ] review list of differences with design team/PMs to determine level of priority for MVP 1
- [ ] review list of prioritized differences with dev team/PMs to determine level of effort for these changes and timeline implications for MVP 1 release
- [ ] based on LOE and timeline implications determine next steps for client communication [PMs]

### Notes
- Consider what is content that is editable from the CMS in the header/footer and what is being added via code (ie some text has changed on Spanish, is that content entry in CMS or do we need a change request for devs?)
- All content in the footer is editable as a raw html block.

**Comment by mworrest** [comment]
Header:

1. Fonts are wrong in megamenu
2. NCI extended desktop longer primary item should be centered with other nav labels, not top aligned https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1638306879101/4adb7154efb0319ee806fbcd3052a180a57fb137?wid=0-1651262845414
3. I don't think this is a bug but just wanted to include anyway. Extended desktop sws looks cut off. Looks better at mobile breakpoint so I think this is just meant to be viewed on mobile even though the page name is desktop.
<img width="1017" alt="Screen Shot 2022-06-03 at 5 01 07 PM" src="https://user-images.githubusercontent.com/4921685/171952221-a00bbe2e-7892-4c33-8349-ec7c5e5ce063.png">


Footer:

1. Return to top incorrect/old version
2. New link for site feedback needed under Contact us on right
5. Follow us icons incorrect/old versions

**Comment by mworrest** [comment]
@meglake assigning to you after my review.

**Comment by meglake** [comment]
Spring 31: Estimated at a 3 originally, at completion closer to a 1 SP

@meglake  to complete remaining documentation and close out ticket.

**Comment by meglake** [comment]
Sprint 32 - Megan will follow up with dev team to see about getting a storybook view using real Spanish section titles to see if their is still an issue with the longer primary item (ie wrapping of nav title).

**Comment by meglake** [comment]
All items have been address and noted in Michelle's comment above (my notes in bold). Closing ticket.
