### ISSUE TITLE
Discovery: News & Event Landing Page

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#482]
Design: [1 Discovery Phase](https://lion.box.com/s/r4vh9g37fps4iafbw41cinahthug8ugf)

# Discovery: News & Events Landing Page
https://www.cancer.gov/news-events

**Task:** The current right rail is a 2 column container, how do we address this content using the new home and landing page modules? Do we need a new module for this kind of content? How is the News & Events page being used? Is the media using this page?

**Reminder:** Dynamic list component functionality should remain the same but does the styling change? Consider how the style may change across all of its use cases (News & Events landing page, blog series, MRB page, etc.). 

**Note:** this will be a part of release 2 (not the initial release, but a subsequent release in release 2)

### Links to related tickets
- Direction Ticket: _TBD_
- Solution Ticket: _TBD_
- Build Ticket(s): _TBD_

### Timeline
Task will be defined to be completed during a certain sprint. Overall ticket to be complete before release 2 development begins.

### Definition of Done/Complete
Identified and conducted discovery work/tasks needed to inform a design solution for the News & Events landing page.

Mural Board Link: _TBD_

### Active Tasks
- [x]  Synthesis of any existing analytics data around use and function | **SP: 1** **[SPRINT 33]** @nicolecrom - Complete
	- *[Landing Pages News.pptx](https://github.com/NCIOCPL/ncids/files/9002138/Landing.Pages.News.pptx)*
- [x]  Identify additional analytics reports needed | **SP: 3** **[SPRINT 34]** @nicolecrom
	- [Outline in below comment](https://github.com/NCIOCPL/ncids/issues/482#issuecomment-1194446268)
	- [Landing Pages News.pptx](https://github.com/NCIOCPL/ncids/files/9183856/Landing.Pages.News.pptx)
- [x]  Stakeholder interviews @lburack @lizsiciliano
	- [x] Identify interviews to be conducted | **SP: 1** **[SPRINT 35]**
	- [x] Create a script | **SP: 2** **[SPRINT 35]** 
	- [x] Scheduling interviews (whomever is conducting the interviews will schedule) | **SP: 1** **[SPRINT 35 & 36]** 
	- [x] Conduct interviews | **SP: 1 / 3** **[SPRINT 36 & 37]** 
	- [x] Conducted additional interviews (not a part of initial scope) | **SP: 2** **[SPRINT 38]**
	- [x] Prepare and share summary of interview findings | **SP: 3** **[SPRINT 38]**
	- [x] https://lion.box.com/s/x6mxzce1bs9ev68ydykrixt7fk0398dj
- [x]  High-level heuristic review of News and Event Landing Pages | **SP: 3** **[SPRINT 38]** @lizsiciliano @monika-jaeger  
	- [x] Review
	- [x] Reporting
	- [x] https://lion.box.com/s/vdr50kepic9q6vpqec8kv9ulxfup7vnb
- [x]  Competitive analysis around use of News and Event Landing Pages | **SP:5** **[SPRINT 39/40]** @lizsiciliano @lburack @monika-jaeger 
	- https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1664464080032/14fa17c1eaa27b7954054e91502ee678c38184c8?sender=lindsayburack3067

### Inactive Tasks
Moved from Sprint 39 to a future card, for which comps and/or prototypes are available:
- [ ]  Technical or accessibility flag: devs to review initial discovery to note red flags, specifically the following - preliminary "gut check" review @sarinapadilla @bryanpizzillo 
	- *Link to flag report*
	- Dynamic lists
	- Anything related to two column paragraph

Removed from scope of this ticket:
- [ ]  User testing and synthesis (Empathy Map as a deliverable) | **[SPRINT 40 - different sprint than A-Z testing]** 
	- [ ] User testing (includes sub-tasks)
	- [ ] Reporting (includes empathy mapping session

### What do you want to learn?
- What are the goals and/or mission?
- Who is our audience?
	- As a [role], I want [feature], so that [benefit]
- What are the known user expectations?
- What goals and tasks should be supported?
- What known user problems do we need to solve?
- What are the required features?

### Organization Goals
1. _TBD_

### Key Opportunities
*Document they discovered key opportunities and add a p1, p2, p3, or p4 to establish its priority*
1. _TBD_

### Resources and Links
_TBD_

### Notes
_TBD_

**Comment by meglake** [comment]
We will storypoint when we go to put this into a sprint so we can break down the tasks for the sprint (ie not all tasks can be done in a single sprint, this ticket will act as more of an epic/meta).

**Comment by laurelthrash** [comment]
Sprint 33: Committed to a total of 5 sprint points in sprint 33, outlined in the tasks.

**Comment by nicolecrom** [comment]
I did find the existing research on the landing page but it was from 2020 looking back on 2019 data so we will need to pull more up to date analytics.
[Landing Pages News.pptx](https://github.com/NCIOCPL/ncids/files/9002138/Landing.Pages.News.pptx)

**Comment by nicolecrom** [comment]
Traffic to page is less than 40k annually
- Visits are 84% desktop, 14% mobile
- 33% enter on to the page, About half bounce 
- 96% of traffic that didn’t enter directly on to the page, go there using mega menu

This page seems less central to navigating the site section than the past
- Visits to this page have been flat over the last 3 years, while overall traffic to the site section has gone up a lot 
- During the same time, blog landing page traffic went up 66%

Feature usage
- 9% of visits click a feature card
- 7% click on a recent news release link
- Media Resources, Blog, and Events in right rail each have clicks from 1% of visits

Attached is full analysis [Landing Pages News.pptx](https://github.com/NCIOCPL/ncids/files/9183856/Landing.Pages.News.pptx)

**Comment by laurelthrash** [comment]
Sprint 35: completed 3 SP

**Comment by laurelthrash** [comment]
Update 09/31: on track to complete interviews in Sprint 37.

**Comment by laurelthrash** [comment]
Completed 3 SP in Sprint 37. Moving to Sprint 38.

**Comment by laurelthrash** [comment]
8 SP completed in sprint 38. Move next points to sprint 39.

**Comment by laurelthrash** [comment]
Active sub-tasks are complete. As noted above, determined that certain sub-tasks should be pulled out of this ticket. Closing this ticket.
