### ISSUE TITLE
Review & Revise: Document Standards & Guidance for NCI Graphics

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#484]
### Description
Issue #450 resulted in the creation of PDF documentation outlining standards and guidance for NCI graphics to align with the ongoing work to redesign [cancer.gov](http://cancer.gov/) using the USWDS. This ticket encompasses:
- reviewing the developed PDF by internal stakeholders
- updating the PDF based on review; and  
- saving the final PDF to the appropriate location. 

**Parent Issue:** #450 

### Sub-Tasks
- [x] Submit PDF to Lynn for review
- [x] Obtain feedback from Lynn
- [x] Incorporate feedback from Lynn by editing the PDF
- [x] Save PDF to https://lion.box.com/s/subrxbisnc4uhn3m9m7krlq2juzam14z (…/NCI/Design/Style Guides) - as indicated in parent ticket
- [x] Notify the team via the #redesign-ds Slack channel that this is saved and the issue is closed

### Notes
*None at this time*

**Comment by meglake** [comment]
Feedback from 6/14 end of sprint demo: please add white space requirements around logo. Once complete, add link to document to this ticket and close out. Thank you!

**Comment by meglake** [comment]
@a-heirtzler  completed edit from Lynn. Will close out this ticket and open a new one depending on if further feedback comes through.
