### ISSUE TITLE
["Inventory: Non-Image and Non-Video Carousels (Exclude DCEG Connect)"]

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#487]
*Generate an inventory of all non-image and non-video carousels that exist on cancer.gov and all microsites, excluding DCEG Connect. Please see the attached screenshot for an example of this type of carousel.*

**Parent Issue:** N/A

### Sub-Tasks
- [ ] Create inventory document, determining the appropriate fields to display
- [ ] Perform inventory search on cancer.gov and all microsites, excluding DCEG Connect
- [ ] Populate the inventory document with findings 
- [ ] Share inventory with the team and mark this issue as closed

### Notes

* This request originated as a Slack request from Bryan on 05/25/22 at 2:10pm in #redesign_ds
* Please see the above Slack conversation for preliminary insights from the team
* This request must be completed in Sprint 31

![Sample Carousel](https://user-images.githubusercontent.com/102998716/171277524-d343d895-1e0a-478a-9d9f-897bf4a1dfa0.png)

**Comment by meglake** [comment]
Will close this ticket as the example noted is likely the only case. Will double check with @bennettcc that DCEG doesn't have any of these on their site. Bryan will also reach out to Min to search on class name.
