### ISSUE TITLE
Inventory all home and landing pages on platform & identify any content/functionality that will not work with new home & landing page modules

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#497]
*Description of what is to be accomplished.*
Inventory all home and landing pages on platform & identify any content/functionality that will not work with new home & landing page modules

### Sub-Tasks
- [x] Create an inventory of all home and landing pages across the platform (include all microsites and Spanish pages)
- [x] Review all home and landing pages and create a list of any content/functionality that will not work with the new home and landing page modules that will be build for release 2
- [ ] Identify and list content owners for each home and landing page [This will help inform content discussions for release 2 launch]
- [ ] Add this information to our 'Team Resources' channel wiki in Teams

### Notes

* This ticket is just to inventory and review all home and landing pages across the platform and then identify any unique content/functionality that will not work with the new home and landing page modules that are being build for release 2. Any additional work will be handled in new tickets.
* This will be a manual report.

**Comment by laurelthrash** [comment]
Blank inventory document created by @lburack: [20220712 Home-Landing-Inventory.xlsx](https://github.com/NCIOCPL/ncids/files/9102969/20220712.Home-Landing-Inventory.xlsx)

**Comment by meglake** [comment]
@mworrest, thank you for pulling together! Looks like the only landing pages that need some extra consideration are all ready in progress (Cancer Types #491 & News & Events #482). For the initial launch of release 2, these two pages will stay as is. We'll do an iterative launch to roll out any additional components that are needed.

**Comment by meglake** [comment]
@mworrest, there is only one home and landing page content type being used on both CCG and SBIR (their home page) see screenshots attached and let me know if you think these will fit into the new modules that are being created. Thanks!

![Image](https://user-images.githubusercontent.com/41208873/180516893-63c4e27d-655a-4ac1-83ca-82d75f4b461b.png)
![Image](https://user-images.githubusercontent.com/41208873/180516892-d6dc258a-8ad1-4b01-8c61-b769f2808904.png)

**Comment by bennettcc** [comment]
Closing ticket as complete
