### ISSUE TITLE
Update footer icon styles

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#499]
> **ESTIMATE** TBD

Update footer component styles to support USWDS + NCIDS icons (new as of #431) in the footer.

Footer before:
![Screen Shot 2022-06-28 at 4 47 06 PM](https://user-images.githubusercontent.com/85901679/176305868-f5a1c453-7b60-45fc-9283-638d89803ec2.png)

Updated footer:
![Screen Shot 2022-06-28 at 4 48 39 PM](https://user-images.githubusercontent.com/85901679/176306128-ea40f515-b43f-486d-9f65-68b2aa0c9201.png)

Invision mocks have all been updated for size and spacing: https://publicis.invisionapp.com/overview/Header-&-Footer-Wireframes-cl17806xjx3ho01x42xix33gc/screens?sortBy=1&sortOrder=1&viewLayout=2

### Tasks

- [x] Update ncids-css
- [x] Update storybook and regression images
- [x] Update example js site
- [x] Update preview in the gatsby doc site

### Dev notes

* Use USWDS for all icons except for Syndication and Linkedin, these are newly created for NCIDS
* Hard code SVGs for now, but this is not a long term solution. How we do icons long term will be discovered sometime between MVP1 and 2 in #434
 

### Related Tickets
* Original design ticket: #431
* Prerequisite for ticket:  https://github.com/NCIOCPL/cgov-digital-platform/issues/3216
* Follow on DS ticket: #434
