### ISSUE TITLE
Move `.hidden` to target list instead of section element

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#501]
> **ESTIMATE** 1

The `.hidden` class that is used to toggle collapsible sections is in the wrong location, causing unwanted side effects on the Drupal site. Move `.hidden` to the content that actually hides/shows content.

## Tasks
- [x] Update documentation site code (live preview and react component)
- [x] Update Storybook site code
- [x] Update Example site code
- [x] Update `ncids-css` to target the list element instead of the section element
- [x] Update `ncids-js` to target  target the list element instead of the section element, update any a11y if necessary

**Comment by bennettcc** [comment]
This is a blocker for: https://github.com/NCIOCPL/cgov-digital-platform/issues/3216
