### ISSUE TITLE
Baseline Discovery: Section Navigation

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#51]
# Baseline Discovery for Section Navigation 

*Description of what is to be accomplished.*

> **ESTIMATE** TBD

### Resources:
* Navigation Discovery Mural: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1602095625783/fa27d5eda78546183c03d428ffee7dc1acfd7fa8
* Design Burst: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1617994245461/f3ec3fa9ae24134ad7b6d4d0c944759dfeeac72f
* NOTION: https://www.notion.so/Secondary-Navigation-1a075f20a14c431da4050436083455bc

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] Inventory and analysis of content type features (Creation of article with all possible features, screen captured)
- [x] Creation of Mural board to capture discovery (logical groupings of sub-features, grids for analysis)

 
### Sub-Tasks
Baseline Discovery
- [x] Heuristic review of feature and sub-features @sewallaa 
- [X] Secondary research compilation and synthesis 
- [x] Confirm and add to analytics data analysis and synthesis on Notion (@nicolecrom )
- [X] Identification of potential USWDS equivalents
- ~Drupal reporting on use of features~

### Working Sessions

- inventory Mural review  (30 minutes)
- Analysis review and problem identification (1-2 hours)
### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction
