### ISSUE TITLE
Update Icons for Use in Presentations (PowerPoint Menu)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#526]
> **_Sprint Points: 3_**
> **_Parent Issue: N/A_**

#### Summary
Issue: The team currently references a PowerPoint (PPT) file that includes the icons available for use in presentations. The PPT file is a menu of icons to choose from and is housed on myNCI ([link here](https://mynci.cancer.gov/topics/nci-icons-use-presentations)). The existing icons need to be refreshed to reflect the new look and feel developed during the Redesign project. 

Goal: Update icon PPT menu to include a refreshed collection of icons that is more streamlined and consistent with updates made during the Redesign project.  

#### Sub-Tasks
- [x] Determine the icons that need to be replaced/condensed/streamlined
- [x] Create new collection of icons to replace the existing collection of icons found on the PPT menu
- [x] Conduct internal review of the icons
- [x] Update icons based on internal feedback
- [x] Share icons with client (08/30 @ 9:30am)
- [x] Update icons based on client feedback
- [x] Receive final client approval (sent to Lynn & Anna via email on 09/01, requested review by 09/07)
- [x] Send final PPT to Lynn/Anna to confirm we can replace the existing version on myNCI
- [x] Obtain opinion from OCS regarding survivorship icon (decision 09/23: post the PPT using the icon with raised hands to represent survivorship and add a ticket to our backlog to revisit the survivorship icons in a future sprint). 
- [x] Replace existing PPT on myNCI with the updated PPT menu (PPT only, submit via a JIRA ticket to add to myNCI)

**Comment by laurelthrash** [comment]
Add to 08/23 meeting with Lynn.

**Comment by laurelthrash** [comment]
Sprint 35: completed 3, move 3 into Sprint 36

**Comment by dcvijanovic1k** [comment]
Hi @meglake & @laurelthrash - PPT of new icons attached. As Aaron mentioned in our meeting - a couple icons will need to be worked on collaboratively: "Understanding" and "Survivorship". Any questions, please let me know
[NCI_Icons_0822_V1.pptx](https://github.com/NCIOCPL/ncids/files/9301273/NCI_Icons_0822_V1.pptx)
.

**Comment by laurelthrash** [comment]
@meglake provided feedback via Slack PPT attachment on 08/11. @dcvijanovic1k to review and revise as needed prior to client mtg. on 08/23.

**Comment by laurelthrash** [comment]
Update: plan to review with federal team on 08/30 @ 9:30am (moved from 08/23 @ 9:30am) Cc: @meglake @dcvijanovic1k

**Comment by laurelthrash** [comment]
Update: Moving from Sprint 36 to 37 since remainder of work has shifted to Sprint 37.

**Comment by laurelthrash** [comment]
Update: targeting completion by 08/29 for final internal review.

**Comment by laurelthrash** [comment]
Update 08/30: Reviewed PPT icons with the federal team during 9:30am meeting. Provided following feedback: 

- Understanding (slide 2): approved proposed direction
- Survivorship (slide 5): connect with Becky and Anne (discussed ideas: uplifting arms/companionship, a bell/rope, hiking/neutral activity)

Next steps: Update survivorship icon (with several choices). Share Survivorship with Becky/Anne for input. Send full PPT - including survivorship - to internal federal group for further review. 

Cc: @meglake @dcvijanovic1k

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash & @meglake - updated PPT attached. Any questions/comments, please let me know. Thank ya- 
[NCI_Icons_0822_V2.pptx](https://github.com/NCIOCPL/ncids/files/9462465/NCI_Icons_0822_V2.pptx)

**Comment by laurelthrash** [comment]
Will conduct one final internal review during 1pm DSM meeting, then will share with Lynn/Anna via email. Cc: @dcvijanovic1k

**Comment by laurelthrash** [comment]
Reviewed internally on 08/31: 
- Remove "Preventing" from slide 4 @dcvijanovic1k 
- Clear out old icons @dcvijanovic1k 
- After updated, next step: LT to send to Lynn/Anna for alignment (specifically request feedback on the proposed direction for survivorship on slide 5) @laurelthrash

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - here's the updated PPT for client review. Please let me know if you have any questions or concerns.
[NCI_Icons_0822_forClientReview_V1.pptx](https://github.com/NCIOCPL/ncids/files/9472426/NCI_Icons_0822_forClientReview_V1.pptx)

**Comment by laurelthrash** [comment]
Sent to Lynn/Anna via email on 09/01 and requested feedback by Wednesday 09/07.

**Comment by laurelthrash** [comment]
Update: met with the federal team, including OCPL peers with experience with survivorship (Anne and Lou). In agreement on the icon that depicts a person with their hands raised. Cc: @dcvijanovic1k @chuckhrose @meglake

**Comment by dcvijanovic1k** [comment]
Hi @meglake and @laurelthrash - here's the updated PPT with the survivorship icon that was chosen. If you need anything else, please let me know!
[NCI_Icons_0822_forClientReview_V2.pptx](https://github.com/NCIOCPL/ncids/files/9576705/NCI_Icons_0822_forClientReview_V2.pptx)

**Comment by dcvijanovic1k** [comment]
Hi @laurelthrash - here's the updated PPT with the raised arms icon for survivorship. If you need anything else, please let me know! 
[NCI_Icons_V3.pptx](https://github.com/NCIOCPL/ncids/files/9627137/NCI_Icons_V3.pptx)

**Comment by laurelthrash** [comment]
Learned from OCS that their preference is to post the PPT to include the raised hands icon to represent survivorship. Team to move forward with replacing the existing PPT on myNCI. Meantime, we will add a ticket to our backlog to specifically review/revise the survivorship icon and consider alternatives in a future sprint.

**Comment by laurelthrash** [comment]
Submitted JIRA ticket for addition to myNCI: https://tracker.nci.nih.gov/browse/CGOV-16972

**Comment by laurelthrash** [comment]
Sub-tasks are complete. Closing this ticket.
