### ISSUE TITLE
Create DS Dev Tickets for Release 2 Iteration 1 (R2.1)

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#530]
Create DS Dev Tickets for all design system components prioritized for Release 2 Iteration 1 (R2.1). 

Iteration | Component Type | Component Variation | Priority
-- | -- | -- | --
R2.1 | [Hero](https://github.com/NCIOCPL/ncids/issues/534) | B. Hero Image  w/ Button & Light Text Box | 1.1
R2.1 | [Hero](https://github.com/NCIOCPL/ncids/issues/534) | E. Hero Image w/Button, Light Text Box & CTA Strip | 1.1
R2.1 | [Hero](https://github.com/NCIOCPL/ncids/issues/534) | G. CTA Strip Only | 1.1
R2.1 | [Guide Cards](https://github.com/NCIOCPL/ncids/issues/537) | A. Audience Guide Card Row | 1.1
R2.1 | [Promo Block](https://github.com/NCIOCPL/ncids/issues/538) | B. Alternating Promo Block - Dark Text Box | 1.1
R2.1 | [Inline Video](https://github.com/NCIOCPL/ncids/issues/539) | A. Video | 1.1
R2.1 | [Feature Card](https://github.com/NCIOCPL/ncids/issues/540) | B.  Feature Card Row - 3 Cards | 2.1

SP: placeholder for planning is 8, will re-examine after prioritization

### Sub-Tasks
**Sprint 36:**
- [x] DS dev tickets for R2.1 ready for internal review by Friday 8/12 at 1:30pm @blilianyu 
- [x] Sarina will start of Drupal Dev ticket versions for R2.1 @sarinapadilla 

**Sprint 37:**
- [x] Review all R2.1 tickets with Bryan/Paul K. (08/23) **Team**
- [x] Make updates to the tickets based on meeting with Bryan/Paul K. [Note: Redefine estimated SPs based on updates] @blilianyu

**Comment by meglake** [comment]
<html>
<body>
<div ccp_infra_version='3' ccp_infra_timestamp='1659968450218' ccp_infra_user_hash='4040218028' ccp_infra_copy_id='1588c4a9-c66f-463e-ac43-03f63add618f' data-ccp-timestamp='1659968450218'><html>

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<style>
table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	text-align:general;
	vertical-align:bottom;
	border:none;
	white-space:nowrap;
	mso-rotate:0;}
.xl146
	{font-weight:700;
	border:.5pt solid black;
	background:#E7E6E6;
	mso-pattern:black none;}
.xl169
	{border:.5pt solid black;
	background:#FFE3E3;
	mso-pattern:black none;}
.xl171
	{border:.5pt solid black;
	background:#FFE3E3;
	mso-pattern:black none;
	white-space:normal;}
</style>
</head>

<body link="#0563C1" vlink="#954F72">



Iteration | Component Type | Component Variation | Priority
-- | -- | -- | --
R2.1 | Hero | B. Hero Image  w/o Button & Light Text Box | 1.1
R2.1 | Hero | E. Hero Image w/Button, Light Text Box & CTA Strip | 1.1
R2.1 | Hero | G. CTA Strip Only | 1.1
R2.1 | Guide Cards | A. Audience Guide Card Row | 1.1
R2.1 | Promo Block | B. Alternating Promo Block - Dark Text Box | 1.1
R2.1 | Inline Video | A. Video | 1.1
R2.1 | Feature Card | B.  Feature Card Row - 3 Cards | 2.1



</body>

</html>
</div>
</body>
</html>

**Comment by laurelthrash** [comment]
Sprint 36: completed XX SP, carrying issue over to Sprint 37 and assigning new SPs

**Comment by laurelthrash** [comment]
Completed 3 SP in Sprint 37, move remainder to Sprint 38.

**Comment by laurelthrash** [comment]
Adding to approved backlog to track final items listed under "Sprint TBD." Otherwise, DS Dev tickets are complete for R2.1.
