### ISSUE TITLE
Create Drupal Tickets for Release 2 Iteration 1 (R2.1)

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#531]
Create Drupal Dev Tickets for all Drupal tasks and components prioritized for Release 2 Iteration 1 (R2.1). [Note - List to be added after 8/4 client prioritization meeting]

### Sub-Tasks
- [ ] Create individual tickets in digital platform repo for each Drupal tasks and components in R2.1
- [ ] Review tickets with design/IA team for alignment [PM to schedule meeting]
- [ ] Review tickets with dev team for alignment [PM to schedule meeting]
- [ ] Once ticket is complete, please include a check list on this ticket for items to include in Drupal dev tickets for future ticket creation (ie always include X type of requirements)

**Comment by meglake** [comment]
Closing this issue since it duplicates https://github.com/NCIOCPL/cgov-digital-platform/issues/3481
