### ISSUE TITLE
Research Plan: Test Mega Menu & Mobile Menu after MVP 1 Launch

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#533]
### Approach ###
**Phase 1: Prep and Execution**
1. Determine Testing Vehicle
2. Create Plan
3. Recruit for Study

**Phase 2: Analysis and Report Delivery**
1. Launch Study
2. Analyze and Report

### Sub-Tasks
**0. Pre-Planning**

- [x] Pull analytics at 2 month (02/15/23) mark prior to conversation with Anna/Federal team (e.g., click through rate, opening the menu, number of visits to L1 vs. L2, utilization of links in MM) @nicolecrom [https://tracker.nci.nih.gov/browse/CGOV-17774] [Complete in former DS Sprint 11]
- [x] Review analytics internally [Complete in former DS Sprint 11]
- [ ] Schedule time with Anna/federal team to have conversation regarding goals for testing [PM to schedule]
    - [ ] Verify with Anna/Federal team regarding specific desires for testing and what questions we want to answer
    - [ ] Determine how in-depth we want to go in regard to testing/scope
    - [ ] Share preliminary data, but note we are pulling fuller data in April

**1. Determine Testing Vehicle**

- [ ] Determine testing vehicle (e.g., live site, prototype)
- [ ] Secure testing vehicle
- [ ] If using a prototype: 
    - [ ] Create prototype
    - [ ] Review internally
    - [ ] Approve prototype

**2. Create Plan**

- [ ] Define study title
- [ ] Establish:
    - [ ] What we want to  accomplish during the study and what are the desired outcomes
    - [ ] What we want to learn from this research
    - [ ] If this includes mobile and desktop
- [ ] Create recruitment screener
    - [ ] Obtain federal approval via email
- [ ] Determine with federal team if wish to explore Spanish language user testing
- [ ] Create guide/script to walk through with participants
    - [ ] Obtain federal approval via email

**3. Recruit for Study**

- [ ] Kick-off recruiting (internal and external) for qualified participants to take part in scheduled moderated user sessions
- [ ] Create testing schedule

**4. Launch Study**

- [ ] Begin user testing with participants
- [ ] Conclude user testing with participants

**5. Analyze and Report**

 - [ ] Generate analysis/report with findings (desktop and mobile, as needed)
 - [ ] Determine next best step with research and prepare new tickets as needed

### Documentation ###

**Plan Details**
- Testing Prototype: INSERT
- Plan Title: INSERT
- Plan Description: INSERT
- Related Tickets: INSERT

**What do you want to learn from this research?**
- List the questions you would like to answer

**User / Audience**
- Who will be using this design? What personas / audiences are you considering?

## NOTES
- IMPORTANT: Connected to April 2023 read-out to address proposed solution of "Consider changes to optimize to click rates across different sections of the mega menu"
- Preliminary questions we have for user testing:
     - Headers vs. sub-headers
     - Does it function as expected (we changed on hover and on click)
     - Because on click opens the MM, we have "Explore XX" - is it clear that "Explore XX" is the link to the landing page? How about in Spanish? 
     - After you open the MM, is it obvious how to get to - as an example - the research page?

**Comment by laurelthrash** [comment]
Reviewed analytics on 02/22 from Jira ticket CGOV-17774 with internal team. Broader team does not see additional analytics needed before initiate conversations with federal team.

**Comment by laurelthrash** [comment]
Schedule time with federal team, to include: Nicole, Liz, PM, Lindsay/Adriana (optional)

**Comment by laurelthrash** [comment]
Updated ticket to adopt sub-tasks/outline of newly revised "User Research" template ticket.

**Comment by bennettcc** [comment]
Closing as not needed at this time
