### ISSUE TITLE
[META] Heros

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#534]
### Build hero component variations based on design specs/requirements documented in this ticket:

**R2.1:**
- [ ] B. Hero Image  w/o Button & Light Text Box 
- [ ] E. Hero Image w/Button, Light Text Box & CTA Strip
- [ ]  G. CTA Strip Only

**R2.2:**
- [ ] D. Hero Image w/o Button, Light Text Box & CTA Strip

**R2.3:**
- [ ] F. Hero Image w/o Button, Light Text Box & CTA Strip

**R2.4:**
- [ ] A. Hero Image w/Button & Dark Text Box
- [ ] C. Hero Image w/Button, Dark Text Box & CTA Strip

> **ESTIMATE** TBD

## Design Definition of Done
*When all criteria below are met.*

**Comment by blilianyu** [comment]
Overall Guidance for Hero components here
(each build ticket will have a specific guidance for the variation)
