### ISSUE TITLE
Update Design: Grants & Training Spanish Solution

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#536]
*Description: Per #418, developed a design solution for the Grants & Training landing page (Spanish). Met with the federal team on 08/09/22 who provided feedback on the proposed comps. This ticket is to capture the proposed changes by the federal team.*

**Related Ticket:** #418 

### Sub-Tasks
- [x] Fedora to review initially proposed content/information provided in [CGOV-16215](https://tracker.nci.nih.gov/browse/CGOV-16215) and revise **[Sprint 36]**
**[Completed] New content from Fedora:** [Subvenciones y capacitación.docx](https://github.com/NCIOCPL/ncids/files/9301214/Subvenciones.y.capacitacion.docx)
- [x] Create a comp to include revised content and revised based on feedback from 8/9 client meeting and using prioritized components in R2.1 ([prioritization Mural board found here](https://app.mural.co/invitation/mural/publicissapient7269/1658156577586?sender=uc8881d65820946a13d002641&key=56676dbc-a73d-4da1-ae7c-225039e1d251)) **[Sprint 37]**
- [x] Create a comp using revised content using any component variation that make the most sense for the content. **[Sprint 37]**
- [x] Review with clients on 09/20 (postponed from 09/13) to determine next steps **[Sprint 38]**
- [x] Update language at the top of each updated comp to include the same Spanish text **[Sprint 39]** SP:1
- [x] Conduct final review of comps with Spanish team (postponed from Oct. 19 @10am due to time sensitive priorities, and rescheduled for 11/2) **[Sprint 42]**

### Notes
**Latest comps:**
- Option 1 (Release 2.1): https://publicis.invisionapp.com/console/NCI-DS-Spanish-cl2qe0hwx001r01aa3ajtac6t/cl8k8ss2p03i1012g2umt5tbp/play
- Option 2 (Release 2.3): https://publicis.invisionapp.com/console/NCI-DS-Spanish-cl2qe0hwx001r01aa3ajtac6t/cl8k8ss2p03i2012ga7ubdxvs/play
- Option 3 (Release 2.5): https://publicis.invisionapp.com/console/NCI-DS-Spanish-cl2qe0hwx001r01aa3ajtac6t/cl8k8ss2p03i3012g1syl46gw/play

**Previous comps:**
- Option 1: https://publicis.invisionapp.com/console/NCI-DS-Spanish-cl2qe0hwx001r01aa3ajtac6t/cl6m7rlmg00b1019cdrmi39j7/play
- Option 2: https://publicis.invisionapp.com/console/NCI-DS-Spanish-cl2qe0hwx001r01aa3ajtac6t/cl6m7rlmg00b2019c5kg3cmjz/play

**Comment by laurelthrash** [comment]
Update: planning to review during Thursday 09/01 internal meeting.

**Comment by laurelthrash** [comment]
Outstanding changes to the comp following 08/31 internal mtg. (@blilianyu)
- Add optional title for Guide card to all comps to row to indicate that Spanish translations are not available
- Add the link to the test in the html block?

Next Steps: 
- Target Tues. 09/13 to review with Lynn/Anna/Fedora

Notes: 
- Comps show what future layouts for future releases (with available future components)

**Comment by laurelthrash** [comment]
Completed 3 SP in Sprint 37, moving remainder to Sprint 38. Confirmed to review with federal team on 09/13.

**Comment by laurelthrash** [comment]
Completed 3 SP in Sprint 37, moving remainder to Sprint 38. Confirmed to review with federal team on 09/13.

**Comment by laurelthrash** [comment]
Completed 3 SP in Sprint 37, moving remainder to Sprint 38. Confirmed to review with federal team on 09/13.

**Comment by laurelthrash** [comment]
Postponing federal review to 09/20 to ensure Fedora is available to attend.

**Comment by laurelthrash** [comment]
Met with federal team on 09/20

Actions:
- Fedora feels that the comps have some tweaks needed
- After we finish the spike, can come back and see if we can make the style translatable. If it requires higher LOE or is not possible, then we will set-up content conversations to ensure we are aligning English and Spanish at the same time. 

Notable decisions/discussion:
- Fedora stated that presenting content in English so quickly feels abrupt
- We are not necessarily looking for agreement on comps, rather, these are the components we have available at different iterations

**Comment by laurelthrash** [comment]
Final step for comp: meet with Carolina and Monica to finalize comp prior to content decisions.

**Comment by laurelthrash** [comment]
Fedora and Laurel met on 09/26. We will update the three new comps to include the same Spanish text at the top of each comp (screen shot of discussed text location). Fedora to provide the updated Spanish text for replacement in the three comps. Once updated, Fedora will select two of the new comps to present and discuss with the Spanish team. Meeting to include: Fedora, Monica, Carolina, Laurel. Cc: @blilianyu 
![image](https://user-images.githubusercontent.com/102998716/192334172-646a7de0-e24d-4fb2-b0e5-c9202a1ba790.png)

**Comment by laurelthrash** [comment]
Updated language for the comps is included in the attached document: [Grants and Trainig LP_ES (2).docx](https://github.com/NCIOCPL/ncids/files/9656038/Grants.and.Trainig.LP_ES.2.docx). Cc: @blilianyu

**Comment by blilianyu** [comment]
@laurelthrash Comps have been updated

**Comment by laurelthrash** [comment]
Sprint 39 - include SP1. Move card to Sprint 40 for presentation to the Spanish team and closing out of the ticket.

**Comment by laurelthrash** [comment]
Shared comp with Carolina on 11/1. Carolina confirmed comps looks good. Notably: 
- Tend to like the 2nd option (R2.2) best
- Like the factoid module (available R2.5), but explained that it is a lower priority and not available until R2.5
- Will discuss content decisions with content owners when we move to implement Release 2 components
- Explained that can exclude certain content, if desired, until a specific component is available

Next steps:
- Close this ticket
- Revisit component selections when we move to implement H&LP components
- Information from [#3520](https://github.com/NCIOCPL/cgov-digital-platform/issues/3520) will inform if the English and Spanish versions of this page need to launch at the same time

Cc: @blilianyu @meglake
