### ISSUE TITLE
[META] Guide Cards

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#537]
### Build guide card component variations based on design specs/requirements documented in this ticket:

**R2.1:**
- [x] A. Guide Card with Image and Description #614 

**R2.2:**
- [x] C. Default Guide Card #648 

**Future:**
- [ ] B. Guide Card with Background Image #597

> **ESTIMATE** TBD

### Design Definition of Done
*When all criteria below are met.*

**Comment by sarinapadilla** [comment]
Closing this, as we have completed building the components decided upon for Home and Landing pages.
