### ISSUE TITLE
[META] Promo Block

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#538]
### Build promo block variations based on design specs/requirements documented in this ticket:

**R2.1:**
- [x] B. Alternating Promo Block Dark #550 
- [x] F. Promo Block No image Dark #598 

**R2.2:**
- [x] A. Light Promo Block with Image #790 
- [x] E. Promo Block Light #791 

**R2.3:**
- [ ] D. Full-width Promo Block Dark #712

**R2.4:**
- [ ] C. Full-width Promo Block Light

> **ESTIMATE** TBD

### Design Definition of Done
*When all criteria below are met.*

**Comment by blilianyu** [comment]
Overall Guidance for Promo Block components
(each build ticket will have a specific guidance for the variation)

**Comment by sarinapadilla** [comment]
Internal decision was made to not implement the full-width promo block as it is basically just a hero.
