### ISSUE TITLE
[META] Feature Card

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#540]
### Build feature card component variations based on design specs/requirements documented in this ticket:

**R2.1:**
- [x] B.  Feature Card Row - 3 Cards #605 

**R2.2:**

**R2.3:**
- [ ] C.  Multiple Link Feature Card Row (dynamic) - 3 Cards #713 
- [ ] D. Thumbnail Card - Optional Description #599 

**R2.4:**
- [ ] A. Feature Cards -  2 Cards

> **ESTIMATE** TBD

### Design Definition of Done
*When all criteria below are met.*

**Comment by blilianyu** [comment]
Overall Guidance for Video components
(each build ticket will have a specific guidance for the variation)

**Comment by sarinapadilla** [comment]
Closing this, as we have completed building the components decided upon for Home and Landing pages.
