### ISSUE TITLE
Design loading feature for megamenu and mobile menu["Short Name"]

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#546]
Need a loading feature for mega menu and mobile menu to inform the user that the menu is in the process of being loaded for slower connections.

### Sub-Tasks
- [ ] Determine loading feature style and functionality and align with USWDS if possible
- [ ] Mock up loading feature for megamenu and mobile menu
- [ ] Review with design and dev teams and revise as needed
- [ ] Get sign off from clients
- [ ] Create build ticket

**Comment by monika-jaeger** [comment]
Looks like USWDS has a loading indicator in V3 as an svg. 
https://github.com/uswds/uswds/blob/e75f3f3/packages/usa-file-input/src/img/loader.svg
I am not sure if we can pull this in from V3? We'll need to take a developer to take a look at this. 

If we can't use V3, then we can look at other options. I saw others mention in the GSA Slack channel that another option is to pull a [spinner icon](https://fontawesome.com/search?q=spinner&o=r&c=spinners&s=solid) from [Font Awesome](https://fontawesome.com/) and use the `fa-spin` class to [animate](https://fontawesome.com/docs/web/style/animate) it.

**Comment by blilianyu** [comment]
CMS's design system is also based off of USWDS. Their loading icon is much smoother than USWDS V3. 
 
https://design.cms.gov/components/spinner/?theme=core

**Comment by laurelthrash** [comment]
Discussed this issue during Dev Backlog Grooming on 1/5/23 - @bryanpizzillo identified that there is a 2.0 loader that is hidden in USWDS source code. We will move forward with development using the the 2.0 loader to visualize and obtain subsequent approval from the client. Thus, we will hold on any comps related to the loader while development work is underway. C.gov ticket #574 is in progress. 

Cc: @meglake @blilianyu @monika-jaeger

**Comment by laurelthrash** [comment]
Moving to Approved Backlog while development work is underway
