### ISSUE TITLE
Build: Feature Card - B. Feature Card Row - 3 Cards

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/ncids#552]
### Build **Feature Card Row** variation of feature card component based on design specs/requirements documented in this ticket

> **ESTIMATE** 5

### Styling: 
*Anatomy of a component*
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

### Behaviors
*Summary of state changes and behaviors. AC's are more detailed.*
- 4:3 image on Widescreen, Desktop (1400 and less)
- 1:1 image on Tablet Large (880 and less)
- 16:9 image on Tablet (640 and less)
- No image on Mobile Large & Mobile (480 and less)

### InVision: 
  * Widescreen (1400) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0282013t7d5l1urr/play
  * Desktop (1024) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0283013t4nhh03fd/play
  * Tablet Large (880) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0284013t4aj381ri/play
  * Tablet (640) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0285013tb131hhax/play
  * Mobile Large (480) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0286013tckea7wt7/play
  * Mobile (320) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0287013t51y80sss/play

### Acceptance Criteria for Behaviors 
*If a component changes between breakpoints, or things show/hide, that gets captured here* 

```gherkin
As a user, I would like to see a feature card row, so that I can quickly scan the featured content. 


Scenario: User views a page with a feature card row on Widescreen or Desktop  
Given a user is viewing a landing page with a feature card row 
  And the browser width is 1400px or less
Then a feature card row will appear 
  And the 4:3 crop of the image associated with the feature card should appear (following our image rules)  
  And the title of the feature card should be font size theme token LG
  And the description will appear 
  And clicking anywhere on the card will take the user to the corresponding page

Scenario: User views a page with a feature card row on Tablet Large  
Given a user is viewing a landing page with a feature card row 
  And the browser width is 880px or less 
Then a feature card row will stack horizontally 
  And the 1:1 crop of the image associated with the feature card should appear on the left
  And the title of the feature card should be font size theme token LG
  And the description will appear on the right
  And clicking anywhere on the card will take the user to the corresponding page

Scenario: User views a page with a feature card row on Tablet
Given a user is viewing a landing page with a feature card row 
  And the browser width is 640px or less
Then the feature card row will stack 
  And the 16:9 crop of the image will appear
  And the title of the feature card should be font size theme token LG
  And the description will appear 
  And clicking anywhere on the card will take the user to the corresponding page

Scenario: User views a page with a feature card row on Mobile Large or Mobile
Given a user is viewing a landing page with a feature card row 
  And the browser width is 480px or less
Then the feature card row will stack 
  And the image will not appear
  And the title of the feature card should be font size theme token LG
  And the description will appear 
  And the container shadow will not appear 
  And clicking anywhere on the card will take the user to the corresponding page
```

---

### Scenarios
- Feature card by itself
  - Short title: CRCHD Diversity Training
  - Short description: Treatment for severe COVID-19 with interferons decreased the viral load of SARS-CoV-2, a new study found. 
  - Button 1: Find a Cancer Type
  - Button 2: Newly Diagnosed
  - Button 3: Cancer Treatment & Side Effects
  - Button 4: Contact Us for Help
  - Spanish title: Capacitación en diversidad CRCHD
  - Spanish description: El tratamiento para la COVID-19 grave con interferones disminuyó la carga viral del SARS-CoV-2, según encontró un nuevo estudio.
  - Button 1: Encontrar un tipo de cáncer
  - Button 2: Recién diagnosticado
  - Button 3: Tratamiento y efectos secundarios
  - Button 4: Póngase en contacto con nosotros para obtener ayuda

- Feature card in a container with other card(s)
**Card 1**
  - Short title: CRCHD Diversity Training
  - Short description: Treatment for severe COVID-19 with interferons decreased the viral load of SARS-CoV-2, a new study found. 
  - Button 1: Find a Cancer Type
  - Button 2: Newly Diagnosed

**Card 2**
  - Long title: Grant Application Development, Submission, Review, & Award
  - Long description: In patients with certain variations in the OAS1 gene, treatment for severe COVID-19 with interferons, a type of protein that can help the body’s immune system fight infections, decreased the viral load of SARS-CoV-2, a new study found. 
  - Button 1: Cancer Treatment & Side Effects of Cancer Treatment
  - Button 2: Grants and Training
  - Button 3: Funding Opportunities 
  - Button 4: Research Program Contacts
  - Button 5: Ongoing Research Studies
  - Button 6: Contact Us for Help

### Prerequisites
- #605 

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

**Comment by blilianyu** [comment]
### NCIDS Guidance
- [ ] *When to use component and its variant(s)*
  * Used when needed to feature content
- [ ] *When to consider something else*
  * If only 1 or 2 featured content, use an alternating promo card
- [ ] *Usability Guidance*
  * Must have 3 cards

**Comment by sarinapadilla** [comment]
Closing this ticket, as we have the individual component ticket (#605) that cover the row scenarios.
