### ISSUE TITLE
Compile Megamenu, Footer, and logos for all microsites

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#555]
To prepare for ACSFdev testing please compile all text/links for megamenu and footer as well as the updated logo files for all microsites on the platform:

- Cancer.gov (logos only - English & Spanish)
- NCI CONNECT (https://www.cancer.gov/rare-brain-spine-tumor/)
- NCI CONNECT - Spanish (https://www.cancer.gov/rare-brain-spine-tumor/espanol)
- MyPART (https://www.cancer.gov/pediatric-adult-rare-tumor/)
- DCEG (https://dceg.cancer.gov/)
- Physics (https://physics.cancer.gov/)
- Nano (https://www.cancer.gov/nano/)
- CCG
- SBIR

### Sub-Tasks
- [x] Compile text/links for megamenu and footer for each microsite
- [x] Create new logo files for each microsite based on guidance from Paul A.
-- [ ] Please add Box link to logo files when done
- [x] Confirm logo files are good to go with Paul A.
- [x] Revise ticket #433 with new guidance from Paul A. for future reference and add a page to 'Team Resources' wiki (see final comment on this ticket for documentation).

**Comment by acsnedegar** [comment]
The logos are in review with Kate and Paul: https://codesandbox.io/s/loving-hypatia-0y5no6?file=/index.html

**Comment by acsnedegar** [comment]
[Compile Megamenu, Footer for all microsites.docx](https://github.com/NCIOCPL/ncids/files/9395716/Compile.Megamenu.Footer.for.all.microsites.docx)

Hi @meglake - I'm attaching the compiled links/text for the microsites. I was able to pull the latest links from SBIR and CCG from the cms so assuming those are up to date but if not, might need to revisit this document later. I added some overall questions and comments in word for things I wasn't sure about. 

@arcepaul - please let @monika-jaeger or I know if you need anything else for the logos or if you are all set with where we landed last week. I can go ahead and download the svgs from the link above if they are good to go and add to Box so they are there too.

**Comment by laurelthrash** [comment]
Complete, with the exception of 1) final review by @meglake; and 2) adding documentation for this process to the ticket.

**Comment by laurelthrash** [comment]
Update: The logos have been reviewed by Kate and we are good to go. Linking this ticket to our YAML (#564)  and HTML (#565) tickets.

**Comment by acsnedegar** [comment]
Here is the documentation for the logo for web creating process: https://lion.box.com/s/ba2w2yth447lvc1xa7w7ndf61natnxbu

The logos live here: https://lion.box.com/s/74kvgh0yu0svumd70lcx8qwzi54jfoop

**Comment by laurelthrash** [comment]
Update 08/30: @dcvijanovic1k to test the documentation before finalizing. Cc: @acsnedegar @monika-jaeger

**Comment by laurelthrash** [comment]
Updated document with ML + LT comments: 
[Compile.Megamenu.Footer.for.all.microsites_ML_LT.docx](https://github.com/NCIOCPL/ncids/files/9586709/Compile.Megamenu.Footer.for.all.microsites_ML_LT.docx)

**Comment by laurelthrash** [comment]
Closing this ticket as all sub-tasks are complete.
