### ISSUE TITLE
Create HTML File for Content of Footers (Enterprise & Microsites)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#565]
To prepare for ACSF-dev testing, please compile the HTML file for content of the footers for the enterprise CGov site and all microsites on the platform:

| Microsite  | Owner | Status | URL | Added to Prod |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Cancer.gov  | Megan | Complete | https://www.cancer.gov/ | Yes |
| NCI CONNECT  | Megan  | Complete | https://www.cancer.gov/rare-brain-spine-tumor/ | Yes |
| NCI CONNECT - Spanish | Megan  | Complete | https://www.cancer.gov/rare-brain-spine-tumor/espanol | Yes |
| MyPART  | Laurel | Complete | https://www.cancer.gov/pediatric-adult-rare-tumor/ | Yes |
| DCEG | Laurel | Complete | https://dceg.cancer.gov/ | Yes |
| Physics | Laurel | Complete | https://physics.cancer.gov/ | Yes |
| Nano | Laurel | Complete | https://www.cancer.gov/nano/ | Yes |
| CCG | Laurel | Complete | https://ccg.cancer.gov/ (not yet live) | Yes |
| SBIR | Laurel | Complete | https://sbir.cancer.gov/ | Yes |

Notes:
- _Insert notes as they arise_

### Sub-Tasks

- [x] Create HTML file for each site
- [x] Test HTML code on ODE to confirm it's working properly (spot check)
- [x] Upload final files to [this folder](https://teams.microsoft.com/_#/files/Team%20Resources?threadId=19%3Ac8d9fd4fe9e0466db1d762af612c456b%40thread.skype&ctx=channel&context=Megamenu%2520YAML&rootfolder=%252Fsites%252FNCI-OCPLNewCgovUXDesignSystem%252FShared%2520Documents%252FDocumentation%2520and%2520Checklists%252FMegamenu%2520YAML)
- [x] Document footer steps in Teams wiki (under Team Resources channel))
- [x] Document any unknown links/content that we need to discuss with each DOC/Microsite owner

### Related Tickets
- #555

### Notes
*HTML is used to define the footer in the CMS. YAML is used to define the megamenu in the CMS.*

**Comment by laurelthrash** [comment]
Completed a spot check of the HTML files on ODE 476.

**Comment by laurelthrash** [comment]
Closing ticket as HTML files are complete. Final files saved to link referenced in description.
