### ISSUE TITLE
`usa-site-alert`: move .hidden to target instead of section element

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#566]
ESTIMATE 2

## Description 

The .hidden class that is used to toggle collapsible sections in the NCIDS Site Alert Component is in the wrong location, causing unwanted side effects on the Drupal site. Move .hidden to the content that actually hides/shows content. 

## Tasks
- [x]  Update ncids-css to target the list element instead of the section element
- [x]  Update ncids-js to target target the list element instead of the section element, update any a11y if necessary
- [x]  Update Storybook tests - no regression tests changes are expected
- [x]  Ensure there is no other code that has these classes because they should only be added with javascript, if it's there, remove it to the correct HTML:
    - [x] DS documentation 
    - [x] Example js site
    - [x] Other Storybook tests that do not have expanded content 
    - [x] Jest tests

## Notes
* See #501 , we did this for footer. Footer collapse and site alert collapse has similar features and therefore code
    * Dev note on the code duplication: we can combine them later, we wanted to build working features first then get requirements
* See VS's comment about original requirements https://github.com/NCIOCPL/ncids/issues/262#issuecomment-1040381290

**Comment by bennettcc** [comment]
1 SP completed during S36, 1 remaining for S37
