### ISSUE TITLE
Allow NCIDS site alert component to be collapsed/expanded on init

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#567]
### Issue description
Add option to NCIDS the standard site alert component to allow the collapsible content to be expanded on default. Currently, it can only be collapsed on default.

> **ESTIMATE** TBD

### What's the expected change?
- Standard site alert component can be collapsed or expanded once the component is initialized. 

### What's the current functionality?
- Standard site alert component is collapsed once the component is initialized. 

### What's the updated acceptance criteria?
```gherkin
@olitharp-nci todo after discussion with @NCIOCPL/product 
```

### Tasks
- [ ] Update DS documentation code
- [ ] Update Storybook code if needed by no regressions are expected
- [ ] Update Example site
- [ ] Update `ncids-js`

### Related Tickets
* See VS's comment about original requirements https://github.com/NCIOCPL/ncids/issues/262#issuecomment-1040381290

**Comment by olitharp-nci** [comment]
https://github.com/orgs/NCIOCPL/teams/product This can be MVP 2
