### ISSUE TITLE
NCIDS Header: Copy `.usa-current` link to button

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#576]
### Issue description
The current page indicator is missing. Upon inspection, we are not copying the `.usa-current` class to the button on header init. 

> **ESTIMATE** 1

### Additional details / screenshot
See clip from @laurelthrash 

https://user-images.githubusercontent.com/85901679/189363362-428cb5b6-f107-48ea-9d99-f1506b332719.mov

### Related Tickets
* https://github.com/NCIOCPL/cgov-dig https://github.com/NCIOCPL/cgov-digital-platform/issues/3268
* https://github.com/NCIOCPL/cgov-digital-platform/pull/3449

### Tasks

- [x] No regression images 
- [x] Add unit test
- [x] Add to ncids-js-testing
