### ISSUE TITLE
Enabler: Update Buttons to handle external (non federal website) links

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#579]
This will comprise only updating `usa-button` when it is applied to an anchor element. Use the existing USWDS Launch icon for the external link. This is not a button variant. 

## Tasks
- [ ] Icon should automatically be added if .gov is not found in the url. 
  - dev note: look into css regex
- [ ] Icon should be able to be forced to show or forced to be suppressed
- [ ] Storybook: create stories with external links. All variants?
- [ ] Example JS site: only updated if JS used
- [ ] Documentation site: update guidance. Needs guidance?

Per discussion with ODDC Feds on 11/8:
- received approval to move forward with CSS approach to trigger the display of exist disclaimer
- exit disclaimer should display on not US Federal sites (sites not ending in .gov)
- exit disclaimer should not display on the following domains (create a rule to not show exit disclaimer): https://public.govdelivery.com/*, https://www.gov.uk/*

**Comment by bennettcc** [comment]
[external links report.csv](https://github.com/NCIOCPL/ncids/files/9890355/external.links.report.csv)

@bryanpizzillo @karlikpj - attached the report to this ticket showing the www.gov edge case URLs that would be impacted by our approach to use CSS to generate the exit disclaimer

**Comment by bennettcc** [comment]
Awaiting metrics on # of external links with .gov

**Comment by bennettcc** [comment]
@karlikpj Per meeting with Anna on 1/23:

Approval received to move forward with the CSS required to build out the button and exit disclaimer logic. The Federal team is comfortable moving forward with the rule 'if .gov exists within the content URL, do not display the exist disclaimer' There may be a limited number of CGDP buttons that do not display the exit disclaimer (https://www.gov.uk/) - the business case is very small.

**Comment by sarinapadilla** [comment]
After finding an issue with the external link displaying on the language toggle on an ODE (found when testing the [USWDS normalize PR](https://github.com/NCIOCPL/cgov-digital-platform/pull/3765) in the digital platform) so reopening this ticket to refactor.

**Comment by bennettcc** [comment]
Updating with decision from 2/14 Federal discussion:

2/14/23: Wait for USWDS to fix ([their ticket](https://github.com/uswds/uswds-site/issues/1519)) which is in the USWDS Backlog, might be a while till they fix

USWDS Link(s): https://github.com/uswds/uswds-site/issues/1519 

External links (when found in buttons) are not indicated on screen readers – this creates a usability concern as users using screen readers wouldn’t receive a notification that the link they are viewing is external.  This is not a 508-compliance violation but rather an opportunity to make the site more accessible 

Impacts items like feature cards which may point to external, non .gov sites – overall, use case is low

**Comment by andyvanavery31** [comment]
Closing due to duplication of work being done on #1899
