### ISSUE TITLE
Create DS Dev Tickets for Release 2 Iteration 2 (R2.2)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#585]
Create DS Dev Tickets for all design system components prioritized for Release 2 Iteration 2 (R2.2). 

Iteration | Component Type | Component Variation | Priority
-- | -- | -- | --
R2.2 | [Hero](https://github.com/NCIOCPL/ncids/issues/534) | D. Hero Image  w/o Button, Light Text Box | 1.2
R2.2 | [Guide Cards](https://github.com/NCIOCPL/ncids/issues/537) | B. Guide Card with Background Image | 1.2
R2.2 | [Promo Block](https://github.com/NCIOCPL/ncids/issues/538) | F. Promo Block - No image - Dark Text Box | 1.2
R2.2 | [Feature Card](https://github.com/NCIOCPL/ncids/issues/540) | D. Thumbnail Card - Optional Description | 2.2

SP: TBD

### Sub-Tasks
**Sprint 41 [SP: 2]:**
- [x] Complete DS dev tickets for R2.2 by 11/1 @blilianyu 

**Sprint 42 [SP: 1]:**
- [x] Sarina start of Drupal Dev ticket versions for R2.2 @sarinapadilla 
- [x] Internal review with internal design team on Thus. 11/3. **Design Team**

**Sprint TBD [SP: 2]:** - (Need to be prioritized before R2.1 development is complete)
- [ ] Review all R2.2 tickets with all devs on TBD **Team**
- [ ] Make updates to the tickets based on meeting with devs @blilianyu

**Comment by laurelthrash** [comment]
Moving to Sprint 41.

**Comment by laurelthrash** [comment]
Met internally on 11/3 and @blilianyu presented the R2.2 tickets. Team did not have any changes or feedback. Marking this ticket as 'Done' to represent completed work in Sprint 42. From there, will move to our 'Approved Backlog' for future prioritization to review with the dev team.

**Comment by laurelthrash** [comment]
Moving to "Approved Backlog" until next best time to review with the developers arises, following review of MVP1 time-sensitive items Cc: @meglake

**Comment by bennettcc** [comment]
Closing as complete
