### ISSUE TITLE
Define Image & Image Display Requirements for R2 Components

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#586]
## In order to implement the changes to Home and Landing pages for Redesign, the designer and product owner need to determine the updated requirements for images within the DS and the Digital Platform.
> **Estimate** *# point*

### Expected Deliverables:
* Define requirements for image sizes and aspect ratios for all breakpoints with the DS
* Define requirements for update cgov_images to support these image sizes and aspect ratios in the Digital Platform
* A story for updating cgov_image based on the image requirements in `cgov-digital-platform`
* Updated requirements on component tickets in `cgov-digital-platform` for which images to use

### Additional Notes:
Mural Board: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1663698618353/28c0e3412e473a41817044386ee09b90823aa6eb?sender=meganlake7790

Using the Mural Board above, document the following:

### Sub-Tasks [Sprint 39]
- [x] Define image display requirements for Drupal for each R2.1 component that includes an image @sarinapadilla (complete for now, however, may change once review full set on Wed. 10/12).

### Sub-Tasks [Sprint 40]
- [x] Define image display requirements for Drupal for each R2.2 - R2.5 component that includes an image @sarinapadilla 
	- [x] Set-up meeting for week of 10/3 to review full Drupal requirements - scheduled for Wed. 10/12 @sarinapadilla 

### Sub-Tasks [Sprint 41 (carried over from previous sprints)] 
- [x] Define image requirements for each R2 component that includes an image @blilianyu 
	- [x] All complete except one question re: the hero image and full-width promo block image that have fixed height on widescreen, desktop & table large. Still need widths for the hero.

 ### Results of Spike
* DS: finalized image requirements for DS components
* Digital Platform:
  - [x] https://github.com/NCIOCPL/cgov-digital-platform/issues/3609

**Comment by laurelthrash** [comment]
All sub-tasks are complete. Closing this ticket.
