### ISSUE TITLE
Revisit Survivorship Icon for PPT w/Icons for Use in Presentations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#592]
**Issue:** In Sprint 39, the team updated the PowerPoint (PPT) file that includes the icons available for use in presentations. The PPT is a menu of icons to choose from and is housed on myNCI ([link here](https://mynci.cancer.gov/topics/nci-icons-use-presentations)). While updating the PPT, the team created several options to represent 'survivorship,' and consulted the Office of Cancer Survivorship (OCS) for their opinion on the proposed icons. OCS recommended we post the PPT with the existing icon (a person with raised hands) but indicated they wish to have input on future alternatives. At the time, we agreed to post the PPT as-is and add a ticket to the backlog to specifically explore alternatives, in conjunction with OCS, for the survivorship icon. 

**Goal:** Update the survivorship icon that is included in PPT menu to include a refreshed icons to represent 'survivorship' that incorporates feedback from OCS. 

**Related Issue:** #526 

### Sub-Tasks (Draft)
- [ ] Conduct a discussion with ODDC + OCS
- [ ] Design potential icons that incorporate information from discussion with OCS
- [ ] Align on design
- [ ] Replace existing PPT on myNCI with the updated PPT (submit via a JIRA ticket to add to myNCI)

**Comment by andyvanavery31** [comment]
Move to Jira and delete from this board.
