### ISSUE TITLE
Build: Guide Card - A. Guide Card with Image & Description

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#614]
## User Story
**As a** developer,
**I want to** have the Development Solution from the DS,
**so that I** can implement the Guide Card with Image & Description component in a website

> **ESTIMATE** 3  

### Guide Card with Image & Description Row
**CONFIRM WITH IA/DESIGN**

**When to use Guide Card with Image & Description Row variation**
- When there is a need to for two specific audiences or groups of content

**When to consider something else**
- If you don't have multiple audiences, use the Feature Card variation

**Additional considerations**
- Minimum of two buttons and a maximum of 6 buttons for each variation

### Behaviors:
*Summary of state changes and behaviors. AC's are more detailed.*
- 16:9 image on all breakpoints
- If description is longer on one card, the buttons will align top for each card
- Minimum of 2, maximum of 6 buttons
- Cards should be the same height at all times on widescreen, desktop and tablet large (880px or larger)
- When cards stack on 879px and smaller, the card height will grow (does not have to be the same height)
- The heading should be styled as theme-h2-font-size

### Comps:
Figma **(WIP)**: https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?node-id=2162%3A3511&t=a5EsCM8h9y7NyKHg-0

InVision: 
  * Widescreen (1400) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0282013t7d5l1urr/play
  * Desktop (1024) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0283013t4nhh03fd/play
  * Tablet Large (880) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0284013t4aj381ri/play
  * Tablet (640) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0285013tb131hhax/play
  * Mobile Large (480) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0286013tckea7wt7/play
  * Mobile (320) mockup: https://publicis.invisionapp.com/console/MVP2-R2.1-Landing-Pages-cl756hway0281013t70e36jn0/cl756hwrg0287013t51y80sss/play

### Acceptance Criteria

``` gherkin
Scenario: User views a page with two (2) Guide Cards with Image & Description
Given a user is viewing a landing page with two (2) Guide Cards with Image & Description
  And the Design Solution has been implemented into the Development Solution in the DS
Then the user will be able to view the two (2) Guide Cards with Image & Description on the example site
  And the Guide Cards with Image & Solution on the example site will match the comp
  And the Guide Cards with Image & Description will be held within a container called the "Guide Card with Image & Description Row"
  And the Images on the Guide Cards with Image & Description will have a 16:9 aspect ratio
  And each Guide Card with Image & Description will display at least two (2) and at most six (6) buttons
  And the Buttons shall have the secondary button outline style
  And the Buttons shall be clickable
  And each Button will be linked to its corresponding content
When the user hovers over the button
Then the button will have the secondary button hover style
When the user clicks a button
Then the user will be redirected to the linked content of that button

Scenario: User views a page with two (2) Guide Cards with Image & Description on Widescreen, Desktop, or Tablet Large
Given a user is viewing a landing page with two (2) Guide Cards with Image & Description
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is at least 880px
Then the user will be able to view the two (2) Guide Cards with Image & Description on the example site
  And the top-most button on each card will be top aligned to each other
  And the Guide Cards with Image & Description will be of equal height to each other
```

### Scenarios
- Audience guide card by itself
  - All description types and languages
- Audience guide card in a container with other card(s)
  - One card with shorter description, one with longer
  - One card with more buttons, one with fewer
  - Ugliest scenario possible: one card with really long description and two links, one card with a really short description and 6 links 

#### Single card
  - Short title: CRCHD Diversity Training
  - Short description: Treatment for severe COVID-19 with interferons decreased the viral load of SARS-CoV-2, a new study found. 
  - Button 1: Find a Cancer Type
  - Button 2: Newly Diagnosed
  - Button 3: Cancer Treatment & Side Effects
  - Button 4: Contact Us for Help
  - Spanish title: Capacitación en diversidad CRCHD
  - Spanish description: El tratamiento para la COVID-19 grave con interferones disminuyó la carga viral del SARS-CoV-2, según encontró un nuevo estudio.
  - Button 1: Encontrar un tipo de cáncer
  - Button 2: Recién diagnosticado
  - Button 3: Tratamiento y efectos secundarios
  - Button 4: Póngase en contacto con nosotros para obtener ayuda

#### 2 card row:
*Card 1*
  - Short title: CRCHD Diversity Training
  - Short description: Treatment for severe COVID-19 with interferons decreased the viral load of SARS-CoV-2, a new study found. 
  - Button 1: Find a Cancer Type
  - Button 2: Newly Diagnosed

*Card 2*
  - Long title: Grant Application Development, Submission, Review, & Award
  - Long description: In patients with certain variations in the OAS1 gene, treatment for severe COVID-19 with interferons, a type of protein that can help the body’s immune system fight infections, decreased the viral load of SARS-CoV-2, a new study found. 
  - Button 1: Cancer Treatment & Side Effects of Cancer Treatment
  - Button 2: Grants and Training
  - Button 3: Funding Opportunities 
  - Button 4: Research Program Contacts
  - Button 5: Ongoing Research Studies
  - Button 6: Contact Us for Help

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Complete DS development of Default Guide Card #648 

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by olitharp-nci** [comment]
@sarinapadilla the AC is looking great, we have some questions regarding the exact pixel matching of widths on fluid column layouts. Instead of hardcoding widths, we probably need focus on making sure we are using correct USWDS tokens for padding/margins instead.

**Comment by bennettcc** [comment]
On hold - discussing this ticket in relation to https://github.com/NCIOCPL/ncids/issues/776 on 2/21
