### ISSUE TITLE
Baseline Discovery: Breadcrumbs

### ISSUE THREAD

**Issue by anthonycuellar** [NCIOCPL/ncids#67]
Do baseline discovery for breadcrumbs.

*Description of any context around the baseline work*

- Findings should be captured in the Notion for discussion.

## Tasks
- [x] Documentation of prior work on Breadcrumbs (pull from Mural and others into Notion)

## Potential Tasks
- ~Drupal report~
- [x]  Synthesis of any existing analytics Data around use and function [COMPLETE - Analysis in notion and Box]
- [ ]  High-level heuristic review of feature
- [ ]  Technical or accessibility flags
- [ ]  Best practices around use of feature

### Resources:
* Notion for Breadcrumbs: https://www.notion.so/Breadcrumbs-baf2759e1e2f4aada77493ef3c0df5de
* Mural: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1602095625783/fa27d5eda78546183c03d428ffee7dc1acfd7fa8

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- 
### Follow Tasks
* Design for Breadcrumbs: https://github.com/NCIOCPL/ncids/issues/22

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by claireblaustein** [comment]
some analysis on length and layers of existing breadcrumbs completed - 
Notion:https://www.notion.so/Breadcrumbs-baf2759e1e2f4aada77493ef3c0df5de
Box: Reporting with analysis on Box: [https://lion.box.com/s/bqrn4bbqfb04xhanrrphiaslko28w4lj](https://lion.box.com/s/bqrn4bbqfb04xhanrrphiaslko28w4lj)
