### ISSUE TITLE
Update R2 Design Files to Reflect USWDS Tokens

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#686]
### Description

**Purpose**
Need to ensure that design files for R2 components use the correct tokens. These design files will be used as reference files on the NCIDS during roll out. 

**Background**
Determined week of 12/6 that the current R2 comps are not aligned so as to use USWDS Spacing Unit Tokens ([link to USWDS page here](https://designsystem.digital.gov/design-tokens/spacing-units/ )). Unlike the font sizing and shadow tokens, the NCIDS will not be defining new pixel values associated with the spacing tokens. Some of the current comps incorporate spacing that does not utilize an available pixel value in accordance with USWDS. On 12/8 & 12/14, the designers and devs convened to discuss the the top prioritized R2 components (1. Feature Cards, 2. Alternating Promo Blocks) for which immediate alignment was needed in regard to the spacing tokens. 

*Parent Issue: N/A*

### Sub-Tasks 
**Need to be revisited at time of execution**
- [ ] Update R2 Sketch files to use USWDS token spacing sizes (consistent with internal conversation)
- [ ] Ensure changes are reflected on the Invision file (referenced below) that is linked on each individual GitHub ticket
- [ ] Design team QA work completed above

### Reference Documents
- Invision file that represents the R2 Sketch file: https://publicis.invisionapp.com/overview/MVP2-Landing-Pages-cl756hway0281013t70e36jn0/screens

### Notes

- [Insert Notes Here]

**Comment by laurelthrash** [comment]
Based on 12/14 conversation, determined we will not update sketch files before completing development, rather, we will adjust all comps as R2 development is complete. For future comps, we will ensure that comps are consistent with the defined USWDS spacing tokens. Need to ensure that Figma pulls in the correct USWDS spacing tokens (not those from Sketch, for which it is not properly defined).

**Comment by laurelthrash** [comment]
Moving to the backlog. Note that this ticket will be part of a larger ticket to prepare design files for NCIDS roll out, which will include all components in the NCIDS with the correct tokens in place.

**Comment by sarinapadilla** [comment]
@laurelthrash, believe this has been done as part of the NCIDS Pilot, and that we are creating all Figma files afterwards using USWDS tokens. Can we close this ticket?

**Comment by laurelthrash** [comment]
@sarinapadilla - yes, I confirmed with @blilianyu that all spacing was updated before the NCIDS Pilot. I will proceed with closing this ticket.
