### ISSUE TITLE
Create usa-section component

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#687]
### Build usa-section component based on design specs/requirements documented in this ticket
> **ESTIMATE** TBD

### USWDS Component Equivalent
* `usa-section` - This component exists only [in source](https://github.com/uswds/uswds/blob/v2.13.3/src/stylesheets/components/_section.scss) and is demonstrated on the [landing page template](https://designsystem.digital.gov/templates/landing-page/).
   * This component hard codes a number of different settings and we should make them theme settings, as well as use the paddings that will work for us.

### InVision: 
  * TODO: Add comps to home/landing pages
  * Desktop mockup: *insert link here, or enter N/A if not needed*
  * Tablet mockup: *insert link here, or N/A if not needed*
  * Mobile mockup: *insert link here, or N/A if not needed*

### Acceptance Criteria for Behaviors 

```gherkin
Scenario: User views a section on tablet
  Given [context]
    And [some more context]
  When  [event]
  Then the padding is X
    And [another outcome]
```

---
### Scenarios
- No color
- light (`usa-section--light`)
- dark (`usa-section--dark`)

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

### NCIDS Guidance
- [ ] *When to use component and its variant(s)*
  * Example: Use a card when featuring content
- [ ] *When to consider something else*
  * Example Use a list when you have multiple pieces of content, and will display too many cards*
- [ ] *Usability Guidance*
  * Example: Don't have 1 button in CTA strip
