### ISSUE TITLE
Define Inner Page Paragraph Styles

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#702]
Define paragraph styles to include text links, bullets, and lists (all types of lists) - anything that might be written into the WYSIWYG. Does not include Intro Text (Intro Text is a separate component). For very basic inner page. 

**Parent Issue:** N/A
**Related Issue:** #610 

### Sub-Tasks
- [x] Create comp for inner page (includes H1-H6 and paragraph styles from #610 ) (NOTE: does not include feature cards, images, etc. Should just be header and paragraph text)
- [ ] Design team to define styles (noted in description) [design]
- [ ] Update styles in Sketch/Figma according to the definitions [design]
- [ ] Update on Documentation Site/Storybook according to the definitions [devs]

### Notes

- This is prepping for NCI DS rollout

**Comment by monika-jaeger** [comment]
USWDS resources:

- [Paragraph Styles](https://designsystem.digital.gov/utilities/paragraph-styles/)
- [List Items](https://designsystem.digital.gov/components/list/)
- [Text Links](https://designsystem.digital.gov/components/link/)

**[InVision Link [WIP]](https://publicis.invisionapp.com/console/share/QV4UZJYTNW9)**

**Comment by monika-jaeger** [comment]
`usa-prose-body`: 
font-open-sans-regular
size-16
line-height-24

`usa-link`:
color-primary (#007BBD)

`usa-link:visited`:
color-violet-70v (#562B97)

`usa-link--light`: _Text links used on dark backgrounds_
color-primary-light (#3395CA)

**Comment by laurelthrash** [comment]
Notes from internal meeting on 01/26/23: 

Actions
- [ ] Include nested list in comp (use what USWDS does)

Outstanding Questions
- [ ] Are we addressing the glossification style at this point? Or will this come later on with dictionaries?

**Comment by monika-jaeger** [comment]
[InVision Comps](https://publicis.invisionapp.com/console/share/ZT27AE89FWV) updated with nested lists

**Comment by laurelthrash** [comment]
Per conversation via Slack, @monika-jaeger going to develop the measure tokens and include consideration of floating items in the text. To discuss further during 1/31 internal UX meeting.  Regarding glossification, it is our decision if we wish to define styling at this point. Do not believe any non-platform sites have dictionary links so would not apply to NCIDS for all. Cc: @monika-jaeger

**Comment by monika-jaeger** [comment]
[Measure token in Figma](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?node-id=2413%3A6301&t=IqcBB5H527WOJ3En-1)

After chatting with Bryan, here are additional areas he noted that use measure:

- Intro text (usa-intro)
- 

> This uses the $theme-lead-measure variable. We can change that stupidly large font size.

- Lists (usa-list)
- 

> Specifically this applies to list items

- Icon Lists (usa-icon-list)
- 

> This one is complicated, but it looks like it sets the measure to a known size if you do not use a size variant of the icon list.

- Lots of instances of hardcoded measure of 5
- Banner (usa-banner)
- 

> Whatever the $banner-guidance-measure is. Maybe this is what you see when you expand the “how can you tell?” link which we don’t use.

- Process List
- 

> List items are hardcoded as a measure of 5

**Comment by laurelthrash** [comment]
Notes from 01/31 internal meeting:

- Decision: desire is to not define the measure so that the text wraps around floating images, but want to confirm with the dev team what the implications are for this.

**Comment by laurelthrash** [comment]
Measurement token conversation on hold until 2/8 Requirements meeting to discuss deeper with designers and devs.

**Comment by laurelthrash** [comment]
Moving to DS Sprint 11.

**Comment by andyvanavery31** [comment]
This is complete.
