### ISSUE TITLE
Create DS Dev Tickets for Release 2 Iteration 3 (R2.3)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#703]
Create DS Dev Tickets for all design system components prioritized for Release R Iteration 3 (R2.3). 

Iteration | Component Type | Component Variation | Priority
-- | -- | -- | --
R2.3 | [Hero](https://github.com/NCIOCPL/ncids/issues/534) | F. Hero Image w/o Button, Light Text Box & CTA Strip | 1.3
R2.3 | [Guide Cards](https://github.com/NCIOCPL/ncids/issues/537) | C. Guide Card Row | 1.3
R2.3 | [Promo Block](https://github.com/NCIOCPL/ncids/issues/538) | D. Full-width Promo Block - Dark Text Box | 1.3
R2.3 | [Feature Card](https://github.com/NCIOCPL/ncids/issues/540) | C. Multiple Link Feature Card Row (dynamic) - 3 Cards | 2.3
R2.3 | [Content Grid](https://github.com/NCIOCPL/ncids/issues/541) | D. 4 links - 1 large image: title only | 3.2

### Sub-Tasks
**DS Sprint 9 [SP: 3]:**
- [x] Complete DS dev tickets for R2.3
- [x] (Also updating existing comps based on conversations between dev/design team)

**DS Sprint 10 [SP: 1]:**
- [ ] Sarina start of Drupal Dev ticket versions for R2.3 @sarinapadilla 
- [ ] Internal review with internal design team on [date TBD] **Design Team**

**DS Sprint TBD [SP: 2]:** - (Need to be prioritized before R2.2 development is complete)
- [ ] Review all R2.3 tickets with devs on [date TBD] **Team**
- [ ] Make updates to the tickets based on meeting with devs @blilianyu

**Comment by blilianyu** [comment]
Component tickets have been created. 
Note: Paul K has already worked on Guide Card row in this sprint #711

**Comment by laurelthrash** [comment]
Counting SP 3 in DS Sprint 9. Adding to "On deck backlog" for next steps with regard to Drupal ticket creation. Cc: @blilianyu @sarinapadilla @meglake

**Comment by bennettcc** [comment]
Closing this as complete
