### ISSUE TITLE
Design Comp for Cancer.gov Home Page Using R2.1 Components (Eng. & Span.)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#704]
Design comp for the Cancer.gov Home Page that uses R2.1 components. Determined on 01/11/23 the need to create a comp to represent the home page at R2.1 launch, using the available components. 

### Sub-Tasks
- [x] Design Cancer.gov home page comp using available R2.1 components, include: [Spanish & English]
    - [x] Update tagline/content
    - [x] Inline Cancer Survivorship video
    - [x] Component for CIS (currently the "Contact Us for Help") 
    - [x] Changes to the footer from MVP1
- [x] Review comp internally [**Thurs 01/18/23**]
- [x] Update comp based on internal review
- [x] Share comp with federal team
- [x] Update "[Latest Cancer.gov Redesign Mock Ups [STAKEHOLDER BOARD]](https://app.mural.co/invitation/mural/publicissapient7269/1652804277768?sender=uc8881d65820946a13d002641&key=1bc9c527-9e14-4d2c-b775-4e8c71f8c9be)" Mural board with comps to reflect comps for R2.1

### Notes
- Insert

**Comment by laurelthrash** [comment]
[Comment in Progress]

Actions

- [ ] Update feature cards so that titles are underlined

Notes

- Consider adding "Survivorship" under Patients and caregivers featured card / Requirements are that it is a minimum of 2 and maximum of 6/ can certainly add another button
- Will talk through content conversations to finalize content

**Comment by blilianyu** [comment]
Updated comps can be viewed here: https://publicis.invisionapp.com/overview/Cancer-gov-Home-Page-R2-1-clcul8x0q0au801augpgc56df/screens

**Comment by laurelthrash** [comment]
Shared Mural board, that includes updated comps, with federal team. Marking this ticket as closed. Cc: @blilianyu @meglake
