### ISSUE TITLE
Update Release 1 Screenshots on Stakeholder Mural Board

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#705]
Replace "Release 1" comps on the "[Latest Cancer.gov Redesign Mock Ups [STAKEHOLDER BOARD]](https://app.mural.co/invitation/mural/publicissapient7269/1652804277768?sender=uc8881d65820946a13d002641&key=1bc9c527-9e14-4d2c-b775-4e8c71f8c9be)" Mural board to include screenshots of the live site. 

### Sub-Tasks
- [x] Visit the "[Latest Cancer.gov Redesign Mock Ups [STAKEHOLDER BOARD]](https://app.mural.co/invitation/mural/publicissapient7269/1652804277768?sender=uc8881d65820946a13d002641&key=1bc9c527-9e14-4d2c-b775-4e8c71f8c9be)" Mural board and see what appears under "Release 1"
- [x] Replace the existing comps with screenshots from the live Cancer.gov site, to represent exactly how the site appears following the MVP 1 release. This includes screenshot changes for:
    - [x] Cancer.gov Home Page
    - [x] Cancer.gov Inner Page
    - [x] Nano Home Page
    - [x] DCEG Home Page (NOTE: This was previously DCEG Fellowships and Training because we did not yet have a comp for the home page. Replacing DCEG Fellowships and Training with the home page now that the site is live).
- [x] Review updates internally
- [ ] Share board with federal team for awareness

### Notes
- Determined during 01/12 meeting the need to update the current comps on the stakeholder board to reflect MVP1

**Comment by monika-jaeger** [comment]
Updated [Mural Board](https://app.mural.co/invitation/mural/publicissapient7269/1652804277768?sender=u55a81cd2c90396f91d135908&key=1bc9c527-9e14-4d2c-b775-4e8c71f8c9be) with Release 1 screenshots. These are at the Widescreen 1400px size. If they need to be a different size, let me know. 
Source folder for screenshots are [here](https://lion.box.com/s/j9s41i1rbyy7lmhayllk8yuvds85tdlu).

@laurelthrash this is ready for review.

**Comment by monika-jaeger** [comment]
Updated [Mural Board](https://app.mural.co/invitation/mural/publicissapient7269/1652804277768?sender=u55a81cd2c90396f91d135908&key=1bc9c527-9e14-4d2c-b775-4e8c71f8c9be) with screenshots including the language banner.
Source folder for screenshots are also updated [here](https://lion.box.com/s/j9s41i1rbyy7lmhayllk8yuvds85tdlu).

**Comment by laurelthrash** [comment]
Shared link to updated Mural board with federal team via Teams. Closing out this ticket. Cc: @meglake @monika-jaeger
