### ISSUE TITLE
Release 2 Internal Documentation Update

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#715]
**Description of what is to be accomplished.**

Need to ensure that the following items are reviewed and adjusted ahead of Release 2 to account for changes implemented in Release 2.

**Related Issues from MVP1:**
1. #676 
2. #607 
3. #688 

### Sub-Tasks
- [ ] Drupal Guide on myNCI: https://mynci.cancer.gov/topics/drupal-guide 
- [ ] Digital Style Guide on myNCI: https://mynci.cancer.gov/topics/nci-digital-style-guide
- [ ] Branding/Logo Guide on myNCI: https://mynci.cancer.gov/topics/nci-branding-and-logo-use-guide

### Notes

*Insert notes, as needed

**Comment by laurelthrash** [comment]
Closing this issue as this information is already captured in https://github.com/NCIOCPL/cgov-digital-platform/issues/3317
