### ISSUE TITLE
Incorporate R2.1 Component Guidance in Stakeholder PPT

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#722]
**Description:** Take guidance that was defined and documented in #721 and incorporate this to the stakeholder R2.1 component PPT slide.

**Parent Issue:** #721 

### Sub-Tasks
- [ ] Incorporate guidance outlined in [#721](https://github.com/NCIOCPL/ncids/issues/721) on "R2.1 Component Variation" slide (Slide 12 of PPT deck below in "Notes")
- [ ] Share for internal review
- [ ] Share with federal team for review

### Notes
- [Redesign Stakeholder Update-2023-01.pptx](https://github.com/NCIOCPL/ncids/files/10495798/Redesign.Stakeholder.Update-2023-01.pptx) (Slide 12)

**Comment by laurelthrash** [comment]
Closing this ticket as this information was incorporated into #721.
