### ISSUE TITLE
Review Platform for Potential Use of the Collection Component 

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#742]
Look into variations of the Collection component (the component used on the New & Events Landing page comp) to determine how the variations of this component could be used elsewhere. As part of the review, please consider the specific elements listed below that appear on the current platform:

- Lists on mini landing pages (see Mural inventory in #651  )
- Blog listings and the right rail
- Related Resources list

This will help with requirements so we are building for the broader platform, as opposed to an isolated use case.

> Priority for DS Sprint 11
> SP: TBD

**Related Issue:** #486 

### Sub-Tasks
- [x] Initial conversation with product/design/dev 02/09 @ 1:30pm
- [x] Conduct review of current platform to determine other locations where the Collection component might be appropriate
- [x] Document platform review
- [ ] Implement findings into DS dev tickets for News & Events

### Resources
- USWDS Collection component documentation: https://designsystem.digital.gov/components/collection/
- USWDS Collection component build ticket: https://github.com/uswds/uswds/issues/3676
- NCI DS Collection component boiler plate: https://github.com/NCIOCPL/ncids/issues/746 [place documentation from review]

**Comment by monika-jaeger** [comment]
Latest comps for News & Events [here](https://publicis.invisionapp.com/console/share/S5Z9QGNKXRC) (for reference to the collection component on each breakpoint). This includes both V1 & V2 (feature cards vs. promo blocks)

**Comment by laurelthrash** [comment]
**Outcome of 02/09 internal UX team meeting:** Identified locations (on our platform as well as other cancer.gov sites) where the Collection component may be used. Cc: @andyvanavery @sarinapadilla @meglake @blilianyu @monika-jaeger @chuckhrose 

Platform
- DCEG News: https://dceg.cancer.gov/news-events/news 
- DCEG Events: https://dceg.cancer.gov/news-events/events 

Other Cancer.gov sites
- CCR News: https://ccr.cancer.gov/news 
- CSSI News: https://cssi.cancer.gov/news-and-events 
- DCP News: https://prevention.cancer.gov/news-and-events/news 
- DCP Blog: https://prevention.cancer.gov/news-and-events/blog 
- DCTD News: https://dctd.cancer.gov/NewsEvents/News-2022.htm 
- Frederick News: https://frederick.cancer.gov/news 
- Frederick Events: https://frederick.cancer.gov/events

Specific Requirement Questions

- [ ] Is there an ability to customize how many items are listed in the collection list? For example, on News & Events, we intentionally want to limit this to 5, however, we may want to include more elsewhere. Suggestion: increments of 5, 
- [ ] Is there an option to determine if the collection list appears dynamically versus manually? For example, blogs might want to be dynamic while lists on landing pages are curated

Notes

- There were previous discussions regarding removal of the right rail for blogs. We would want to revisit this before deciding and building the component to match this.

**Comment by laurelthrash** [comment]
Tagging @sarinapadilla and @andyvanavery to incorporate the above findings from the internal UX discussion in the DS Dev ticket and next steps: #746
