### ISSUE TITLE
[META] UX Team Tasks for R2.1 Content Conversations 

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#743]
> [Landing Page Recommendation Calendar Here](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1%20Landing%20Page%20Update%20Schedule.xlsx?d=w6976516d4d8048cb9f83258530f202b8&csf=1&web=1&e=Zk5aO6)

### Description
We will conduct conversations with content owners ahead of the R2.1 release. This meta ticket outlines the steps that the UX team, specifically IAs/Designers, will need to take to prepare for the R2.1 content conversations.

### Tickets/Sub-tasks
- [x] #721
- [x] #752
- [x] #748
- [x] #798
    - [x] #805
    - [x] #806
    - [x] #807
 - [x] Cgov: Designer & IA review each landing page to determine recommendations and create mock up that use R2.1 components only (NOTE: only create a mock up if the recommendation is to use R2.1 components)
    - [x] Creation
        - [x] #760
        - [x] #762
        - [x] #761
        - [x] #763
        - [x] #764 
    - [x] Revision/Approval
        - [x] #964
- [x] Microsites: Designer & IA review each landing page to determine recommendations and create mock up that use R2.1 components only (NOTE: only create a mock up if the recommendation is to use R2.1 components)
    - [x] #745
    - [x] #753
    - [x] #754
    - [x] #991 
    - [x] #755
    - [x] #759
    - [x] #744
    - [x] #758
    - [x] #1380
    - [x] #1381
    - [x] #756
    - [x] #757
- [x] Special Report style Landing pages: To be done in context of their related project, Megan to connect with Anna on next steps.
    - [x] Annual Plan landing page (English only) https://www.cancer.gov/research/annual-plan
    - [x] Partners in Cancer Research landing page (English & Spanish) https://www.cancer.gov/research/cancer-research-partners
    - NCA50 landing page (English & Spanish) https://www.cancer.gov/news-events/nca50 [Will not update]
- [x] Known landing pages that will not move over in R2.1
    - Cgov Cancer Types & Cgov Spanish Cancer Types - Tipos de cáncer
    - Cgov News & Events & Spanish News & Events - Noticias

### Notes
- [Preliminary content conversation plan (Word doc)](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1_%20recommendations%20for%20landing%20page%20content%20convo%20process.docx?d=w6811cae7c7024b8982fb9dd72f59f0a8&csf=1&web=1&e=m4C0K7)
