### ISSUE TITLE
CCG Homepage: R2 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#744]
> META: #743

### Description
CCG Homepage: https://ccg-cms.cancer.gov/ccg/

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

### Sub-Tasks
- [x] Generate page analytics (Joe & Nicole)
- [x] Conduct review of specific landing page (IA) 
- [x] Document content recommendations (IA)
- [x] Create comp that demonstrates recommendations (Design)
- [x] Review comp internally (UX)
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]
- [x] Content stakeholder review
- [x] Align with federal team and update comp
- [x] CCG Leadership review **[Deadline: 11/22]**

### Final Documentation
- Mural board for content owner feedback: [Mural](https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1696857721628/7a4947382c0e05950c909ee650baa58b21cd6fb1?sender=u4f98fba0cad73dd945780265)
- Content supplemental document/talking points: [INSERT]
- English Comp: [INSERT]
- Analytics PDF: https://www5.an.adobe.com/x/5_11f01j

**Comment by laurelthrash** [comment]
Comments from internal UX meeting @driscollmd 

- [ ] Consider use of three guide card row in place of two guide card row 

Otherwise, all checks out from internal team!

**Comment by laurelthrash** [comment]
Final internal review approved during 10/19 UX team review.

**Comment by laurelthrash** [comment]
Reviewed Mural board with home page comp with federal team 10/25/23. No changes to the comp. Comp is set for meeting with CCG on Fri. 11/3. Cc: @driscollmd @dcvijanovic1k @monika-jaeger

**Comment by laurelthrash** [comment]
Changes to comp following stakeholder review (also outlined in the Mural board) @dcvijanovic1k 
- [ ] Update tagline to: Supporting genomic science to improve cancer diagnosis, treatments, and outcomes
- [ ] Left Guide card
    - [ ] Replace image with option A from Dragutin's selections
    - [ ] Change heading from "Programs & Initiatives" to "Explore Research Programs"
    - [ ] Update order of guide card links (see order on Mural board sticky - but do not include "Genomic Data Commons (GDC)" due to 6 link limit) 
 - [ ] Right Guide card
     - [ ] Create two mock ups that include option 1 and option 3 from Dragutin's selections
     - [ ] Update order of guide card links (see order on Mural board sticky) - consult Michael on which we should leave out for the next comp (will note in the Mural that we adopted their list but are limited to 6 links)

Change to production content @driscollmd 
- [ ] Update the card description for the "Personal Genomics Podcast" so as to be: Listen to first-hand stories about what it's like to work in one of the most complex areas of cancer research.

**Comment by laurelthrash** [comment]
Will close this ticket since the work outlined in the ticket is complete. Will create additional tickets for next steps. Cc: @driscollmd @dcvijanovic1k
