### ISSUE TITLE
DCEG Homepage: R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#745]
> META: #743 
> SP: TBD

### Description
DCEG Homepage: https://dceg.cancer.gov/

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

### Sub-Tasks
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]
- [x] Make updated based on v2 Mural review

### Final Documentation
- Mural board for content owner feedback: [INSERT]
- Content supplemental document/talking points: [INSERT]
- [Figma Comp](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=310%3A17099&type=design&node-id=895-14271&viewport=611%2C-1131%2C0.25&scaling=min-zoom)
- Analytics PDF:[Redesign_ DCEG Home.pdf](https://github.com/NCIOCPL/ncids/files/11138758/Redesign_.DCEG.Home.pdf)
- Analytics Dashboard: [Dashboard](https://www5.an.adobe.com/x/5_tr75o)

**Comment by laurelthrash** [comment]
**Notes from 05/25 internal review** @dcvijanovic1k 
- [ ] Recommend selecting photos (for all pages) for DCEG to react to
- [ ] Preference for promo blocks to have an image, unless it is a special circumstance
- [ ] Video - Figma will change based on behavior in dev environment

**Comment by laurelthrash** [comment]
Changes discussed during meeting with ODDC 7/17: 

- [ ] Revert the thumbnail for the video back to purple tile since there is the existing bug with pulling the thumbnail from YT

**Comment by laurelthrash** [comment]
Updated comps approved internally via Slack 7/20. @driscollmd preparing associated Mural board.

**Comment by laurelthrash** [comment]
Updates based on ODDC sync 8/2:
- [ ] Add "Working Groups" as fifth item in left guide card ("Public Health Impact of DCEG Research" to appear 6th)
- [ ] Change right guide card title to "Careers, Fellowships, and Training"
- [ ] Change feature card heading to "Research Tools" from "Research Tools for Scientific Community"
- [ ] Remove IWG Promo block and replace with Diversity and Inclusion at DCEG page
- [ ] Update video on homepage following recent DCEG meeting on 7/278
- [ ] [Need to confirm with Michael] awaiting analytics for one area on the comp and need to confirm if this requires a comp update

Note:
- Consider using and recommending dark tagline (R2.2), once available.

**Comment by laurelthrash** [comment]
@dcvijanovic1k @driscollmd Changes from v2 Mural board. Aligned with ODDC on 08/15:
- [ ] Add language to "Research" guide card description: Our scientists—epidemiologists, geneticists, biostatisticians, and clinicians—form interdisciplinary teams to study complex questions often in collaboration with scientists around the world.
- [ ] Add language to "Careers, Fellowships, and Training" guide card description: Browse a range of opportunities for every career stage: tenure-eligible senior investigator, staff scientist, postdoctoral fellow, and more.
- [ ] Replace language for "Index of Tools & Resources" guide card: We have created many tools for study design and planning, analysis, and risk assessment for the scientific community.
- [ ] Replace language for "Analysis Tools" guide card: Our experts develop cutting-edge analysis methods to answer tomorrow's research questions.
- [ ] Replace language for "Descriptive Epidemiology Resources" guide card: We produce descriptive epidemiology  resources, such as APC cohort analysis, NCI Cancer Atlas, and MP-SIT SEER*Stat.
- [ ] Replace Twitter feature card with LinkedIn Spotlight. Use language on the current DCEG home page (dceg.cancer.gov) and link to intermediary page. 
- [ ] For "DCEG Sponsored Events" feature card, use the iStock image from the News and Events promo block for Events.  
- [ ] Replace language for "Diversity and Inclusion" promo block description: Stay up to date on DCEG news, including in-depth articles on research or profile investigators. Distributed three times a year.
- [ ] Add language for "DCEG Publications" promo block description: Search by author, topic, or other factors: Publications by DCEG scientists, including book chapters and papers published in journals not indexed by PubMed.

**Comment by laurelthrash** [comment]
@dcvijanovic1k @driscollmd Changes from v3/final Mural board. Aligned with ODDC on 09/11:
- [ ] Change "Careers, Fellowships, and Training" guide card heading to "Come Work in DCEG"
- [ ] Remove "for the scientific community" from "Index Tools & Resources" feature card.
- [ ] Replace "Analysis Tools" with the Exposure Assessment page (title and card description)
    - [ ] Identify a new image (or confirm that the existing image works) since the Exposure Assessment page does not have a promo image
- [ ] Move "Commitment to..." to the second in list for the right guide card, under "Careers at DCEG"
- [ ] Replace "Descriptive Epidemiology" feature card with:
    - [ ] Title: NCIDose
    - [ ] Desc: NCIDose is a collection of medical radiation dosimetry tools developed by medical physicists.
    - [ ] Use existing promo image for the NCIDose page (https://dceg.cancer.gov/tools/radiation-dosimetry-tools)
- [ ] Adjust LinkedIn feature care to read "Follow us on LinkedIn for research stories, career and fellowship opportunities, and more." @driscollmd to provide text that notes this requires login
- [ ] "Events" feature card 
    - [ ] Change from "Events" to "Scientific Meetings and Workshops"
    - [ ] Remove "informal" from description
- [ ] Replace description for "Diversity and Inclusion" promo block with: "DCEG is committed to the recruitment, retention, and development of a diverse group of investigators and trainees."
- [ ] DCEG Publications promo block
    - [ ] Change button to "Search our Publications Database"
    - [ ] Identify a new image
- [ ] Remove Instagram from desktop and mobile footer

**Comment by laurelthrash** [comment]
@driscollmd @dcvijanovic1k I missed one from the above list:
- [ ] Replace lorem ipsum for Linkage newsletter: "Subscribe to receive our newsletter, Linkage, published March, July, and November, with longer-format articles and a summary of research and staff news from DCEG."

**Comment by laurelthrash** [comment]
Final Mural shared with ODDC on Thurs. 09/14. Closing this ticket as all subtasks are complete. Will create a new ticket for new items that arise. Cc: @dcvijanovic1k @driscollmd
