### ISSUE TITLE
Create usa-collection component

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#746]
### Build usa-collection component based on design specs/requirements documented in this ticket

> **ESTIMATE** TBD

### USWDS Component Equivalent
`usa-collection` - This [USWDS component](https://designsystem.digital.gov/components/collection/) displays related items in a list format. This component has multiple different variations:
* Default: displays title, description, and metadata (author, date, tags)
* Media thumbnail: displays image, title, description, and metadata (author, date, tags)
* Calendar display: displays calendar date month and day, title, and description
* Headings only: displays title and metadata (linked page information)

### InVision: 
  * TODO: Add comps to News & Events, Blog Series, Mini Landing pages (and possibly more)
  * Desktop mockup: *insert link here, or enter N/A if not needed*
  * Tablet mockup: *insert link here, or N/A if not needed*
  * Mobile mockup: *insert link here, or N/A if not needed*

### Acceptance Criteria for Behaviors 

```gherkin
Scenario: User views a section on tablet
  Given [context]
    And [some more context]
  When  [event]
  Then the padding is X
    And [another outcome]
```

---
### Scenarios
- Title (`usa-collection__heading`)
- Description (`usa-collection__description`)
- Image (`usa-collection__img`)
- Metadata (`usa-collection__meta`)
- Calendar date (`usa-collection__calendar-date`)

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*

- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Update Documentation Site (docs)
  - [ ] Create or update [INSERT DOCUMENTATION PAGE OR SECTION ON PAGE HERE] that includes:
    - Developer Documentation
      -  What SASS partial to import
      - (HTML Tab) What is the HTML?
      - (HTML Tab) (for vanilla js) What is the js library to import?
      - (React Tab) What is the react library to import?
      - (React Tab) What is the react markup?
    - **IA Provided** Guidance Documentation  
      - Includes when/how the component should be used
  - [ ] If the component is a global component like the footer, then it needs to be added to the documentation site as well as a real usage.
- [ ] Update NCIDS-CSS
  - **Insert list here of partials to be created** (There should be a sass partial available for all variants that are being created in this ticket)
- [ ] Update NCIDS-JS
  - **Insert requirements/list of components for JS**
- [ ] Update NCIDS-React
  - [ ] **Insert requirements/list of components for react**
    - (it can also be a separate ticket, should be linked here)

### NCIDS Guidance
- [ ] *When to use component and its variant(s)*
  * Example: Use a card when featuring content
- [ ] *When to consider something else*
  * Example Use a list when you have multiple pieces of content, and will display too many cards*
- [ ] *Usability Guidance*
  * Example: Don't have 1 button in CTA strip

**Comment by sarinapadilla** [comment]
#1149 addresses this issue as well.
