### ISSUE TITLE
Update R2 stakeholder PPT with updated component images and guidance

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#752]
[Ticket in progress]

# Tasks:

- [x] @blilianyu to update component wireframe images with the following:
   - [x] Correct name of component
   - [x] Any updates to the component based on latest requirements

- [x] Megan to update [R2 stakeholder deck](https://nih.sharepoint.com/:p:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/Redesign_Release%202%20Overview.pptx?d=wa22a327d91fd427f86aead7e2d095518&csf=1&web=1&e=Iagje1) with images from Lilian and guidance from ticket #721

**Comment by laurelthrash** [comment]
Images updated and PPT completed. Closing out this ticket. Cc: @blilianyu @meglake
