### ISSUE TITLE
DCEG Fellowships & Training: R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#753]
DCEG Fellowships & Training: https://dceg.cancer.gov/fellowship-training

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

### Sub-Tasks
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]
- [x] Make updated based on v2 Mural review

### Final Documentation
- Mural board for content owner feedback: [INSERT]
- Content supplemental document/talking points: [INSERT]
- [Figma Fellowships & Training Comp](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=310%3A17100&type=design&node-id=895-15017&viewport=866%2C113%2C0.16&scaling=min-zoom)
- Analytics PDF: [Redesign_ DCEG Fellowships & Training.pdf](https://github.com/NCIOCPL/ncids/files/11138732/Redesign_.DCEG.Fellowships.Training.pdf)
- Analytics Dashboard: [Dashboard](https://www5.an.adobe.com/x/5_tr75c)

**Comment by laurelthrash** [comment]
Determined on 05/10 with federal team that DCEG recommendation/comp strategy will differ from CGOV pages and other DOCs, whereby we will create a mock of what the current pages look like (e.g., all current content on the home and landing pages as a 1:1) and use this as an opportunity to show DCEG pages they might consider based on analytics. This differs from other home/landing pages for which we are creating recommendations/comps based on our recommendation that is not necessarily a 1:1 to their current page. Cc: @driscollmd @dcvijanovic1k @meglake

**Comment by laurelthrash** [comment]
**Notes from 05/25 internal review**
- [ ] Identify images to fill the placeholders
- [ ] Videoa - will be updated in Figma

**Comment by laurelthrash** [comment]
**Notes from 6/1** @dcvijanovic1k @driscollmd 
- [ ] Video - will be updated in Figma @monika-jaeger 
- [ ] Verify that the feature card descriptions are up to date with what is in Drupal
- [ ] Verify that the Browser Title is specific for DCEG (across all pages)

Notes
- Rotating featured content will be updated directly before launch

**Comment by laurelthrash** [comment]
Reviewed and approved comp internally on 6/29: Cc: @driscollmd @dcvijanovic1k

**Comment by laurelthrash** [comment]
Changes discussed during meeting with ODDC 7/17 @driscollmd @dcvijanovic1k
- [ ] Verify if the thumbnail for the video needs to be reverted to another thumbnail due to image issue with pulling from YT

**Comment by laurelthrash** [comment]
Updated comps approved internally via Slack 7/20. @driscollmd preparing associated Mural board.

**Comment by laurelthrash** [comment]
Updates based on ODDC sync 8/2:

- [ ] Add promo block to highlight publications written by fellows (@driscollmd to help provide recommendation) 
- [ ] Change tagline to "DCEG trains the next generation of scientists in cancer epidemiology and genetics" 
- [ ] Update to a hero with tagline and CTA button, with CTA button reading "Apply Now"
- [ ] Update video thumbnail

Notes:
- Regarding the recommendation to change the name of the "Advantages of a DCEG Fellowship" page: recommend treating this as a separate track outside of Redesign. Can rename the page but will need more data for a recommendation.

**Comment by laurelthrash** [comment]
@dcvijanovic1k @driscollmd Changes from v2 Mural board. Aligned with ODDC on 08/15:

- [ ] Add "Fellowship Opportunities & How to Apply" description text: We recruit fellows at many career stages. Learn how to apply and submit your application today.
- [ ] Add "Fellowship Experience" description text: What makes a DCEG fellowship experience extraordinary? Learn more about about our distinctive environment and the successful career paths of our former fellows.
- [ ] Recommend title/description for "Publications by DCEG Fellows" promo block that more better represents content found within the topic 504 page (https://dceg.cancer.gov/news-events/news?topic=504)
    - Potential titles discussed during meeting: News Updates on DCEG Fellowships & Training OR Updates on DCEG Fellowships & Training

**Comment by laurelthrash** [comment]
@dcvijanovic1k @driscollmd Changes from v3/final Mural board. Aligned with ODDC on 09/11:

- [ ] Change tagline to: :DCEG trains the next generation of cancer researchers in biostatistics, epidemiology, genetics, and related fields."
- [ ] Left guide card
    - [ ] Change "Summer Interns" to "Summer Internships"
    - [ ] Add "Fellowships" after postdoctoral and predoctoral
    - [ ] Remove "CIDP" acronym
- [ ] Right guide card
    - [ ] Add link to Commitment to Training video for the right guide card @driscollmd to provide specific text
    - [ ] Remove double "about" in the description
- [ ] Diversity and Inclusion promo block should match the one on the home page (with suggestions incorporated including the hand image and description updates).
- [ ] Change "Fellowship & Training News" description to: "Browse research news on studies led by our fellows."
