### ISSUE TITLE
DCEG News & Events: R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#754]
> META: #743 
> SP: TBD

### Description
https://dceg.cancer.gov/news-events

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

### Sub-Tasks
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]
- [x] Make updated based on v2 Mural review

### Final Documentation
- Mural board for content owner feedback: [INSERT]
- Content supplemental document/talking points: [INSERT]
- [Figma Comp: News & Events](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=310%3A17101&type=design&node-id=895-15473&viewport=774%2C65%2C0.13&scaling=min-zoom)
- Analytics PDF: [Redesign_ DCEG News and Events.pdf](https://github.com/NCIOCPL/ncids/files/11138764/Redesign_.DCEG.News.and.Events.pdf)
- Analytics Dashboard: [Dashboard](https://www5.an.adobe.com/x/5_tr7fj)

**Comment by laurelthrash** [comment]
Determined on 05/10 with federal team that DCEG recommendation/comp strategy will differ from CGOV pages and other DOCs, whereby we will create a mock of what the current pages look like (e.g., all current content on the home and landing pages as a 1:1) and use this as an opportunity to show DCEG pages they might consider based on analytics. This differs from other home/landing pages for which we are creating recommendations/comps based on our recommendation that is not necessarily a 1:1 to their current page. Cc: @driscollmd @dcvijanovic1k @meglake

**Comment by laurelthrash** [comment]
**Notes from 05/25 internal review** @dcvijanovic1k 
- [ ] Identify images (including hero) to fill the placeholders
- [ ] Consult Michael regarding the Linkage newsletter and keeping in mind their content strategy to consider if this will be different content, if not, consider combining two feature card rows Cc: @lburack 
- [ ] Reduce Linkage heading so that it is consistent with guidance @adrianacastaneda to share
- [ ] Refresh "Video Library" promo block image

**Comment by laurelthrash** [comment]
**Notes from 6/1** @dcvijanovic1k @driscollmd 
- [ ] Verify that feature card descriptions match what is in the CMS
- [ ] Remove double appearance of "Mustapha Abubakar Appointed..." feature card
- [ ] Reduce Linkage heading so that it is consistent with guidance @adrianacastaneda to share
- [ ] Needs further thought/Discussion: Linkage Newsletter feature card row not fitting quite right. Find a way to implement a "See all" so you can get to the blog landing page. Review Linkage Newsletter vs. People in the News articles to see how many are dual tags and consider streamlining these. @lburack @adrianacastaneda 

Notes
- First two feature card rows (Upcoming Events, Highlighted Research...) are fine and stand on their own

**Comment by laurelthrash** [comment]
Changes discussed during meeting with ODDC 7/17 @driscollmd @dcvijanovic1k 
- [ ] Add the CTA for designated news and events pages

**Comment by laurelthrash** [comment]
Updated comps approved internally via Slack 7/20. @driscollmd preparing associated Mural board.

**Comment by laurelthrash** [comment]
Updates based on ODDC sync 8/2:

- [ ] Remove Upcoming Events. Move Latest News to top item.
- [ ] Switch CTA buttons: News first, then Events.
- [ ] Add "DCEG at Scientific Meetings" as a promo block 
- [ ] Remove video component

**Comment by laurelthrash** [comment]
@dcvijanovic1k @driscollmd Changes from v3/final Mural board. Aligned with ODDC on 09/11:

- [ ] Change changing "profile investigators" to "investigator profiles" in Linkage eNewsletter promo block.

**Comment by laurelthrash** [comment]
Final Mural shared with ODDC on Thurs. 09/14. Closing this ticket as all subtasks are complete. Will create a new ticket for new items that arise. Cc: @dcvijanovic1k @driscollmd
