### ISSUE TITLE
Nano Homepage: R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#755]
> META: #743 
> SP: TBD

### Description
https://www.cancer.gov/nano/

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

### Sub-Tasks
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [ ] Add final comp to Mural board for content owner review [add link to this tic

### Final Documentation
- Mural board for content owner feedback: https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1686842633243/9e363786dcf8b6f9c043e6c4d350b0fabe81e2a3?sender=uc8881d65820946a13d002641
- Content supplemental document/talking points: [Content recommendations](https://nih-my.sharepoint.com/:w:/r/personal/castanedaam_nih_gov/Documents/C.gov%20Landing%20Page%20Recommendations.docx?d=wbf144a60b8df4239be51c7ebc28a191c&csf=1&web=1&e=DLBSSI)
- Comp: [Figma link](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?node-id=514-12336&scaling=min-zoom&page-id=310%3A17103)
- Analytics PDF: [Redesign_ Nano.pdf](https://github.com/NCIOCPL/ncids/files/11212630/Redesign_.Nano.pdf)
- Analytics Dashboard: https://www5.an.adobe.com/x/5_u5sxa

**Comment by laurelthrash** [comment]
Approved internally via internal meeting and Slack on 04/27. Moving to "on hold" until time is scheduled for review with the federal team.

**Comment by laurelthrash** [comment]
**[In Progress] Updates from meeting with federal team 05/15:**

- [ ] Add suggested images to the placeholder images 
- [ ] Remove heading/title and sub-heading 
- [ ] Remove “About NSDB” from the CTA and replace with “Apply for the Alliance for Nanotechnology”  
- [ ] Add “Related NCI Funding and Initiatives” to right guide card, and move “Apply for the Alliance for Nano...” since this was moved to the CTA
- [ ] Add “Data Sharing” to right guide card 
- [ ] Add nanotechnology characterization lab to promote it

**Comment by laurelthrash** [comment]
**Updates noted via Slack review 05/18:** @a-heirtzler @adrianacastaneda 
- [ ] Pull feature card descriptions for "Publication and Presentations" and "Cancer Nanotechnology Plan" to replace the lorem ipsum?
- [ ] Remove the "Funded Research" link in the CTA strip. We can now have two button links in the CTA strip. So we can just keep those two.
- [ ] Add "NCI Alliance Companies"  to the Research guide card
- [ ] Order of the links on the Research guide card should be:
    - Nanotechnology Characterization Lab
    - Data Sharing
    - NCI Alliance Companies
    - Related NCI Funding Initiatives

**Comment by laurelthrash** [comment]
Team reviewing for final changes - will send to ODDC federal team early week of 6/5 for final review.

**Comment by laurelthrash** [comment]
Sent via Teams to federal team. Requested feedback by EOD Thurs. 6/9. Will otherwise call the comps final ahead of stakeholders conversations.

**Comment by laurelthrash** [comment]
@adrianacastaneda - note from Anna for the talking points of our first stakeholder meeting. Will you please ensure this is incorporated?

"[Based on our attendees]...please include high level information about the functionality and flexibility of the modular components when we present our recommendations to them."

**Comment by adrianacastaneda** [comment]
@laurelthrash thanks! Copy that!

**Comment by laurelthrash** [comment]
**Feedback from federal team shared with Teams 6/6 and 6/8:**

- [x] The hero image (I can't see it now because I think Monika is editing) had a version of this image with a different crop, so there was lots of space between the top of the image and the balls. Please consider reducing that space or adjusting the crop.

Notes from Teams exchange: 
- Determined we do not want to implement a page title. If DCTD advocates to have the full DOC name identified we can consider it, but want to initially leave it off the comp.

**Comment by laurelthrash** [comment]
Final comp approved by Anna on 6/20. Next step: prepare Mural board ahead of 6/20 stakeholder conversation. Cc: @a-heirtzler @adrianacastaneda

**Comment by laurelthrash** [comment]
Marking this ticket as complete and will open a new ticket as all sub-tasks are complete. Will open a new ticket if subsequent changes are needed. Cc: @adrianacastaneda @a-heirtzler
