### ISSUE TITLE
Physics Homepage: R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#756]
> META: #743 
> SP: TBD

### Description
https://physics.cancer.gov/

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

### Sub-Tasks
- [ ] Conduct review of specific landing page 
- [ ] Document content recommendations 
- [ ] Review content recommendations internally
- [ ] Create comp that demonstrates recommendations 
- [ ] Review comp internally
- [ ] Review final recommendations and comp with federal team
- [ ] Make necessary revisions and finalize for content owner conversations
- [ ] Receive final ODDC team approval
- [ ] Add final comp to Mural board for content owner review [add link to this ticket]

### Final Documentation
- Mural board for content owner feedback: [INSERT]
- Content supplemental document/talking points: [INSERT]
- Comp: [INSERT]
- Analytics PDF: [INSERT]
- Analytics Dashboard: [INSERT]

**Comment by laurelthrash** [comment]
Schedule updated so that Physics is on hold.

**Comment by laurelthrash** [comment]
The Physics microsite was retired so the use of NCIDS components is not necessary. Closing this ticket.
