### ISSUE TITLE
SBIR Homepage: R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#757]
> META: #743 
> SP: TBD

### Description
https://sbir.cancer.gov/

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

### Sub-Tasks (revived Nov. 2023)
- [x] Review and revise home page recommendations and comp
- [x] Review comp internally (via Slack)
- [x] Review final recommendations and comp with federal team
- [x] Update comp/Mural board
- [x] Share with federal team
- [x] Share Mural with SBIR 

### Sub-Tasks (from initial comp creation)
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally (via Slack)
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally (via Slack)
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [ ] Add final comp to Mural board for content owner review [add link to this ticket]

### Final Documentation
- Mural board for content owner feedback: [word doc link](https://nih-my.sharepoint.com/:w:/r/personal/castanedaam_nih_gov/Documents/C.gov%20Landing%20Page%20Recommendations.docx?d=wbf144a60b8df4239be51c7ebc28a191c&csf=1&web=1&e=0vNNOJ)
- Content supplemental document/talking points: [INSERT]
- Comp: [Figma Link](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=279%3A11473&node-id=279-11571&viewport=819%2C390%2C0.13&scaling=min-zoom)
- Analytics PDF: [Redesign_ SBIR.pdf](https://github.com/NCIOCPL/ncids/files/11159039/Redesign_.SBIR.pdf)
- Analytics Dashboard: [Dashboard](https://www5.an.adobe.com/x/5_tujoo)
Note: many elements on the page do not have analytics on them so this is a much more limited report with many caveats

**Comment by ellisap** [comment]
SBIR is particularly interested in how to feature upcoming events on their homepage. They want to highlight upcoming webinars for specific audiences, and have it be easy [for anyone on their staff?] to maintain. During their initial microsite migration, they prioritized this and we built the "Information Sessions" section on their custom homepage. Problems they're currently facing with this section: Sometimes there are no upcoming events. Sometimes there are many upcoming events. The raw HTML block is hard to edit. Sometimes the event passes and they don't update it. There may be more. [Note: These are all points we anticipated and made when they identified the need for this section.]

They're interested if their analytics show people are using the links on their current homepage. (If users are not using the links, it may be because the content isn't frequently updated, and events have often passed.)

**Comment by nicolecrom** [comment]
Hi @ellisap - Here is some info on the events link on the homepage. I will say that SBIR analytics is not fully capturing everything in the custom html block, and Events is one of them. I can see the clicks to that block but not the specific name of the link, so I cannot distinguish between the different events clicked at this time.

Overall usage is fairly low of this section. 
From 8/24 - 3/31, there were 73 visits that clicked the link - this is 0.9% of visits to the homepage. 
In that same time, 107 visits used the "Events" link in the mega menu from the homepage.

The main events page is seeing decent traffic with almost 1,300 visits in that time.
The individual pages are lower traffic - one the ones featured on the home page right now (despite being past) is the informational webinar and has the highest traffic of event pages with 97 visits. about 50% of those came directly on to the page and 16% were on the homepage before this page (and so may have used the link).
Hope that helps!

**Comment by monika-jaeger** [comment]
[Comp for SBIR](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=279%3A11473&node-id=279-11571&viewport=819%2C390%2C0.13&scaling=min-zoom)

**Comment by laurelthrash** [comment]
Reviewed internally via Slack on 04/19 - no changes requested on the comps.

**Comment by laurelthrash** [comment]
**ODDC Federal Review Meeting 04/25**

- [ ] Change “About SBIR” to “Funding” and link to the Small Business Funding MLP in CTA strip. This is to be consistent with our CTA strip guidance.
- [ ] Select another hero. Current hero feels unfinished. Either generate a new image (ideas provided by Chuck) or use a placeholder that makes it is clear it is not an image.
- [ ] Replace “Illumina Success Story” logo with generic image.
- [ ] Add new promo block for “Bring Ideas to Life” event. 
    - This as an example to demonstrate how to highlight events. 
- [ ] Replace guide card links with high priority items: 
    - [ ] I-Corps at NIH 
    - [ ] Small business applicant assistance program 
- [ ] Feature Card: Replace I-Corps with About SBIR 
- [ ] Feature Card Heading: Replace "Placeholder Heading" with "Propelling Innovation in Cancer Technology Development"
- [ ] Review possible solutions: Can we add a feature card row for success stories?
- [ ] Add content regarding SBIR’s equity efforts 
    - Current Content: Underrepresented small businesses 
    - Alternative: Add a placeholder to show gap in content 
- [ ] Revisit which evergreen content to highlight and how 

Notes
- There is an upcoming paid campaign. ODDC federal team will let us know if there is content from this campaign that should be incorporated. 
- Frame conversation around images as an opportunity to collaborate/partner with SBIR to create the best design. 

Cc: @monika-jaeger @adrianacastaneda

**Comment by laurelthrash** [comment]
Coordinating with Anna on final updates.

**Comment by adrianacastaneda** [comment]
New updates for SBIR comp:

SBIR Comp updates:

- Change "SBIR Events" to "About SBIR"
- Add promo block for "FDA Regulation of Oncology-related Technologies"
   - It will lead to this page: https://sbir.cancer.gov/commercialization/fda
- Change the title for the Illumina feature card title to: Success Story: Illlumina
- Change the description for the Illumina feature card to the below:
   - "Biomedical researchers at Illumina are developing next-generation tools to analyze genetic variation and function on a massive scale. Illumina used NCI SBIR funding to develop their Next Generation Sequencing technology."
- Remove the subheading "SBIR Development Center" since it's already included in the logo
- For the middle feature card “I-Corps at NIH,” shift the crop so the person isn’t decapitated

**Comment by laurelthrash** [comment]
@adrianacastaneda to take a look before calling comps complete. Require final ODDC federal team sign-off. Cc: @monika-jaeger

**Comment by laurelthrash** [comment]
**From 05/23 Slack conversation**
- [ ] Update hero image to offset negative space @chuckhrose

**Comment by monika-jaeger** [comment]
@laurelthrash @chuckhrose updated widescreen hero image in [SBIR comps](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=279%3A11473&type=design&node-id=279-11571&viewport=2353%2C1438%2C0.5&scaling=min-zoom) with new hero image.

**Comment by laurelthrash** [comment]
Sent via Teams to federal team. Requested feedback by Thurs. 6/9. Will otherwise call the comps final ahead of stakeholders conversations.

**Comment by laurelthrash** [comment]
**Changes requested via Teams 6/6:** Cc: @monika-jaeger 

- [ ] Update event descriptions to the following:
    - [ ] Dallas: "On April 23, meet our experts in Dallas to learn about NIH-wide aspects of the federal SBIR/STTR programs and to discuss NCI-specific details of these programs."
    - [ ] Informational Webinar: "Cancer technology innovators, we want to help you get your projects to the market! On February 23, join us virtually to learn about funding opportunities and helpful resources available to you."
    - [ ] Office Hours: Schedule a one-on-one conversation with an SBIR expert! From 2 to 4PM ET on Friday, February 24, NCI Program Directors will talk directly to potential and current applicants, awardees, or anyone else who could benefit from a conversation with our team."

Add to Mural @adrianacastaneda 
- [ ] Discuss optimal event promo description text

**Comment by laurelthrash** [comment]
Confirmed 6/12: no additional feedback from the federal team on the above comp. This is considered final ahead of our content stakeholder meeting with SBIR, which is TBD. Cc: @monika-jaeger @adrianacastaneda

**Comment by laurelthrash** [comment]
On hold for the time being - awaiting confirmation from SBIR that they are ready to move forward with adopting the R2.1 components for their site. Moving to our approved backlog until we hear more.

**Comment by laurelthrash** [comment]
@adrianacastaneda @dcvijanovic1k Changes to comps (and update to Mural board) following meeting with federal team on 12/5/23: 
- [ ] Update the comp with the SBIR mega menu
- [ ] Remove SBIR page title (conversation with SBIR regarding spelling this out)

Notes:
- Need to stress to SBIR that if they don't have three events, they can move to a promo block. Stress flexibility of the design. 
- Leave Events feature card row as-is but stress flexibility of components to SBIR. 
- These are placeholder images - their design team can design updated images, as desired.
