### ISSUE TITLE
MyPART Homepage (English & Spanish): R2 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#758]
> META: #743

### Description
- EN: https://www.cancer.gov/pediatric-adult-rare-tumor/
- SP: https://www.cancer.gov/pediatric-adult-rare-tumor/espanol

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2 recommendations and create mock up that use R2 components only. 

### Sub-Tasks
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]

### Final Documentation
- Mural board for content owner feedback: [INSERT]
- Content supplemental document/talking points: [INSERT]
- English Comp: [INSERT]
- Spanish Comp: [INSERT]
- Analytics Dashboard: https://www5.an.adobe.com/x/5_12xz9e

**Comment by laurelthrash** [comment]
Changes on comp discussed 11/7:
- [ ] Adjust "Header here" (x2) on Spanish version
- [ ] Update clinic imagery on Spanish (Adriana to share input here)
- Leave tagline as-is, but point out as possible changes

Cc: @dcvijanovic1k @adrianacastaneda @monika-jaeger

**Comment by laurelthrash** [comment]
@adrianacastaneda @dcvijanovic1k @monika-jaeger Changes following federal team sync:

- [ ] Find a way to incorporate the full study title into the page (avoid using the tagline, if possible)

Notes
- Leave feature card row that contains blogs to generate discussion around connection to the Cancer Currents blog
- Federal team to provide information/recommendation regarding Spanish translation support

**Comment by laurelthrash** [comment]
Mural board shared with ODDC ahead of 12/5 kick-off meeting.

**Comment by laurelthrash** [comment]
Mural board shared with client for review. Will close this ticket since the work outlined in the ticket is complete. Will create additional tickets for next steps. Cc: @adrianacastaneda @dcvijanovic1k
