### ISSUE TITLE
NCI-CONNECT Homepage (English & Spanish): R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#759]
> META: #743 
> SP: TBD

### Description
- https://www.cancer.gov/rare-brain-spine-tumor/
- https://www.cancer.gov/rare-brain-spine-tumor/espanol

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

PAGES in ENGLISH and SPANISH:  If a landing page has pages in both English and Spanish, both pages must either move to R2.1 at the same time, or both wait to move until after R2.1. 

### Sub-Tasks
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]

### Final Documentation
- Mural board for content owner feedback: https://app.mural.co/invitation/mural/publicissapient7269/1686257574978?sender=u44cc8ba0586f3bbc923b4447&key=465e29ea-bd57-4f04-97a0-1c1523444945
- Content supplemental document/talking points: [Content recommendations](https://nih-my.sharepoint.com/:w:/r/personal/castanedaam_nih_gov/Documents/C.gov%20Landing%20Page%20Recommendations.docx?d=wbf144a60b8df4239be51c7ebc28a191c&csf=1&web=1&e=DLBSSI)
- Comp: https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=310%3A17102&node-id=583-13006&viewport=584%2C8%2C0.25&scaling=min-zoom
- Analytics PDF (English): [Redesign_ NCI Connect Home.pdf](https://github.com/NCIOCPL/ncids/files/11213068/Redesign_.NCI.Connect.Home.pdf)
- Analytics Dashboard (English): https://www5.an.adobe.com/x/5_u5sx6
- Analytics PDF (Spanish): [Redesign_ NCI Connect Spanish Home.pdf](https://github.com/NCIOCPL/ncids/files/11213067/Redesign_.NCI.Connect.Spanish.Home.pdf)
- Analytics Dashboard (Spanish): https://www5.an.adobe.com/x/5_u5swx

**Comment by laurelthrash** [comment]
**Internal UX review meeting 04/27:**

- [ ] Ensure headings and links are title case (English)
     - [ ] Tumor types 
     - [ ] Links in guide card
- [ ] Figure out why shadow is a coral color when it should be grey (English and Spanish)

**Comment by laurelthrash** [comment]
Approved internally via Slack. Moving to "on hold" until time is scheduled to review with the ODDC federal team.

**Comment by laurelthrash** [comment]
**Action items from 6/6 federal conversation:**
- [ ] Keep "Explore Clinical Studies" button on CTA strip, and note we want to to discuss this with the NCI-CONNECT team
- [ ] Make sure "Connect" is title case
- [ ] Be prepared for request to highlight Tumor Types in Spanish 
- [ ] Add sub-heading back in for English and Spanish

Notes
- Leave as-is and note we can pull the feature card row "Patient Resources" above guide card row
- Mention flexibility with different components, but noting certain things can be found via search

**Comment by laurelthrash** [comment]
Review Mural shared with Anna 6/12 via email. Closing this ticket and will open a new ticket for future updates. Cc: @adriancofie @dcvijanovic1k
