### ISSUE TITLE
Cgov Homepage (English & Spanish): R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#760]
> META: #743 

### Description
- https://www.cancer.gov/
- https://www.cancer.gov/espanol

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

PAGES in ENGLISH and SPANISH:  If a landing page has pages in both English and Spanish, both pages must either move to R2.1 at the same time, or both wait to move until after R2.1. 

### Sub-Tasks
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]. Include: 
    - [x] Reference all available R2.1 components
    - [x] Denote content that is intended to be rotating content  

### Final Documentation
- Mural board for content owner feedback: [Mural Board](https://app.mural.co/invitation/mural/publicissapient7269/1681745427641?sender=u44cc8ba0586f3bbc923b4447&key=c291608a-8624-4fc3-9efc-83ad0be99de9)
- Content supplemental document/talking points: [Content recs doc](https://nih-my.sharepoint.com/:w:/r/personal/castanedaam_nih_gov/Documents/C.gov%20Landing%20Page%20Recommendations.docx?d=wbf144a60b8df4239be51c7ebc28a191c&csf=1&web=1&e=0vNNOJ)
- English Comp: [Figma Link](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7001&node-id=142-7351&viewport=281%2C1653%2C0.25&scaling=min-zoom)
- Spanish Comp: [Figma Link](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7001&node-id=142-8600&viewport=281%2C1653%2C0.25&scaling=min-zoom)
- Analytics PDF: [Redesign_ Homepage.pdf](https://github.com/NCIOCPL/ncids/files/10902533/Redesign_.Homepage.pdf)
- Analytics Dashboard: https://www5.an.adobe.com/x/5_sfp11

**Comment by laurelthrash** [comment]
Notes from 3/7 internal meeting:

- Plan is to generally speak to components/content using informal bullet points from IAs (takeaway: supplemental document with content recommendations/talking points), followed by the comp that demonstrates recommendations
- Can consider an annotated wireframe or other tactic for how to address with content owners

Actions for Cgov HP:

- [ ] Remove "Newly Diagnosed" button from the comp, and add a note as a content project in the future [English] 
- [ ] Develop supplemental document/talking points for content recommendations [English & Spanish]

**Comment by blilianyu** [comment]
Update Cancer.gov home page comps with content recommendations 

English: https://publicis.invisionapp.com/console/Cancer.gov-Home-Page-R2.1-clcul8x0q0au801augpgc56df/clefr15n601820193doqieveq/play

Spanish: https://publicis.invisionapp.com/console/Cancer.gov-Home-Page-R2.1-clcul8x0q0au801augpgc56df/cld35kfqs3rfd01ftautl0dij/play

**Comment by monika-jaeger** [comment]
Updated comps for English & Spanish here: https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7001&node-id=142-7351&viewport=899%2C661%2C0.06&scaling=min-zoom

**Comment by laurelthrash** [comment]
Federal team review meeting 04/4 changes below and found in the [full meeting notes](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/Home%20and%20Landing%20Page%20Review/Cgov%20Home%20Page/2023.04.04%20ODDC%20Review.docx?d=w07f65bddb2b546648d1f5d411f1a0f30&csf=1&web=1&e=jvG2nL):

**English**

- [ ] Replace one of the guide card links with Partners in Cancer Research  
- [ ] Potential change to sentences under the guide cards **[Need from federal team]** 
- [ ] Make guide cards level on comp.  
- [ ] Add another feature card or guide card for admin/evergreen content [verify - could add a title to indicate it is more evergreen content] 
    - [ ] Leadership 
    - [ ] List of NCI organizations 
    - [ ] Maybe one other thing that is more Admin (e.g., director) 
- [ ] Try feature cards in between promo blocks to bring up featured content 
- [ ] Add NCP graphic to the promo block **[Can get the promo graphic from Aaron]**  
- [ ] Add "play" overlay on video component

**Spanish**

- [ ] Switch out Researchers (Investigación) guide card for a Health Professional-centered guide card 
- [ ] Remove EIP promo block 
- [ ] Consider moving guide cards up to be consistent with English

Excluded above is to ensure Spanish is formally translated since this will happen during content conversations/touch points with the Spanish team. 

Cc: @meglake @chuckhrose @lburack @adrianacastaneda @monika-jaeger

**Comment by laurelthrash** [comment]
Requested guide card sentence changes from federal team by Wed. 04/12.

**Comment by laurelthrash** [comment]
@monika-jaeger I have updated the above comment to include requested changes to the Spanish comp identified on 04/13. Cc: @adrianacastaneda

**Comment by monika-jaeger** [comment]
Updates to Home Page comps are [HERE](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7001&node-id=142-7351&viewport=-4%2C1526%2C0.25&scaling=min-zoom).

**Comment by laurelthrash** [comment]
Closing this ticket since all work in preparing the recommendations and associated comps are complete.
