### ISSUE TITLE
Cgov About Cancer (English & Spanish): R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#761]
> META: #743 
> [Landing Page Recommendation Calendar Here](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1%20Landing%20Page%20Update%20Schedule.xlsx?d=w6976516d4d8048cb9f83258530f202b8&csf=1&web=1&e=Zk5aO6)

### Description
- https://www.cancer.gov/about-cancer
- https://www.cancer.gov/espanol/cancer

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

PAGES in ENGLISH and SPANISH:  If a landing page has pages in both English and Spanish, both pages must either move to R2.1 at the same time, or both wait to move until after R2.1. 

### Sub-Tasks
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]

### Final Documentation
- Mural board for content owner feedback: [Mural Board](https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1683922385827/d78b1fe34e23c3235e980c3fa729fc93674d77d5?sender=uc8881d65820946a13d002641)
- Content supplemental document/talking points: https://nih-my.sharepoint.com/:w:/r/personal/castanedaam_nih_gov/Documents/C.gov%20Landing%20Page%20Recommendations.docx?d=wbf144a60b8df4239be51c7ebc28a191c&csf=1&web=1&e=0vNNOJ
- Comp: [Figma Link](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=0%3A1&node-id=20-2546&viewport=318%2C71%2C0.5&scaling=min-zoom)
- Analytics PDF: [Redesign_ About Cancer.pdf](https://github.com/NCIOCPL/ncids/files/10943326/Redesign_.About.Cancer.pdf)
- Analytics Dashboard: https://www5.an.adobe.com/x/5_smfbe

**Comment by laurelthrash** [comment]
No notes or changes to recommendations or comps from internal UX team meeting on 03/28.

**Comment by meglake** [comment]
**ODDC review feedback from 4/20:**
English: 
- [ ] Make sure imagery is more diverse and not same stock models in photos 
- [ ] Add a button/link to CIS to ‘Newly Diagnosed’ guide card (Lindsay/Adriana to connect with Michael on labels)  
- [ ] Check with Michael on the Clinical trials for patients and caregivers page for potential label shortening and pending site arch changes to consider 
- [ ] Connect with Michael on visual treatment and messaging for CIS promo block 
- [ ] Check label title case and make sure consistent across comp 

Spanish: 
- [ ] Make sure imagery is more diverse and not same stock models in photos 
- [ ] For content owner meeting: Discuss adding CIS to Newly Diagnosed guide card (removing one of the links on there now) with Carolina 

@monika-jaeger @adrianacastaneda

**Comment by laurelthrash** [comment]
**Feedback from Anna 05/05 via Teams**

- Determination: Keep the comp as-is and be prepared to discuss the justification and the alternatives, or other alternatives we think of, and explore other suggestions and options from the decisionmakers/stakeholders. 
- Justification and alternatives: 
    - We initially removed the "Patient Education Publications" card due to low visits and a sense that this was a lower priority overall. Additionally, the best available component to showcase this content is a promo block, which we did not feel the content necessarily warranted. However, we can revisit this placement if this content is a high priority to feature. 
    - As alternatives, we can consider adding a promo block or swapping out the current "Managing Cancer Costs" feature card.

@monika-jaeger @adrianacastaneda

**Comment by laurelthrash** [comment]
Doing some clean up and realized this ticket is not closed. Closing out as pages are complete.
