### ISSUE TITLE
Cgov About NCI (English & Spanish): R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#762]
> META: #743 

### Description
- https://www.cancer.gov/about-nci
- https://www.cancer.gov/espanol/instituto

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

PAGES in ENGLISH and SPANISH:  If a landing page has pages in both English and Spanish, both pages must either move to R2.1 at the same time, or both wait to move until after R2.1. 

### Sub-Tasks
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally
- [x] Get w/Megan re: incorporating National Cancer Plan
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]. Include: 
    - [x] Reference all available R2.1 components
    - [x] Denote content that is intended to be rotating content  

### Final Documentation
- Mural board for content owner feedback: [Mural Board](https://app.mural.co/invitation/mural/publicissapient7269/1681745427641?sender=u44cc8ba0586f3bbc923b4447&key=c291608a-8624-4fc3-9efc-83ad0be99de9)
- Content document: [Content recs doc](https://nih-my.sharepoint.com/:w:/r/personal/castanedaam_nih_gov/Documents/C.gov%20Landing%20Page%20Recommendations.docx?d=wbf144a60b8df4239be51c7ebc28a191c&csf=1&web=1&e=0vNNOJ)
- Comp: [About NCI Comp (in Figma)](https://www.figma.com/file/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?node-id=21%3A4037&t=GrRVAr6jFviVNSOK-1)
- Analytics PDF: [Redesign_ About NCI Landing Page.pdf](https://github.com/NCIOCPL/ncids/files/10902534/Redesign_.About.NCI.Landing.Page.pdf)
- Analytics Dashboard: https://www5.an.adobe.com/x/5_sfpkf

**Comment by monika-jaeger** [comment]
Added [About NCI](https://www.figma.com/file/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?node-id=21%3A4037&t=GrRVAr6jFviVNSOK-1) comp under 'Documentation' in ticket description.

**Comment by monika-jaeger** [comment]
Updates for About NCI English & Spanish comps here: https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=21%3A4037&node-id=21-4038&viewport=777%2C471%2C0.25&scaling=min-zoom

**Comment by laurelthrash** [comment]
@monika-jaeger Requested change to the English comp following ODDC review on 04/13:

- [ ] English: Replace 'Overview & Mission' promo block with 'Equity and Inclusion'

Cc: @lburack @adriancofie

**Comment by laurelthrash** [comment]
Closing this ticket since all work in preparing the recommendations and associated comps are complete.
