### ISSUE TITLE
Cgov Grants & Training (English & Spanish): R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#763]
> META: #743 
> SP: TBD

### Description
- https://www.cancer.gov/grants-training
- https://www.cancer.gov/espanol/subvenciones-capacitacion

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

PAGES in ENGLISH and SPANISH:  If a landing page has pages in both English and Spanish, both pages must either move to R2.1 at the same time, or both wait to move until after R2.1. 

### Sub-Tasks
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]

### Final Documentation
- Mural board for content owner feedback: [Mural Board Link](https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1683305102077/dad9b160d2427c5a053afe279918c8be01068484?sender=uc8881d65820946a13d002641)
- Content supplemental document/talking points: [Talking Points](https://nih-my.sharepoint.com/:w:/r/personal/castanedaam_nih_gov/Documents/C.gov%20Landing%20Page%20Recommendations.docx?d=wbf144a60b8df4239be51c7ebc28a191c&csf=1&web=1&e=0vNNOJ)
- Comp: [Figma Link](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A11354&node-id=142-11355&viewport=174%2C867%2C0.25&scaling=min-zoom)
- Analytics PDF: [Redesign_ Grants and Training.pdf](https://github.com/NCIOCPL/ncids/files/10943328/Redesign_.Grants.and.Training.pdf)
- Analytics Dashboard: https://www5.an.adobe.com/x/5_smfbq

**Comment by laurelthrash** [comment]
Changes based on internal UX team discussion on 03/30: @monika-jaeger 

- [ ] Switch out photo for "Grant Funding & Process" so that it does not match the hero

**Comment by monika-jaeger** [comment]
Updated comp with new photo for 1st guide card. Link is under 'Documentation'
cc @laurelthrash

**Comment by meglake** [comment]
**ODDC review feedback from 4/20:**
- [ ] Make sure imagery is more diverse and not same stock models in photos 
- [ ] Change order of Grant Funding & Process guide card links:  
  - Funding Opportunities 
  - Funding Strategy 
  - Apply for a Grant 
  - Manage Your Award 
  - Grant Policies & Process 
  - Research Program Contacts 
- [ ] Training Opportunities guide card – need to determine better label for ‘CRCHD Diversity Training’ button (It’s about offering/providing funding for cancer research training for those from backgrounds underrepresented in cancer research work (not about internal diversity training, like the mandatory trainings we all do) 
- [ ] Change Bottom Line blog promo title to the actual blog name “NCI Bottom Line: A Blog about Grants and More” 
- [ ] Content Owner Question – Ask Carolina for text/formatting for best way to indicate that the link on the landing page is taking you to an English page. 

@monika-jaeger @adrianacastaneda

**Comment by laurelthrash** [comment]
All to-dos addressed so closing this ticket. Will track next steps following content owner review in a new ticket. Cc: @adrianacastaneda @monika-jaeger
