### ISSUE TITLE
Cgov Research (English & Spanish): R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#764]
> META: #743 
> [Landing Page Recommendation Calendar Here](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1%20Landing%20Page%20Update%20Schedule.xlsx?d=w6976516d4d8048cb9f83258530f202b8&csf=1&web=1&e=Zk5aO6) 

### Description
- https://www.cancer.gov/research
- https://www.cancer.gov/espanol/investigacion

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

PAGES in ENGLISH and SPANISH:  If a landing page has pages in both English and Spanish, both pages must either move to R2.1 at the same time, or both wait to move until after R2.1. 

### Sub-Tasks
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]

### Final Documentation
- Mural board for content owner feedback: [Mural Board](https://app.mural.co/invitation/mural/publicissapient7269/1683558339751?sender=u44cc8ba0586f3bbc923b4447&key=4377eaf1-c6c0-4e8a-8569-ae2bbad38f25)
- Content supplemental document/talking points: https://nih-my.sharepoint.com/:w:/r/personal/castanedaam_nih_gov/Documents/C.gov%20Landing%20Page%20Recommendations.docx?d=wbf144a60b8df4239be51c7ebc28a191c&csf=1&web=1&e=0vNNOJ
- Comp: [Figma Link: Research Page Content Recs: English & Spanish](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7002&node-id=142-10148&viewport=-111%2C1828%2C1&scaling=min-zoom)
- Analytics PDF: [Redesign_ Research.pdf](https://github.com/NCIOCPL/ncids/files/10943325/Redesign_.Research.pdf)
- Analytics Dashboard: https://www5.an.adobe.com/x/5_smfbm

**Comment by laurelthrash** [comment]
Internal review on 03/23:

English
- [ ] Replace "Research Advances by Cancer Type" in the CTA strip with "[Partners in Cancer Research](https://www.cancer.gov/research/cancer-research-partners)" 
- [ ] Add "...Cancer Workforce" under the right hand guide card as the 6th link
- [ ] Description on Guide Card w/Image and Description - either use lorem ipsum or make it more specific to the topic
- [ ] Create mobile comp for English and Spanish

Notes:

- Might have to revisit this comp based on NCP progress

**Comment by monika-jaeger** [comment]
Updated comp link added to 'Comp' under 'Documentation' heading.
cc @laurelthrash

**Comment by meglake** [comment]
**ODDC review feedback from 4/20:**
- [ ] Change feature card row header to ‘Featured Initiatives and Programs’ 
- [ ] Replace Stories of Discovery feature card with TTC & SBIR page  
- [ ] NCI’S Role in Cancer Research & Infrastructure guide card – Move NCI-Designated Cancer Centers up under NCI’s Clinical Trials Programs 

@monika-jaeger @adrianacastaneda

**Comment by laurelthrash** [comment]
**Updates requested from Anna on 05/05 via Teams**
- [ ] Include EIP as a promo block below Cancer Moonshot
- [ ] Update the feature card title to "Tech Transfer & Small Business Partnership"

@monika-jaeger @adriancofie

**Comment by monika-jaeger** [comment]
[Research](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7002&type=design&node-id=142-9370&viewport=15%2C783%2C0.25&scaling=min-zoom) comp has been updated to add the EIP Promo Block and updated feature card title.

**Comment by laurelthrash** [comment]
All next steps complete - closing this ticket. Cc: @adrianacastaneda @monika-jaeger
