### ISSUE TITLE
Guidance for R2.2 Components

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/ncids#789]
Description: Define and document content strategy guidance for R2.2 components to implement on the NCIDS site and in the Drupal guide. This guidance will also be added as part of the R2 Details PPT stakeholder deck. 

**META:** https://github.com/NCIOCPL/cgov-digital-platform/issues/3317

### Sub-Tasks
- [x] Define content strategy for NCIDS site and Drupal Guide for each R2.2 component:
   - [x] Hero w/ Tagline (dark
   - [x] Hero w/ Primary CTA (dark)
   - [x] Promo Block w/Image (light)
   - [x] Promo Block - text only (light)
   - [x] Guide Card Row
- [x] Review guidance internally
- [x] Receive approval from federal team
- [x] Submit for formal copy edit: https://tracker.nci.nih.gov/browse/CGOV-18381
- [x] Document guidance in GH Wiki for implementation on NCIDS site
    - [x] Use this as a test run with regard to how to format content in GH Wiki so that it is clear which information is a part of R2.1 and which is new as part of R2.2 
- [x] Separate tickets to be created to update Drupal Guide with guidance and adding information to the DS documentation site. 

Guidance to include:
-  Word counts or character limits
-  Scenarios

### Notes
Similar task requested in #721

**Comment by laurelthrash** [comment]
Determined on 03/14 that we will use the R2.2 guidance as a test run with regard to how to format the [NCIDS Git Hub Wiki](https://github.com/NCIOCPL/ncids/wiki) to clearly indicate the addition of new R2.2 guidance. @adrianacastaneda @lburack @sarinapadilla

**Comment by laurelthrash** [comment]
Goal for completion of adding to the GH Wiki is Fri. 04/21 Cc: @adrianacastaneda

**Comment by laurelthrash** [comment]
GH Wiki updated - closing this ticket.
