### ISSUE TITLE
User Story: Build A. Promo Block - Light Promo Block with Image

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#790]
## User Story
**As a** website editor
**I want to** be able to promote content with light-colored, left or right anchored visuals
**so that** users can easily see identify and navigate to important content.

### Tasks
- [ ] Create Scenarios for this component
- [ ] Create component
- [ ] Update Documentation Site (docs)
- [ ] Update Storybook Site
- [ ] Update Example Site

### Technical Notes
**Styling**
_Anatomy of a component_
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

**Behaviors**
_Summary of state changes and behaviors. AC's are more detailed._

- [ ] 1:1 image on Widescreen, Desktop & Tablet Large (880px or larger)
- [ ] 16:9 image on Tablet, Mobile Large & Mobile (879px or smaller)
- [ ] Image will alternate left and right positioning
- [ ] The heading should be styled as theme-h2-font-size

**Comps**
InVision: https://publicis.invisionapp.com/console/share/GV6QB3AMTEY/981360882

### Acceptance Criteria

```gherkin
Scenario: User views a page with a Light Promo Block with Image
Given a user is viewing a page with a Light Promo Block with Image
  And the Design Solution has been implemented into the Development Solution in the DS
Then the user will be able to view the Light Promo Block with Image on the example site
  And the Light Promo Block with Image on the example site will match the comp
  And the button will have the secondary button style 
  And the button on the Light Promo Block with Image will be clickable
  And the button will be linked to its corresponding content
When the user hovers over the button
Then the button will have the secondary button hover style

Scenario: User views a page with a Light Promo Block with Image on Widescreen, Desktop, or Tablet Large
Given a user is viewing a landing page with a Light Promo Block with Image
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is at least 880px
Then the user will be able to view the Light Promo Block with Image on the example site
  And the image will have a 1:1 aspect ratio

Scenario: User views a page with a Light Promo Block with Image on Tablet, Mobile Large, or Mobile
Given a user is viewing a landing page with a Light Promo Block with Image
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is less than 880px
Then the user will be able to view the Light Promo Block with Image on the example site
  And the image will have a 16:9 aspect ratio

Scenario: User views a page with more than one (1) light Promo Blocks with Image
Given a user is viewing a landing page with more than one (1) Light Promo Blocks with Image
  And the Design Solution has been implemented into the Development Solution in the DS
Then the user will be able to view the Light Promo Blocks with Image on the example site
  And the top-most Light Promo Block with Image should have the image on the left
  And the following Light Promo Block with Image should have the image on the right
  And each subsequent Light Promo Block with Image should alternate the side of the image following the above pattern
```

### Scenarios
**TO BE ADDED**
