### ISSUE TITLE
User Story: Build Promo Block - E. Promo Block Light

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#791]
## User Story
**As a** website editor
**I want to** be able to promote content with dark-colored text
**so that** users can easily see identify and navigate to important content.

### Prerequisites
None

### Tasks
- [ ]  Create Scenarios for this component
- [ ]  Create component
- [ ]  Update Documentation Site (docs)
- [ ]  Update Storybook Site
- [ ]  Update Example Site

### Technical Notes
**Styling**
_Anatomy of a component_
- [ ] Use correct spacing (8px grid) size, emphasis, alignment

**Behaviors**
_Summary of state changes and behaviors. AC's are more detailed.
- [ ]  1:1 image on Widescreen, Desktop & Tablet Large (880px or larger)
- [ ]  16:9 image on Tablet, Mobile Large & Mobile (879px or smaller)
- [ ]  Image will alternate left and right positioning
- [ ]  The heading should be styled as theme-h2-font-size

**Comps**
InVision: https://publicis.invisionapp.com/console/share/GV6QB3AMTEY/981360886

### Acceptance Criteria

```gherkin
Scenario: User views a page with a Light Promo Block
Given a user is viewing a page with a Light Promo Block
  And the Design Solution has been implemented into the Development Solution in the DS
Then the user will be able to view the Light Promo Block on the example site
  And the Light Promo Block on the example site will match the comp
  And the button will have the secondary button style 
  And the button on the Light Promo Block will be clickable
  And the button will be linked to its corresponding content
When the user hovers over the button
Then the button will have the secondary button hover style
```

### Scenarios
**TO BE ADDED**
