### ISSUE TITLE
User Story: Build Hero - A. Hero with Dark Primary Call to Action

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#792]
## User Story
**As a** website editor
**I want** to be able to introduce a page with lighter visuals
**so that** the user's attention is captured and they see a main call-to-action

### Prerequisites
None

### Tasks
- [ ] Create Scenarios for this component
- [ ]  Create component
- [ ]  Update Documentation Site (docs)
- [ ]  Update Storybook Site
- [ ]  Update Example Site

### Technical Notes
**Styling**
_Anatomy of a component_
- [ ]  Use correct spacing (8px grid) size, emphasis, alignment

**Behaviors**
_Summary of state changes and behaviors. AC's are more detailed_
- [ ] Hero image height will be fixed at 427px on widescreen, desktop & tablet large at 641px or larger
- [ ] Hero image will swap out with a 16:9 image on tablet & mobile large at 640px and less
- [ ] Hero image will swap out with a 1:1 image on mobile at 320px
- [ ] Dark text box button will be fixed position so that it is always halfway between the image

**Comps**
InVision: https://publicis.invisionapp.com/console/share/GV6QB3AMTEY/981360873y

### Acceptance Criteria

```gherkin
Scenario: User views a page with a Hero with Dark Primary Call to Action
Given a user is viewing a page with a Hero with Dark Primary Call to Action
  And the Design Solution has been implemented into the Development Solution in the DS
Then the user will be able to view the Hero with Dark Primary Call to Action on the example site
  And the Hero with Dark Primary Call to Action on the example site will match the comp
  And the button will have the primary button style 
  And the button on the Hero with Dark Primary Call to Action will be clickable
  And the button will be linked to its corresponding content
When the user hovers over the button
Then the button will have the primary button hover style

Scenario: User views a page with a Hero with Dark Primary Call to Action on Widescreen, Desktop, or Tablet Large
Given a user is viewing a landing page with a Hero with Dark Primary Call to Action
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is at least 880px
Then the user will be able to view the Hero with Dark Primary Call to Action on the example site
  And the image will have a fixed height of 427px

Scenario: User views a page with a Hero with Dark Primary Call to Action on Tablet or Mobile Large
Given a user is viewing a landing page with a Hero with Dark Primary Call to Action
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is less than 880px and at least 320px
Then the user will be able to view the Hero with Dark Primary Call to Action on the example site
  And the image will have a 16:9 aspect ratio

Scenario: User views a page with a Hero with Dark Primary Call to Action on Mobile
Given a user is viewing a landing page with a Hero with Dark Primary Call to Action
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is less than 320px
Then the user will be able to view the Hero with Dark Primary Call to Action on the example site
  And the image will have a 1:1 aspect ratio
```

### Scenarios
**TO BE ADDED**
