### ISSUE TITLE
User Story: Build Hero - C. Hero with Dark Tagline

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#793]
## User Story
**As a** website editor
**I want to** be able to introduce a page with lighter visuals
**so that** the user's attention is captured and they see a longer tagline

### Prerequisites
None

### Tasks
- [ ] Create Scenarios for this component
- [ ]  Create component
- [ ]  Update Documentation Site (docs)
- [ ]  Update Storybook Site
- [ ]  Update Example Site

### Technical Notes
**Styling**
_Anatomy of a component_
- [ ]  Use correct spacing (8px grid) size, emphasis, alignment

**Behaviors**
_Summary of state changes and behaviors. AC's are more detailed_
- [ ] Hero image height will be fixed at 427px on widescreen, desktop & tablet large at 641px or larger
- [ ] Hero image will swap out with a 16:9 image on tablet & mobile large at 640px and less
- [ ] Hero image will swap out with a 1:1 image on mobile at 320px
- [ ] Dark text box button will be fixed position so that it is always halfway between the image

**Comps**
InVision: https://publicis.invisionapp.com/console/share/GV6QB3AMTEY/981360875

### Acceptance Criteria

```gherkin
Scenario: User views a page with a Hero with Dark Tagline
Given a user is viewing a page with a Hero with Dark Tagline
  And the Design Solution has been implemented into the Development Solution in the DS
Then the user will be able to view the Hero with Dark Tagline on the example site
  And the Hero with Dark Tagline on the example site will match the comp

Scenario: User views a page with a Hero with Dark Tagline on Widescreen, Desktop, or Tablet Large
Given a user is viewing a landing page with a Hero with Dark Tagline
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is at least 880px
Then the user will be able to view the Hero with Dark Tagline on the example site
  And the image will have a fixed height of 427px

Scenario: User views a page with a Hero with Dark Tagline on Tablet or Mobile Large
Given a user is viewing a landing page with a Hero with Dark Tagline
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is less than 880px and at least 320px
Then the user will be able to view the Hero with Dark Tagline on the example site
  And the image will have a 16:9 aspect ratio

Scenario: User views a page with a Hero with Dark Tagline on Mobile
Given a user is viewing a landing page with a Hero with Dark Tagline
  And the Design Solution has been implemented into the Development Solution in the DS
  And the browser width is less than 320px
Then the user will be able to view the Hero with Dark Tagline on the example site
  And the image will have a 1:1 aspect ratio
```

### Scenarios
**TO BE ADDED**
