### ISSUE TITLE
Create Adobe Dashboard Template for Home and Landing Page Data for Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#798]
> META: #743 

### Description
Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

To complete the recommendations, Designers & IAs need analytics data for each home and landing page. This ticket is to create, review, and finalize the dashboard to house the relevant data. 

IMPORTANT NOTE: Analytics information should include data for Spanish. If a landing page has pages in both English and Spanish, both pages must either move to R2.1 at the same time, or both wait to move until after R2.1. 

### Sub-Tasks
- [x] Create preliminary dashboard for home and landing page data
- [x] Internal review of the dashboard and provide feedback
- [x] Make updates [N/A]
- [x] Review final dashboard [N/A]

### Documentation
- N/A - dashboards to be added to associated landing page ticket [[META](https://github.com/NCIOCPL/ncids/issues/743)]

**Comment by nicolecrom** [comment]
Here are the dashboards for the 1st two pages
[Redesign_ Homepage.pdf](https://github.com/NCIOCPL/ncids/files/10902533/Redesign_.Homepage.pdf)
[Redesign_ About NCI Landing Page.pdf](https://github.com/NCIOCPL/ncids/files/10902534/Redesign_.About.NCI.Landing.Page.pdf)
https://www5.an.adobe.com/x/5_sfp11
https://www5.an.adobe.com/x/5_sfpkf

**Comment by laurelthrash** [comment]
Notes from 03/09:

- Did not identify any changes to the analytics dashboards

**Comment by laurelthrash** [comment]
Determined on 03/09 with the team that there are no subsequent edits to the analytics dashboards. Closing this ticket. Will use individual tickets to track creation of the individual dashboards.

**Comment by nicolecrom** [comment]
[Redesign_ Research.pdf](https://github.com/NCIOCPL/ncids/files/10943325/Redesign_.Research.pdf)
https://www5.an.adobe.com/x/5_smfbm
[Redesign_ About Cancer.pdf](https://github.com/NCIOCPL/ncids/files/10943326/Redesign_.About.Cancer.pdf)
https://www5.an.adobe.com/x/5_smfbe
[Redesign_ Grants and Training.pdf](https://github.com/NCIOCPL/ncids/files/10943328/Redesign_.Grants.and.Training.pdf)
https://www5.an.adobe.com/x/5_smfbq
