### ISSUE TITLE
Use USWDS body styles

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#802]
### Issue description
NCIDS currently does not have the expected body color token set. While working on the USWDS v3 upgrade, a number of regressions were found due to inconsistent setting of this token. Update `ncids-css` and related resources to correctly use and show the correct token on the `body` element.

> **ESTIMATE** TBD

#### Task list
- [x] Update ncids-css
- [x] Fix storybook stories and generate correct reference files
- [x] Fix documentation site
- [x] Fix example site

#### Notes
- Body token should be set to `ink` `#1b1b1b`

**Comment by bennettcc** [comment]
Approved by ODDC Feds - please move forward with this fix
