### ISSUE TITLE
Group 4: Analytics for Home and Landing Page Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#807]
> META: #743 ### Description
Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. To complete the recommendations, Designers & IAs need analytics data for each home and landing page. 

This ticket is to create the analytics dashboard for the relevant data. 

Full landing page review schedule [found here](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1%20Landing%20Page%20Update%20Schedule.xlsx?d=w6976516d4d8048cb9f83258530f202b8&csf=1&web=1&e=HcTxxS). 

### Group 4 | April 3 - April 17
- [x] Nano Homepage 
- [x] NCI Connect Homepage (English and Spanish)

### Sub-Tasks
- [x] Create dashboards
- [x] Share dashboard internally and collect feedback, if applicable 
- [x] Add link to dashboard on the associated landing page ticket
     - [x] #755 
     - [x] #759

**Comment by laurelthrash** [comment]
Ticket complete - closing this issue.
