### ISSUE TITLE
Update Drupal Guide for R2.1 Components

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#808]
### Description
Determine if updates need to be made to the Drupal Guide on myNCI (https://mynci.cancer.gov/topics/drupal-guide) based on changes to Drupal during R2.1 release. If changes are needed, make changes and implement the updated information to MyNCI.

**META:** https://github.com/NCIOCPL/cgov-digital-platform/issues/3317

### Subtasks
- [x] Review Drupal Guide and determine if updates need to be made based on R2.1 component release
    - [x] Consider adding new content that is missing
- [x] Outline specific updates
- [x] Obtain internal team approval of updates
- [x] Update as needed
- [x] Obtain federal approval
- [x] Perform copy edit on content [JIRA CGOV-19175]
- [x] Post Drupal guide to MyNCI on Thurs. 07/13 [JIRA CGOV-19176]

### Notes
- Enter as needed

**Comment by laurelthrash** [comment]
Due date of 06/09 to allow time for copy editing and federal review.

**Comment by laurelthrash** [comment]
Update due date: Finalize MyNCI updates by 7/12, for 7/13 content launch.

**Comment by lburack** [comment]
We'll need to update the following Drupal Guide pages:

1. [Images and Multimedia](https://mynci.cancer.gov/topics/drupal-guide-images-and-multimedia), particularly the cropping section but also review the alt text information to make sure it's still accurate. 
2.  [Content Fields](https://mynci.cancer.gov/topics/drupal-guide-content-fields) - update title and description fields to include new components 
3. [Featuring Content in Lists and Cards](https://mynci.cancer.gov/topics/drupal-guide-featuring-content-lists-and-cards)
    - This page primarily focuses on the mini landing page, although homepage feature cards are included. These cards and their design are still technically available on home and landing pages using the existing template (not the new NCIDS option). The question is do we add NCIDS elements to this page or create a new page to house that information? Ultimately components will be available on other inner pages, but we don't yet know which ones. 

@adrianacastaneda @laurelthrash

**Comment by adrianacastaneda** [comment]
Thanks @lburack! 

I agree re: adding the components to the Featuring Content in Lists and Cards page— and think we should change the name (maybe: Lists, Cards, and other Components). We can section off the new components and mention that they're only used within home and landing pages. Once that changes, we can update this page to include inner pages where appropriate. 

I also think we should add the Home and Landing page content type to the [Common Content Types](https://mynci.cancer.gov/topics/drupal-guide-common-content-types) page. We could crosslink to the current "Featuring Content in Lists and Cards" page from here. 

cc: @laurelthrash

**Comment by laurelthrash** [comment]
**Notes from 7/6 conversation:**
- [ ] Delete "very" from "very rarely" from override crops section
- [ ] Add "NCIDS home and landing page components" to use of 16x9 crop
- [ ] Update 1:1 crop (Adriana wrote language on Word doc)
- [ ] Add mention of best practice to set all crops for best performance  
- [ ] Home and landing page fields
    - [ ] Add in the style selection
    - [ ] Keep Word doc with language that can either be 1) shared with H&L page content owners, or 2) used as updated version for the Drupal Guide 
- [ ] Review feature card section and "Other components" section for further edits @lburack

**Comment by adrianacastaneda** [comment]
@laurelthrash Lindsay and I reviewed the doc and made revisions. I've highlighted all that should be added to the guide. The rest of the doc (that is not highlighted) should be kept for reference but will not be added to the drupal guide at this time. Let me know if you have any questions! Thank you!

https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/MyNCI%20Drupal%20Guide%20Updates/MyNCI%20Drupal%20Guide%20Updates%20for%20R2.docx?d=w3f46b146ce9a4cebbc6c971aa2e7944b&csf=1&web=1&e=vOhhio

cc: @lburack

**Comment by adrianacastaneda** [comment]
Link to file for our records: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.1/MyNCI%20Drupal%20Guide%20Updates/For%20Records_Not%20approved_MyNCI%20Drupal%20Guide%20Updates%20for%20R2.docx?d=w2348d6ab3c1442c8a85b1264ee928d4c&csf=1&web=1&e=6KPXLO

cc: @laurelthrash

**Comment by laurelthrash** [comment]
Approved by Anna 7/10 in 3:30pm sync. Next steps: move forward with copy edit, then set for publishing on 7/13 via Jira ticket. Complete supplemental document for specific H&L page training.

**Comment by laurelthrash** [comment]
Posted to MyNCI via JIRA CGOV-19176. Closing out this ticket.
