### ISSUE TITLE
Change usa-footer Storybook story to use twig

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/ncids#826]
### Issue description
> **ESTIMATE** TBD

### Subtasks
- [x] Create a shared template for the subscribe form
- [x] Create a shared template for the nci-big variant of the usa-footer
- [x] Change the nci-big variant of the usa-footer storybook stories to use that shared template

**Comment by sarinapadilla** [comment]
Closing since we are addressing this in #1584.
