### ISSUE TITLE
Collection USWDS Pass Through to NCIDS

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#857]
### USWDS Component Name
[Collection](https://designsystem.digital.gov/components/collection/)

### USWDS Component Packages
* Package usage: `@forward "usa-collection";`
* Dependencies: `uswds-fonts`

### Subtasks
- [x] Make a folder with the component name under uswds-native
- [x] Copy USWDS twig and any JSON
- [x] Make an index.scss for the stories
- [x] Copy and hack up USWDS stories.js file to use our story format
- [x] Create scenarios.js by adding a scenario for each story in stories.js
- [x] Add link to the USWDS documentation on the NCIDS documentation site
- [x] **Patch font size to xs**

**Comment by sarinapadilla** [comment]
This is color meeting dependent. @bennettcc will schedule that meeting for the week of 6/12.

**Comment by bennettcc** [comment]
Moving this item off hold and back to in progress - the color story is complete: https://github.com/NCIOCPL/ncids/issues/978

**Comment by bennettcc** [comment]
Moving back to ready - luminance color story has been merged
