### ISSUE TITLE
Embed Container USWDS Pass Through to NCIDS

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#858]
### USWDS Component Name
[Embed Container] *No documentation page on USWDS*

### USWDS Component Packages
* Package usage: *To be found*
* Dependencies: *To be found*

### Subtasks
- [x] Make a folder with the component name under uswds-native
- [x] Copy USWDS twig and any JSON
- [x] Make an index.scss for the stories
- [x] Copy and hack up USWDS stories.js file to use our story format
- [ ] Create scenarios.js by adding a scenario for each story in stories.js
- [x] Add link to the USWDS documentation on the NCIDS documentation site
