### ISSUE TITLE
Identifier USWDS Pass Through to NCIDS

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#860]
### USWDS Component Name
[Identifier](https://designsystem.digital.gov/components/identifier/)

### USWDS Component Packages
* Package usage: `@forward "usa-identifier";`
* Dependencies: `uswds-fonts`, `uswds-core`

### Subtasks
- [x] Make a folder with the component name under uswds-native
- [x] Copy USWDS twig and any JSON
- [x] Make an index.scss for the stories
- [x] Copy and hack up USWDS stories.js file to use our story format
- [x] Create scenarios.js by adding a scenario for each story in stories.js
- [x] Add link to the USWDS documentation on the NCIDS documentation site
- [x] **Patch font size to xs**
