### ISSUE TITLE
List USWDS Pass Through to NCIDS

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/ncids#863]
### USWDS Component Name
[List](https://designsystem.digital.gov/components/list/)

### USWDS Component Packages
* Package usage: `@forward "usa-list";`

### Subtasks
- [x] **Replace our usa-list twig to match uswds twig**
- [x] Make a folder with the component name under uswds-native
- [x] Copy USWDS twig and any JSON
- [x] **Update stories.js file to match all other uswds native files**
- [x] **Update scenarios.js by adding a scenario for each story in stories.js**
- [x] **Update documentation page with missing content to match USWDS**
    > Using the list component
For unstyled lists, use either the .usa-list.usa-list--unstyled classes or the unstyled list mixin: @include unstyled-list.
