### ISSUE TITLE
Discovery: Pagination + Index

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#87]
# Pagination Discovery

Looking at pagination and indexes across the site 

## Partial List

A-Z
- dictionary
- cancer types pages
Pagination
- Search Results
- Dynamic listings
- blog index

**Intended Outcomes**

- Understanding of features
- Define problems to solve

> **ESTIMATE** TBD

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Inventory and analysis of content type features (Creation of article with all possible features, screen captured)
- [ ] Creation of Mural board to capture discovery (logical groupings of sub-features, grids for analysis)

 
### Sub-Tasks
- [ ] Heuristic review of feature and sub-features
- [ ] Secondary research compilation and synthesis
- [ ] Analytics data analysis and synthesis
- [ ] Identification of potential USWDS equivalents
- [ ] Drupal reporting on use of features

### Design Tickets
*Add links to the design tickets:*

### Research Tickets
*Add links to the design tickets:*

### Analytics Tickets
*Add links to the design tickets:*

### Dev Tickets
*Add links to the design tickets:*

### Artifacts & Resources

* Modular Features Discovery Mural: 
* USWDS: 

### Working Sessions

- inventory Mural review  (30 minutes)
- Analysis review and problem identification (1-2 hours)

### Notes
*Some complementary notes if necessary:*
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by blilianyu** [comment]
A-Z on Cancer Types are jump links and not pagination. This should be separate from pagination.

**Comment by VictoriaSunNIH** [comment]
Adding some places with pagination: Clinical Trials Search Results, All 3 dictionaries (cancer terms, genetics and drugs) and also in spanish, R4R. Is blog index referring to the blog series page? or the older/newer options at the bottom of the blog posts and blog series?

**Comment by claireblaustein** [comment]
@blilianyu  I was thinking that it made sense to look at all these types together, since they serve a similar function of moving people through lists of content - and maybe we don't want the cancer types list to just be jumps anymore, since other A-Zs aren't. But hoping we can talk that through once the inventory is pulled together. 

@VictoriaSunNIH yeah, the index was referencing the series, but added the individual posts (we'll also talk about them in context of the blog post today)

I'm changing this ticket from a baseline discovery to a "discovery kickoff" to capture the inventory and discussion prep, then we can see if they should be split into two parts for further investigation or shifted into design.
