### ISSUE TITLE
Intro USWDS Pass Through to NCIDS

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#890]
### USWDS Component Name
[Intro](https://designsystem.digital.gov/documentation/settings/)

* Font: lead font, font size 22px (lg)
* Font weight: regular
* Line height: 24.6 (4)
* Font family: Open sans (body)
* Create storybook with regression (say it’s ours and we own it)

### USWDS Component Packages
* Package usage: 
* Dependencies: 

### Subtasks
- [ ] **Create story under NCIDS components as we will own this one**
- [ ] **Create shared twig template under ncids-twig with default content from the documentation page template**
- [ ] Make an index.scss for the stories
- [ ] **Create story following new twig format**
- [ ] Create scenarios.js by adding a scenario for each story in stories.js
- [ ] **As there is no documentation page and no guidance yet, just add bullet to USWDS component to documentation page (See embed container example)**
- [ ] **Patch font family and line height to values listed above**
