### ISSUE TITLE
Review and Revise Documentation Site MVP1 Content

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#922]
### Description
There is documentation on the NCIDS Documentation Site (https://designsystem-dev.cancer.gov/develop/) that includes information regarding MVP1. However, this information has not been fully reviewed for accuracy since site launch. We need to review this information and update it retroactively so it is up-to-date.

Timeline: complete prior to Pilot launch (exact timing TBD).

### Sub-Tasks
- Review documentation site content [Design team/Adriana/IAs]
    - [ ] Review documentation site for accuracy regarding MVP1 documentation. Specifically, review *these components* on the documentation site
      - Components
        - Autocomplete
        - Banner
        - Breadcrumb
        - Button
        - Footer
        - Header
        - Icons
        - List
        - Side Navigation
        - Site Alert
        - Subscribe
        - Skipnav
      - All Design Tokens
        - Theme Tokens
        - State Tokens
        - System Tokens
        - Typography > Fonts
        - Properties > Shadow
    - [ ] Record updated documentation for review
- Review internally
    - [ ] Review documentation internally with UX team 
    - [ ] Review documentation internally with development team 
    - [ ] Make updates, as needed
- Review updated documentation for copyediting (submit separate Jira ticket)
- Update guidance on GH wiki
    - [ ] Add guidance to GH wiki (https://github.com/NCIOCPL/ncids/wiki/components)
- Update documentation site
    - [ ] Create new development ticket to update the documentation site itself with revised information

### Additional Notes:
* Insert notes as needed

**Comment by laurelthrash** [comment]
Determined we will close this ticket in favor of referring to the individual component/page tickets. Converted the Word document referenced here to be the language document for autocomplete. Cc: @adrianacastaneda @bennettcc @sarinapadilla
