### ISSUE TITLE
NCIDS For All Pilot - Design Tokens and Utilites

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#934]
## As a developer, I want to see the tokens and utilities across NCIDS, so that I can build my website using correct colors, fonts, spacing, etc.

* Determine which items are classified as design tokens - system and theme tokens
* Determine which items are classified as utilities
* Where are they referenced across USWDS
* Use this to drive our decision on how to document our design tokens
  * For pilot and for hard launch

### Tasks

- [x] Create list of all design tokens @monika-jaeger 
    - [x] QC from other designers [Shared via Slack 7/20 for @a-heirtzler @dcvijanovic1k @blilianyu]
    - [x] QC from developers [conduced with Slack]
    - [x] Update comps accordingly 
- [x] Developers draft all coding examples needed to accompany design tokens
- [x] Designers draft descriptions to accompany design tokens
- [x] Developers create the pages within the "Foundations" navigation section to contain all the design tokens per the [NCIDS for All - Sitemap_2023-08-22.pdf](https://github.com/NCIOCPL/ncids/files/12420374/NCIDS.for.All.-.Sitemap_2023-08-22.pdf) [Updated 08/22/23]

### Requirements

- The information of the Design Tokens and Utilities shall be placed within the "Foundations" page.
- The information of the Design Tokens and Utilities shall be placed on the same page within the Figma file
- The information for the Design Tokens and Utilities shall be organized as indicated on the Site Map and as described in the comments from Monika Jaeger from 10JUL2023 and 20JUL2023

### Resources:
- [USWDS Design Token Page](https://designsystem.digital.gov/design-tokens/)
- [Master Figma File](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?type=design&mode=design&t=5CkFYEvdox3IQb1Z-1)

### Notes

---

### Prerequisites
- None Identified

### Tasks
- None Identified

### Technical Notes
- More notes, or technical nuances/direction

**Comment by monika-jaeger** [comment]
Tokens are loaded into Figma and presented like this: 

![Image](https://github.com/NCIOCPL/ncids/assets/109552399/78af4746-afd5-43bb-bf2b-38b9b0e593c7)

These are the tokens we have loaded into Figma

- [Shadows](https://www.figma.com/proto/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?page-id=0%3A1&type=design&node-id=2528-8143&viewport=14748%2C-110%2C0.5&t=sYAKRFTreSzAQsqr-1&scaling=min-zoom&mode=design)
- [Colors](https://www.figma.com/proto/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?page-id=0%3A1&type=design&node-id=287-98&viewport=14748%2C-110%2C0.5&t=sYAKRFTreSzAQsqr-1&scaling=min-zoom&mode=design)
- [Font Sizes](https://www.figma.com/proto/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?page-id=0%3A1&type=design&node-id=1892-7566&viewport=14748%2C-110%2C0.5&t=sYAKRFTreSzAQsqr-1&scaling=min-zoom&mode=design)
- [Typography](https://www.figma.com/proto/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?page-id=0%3A1&type=design&node-id=63-49&viewport=14748%2C-110%2C0.5&t=sYAKRFTreSzAQsqr-1&scaling=min-zoom&mode=design)
- [Poppins Typescale](https://www.figma.com/proto/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?page-id=0%3A1&type=design&node-id=1984-2505&viewport=14748%2C-110%2C0.5&t=sYAKRFTreSzAQsqr-1&scaling=min-zoom&mode=design)
- [Open Sans Typescale](https://www.figma.com/proto/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?page-id=0%3A1&type=design&node-id=63-51&viewport=14748%2C-110%2C0.5&t=sYAKRFTreSzAQsqr-1&scaling=min-zoom&mode=design)

**Comment by monika-jaeger** [comment]
For the tokens above, we will have to cross-check with the developers that these are correct and are not missing any.

**Comment by monika-jaeger** [comment]
[WIP]

Tokens in Mural:
- [Color](https://www.figma.com/proto/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?page-id=0%3A1&type=design&node-id=287-98&viewport=30207%2C-245%2C1&t=ftswd9zQNFcTkzLM-1&scaling=min-zoom&mode=design)
- Appearance
   - Border
   - Outline
   - [Shadow](https://www.figma.com/proto/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?page-id=0%3A1&type=design&node-id=2528-8143&viewport=30123%2C-102%2C1&t=8slUX2cLAajROzZu-1&scaling=min-zoom&mode=design)
   - [Opacity](https://www.figma.com/proto/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?page-id=0%3A1&type=design&node-id=3695-8984&viewport=30207%2C-245%2C1&t=ftswd9zQNFcTkzLM-1&scaling=min-zoom&mode=design)
- Typography 
   - Font Size & Family
   - Text Styles
   - Paragraph Styles
   - List Reset
- Spacing Units
   - Height & Width
      - Margin & Padding
- Layout and Positioning
   - Float
   - Z-index
   - Clearfix
   - Display
   - Order
   - Layout Grid
   - Flex

**Comment by laurelthrash** [comment]
@monika-jaeger @blilianyu working through updates found on Word document. Updates are a part of the Figma file updates

**Comment by laurelthrash** [comment]
Closed #936 in order to address both tokens and utilities as part of this ticket. Tokens and utilities are found on the same page in the DS Figma Files. Cc: @blilianyu @monika-jaeger @sarinapadilla @andyvanavery

**Comment by laurelthrash** [comment]
As of 08/11, developers reviewed. Designers implementing final feedback.

**Comment by monika-jaeger** [comment]
All feedback from designers and developers has been implemented! Any work to do on the community file with tokens is noted in ticket https://github.com/NCIOCPL/ncids/issues/1140. 
cc: @blilianyu @laurelthrash

**Comment by laurelthrash** [comment]
Confirmed with Anna during mid-sprint on 08/15 that we will consider the primary/master DS Figma File (that includes design tokens and utilities) complete. ODDC does not need to take another review of the primary/master file (reviewed during previous two end of sprints). We will review the Community file (tracked in #1140) with ODDC to finalize all Figma Files. 

Passing this over to @sarinapadilla @andyvanavery to facilitate next steps form dev side. Adding as "on hold" from design side. 

Cc: @monika-jaeger @blilianyu @bennettcc

**Comment by bennettcc** [comment]
Closing this ticket - a separate page will not be used to show design tokens and utilties
