### ISSUE TITLE
Baseline Discovery: On This Page

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#94]
## Baseline Discovery: On This Page

Do baseline discovery for the On This Page functionality.

Should consider both desktop (jump links) and mobile (collapsed accordions)

Component Details: https://www.notion.so/On-This-Page-3db0e04f3457411f854c77503e1ab7cf

- Findings should be captured in the Notion for discussion. 
- **All reflections should be in by EOD Thursday, April 8.**

> **ESTIMATE** TBD

## Tasks

- [x] Drupal report of pages with OTP (Min)
- [x] Synthesis of any existing analytics Data around use and function of OTP (Joe/Nicole)
- [x] High-level heuristic review of feature (Ashley)
- [x] Technical or accessibility flags (Paul A)
- [x] Best practices around navigating within page AND accordion functions (Claire)

### Resources
* Notion: https://www.notion.so/On-This-Page-3db0e04f3457411f854c77503e1ab7cf

### Notes
*Some complementary notes if necessary:*

**Comment by nicolecrom** [comment]
@claireblaustein I've added very high level analytics to notion - does this look like enough for our conversation on Friday or should I continue digging in?

**Comment by claireblaustein** [comment]
Examples of pages with OTP now in box - link in notion under Drupal Reporting.
