### ISSUE TITLE
NCIDS For All Pilot - Components

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#945]
## As anyone who uses NCIDS For All, I want to see and navigate through all available components in NCIDS, so that I can create and execute the design for my pages.

This will involve creating a comp for the display of the components needed for the pilot. Include both the overview page and the individual component pages.

Tasks:
- [x] Create comp that represents consistent styling across component pages
  - [x] Review with UX
  - [x] Review with dev
  - [x] Update comp and align internally
  - [x] Create a standard template to be implemented for all component pages
  - [x] Make determination regarding "Anatomy" section (heading and image) and update comp accordingly
  - [x] Outstanding question: remove "Patterns" from the site map and add to the specific component (for design/developer discussion week of 08/21) [tracked in #993] 
  - [x] Obtain developer confirmation for variation FigJam (dev feedback obtained 08/18, with @monika-jaeger @adrianacastaneda for updates on hold as of 08/20 to account for variation review - tracking this as part of #1140 as the FigJam does not impact the individual component page mock up)
  - [x] Confirm "Anatomy" decision (change to "Overview") with developers (sent via Slack for review 08/17)
  - [x] Pass to development for next steps
- [ ] Related tickets that integrate with this ticket:
    - [x] #938 
    - [x] #944 
    - [x] Cross-linking to pattern pages: #993 

Resources: 

- Let's not make it look like this: https://designsystem.digital.gov/components/overview/
- Variation FigJam: https://www.figma.com/file/mLlEkBBiU4bCjZqcgj2ewh/Component-Variations-Audit?type=whiteboard&node-id=0%3A1&t=qRxwPJX14HP1aGVW-1
- Component Figma: https://www.figma.com/file/8qu1psEjnehVDoZyWrH7ny/NCI-DS-For-All?type=design&node-id=0%3A1&mode=design&t=gnIwhwi6D18MTuME-1

**Comment by monika-jaeger** [comment]
Compiling the comp here: [Figma Link](https://www.figma.com/file/8qu1psEjnehVDoZyWrH7ny/NCI-DS-For-All?type=design&node-id=0%3A1&mode=design&t=gnIwhwi6D18MTuME-1)

**Comment by laurelthrash** [comment]
[In Progress] Notes from internal discussion during 7/19 requirements meeting:
- Decisions added as replies in the Figjam

Next steps for UX (also tracked in Figjam) @monika-jaeger @adrianacastaneda 
- [ ] Variations: Take inventory of all variations of all components (work with devs to confirm full list has been captured), investigate parent and child structure with the guidance relating to each to determine best strategy.
- [ ] Footer Links: provide updated footer links for doc site (outstanding from previous 7/13 comment)
- [ ] Code Snippets:

**Comment by monika-jaeger** [comment]
Initial audit of [all component variations here](https://www.figma.com/file/mLlEkBBiU4bCjZqcgj2ewh/Component-Variations-Audit?type=whiteboard&node-id=0%3A1&t=qRxwPJX14HP1aGVW-1). cc @adrianacastaneda  @laurelthrash

**Comment by lburack** [comment]
Suggested footer links:

**About**
- About NCIDS
- Design Principles

**Resources (option 1)**

- Getting Started
- Foundations
- Components

**Resources (option 2)**

- For Designers
- For Developers
- Foundations
- Components

**Policies** [keep same links]

- Accessibility
- FOIA
- Privacy & Security
- Disclaimers
- Vulnerability Disclosure

**Comment by laurelthrash** [comment]
Notes from 8/2 Requirements Meeting // Next steps: @monika-jaeger update comp based on below updates. @arcepaul build this out on the documentation site. 

Variations
- [ ] Remove minus symbol at top of the buttons page for Variants (internal note: this will be a code block)

Code Snippet
- [ ] Make page look like top comp 
- [ ] Remove the minus symbol on right side by the component preview 
- [ ] Add "Show More" for the code preview (reference Atlassian example)
- Future: talk about how to collapse sections of pages (if it is a section that should collapse)

Cc: @bennettcc @sarinapadilla @andyvanavery

**Comment by monika-jaeger** [comment]
Updated comps for the [Individual Component Page](https://www.figma.com/proto/8qu1psEjnehVDoZyWrH7ny/NCI-DS-For-All?page-id=1%3A2&type=design&node-id=15-2881&viewport=-254%2C794%2C0.5&t=HfdmPAS9ma6WCgOe-1&scaling=scale-down-width&starting-point-node-id=183%3A3386&mode=design) is here.
cc @laurelthrash @blilianyu

**Comment by laurelthrash** [comment]
@monika-jaeger shared updated version with designers via Slack on 08/07. Next steps: designers to review, then send to developers for review. On track to show at end of sprint on 08/08.

**Comment by laurelthrash** [comment]
@monika-jaeger updated based on designer input. Shared with developers on 08/07 for feedback.

**Comment by laurelthrash** [comment]
Changes from 08/09 Requirements Meeting:
- [ ] Remove storybook from component page

Notes
- Storybook - will we include a link to Storybook on components? 
    - What is included in Storybook that cannot be delivered elsewhere?
    - We use Storybook for visual regressions. 
    - Decision: for now, we do not see anything mission critical in Storybook that devs cannot obtain through our other resource, and by including Storybook link it would result in changing how we currently use Storybook as well as add additional maintenance in the future
- OTP table of contents - agree this is out of scope for the pilot, but may want to consider in the future. Anchor links satisfies Anna's initial want/desire.

**Comment by monika-jaeger** [comment]
@laurelthrash 
- Removed 'storybook' button from [Buttons](https://www.figma.com/proto/8qu1psEjnehVDoZyWrH7ny/NCI-DS-For-All?page-id=1%3A2&type=design&node-id=15-2881&viewport=432%2C743%2C0.25&t=dOKoLfFzstqmtl6R-1&scaling=min-zoom&starting-point-node-id=183%3A3386&mode=design) and [Guide Card](https://www.figma.com/proto/8qu1psEjnehVDoZyWrH7ny/NCI-DS-For-All?page-id=1%3A2&type=design&node-id=183-3386&viewport=432%2C743%2C0.25&t=dOKoLfFzstqmtl6R-1&scaling=min-zoom&starting-point-node-id=183%3A3386&mode=design) pages.
- Added 'Demo' button to [Guide Card](https://www.figma.com/proto/8qu1psEjnehVDoZyWrH7ny/NCI-DS-For-All?page-id=1%3A2&type=design&node-id=183-3386&viewport=432%2C743%2C0.25&t=dOKoLfFzstqmtl6R-1&scaling=min-zoom&starting-point-node-id=183%3A3386&mode=design) page.
cc @blilianyu

**Comment by laurelthrash** [comment]
@adrianacastaneda @blilianyu @monika-jaeger Discussion during 08/17 UX meeting regarding the "Anatomy" section:

Decision:
- [ ] Change "Anatomy" to "Overview"
- [ ] Use static image below "Overview" with numbers that notes the different attributes (e.g., [Dell](https://www.delldesignsystem.com/components/accordion/#anatomy))
    - Overview section will include static image and labels associated with the numbered attributes
    - Clearly note which variant is displayed under "Overview" and point to the variant section
    - Use most robust variation of the component (e.g., hero with tagline, primary CTA button, and CTA strip)
    - Note: do not believe the basic attributes of the components will change regularly enough - but want to discuss further
- [ ] Change "Best Practice" to "Usage" - include text currently under "Anatomy" to this section
- [ ] Change "Content Guidance" to "Best Practices"

Next Steps:
- [ ] Update comp @monika-jaeger 
- [ ] Share with Paul A./developers to verify no concerns
- [ ] Determine how to track static images needed for site @laurelthrash

**Comment by laurelthrash** [comment]
Confirmed during standup 08/24 that the comp is finalized, and includes the "Anatomy" (changed to "Overview"). Documentation (tracked in XX), Cc: @monika-jaeger @adrianacastaneda @bennettcc

**Comment by bennettcc** [comment]
Closing this as complete - the component landing page is being tracked here: https://github.com/NCIOCPL/ncids/issues/1221
