### ISSUE TITLE
Cleanup NCIDS passthroughs

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#954]
Several issues have been spotted during the rollout of USWDS components to NCIDS. This may need to be converted to a meta and tickets broken up if this list gets too long.

This should be done after all passthrough tickets are completed.

### Subtasks 

- [ ] Fix `usa-table` warning

    ```bash
    Browser Console Log 0: %c[HMR] bundle 'preview' has 4 warnings
    Browser Console Log 1: color: #999933;
    Browser Console Log 0: %c./stories/uswds-native/usa-table/src/usa-table--stacked/usa-table--stacked.stories.js 117:45-69
    "export 'StackedBorderlessContent' was not found in '../content'
    ./stories/uswds-native/usa-table/src/usa-table--stacked/usa-table--stacked.stories.js 109:28-49
    "export 'StackedDefaultContent' was not found in '../content'
    ./stories/uswds-native/usa-table/src/usa-table--stacked/usa-table--stacked.stories.js 133:51-81
    "export 'StackedHeaderBorderlessContent' was not found in '../content'
    ./stories/uswds-native/usa-table/src/usa-table--stacked/usa-table--stacked.stories.js 125:41-61
    "export 'StackedHeaderContent' was not found in '../content'
    ```

- [ ] Fix ncids-css package.json uswdsExcludeComments

    This list is missing comments that were originally in tickets. This could be due to bad copypasta or a bad merge conflicts. May require to review merged PRs and [Bryan's original twig PR](https://github.com/NCIOCPL/ncids/pull/813)

- [ ] Patch or repatch all font "sm" and "xs" font token sizes to use body. 

- [ ] It may be important at this time to ensure there are no packages that got imported that are not needed. Or that we are not missing an important one. This bullet may require developer discussion.

**Comment by dlescarbeau** [comment]
Note: move usa-intro to passthroughs
