### ISSUE TITLE
Discovery: Sortable Tables

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#96]
## Baseline discovery for Sortable tables

Do baseline discovery for the sortable tables. Should consider particularly current implementations and heuristic eval. 

Tables Component details:  https://www.notion.so/Tables-502c5cf8322d4a37abe11e5d3af514df

- Findings should be captured in the Notion for discussion. 

> **ESTIMATE** TBD

## Tasks

- [ ] Drupal report of pages with Sortable Tables (Min)
- [ ] High-level heuristic review of feature (Ashley)
- [ ] Technical or accessibility flags (Paul A)

**Optional**
- [ ] Existing analytics on sorting sortable tables (Joe/Nicole)
- [ ] Best practices around table design

### Notes
*Some complementary notes if necessary:*

**Comment by VictoriaSunNIH** [comment]
Convert to discovery ticket when we are ready
