### ISSUE TITLE
[Updates/Revisions] Cgov Homepage & About NCI (Eng. and Span.) R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#964]
> META: #743 
> Creation Ticket (with source data/files): #760 

### Description
- https://www.cancer.gov/
- https://www.cancer.gov/espanol

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

PAGES in ENGLISH and SPANISH:  If a landing page has pages in both English and Spanish, both pages must either move to R2.1 at the same time, or both wait to move until after R2.1. 

### Sub-Tasks
- [x] Reply via email to questions posed in the Mural board
- [x] Aggregate suggestions that require review/approval
    - [x] Make recommendations regarding suggested changes
    - [x] Make determination with federal team regarding changes
    - [x] Complete tasks following federal team review
- [x] Update comps based on 2nd review from content owners
- [x] Update comps based on Spanish-language meeting 

### Notes
- Insert notes as needed

**Comment by laurelthrash** [comment]
Sent questions via email to Anna on 05/04 for review prior to sharing with content owners.

**Comment by laurelthrash** [comment]
**Next Steps following 5/9 Federal Team Review**

General @adrianacastaneda 

- [ ] Pull Analytics for "Coping with Cancer" page analytics in response to "Coping with Cancer may be a better choice than Managing Cancer Care on the guide card for patients. It gets more traffic and may address more immediate questions for people affected by cancer" 
    - [ ] Add information to ticket, along with any commentary/suggestions to be shared with the federal team

Updates to Homepage Comp @monika-jaeger 

_Spanish_

- [ ] Move the Managing Cancer Care link down from # 2 position and swap with Treatment.

_English_

- [ ] Update position of guide card links (inclusive of the change above) to match the same order as Spanish
- [ ] Change "Latest News and Research" to "Featured News and Research" 
- [ ] Swap Key Initiatives for EIP for now in the guide card. Select a new label that includes" Key initiatives" and is more appropriate for this audience (specific label not determined with the federal team).

Updates to About NCI Comp @monika-jaeger 

- [ ] Change "The Basics" to "Get to Know NCI"

**Comment by adrianacastaneda** [comment]
@monika-jaeger @laurelthrash 

**Suggestions on Coping with Cancer/Managing Cancer Care question and options for a new Key Initiatives label for the Researcher guide card:**

With regards to the Coping with Cancer versus Managing Cancer Care page question, Coping with Cancer has a higher **number of visits (18,804)** but also a **higher average bounce rate (20.59%)**, probably because the content is not as focused as the content on Managing Cancer Care. The Managing Cancer Care page has **6,944 visits** for the year and **average bounce rate of 9.89%**. Time frame for these analytics is May 1, 2022 - April 30, 2023. 

While, both pages would be successful as pages on this guide card, we recommend testing how the Managing Cancer Care page performs. Despite lower visits, we believe that the content provided on this page is important to users due to low bounce rates and 36% of visits coming from returning visitors. 

Options for Key Initiatives label on Researcher guide card. Currently the comp is showing the "Key Initiatives" placeholder. 
- Cancer research community initiatives 
- Research community focused initiatives 
- Cancer research community-led initiatives

**Comment by laurelthrash** [comment]
Meeting with federal team on 05/16 for quick sync to review/adopt the above changes.

**Comment by laurelthrash** [comment]
**@monika-jaeger Changes after meeting with federal team (also represented on Mural board) Cc: @adrianacastaneda** 

_Homepage_

- [ ] No change to comp needed, but need to add a sticky on the next round of comps that we will keep "Managing Cancer Care" and set a milestones to see how performs and circle back.
- [ ] Swap EIP on right guide card with "Key NCI Initiatives" 
- [ ] Swap "Partners in Cancer Card" promo block with EIP

_About NCI_
- [ ] Change "The Basics" guide card to "NCI at a Glance"

**Comment by monika-jaeger** [comment]
Was able to work on these changes in the background of the meeting so these are all set to go!

- [Homepage](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7001&type=design&node-id=142-7351&viewport=-1753%2C1631%2C1&scaling=scale-down-width)
- [About NCI](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=21%3A4037&type=design&node-id=21-4038&viewport=-651%2C-44%2C0.5&scaling=scale-down-width)

cc @laurelthrash @adrianacastaneda

**Comment by laurelthrash** [comment]
Sent updated comps/Mural board to Anna via email to share with content owners.

**Comment by laurelthrash** [comment]
**[In Progress] Changes to Cgov comps based on stakeholder v2 review**

**Homepage**
_English_
- [ ] Reorder last three links on "People Affected by Cancer" guide card to be Diagnosis and Staging > Managing Cancer care > Finding a Clinical Trial
- [ ] Swap location of CIS and NCP promo blocks (note: please be sure to update the image alternation)

_Spanish_

_Both Eng and Span_
- [ ] Replace "People Affected by Cabcer" guide card image, preferably with an adult cancer patient - that is appropriate for both English and Spanish

**About NCI**
_English_
_Spanish_
_Both Eng and Span_

**Comment by laurelthrash** [comment]
Per Slack conversation, refreshing images on the home page. Alerted Anna so as to hold on sending to stakeholders until the images are replaced. Cc: @monika-jaeger @chuckhrose:
- [ ] "People Affected by Cancer" guide card image [English]
- [ ] Hero - reduce gradient [English and Spanish]
- [ ] "Profesionales de salud" guide card image [Spanish] 
- [ ] "Recursos para pacientes" guide card image [Spanish]
- [ ] "Noticias e investigacions" feature card row image for "la telemedecina..." card [Spanish]

**Comment by monika-jaeger** [comment]
[Homepage](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A7001&type=design&node-id=142-8600&viewport=-3808%2C5801%2C1&scaling=min-zoom):
- Images updated. People Affected by Cancer & Recursos para pacientes use the same image.
- Hero updated to remove gradient.
- Profesionales de salud: Chuck and I discussed that this image is actually ok for this guide card, so there are no changes.
- "La telemedicina ahorra..." feature card updated. 

[About NCI](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=21%3A4037&type=design&node-id=21-4038&viewport=772%2C161%2C0.25&scaling=min-zoom):
- Guide Card descriptions added.

**Comment by laurelthrash** [comment]
Sent updated Mural with v3/near final versions to Anna 6/6 via email.
