### ISSUE TITLE
[META] Update Existing Design Assets to Align with Updated Color Palette/Style

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#969]
### Description 
- Details: Need to update existing design assets to align with the updated color palette/style. Assets should also be verified to meet 508 compliance standards. 
- Assets that need to be updated are found here on MyNCI: https://mynci.cancer.gov/topics/nci-branding-logo-use-templates#Templates. 

These include the following (and part of this ticket will be to determine if this is the complete list of assets): [Start from the top!]

- [ ] #1453 (to be addressed via https://tracker.nci.nih.gov/browse/CGOV-21791)
- [x] #1455
- [x] #1457
- [x]  #1249 
- [x] #1452
- [x] Update Design Assets - Webinar, Meeting and Presentation Videos - will not address. Consolidated PPT slides and webinar templates into one template.
- [x] #1454
- [x] #1456

Internal notes: 
- separate ticket with Tyeisha re: MyNCI clean up
- confirm timeline with Anna

### Sub-Tasks
- [ ] Update identified assets
- [ ] Receive federal approval
- [ ] Update on MyNCI or other location where asset is housed 

For individual tickets
- Dragutin pulls out major questions / here is the recommendation to make it consistent - holistic questions
- Add step for discovery/post info to ticket

**Comment by laurelthrash** [comment]
Determined that all remaining tickets within this META will transition to Jira to be addressed as part of O&M. Please reference https://tracker.nci.nih.gov/browse/CGOV-21789 for next steps on this ticket. Closing this META ticket and the associated sub-tickets to clear from the Redesign backlog. Cc: @andyvanavery31 @sarinapadilla
