### ISSUE TITLE
Create Annual Plan Comp to Utilize R2.1 Components

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#970]
### Description
Need to update the Annual Plan (AP) comp to utilize R2.1 components. This is just a sample and does not represent final content to be used when implementing R2.1 components for AP. 

Link to AP: https://www.cancer.gov/research/annual-plan

### Sub-Tasks
- [x] Create comp so that it only utilizes R2.1 components
    - Note: can use any content from current AP page
    - Note: Megan L. available for any questions on this task
- [x] Review internally (facilitated by Megan L.)
- [x] Make updates, as needed

Megan to facilitate next steps, as needed.

### Notes
- Link to Comp: [Figma Link (WIP)](https://www.figma.com/proto/I8ilFm7g9Us2OVLmiBAgj0/Annual-Plan?page-id=0%3A1&type=design&node-id=1-6999&viewport=591%2C588%2C0.25&scaling=scale-down-width)

**Comment by monika-jaeger** [comment]
Link to [WIP Comps](https://www.figma.com/proto/I8ilFm7g9Us2OVLmiBAgj0/Annual-Plan?page-id=0%3A1&type=design&node-id=1-6999&viewport=591%2C588%2C0.25&scaling=scale-down-width) added under 'Notes'

**Comment by laurelthrash** [comment]
Updated comps per @meglake recommendations. This ticket will now transition over to the AP team for next steps. Closing this ticket from the Redesign board. Cc: @monika-jaeger
