### ISSUE TITLE
Research Plan: Home and Landing Pages in Relation to R2

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#971]
### Description  ###
This ticket is recommended by the team to propose a research plan associated with the Home and Landing pages. This is in connection with the R2 release, following which the home and landing pages will be updated to utilize R2 components. 

**Phase 1: Prep and Execution**
1. Determine Testing Vehicle
2. Create Plan
3. Recruit for Study

**Phase 2: Analysis and Report Delivery**
1. Launch Study
2. Analyze and Report

### Sub-Tasks ###

**1. Determine Testing Vehicle**
- [ ] Determine testing vehicle (e.g., live site, prototype)
- [ ] Secure testing vehicle
- [ ] If using a prototype: 
    - [ ] Create prototype
    - [ ] Review internally
    - [ ] Approve prototype

**2. Create Plan**

- [ ] Define study title
- [ ] Establish:
    - [ ] What we want to  accomplish during the study and what are the desired outcomes
    - [ ] What we want to learn from this research
    - [ ] If this includes mobile and desktop
- [ ] Create recruitment screener
    - [ ] Obtain federal approval via email
- [ ] Determine with federal team if wish to explore Spanish language user testing
- [ ] Create guide/script to walk through with participants
    - [ ] Obtain federal approval via email

**3. Recruit for Study**

- [ ] Kick-off recruiting (internal and external) for qualified participants to take part in scheduled moderated user sessions
- [ ] Create testing schedule

**4. Launch Study**

- [ ] Begin user testing with participants
- [ ] Conclude user testing with participants

**5. Analyze and Report**

 - [ ] Generate analysis/report with findings (desktop and mobile, as needed)
 - [ ] Determine next best step with research and prepare new tickets as needed

### Documentation ###

**Plan Details**
- Testing Prototype: INSERT
- Plan Title: INSERT
- Plan Description: INSERT
- Realted Tickts: INSERT

**What do you want to learn from this research?**
- List the questions you would like to answer

**User / Audience**
- Who will be using this design? What personas / audiences are you considering?

## NOTES
- INSERT
- INSERT
