### ISSUE TITLE
Baseline Discovery: References/Citations

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/ncids#98]
## Baseline Discovery: References

Do baseline discovery for References

Component Details: https://www.notion.so/References-0909b58bb087456681e792d154816e6a

- Findings should be captured in the Notion for discussion. 

> **ESTIMATE** TBD

## Tasks

- [x] Drupal report of pages with References (Min)
- [x] Prep discussion of current functionality (Claire)

Optional
- [ ] Synthesis of any existing analytics Data around use and function of references (Joe/Nicole)
- [ ] High-level heuristic review of feature (Ashley)
- [ ] Technical or accessibility flags (Paul A)

### Resources
* Notion: https://www.notion.so/References-0909b58bb087456681e792d154816e6a

### Notes
*Some complementary notes if necessary:*

**Comment by claireblaustein** [comment]
@arcepaul could you take a look at this example: 
https://www.cancer.gov/about-cancer/causes-prevention/risk/substances/cancer-clusters-fact-sheet

- Accessibility concerns around the tooltip that appears on number hover
- And is it actually a tooltip, or something else?
