### ISSUE TITLE
DCEG About DCEG: R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#991]
> META: #743 

### Description
CMS URL (page is not published): https://dceg-cms.cancer.gov/about/michael-new-about-us

Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

IMPORTANT NOTE 1: Michael proposed a new "About DCEG" landing page ([draft here](https://dceg-cms.cancer.gov/about/michael-new-about-us)) to Jennifer L., however, it has not yet been reviewed. Team confirmed on 05/09 with the federal team that this tentative landing page should be included in the scope with the other DCEG HLPs.

IMPORTANT NOTE 2: don't create a mock up for landing pages that clearly should wait, but instead prepare to share recommendations for why that page should wait.

### Sub-Tasks
- [x] Conduct review of specific landing page 
- [x] Document content recommendations 
- [x] Review content recommendations internally
- [x] Create comp that demonstrates recommendations 
- [x] Review comp internally
- [x] Review final recommendations and comp with federal team
- [x] Make necessary revisions and finalize for content owner conversations
- [x] Receive final ODDC team approval
- [x] Add final comp to Mural board for content owner review [add link to this ticket]
- [x] Make updated based on v2 Mural review

### Final Documentation
- Mural board for content owner feedback: [INSERT]
- Content supplemental document/talking points: [INSERT]
- [Figma About DCEG Comp](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=1271%3A17063&type=design&node-id=1271-17103&viewport=809%2C65%2C0.14&scaling=min-zoom)
- Analytics PDF: N/A - page is not yet published
- Analytics Dashboard: N/A - page is not yet published

**Comment by laurelthrash** [comment]
**Notes from 05/25 internal review** @dcvijanovic1k 
- [ ] Edit/reduce tagline so it is shorter
- [ ] Hero - consider image from the photo shoot or consult Kim for b-roll/photo shoot from DCEG site visit
- [ ] Guide card images:
    - Organization: exterior shot of the lab or office space
    - Branches: a graphic that implies an org chart 
- [ ] Staff directory promo block - add image
- [ ] Identify images to fill the placeholders
- [ ] Update CTA bounding box to ensure it does not overlap with the hero
- [ ] Video - will be updated in Figma

**Comment by laurelthrash** [comment]
**Notes from 6/28 brainstorm. Consider the following:**
- Remove right guide card and replace with a promo block to highlight the branches, adding more specific text to describe the seven branches. 
- Is it possible to have one link to all branches, which is actually the TDRP?
- Can we suggest integrating the TDRP page into the Organization page?

**Comment by laurelthrash** [comment]
Reviewed and discussed 6/29:
- [ ] Add lorem ipsum for feature card that lacks description
- [ ] Check alignment on CTA (specifically, Career Opportunities and Staff Directory)
- [ ] Spell out DCEG in the Browser Title

Notes:
- Pulled analytics via https://tracker.nci.nih.gov/browse/CGOV-19115 which indicated that a low number of people are navigating to the branch pages from the About page, thus supporting that we did not feature each individual branch on the page

**Comment by laurelthrash** [comment]
Approved internally via Slack on 7/6.

**Comment by driscollmd** [comment]
> Changes discussed during meeting with ODDC 7/17 @driscollmd @dcvijanovic1k
> 
> * [ ]  Keep the two links to the "Staff Directory" on the page, but for the promo block, update the language to communicate how/why you want to connect with an expert

After reviewing this feedback to update staff directory promo, the "connect with an expert" messaging is only for people seeking a fellowship or training. this promo block is outside of F&T and should be more general messaging. Leaving it as is for presentation. :)

**Comment by laurelthrash** [comment]
Updated comps approved internally via Slack 7/20. @driscollmd preparing associated Mural board.

**Comment by laurelthrash** [comment]
Updates based on ODDC sync 8/2:
- [ ] Add "cancer" between "comprehensive" and "epidemiology" in tagline
- [ ] Remove "Contact Us" CTA button and reduce to two CTA buttons
- [ ] Add promo block for Apply for Fellowships
- [ ] Add promo block for Publications
- [ ] Update video thumbnail to current version on the site

Notes:
- Consider adding Publications to primary navigation

**Comment by laurelthrash** [comment]
@dcvijanovic1k @driscollmd Changes from v3/final Mural board. Aligned with ODDC on 09/11:

- [ ] Change tagline to: "The world's largest cancer epidemiology research group with research informing public health policy."
- [ ] Change "Organization" feature card to "Organizational structure of DCEG"
- [ ] Change "Diversity and Inclusion" feature card description to: "DCEG is committed to the recruitment, retention, and development of a diverse group of investigators and trainees."
- [ ] Staff Directory promo block
    - [ ] Change "Visit the Directory" button to "Search the Directory"
    - [ ] Change desc. to: "DCEG is home to some of the world's leading experts in cancer etiology. Use our directory to search alphabetically or by office, program, or branch."
- [ ] Add "Learn about the application process." before the existing sentence on the "Apply for Fellowships" promo block so that this reads: "Learn about the application process. Submit an application, discover..."
- [ ] Change "DCEG Publications" promo block to "Search our Publications Database"

**Comment by laurelthrash** [comment]
Final Mural shared with ODDC on Thurs. 09/14. Closing this ticket as all subtasks are complete. Will create a new ticket for new items that arise. Cc: @dcvijanovic1k @driscollmd
