### ISSUE TITLE
[Updates/Revisions] Grants & Training (Eng. and Span.) R2.1 Content Recommendations

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#994]
> META: #743 
> Creation Ticket (with source data/files): #763

### Description
Team is preparing for content conversations ahead of R2.1 launch. In keeping with this Designers & IAs will review each landing page to determine R2.1 recommendations and create mock up that use R2.1 components only. 

This ticket documents updates and revisions following the creation of the recommendations and associated comps.

### Sub-Tasks
- [x] Reply via to questions posed in the Mural board **05/22**
- [x] Aggregate suggestions that require review/approval
    - [x] Make recommendations
    - [x] Make determination w/federal team regarding changes **Slated: 05/17**
    - [x] Make updates following federal review
- [x] Update comps based on Review # 2
- [ ] Update comps based on Spanish-language meeting

### Notes
- [Grants & Training comp](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A11354&type=design&node-id=142-11355&viewport=661%2C914%2C0.25&scaling=min-zoom)

**Comment by laurelthrash** [comment]
**Updates to comp following conversation with Anna/Alex:** @monika-jaeger @adriancofie 

- [ ] Replace stock imagery so there are fewer people in lab coats
- [ ] Revert "Training Opportunities for Diverse Populations" to "CRCHD Diversity Training" in the guide card

**Comment by monika-jaeger** [comment]
@laurelthrash I have the "CRCHD Diversity Training" button updated in the guide card [in the comp](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A11354&type=design&node-id=142-11355&viewport=661%2C914%2C0.25&scaling=min-zoom). I will await to hear more from Alex for updating the imagery.

**Comment by laurelthrash** [comment]
**Discussed during requirements meeting 05/18** @monika-jaeger 

- [ ] Update link to "Grants & Training del NCI en ingles" in Spanish Grants and Training so that it is 1) underlined and, 2) link color matches link token color

**Comment by monika-jaeger** [comment]
@laurelthrash 

Changed "Grants & Training del NCI en ingles" to underlined in [Spanish comps](https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A11354&type=design&node-id=142-11391&viewport=-462%2C1534%2C0.5&scaling=min-zoom). Link color should be our primary color #007bbd.

**Comment by laurelthrash** [comment]
**@monika-jaeger changes to Spanish comp based on 6/1 Spanish-specific meeting**

- [ ] Keep raw HTML block (modify previously drafted and approved language to be more clear/concise)
- [ ] Add a feature card row that includes:
    - https://www.cancer.gov/grants-training/grants-funding
    - https://www.cancer.gov/grants-training/manage-award
    - https://www.cancer.gov/grants-training/training
- [ ] Use Spanish override title to denote that this information is in English

**Comment by laurelthrash** [comment]
@monika-jaeger changes to English comp based on 6/5 ODDC Sync:
- [ ] Replace "Training Opportunities" guide card image, per feedback from Alex. Current image is used on DCEG and a new image should be selected that is in the same spirit as current image.
- [ ] Adjust "Training Opportunities" guide card links to be in the following order (removing "CRCHD Diversity Training"):
    1. Building a Diverse Workforce
    2. Funding for Cancer Training
    3. Research Training at NCI
    4. Training Program Contacts
    5. Center for Cancer Training
- [ ] Add promo block for "CRCHD Diversity Training" (@adrianacastaneda may need to consult on this one)
- [ ] Put in CMS image as placeholder for "NCI funds more research grants thanks to congress," knowing this will rotate out and not be included at time of launch.

**Comment by laurelthrash** [comment]
@monika-jaeger updated text for the raw HTML block is located in Jira ticket CGOV-18850. Cc: @adrianacastaneda
