### ISSUE TITLE
Create Cgov Home and Landing Page Content Templates

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#996]
### Description
For our R2.1 content launch for home and landing pages, we will create content templates so that we can build out the new home and landing pages in ACSF-dev and production. Content templates should include: notations regarding the selected component, override fields (if applicable), content titles, and images. 

### Sub-Tasks (English and Spanish)
- [x] Create content templates:
    - [x] Home Page
    - [x] About NCI
    - [x] Grants & Training
    - [x] Research
    - [x] About Cancer
- [x] QC content templates:
    - [x] Home Page
    - [x] About NCI
    - [x] Grants & Training
    - [x] Research
    - [x] About Cancer
- [x] Update content templates:
    - [x] Home Page
    - [x] About NCI
    - [x] Grants & Training
    - [x] Research
    - [x] About Cancer
- [x] Update templates following first round of ACSF content entry

### Notes
- Insert notes as needed

**Comment by laurelthrash** [comment]
@adrianacastaneda marking this ticket as complete as we are tracking new updates to the content templates via separate tickets
