### ISSUE TITLE
Aggregate All R2.1 Home and Landing Page Images 

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/ncids#999]
### Description
For our R2.1 content launch for home and landing pages, we will need to aggregate all of the images that we plan to use. This ticket is to ensure we know where all source files are located for images for when it is time to build the pages in the CMS (ACSF-dev and Prod). These will be folded into the content templates from #996.

### Sub-Tasks (English and Spanish)
- [x] Identify all images for the following pages and outline where they are located and their image name: 
    - [x] Home Page
    - [x] About NCI
    - [x] Grants & Training
    - [x] Research
    - [x] About Cancer
- [x] Save all images to a shared Teams folder, or indicate that they are already available images in the CMS
- [x] Discuss special cases. [Link in Figma](https://www.figma.com/file/x5x9fvmpwvVOdKWoa1tuPJ/R2.1-Landing-Pages-Image-Audit?type=whiteboard&node-id=0%3A1&t=3c82pymIDNLxmbw1-1) **Slated: Tues. 05/23**

### Notes
- Insert notes as needed

**Comment by monika-jaeger** [comment]
Special Cases audit linked here. https://www.figma.com/file/x5x9fvmpwvVOdKWoa1tuPJ/R2.1-Landing-Pages-Image-Audit?type=whiteboard&node-id=0%3A1&t=3c82pymIDNLxmbw1-1

**Comment by laurelthrash** [comment]
**Internal discussion on 05/23** @monika-jaeger 

- [ ] Check if the Getty images are available on iStock
- [ ] If already existing (should be available on visuals online), if uncertain, we can share the iStock number with Kim to verify
- [ ] Add line item on the schedule for purchasing stock imagery 

Notes

- Need client approval prior to purchasing

**Comment by monika-jaeger** [comment]
All image accounted for [HERE](https://www.figma.com/file/x5x9fvmpwvVOdKWoa1tuPJ/R2.1-Landing-Pages-Image-Audit?type=whiteboard&node-id=0%3A1&t=jcOYT9lvOox2nBIx-1) and ready to discuss

cc: @laurelthrash @adriancofie

**Comment by laurelthrash** [comment]
Marking this ticket as complete as the FigJam with the image aggregation is complete. Cc: @monika-jaeger @adriancofie
